- grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-kafka-argo-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-knowledge-graph-content-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-postgresql-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-service-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-sli-slo.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-user-api-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-workflow-controllers-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/prod/argocd.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-kafka-argo-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-knowledge-graph-content-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-postgresql-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-service-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-sli-slo.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-user-api-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-workflow-controllers-metrics.yaml
update the thoth-station dashboard with new content
Fixes: https://github.com/thoth-station/thoth-application/issues/2140
Updated the version to get the latest dashboard live.
> update the thoth-station dashboard with new content

- grafana/overlays/moc/smaug/dashboards/kustomization.yaml
- grafana/overlays/moc/smaug/dashboards/prometheus-anomaly-detector/kustomization.yaml
- grafana/overlays/moc/smaug/dashboards/prometheus-anomaly-detector/pad-demo.yaml
- grafana/overlays/moc/smaug/grafana-oauth.yaml
give pad team `Editor` role in Opf Grafana
> Add prometheus-anomaly-detection demo grafana dashboard

- cluster-scope/base/core/namespaces/opf-trino-stage/kustomization.yaml
- cluster-scope/base/core/namespaces/opf-trino-stage/namespace.yaml
- cluster-scope/base/core/namespaces/opf-trino-stage/resourcequota.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
- dex/overlays/moc/smaug/dex-clients.enc.yaml
- dex/overlays/moc/smaug/dex-cm.yaml
- kfdefs/overlays/moc/smaug/kustomization.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/.sops.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/hive-metastores/kustomization.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/hive-metastores/operate-first_general/kustomization.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/kustomization.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/obcs/kustomization.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/obcs/trino-stage-bucket.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/file-auth-secret.enc.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/kustomization.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/postgres-dbs.enc.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/s3buckets.enc.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/secret-generator.yaml
- kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/trino-oauth.enc.yaml
- odh-manifests/smaug-stage/trino/base/hive-config.yaml
- odh-manifests/smaug-stage/trino/base/kustomization.yaml
- odh-manifests/smaug-stage/trino/base/trino-catalog-secret.yaml
- odh-manifests/smaug-stage/trino/base/trino-config-secret.yaml
- odh-manifests/smaug-stage/trino/base/trino-coordinator-dc.yaml
- odh-manifests/smaug-stage/trino/base/trino-route.yaml
- odh-manifests/smaug-stage/trino/base/trino-worker-dc.yaml
> Add trino staging env to smaug.

- cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.yaml
- cluster-scope/overlays/prod/moc/smaug/configmaps/user-workload-monitoring-config.yaml
Related https://github.com/operate-first/apps/issues/1327
> Remotewrite smaug cluster and uwm metrics to thanos

- kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/file-auth-secret.enc.yaml
- odh-manifests/smaug-stage/trino/base/trino-catalog-secret.yaml
> Correct op1st trino staging catalog env vars:x.

- cluster-scope/base/core/namespaces/opf-trino-stage/resourcequota.yaml
> Increase memory quota for trino stage on smaug.

- argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/cloudbeaver-stage.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/cloudbeaver.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
- cloudbeaver/overlays/moc/smaug-stage/add_configs.yaml
- cloudbeaver/overlays/moc/smaug-stage/configs/cloudbeaver.conf
- cloudbeaver/overlays/moc/smaug-stage/configs/initial-data-sources.conf
- cloudbeaver/overlays/moc/smaug-stage/configs/initial-data.conf
- cloudbeaver/overlays/moc/smaug-stage/configs/product.conf
- cloudbeaver/overlays/moc/smaug-stage/kustomization.yaml
I've also moved cloudbeaver from `cluster-management` to `operate-first` folder, and updated the ns path as both of these were incorrect.
> Add cloudbeaver stage instance to smaug.

- observatorium/base/instance/thanos/kustomization.yaml
- observatorium/base/instance/thanos/query-frontend/deployment.yaml
- observatorium/base/instance/thanos/query-frontend/kustomization.yaml
- observatorium/base/instance/thanos/query-frontend/service.yaml
- observatorium/base/instance/thanos/query/deployment.yaml
- observatorium/base/instance/thanos/query/kustomization.yaml
- observatorium/base/instance/thanos/query/service.yaml
- observatorium/overlays/moc/smaug/thanos/servicemonitors/kustomization.yaml
- observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-query-frontend.yaml
- observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-query.yaml
Related https://github.com/operate-first/apps/issues/1327
> Add Thanos Query/Query-Frontend deployment

- cluster-scope/base/core/namespaces/opf-trino-stage/resourcequota.yaml
> Increase trino stage cpu quota on smaug.

- argocd/overlays/moc-infra/projects/apicurio-registry.yaml
server in apicurio project is incorrect and that made application to not deploy.
> fix apicurio project

- cluster-scope/base/core/namespaces/opf-observatorium/resourcequota.yaml
- observatorium/base/instance/thanos/query/deployment.yaml
- observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-query-frontend.yaml
- observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-query.yaml
1. Update resourcequota for `opf-observatorium` namespace
2. fix namespaces in thanos query servicemonitors
3. remove thanos query empty securityContext from deployment
> Fix thanos deployment sync issues

- observatorium/base/instance/thanos/receive/statefulset.yaml
> increase spu/memory resources for thanos receive sts

- cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml
This PR is in prep for ACM upgrade on Monday November 22nd
issue: https://github.com/operate-first/apps/issues/1321
> upgrade ACM to 2.4

- cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.yaml
- cluster-scope/overlays/prod/moc/smaug/configmaps/user-workload-monitoring-config.yaml
Docs: https://docs.openshift.com/container-platform/4.8/monitoring/configuring-the-monitoring-stack.html#configuring-persistent-storage
Related https://github.com/operate-first/apps/issues/1352
> Attach PVCs to openshift-monitoring and uwm prometheuses in MOC/Smaug

- cloudbeaver/overlays/osc/OWNERS
- cluster-scope/overlays/prod/osc/OWNERS
- dex/overlays/osc/OWNERS
- kfdefs/overlays/osc/OWNERS
- odh-manifests/osc-cl1/OWNERS
Resolve: https://github.com/operate-first/support/issues/479
> Add osc owners to osc overlays.

- cluster-scope/base/operators.coreos.com/subscriptions/camel-k/kustomization.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/camel-k/subscription.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
to the smaug cluster
I clicked install at https://operatorhub.io/operator/camel-k and added the contents of https://operatorhub.io/install/camel-k.yaml
anything more needed?
fixes https://github.com/operate-first/support/issues/476
> added camel-k operator

- docs/ocs/claiming_object_store.md
- docs/ocs/runbook.md
Provide some basic OCS troubleshooting documentation.
Closes operate-first/SRE#426
> docs: Updates to OCS documentation

- docs/ocs/buckets-external-access.md
> docs: Document how to access object buckets externally

- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review-opf-observatorium/clusterrolebinding.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
- docs/observatorium/thanos/README.md
- docs/observatorium/thanos/request_thanos_access.md
- observatorium/overlays/moc/smaug/thanos/deployments/kustomization.yaml
- observatorium/overlays/moc/smaug/thanos/deployments/thanos-query-frontend-oauth-proxy.yaml
- observatorium/overlays/moc/smaug/thanos/deployments/thanos-receive-oauth-proxy.yaml
- observatorium/overlays/moc/smaug/thanos/kustomization.yaml
- observatorium/overlays/moc/smaug/thanos/rolebindings/kustomization.yaml
- observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
- observatorium/overlays/moc/smaug/thanos/roles/kustomization.yaml
- observatorium/overlays/moc/smaug/thanos/roles/opf-observatorium-view.yaml
- observatorium/overlays/moc/smaug/thanos/routes/kustomization.yaml
- observatorium/overlays/moc/smaug/thanos/routes/thanos-query-frontend-oauth-proxy.yaml
- observatorium/overlays/moc/smaug/thanos/routes/thanos-receive-oauth-proxy.yaml
- observatorium/overlays/moc/smaug/thanos/serviceaccounts/kustomization.yaml
- observatorium/overlays/moc/smaug/thanos/serviceaccounts/thanos-query-frontend-oauth-proxy.yaml
- observatorium/overlays/moc/smaug/thanos/serviceaccounts/thanos-receive-oauth-proxy.yaml
- observatorium/overlays/moc/smaug/thanos/services/kustomization.yaml
- observatorium/overlays/moc/smaug/thanos/services/thanos-query-frontend-oauth-proxy.yaml
- observatorium/overlays/moc/smaug/thanos/services/thanos-receive-oauth-proxy.yaml
Also add docs on how to request access to thanos metrics
Related https://github.com/operate-first/apps/issues/1357
> Add oauth proxy for opf-observatorium thanos query and receive endpoints

- docs/acm/adding_managed_cluster_to_argocd.md
- docs/argocd-gitops/get_access_to_argocd.md
- docs/cluster-scope/add_user_to_group.md
- docs/odh/trino/add_more_postgress_catalogs.md
Check off some of the items here: https://github.com/operate-first/SRE/issues/417
> Add docs based on recent support cases.

- kfdefs/overlays/osc/osc-cl1/trino-dev/configs/kustomization.yaml
- kfdefs/overlays/osc/osc-cl1/trino-dev/configs/node.properties
- odh-manifests/osc-cl1/trino-dev/base/trino-coordinator-dc.yaml
- odh-manifests/osc-cl1/trino-dev/base/trino-worker-dc.yaml
> Correct conflict with configmap name for osc dev trino.

- acm/overlays/moc/infra/gitopsclusters/argocd-managed.yaml
Resolve: https://github.com/operate-first/apps/issues/1371
> Update api version for gitopscluster resource in acm infra.

- cluster-scope/base/core/namespaces/tremor-demo/kustomization.yaml
- cluster-scope/base/core/namespaces/tremor-demo/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/tremor-demo/group.yaml
- cluster-scope/base/user.openshift.io/groups/tremor-demo/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/tremor-demo/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/tremor-demo/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Following Hitchhikers guide -- I think I did this right!
> feat(onboarding): Add team tremor-demo

- grafana/overlays/moc/smaug/grafanadatasource.enc.yaml
> Add thanos frontend grafana datasource

- cluster-scope/base/user.openshift.io/groups/data-science/group.yaml
- cluster-scope/base/user.openshift.io/groups/operate-first/group.yaml
- cluster-scope/base/user.openshift.io/groups/sre/group.yaml
- added schwesig as user to data-science, operate-first, sre
- sorted the member list user alphabetically where needed (data- science, operate-first)
> add schwesig to users | sort members alphabetical where needed

- docs/observatorium/thanos/request_thanos_access.md
Related https://github.com/operate-first/apps/issues/1361
> [Fix] Update link in Thanos API Access doc 

- cluster-scope/base/core/namespaces/opf-jupyterhub/resourcequota.yaml
Resolves https://github.com/operate-first/support/issues/487
> Update resource quota for opf-jupyterhub ns

- docs/argocd-gitops/onboarding_to_argocd.md
Follow up on : https://github.com/operate-first/support/pull/432
> Correct outdated links and info in argocd docs.

- kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/elyra-image.yaml
- kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/kustomization.yaml
> Add Elyra image to OSC

- argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/arrow-flight-module.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/vault.yaml
This PR adds the ArgoCD application manifests to deploy Vault and Arrow Flight Module on the Smaug cluster
@ronenkat @HumairAK
> Fybrik - adding ArgoCD application manifests for Vault and Arrow Flight Module

- grafana/overlays/moc/smaug/dashboards/kustomization.yaml
- grafana/overlays/moc/smaug/dashboards/prometheus/kustomization.yaml
- grafana/overlays/moc/smaug/dashboards/prometheus/overview.yaml
- grafana/overlays/moc/smaug/dashboards/prometheus/remote-write.yaml
> Add dashboards to check how prometheus is doing

- docs/_config.yml
Resolve: https://github.com/operate-first/apps/issues/1399
> Set op1st authors for doc jbook.

- docs/content/observatorium/thanos/README.md
- docs/content/observatorium/thanos/request_grafana_access.md
- docs/content/observatorium/thanos/request_thanos_access.md
- docs/content/observatorium/thanos/thanos_programmatic_access.md
Inspired from [Internal Data Hub docs](https://gitlab.cee.redhat.com/data-hub/dh-docs/-/blob/master/docs/interacting-with-telemetry-data.adoc)
Resolves https://github.com/operate-first/apps/issues/1361
> Add docs for accessing thanos metrics

- docs/_toc.yml
- docs/content/observatorium/thanos/request_grafana_access.md
- docs/content/observatorium/thanos/request_thanos_access.md
- docs/content/observatorium/thanos/thanos_programmatic_access.md
fix items that caused warnings in jupyterbook build process
> [fix] thanos docs listing in jupyterbook

- grafana/overlays/moc/smaug/dashboards/cluster-management/kustomization.yaml
- grafana/overlays/moc/smaug/dashboards/cluster-management/vpa-rc-cpu-and-memory-overview.yaml
- Regexp was added for cron job into the pod variable
- Added new panels to the dashboard
- Variable component was removed.
> [NEU CS6620] Updated grafana dashboard 

- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/applicationsets.argoproj.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/batchtransfers.motion.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/observatoria.core.observatorium.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reports.batch.curator.openshift.io/batch.curator.openshift.io_reports.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/streamtransfers.motion.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-report-manager-role/clusterrole.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/opendatahub-operator/clusterrole.yaml
- cluster-scope/base/storage.k8s.io/storageclasses/moc-nfs-csi/storageclass.yaml
- cluster-scope/overlays/prod/emea/rick/clusterversion.yaml
- cluster-scope/overlays/prod/moc/infra/clusterversion.yaml
- cluster-scope/overlays/prod/moc/zero/clusterversion.yaml
- cluster-scope/overlays/prod/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml
- kubevirt-hyperconverged/base/hyperconverged.yaml
This PR tries to fix various issues in our manifests. Changes were made, when CI which will be introduced in PR https://github.com/operate-first/apps/pull/1318, failed with error on some resource. 
Part of: https://github.com/operate-first/SRE/issues/107
> fix: Fix issues in manifests in apps repo

- cert-manager/overlays/moc/infra/openshift-api-issuer.yaml
- cert-manager/overlays/moc/infra/openshift-ingress-issuer.yaml
Follow up to: https://github.com/operate-first/apps/pull/1416
> Fix issuer selector invalid formatting.

- odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Access control changes to test row-level filtering in Trino, based on column-level condition.
> Access config changes for trino-datavault-test

- odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
fix errors introduced by #1418
> fix trino config json syntax

- observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
Resolves https://github.com/operate-first/apps/issues/1429
> Give curator group access to thanos metrics

- cluster-scope/overlays/prod/emea/rick/configmaps/user-workload-monitoring-config.enc.yaml
Reencrypt so @rbo can decrypt these files.
> Reencrypt rick emea uwm resources with new key.

- argocd/base/deployments/argocd-redis_patch.yaml
Related: https://github.com/AICoE/aicoe-cd/pull/740/files
> Remove Upstream Redis SCC's to allow ArgoCD to run on OpenShift

- argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-ocp-prod.yaml
This seems to already be enabled on live, the pr just sync's this with git.
> Enable prune for ocp prod argocd app.

- observatorium/base/instance/thanos/kustomization.yaml
- observatorium/base/instance/thanos/store-bucket-cache/kustomization.yaml
- observatorium/base/instance/thanos/store-bucket-cache/service.yaml
- observatorium/base/instance/thanos/store-bucket-cache/statefulset.yaml
- observatorium/base/instance/thanos/store-index-cache/kustomization.yaml
- observatorium/base/instance/thanos/store-index-cache/service.yaml
- observatorium/base/instance/thanos/store-index-cache/statefulset.yaml
- observatorium/base/instance/thanos/store/kustomization.yaml
- observatorium/base/instance/thanos/store/shard-0/kustomization.yaml
- observatorium/base/instance/thanos/store/shard-1/kustomization.yaml
- observatorium/base/instance/thanos/store/shard-base/kustomization.yaml
- observatorium/base/instance/thanos/store/shard-base/service.yaml
- observatorium/base/instance/thanos/store/shard-base/statefulset.yaml
- observatorium/overlays/moc/smaug/thanos/servicemonitors/kustomization.yaml
- observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-store-bucket-cache-memcached.yaml
- observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-store-index-cache-memcached.yaml
- observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-store-shard.yaml
Also add caches to reduce queries to Object Storage
Related https://github.com/operate-first/support/issues/494
> Add Thanos Store API component

- cluster-scope/base/core/namespaces/opf-observatorium/resourcequota.yaml
- observatorium/base/instance/thanos/receive/statefulset.yaml
- observatorium/overlays/moc/smaug/thanos/horizontalpodautoscalers/observatorium-thanos-receive-default.yaml
update thanos receive HPA
increase Thanos receive pvc size
Related https://github.com/operate-first/apps/issues/1402
> Update resource quota for observatorium

- kfdefs/overlays/osc/osc-cl1/trino-dev/configs/jvm.config
- kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
- odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
> Increase osc trino memory req & limit.

- cluster-scope/base/user.openshift.io/groups/fybrik/group.yaml
This PR adds a user to the Fybrik user group on the Smaug cluster
@roytman @HumairAK
> Add user to Fybrik user group

- cluster-scope/overlays/prod/moc/smaug/clusterversion.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Related https://github.com/operate-first/apps/issues/1388
> update smaug clusterversion to 4.8.23 from 4.8.4

- cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/group.yaml
Users need to be added to see if the machine learning vm will work before requesting NS and quota
> Add users to test virtual machine capabilities

- cluster-scope/base/operators.coreos.com/subscriptions/opf-grafana/subscription.yaml
As per: https://github.com/operate-first/apps/issues/1388
> Upgrade grafana sub channel to v4.

- docs/content/odh/trino/access_public_bucket.md
Bucket had to be recreated due to: https://github.com/operate-first/SRE/issues/430#issuecomment-987040127
Resolve: https://github.com/operate-first/support/issues/499
> Add new pub bucket info in public access docs.

- docs/content/argocd-gitops/import_dev_gpg.md
- docs/content/argocd-gitops/secret_management.md
Some small doc fixes around gpg
> Some small doc fixes around gpg

- argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/reloader.yaml
- cluster-scope/base/core/namespaces/reloader/kustomization.yaml
- cluster-scope/base/core/namespaces/reloader/namespace.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/reloader-reloader-role-binding/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/reloader-reloader-role-binding/kustomization.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/reloader-reloader-role/clusterrole.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/reloader-reloader-role/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
- reloader/base/deployment.yaml
- reloader/base/kustomization.yaml
- reloader/base/serviceaccount.yaml
- reloader/overlays/moc/smaug/kustomization.yaml
@4n4nd Removed unnecessary annotations related to helm
> add: reloader manifests

- odh-manifests/smaug/jupyterhub/base/jupyterhub-cluster-rolebinding.yaml
> Manually add JH SA to crb for smaug.

- kfdefs/base/jupyterhub/kfdef.yaml
> Update JH kfdef to use version v1.1.1 manifests

- kfdefs/base/trino/kfdef.yaml
- kfdefs/overlays/moc/smaug/opf-trino/kustomization.yaml
- odh-manifests/smaug/trino/base/hive-config.yaml
- odh-manifests/smaug/trino/base/kustomization.yaml
- odh-manifests/smaug/trino/base/trino-config-secret.yaml
- odh-manifests/smaug/trino/base/trino-coordinator-dc.yaml
- odh-manifests/smaug/trino/base/trino-worker-dc.yaml
Related: #1257 and https://github.com/operate-first/apps/issues/1476
> Make trino configurations on smaug compatible with odh 1.1.1 updates.

- odh-manifests/smaug-stage/trino/base/hive-config.yaml
- odh-manifests/smaug-stage/trino/base/kustomization.yaml
- odh-manifests/smaug-stage/trino/base/trino-config-secret.yaml
- odh-manifests/smaug-stage/trino/base/trino-coordinator-dc.yaml
- odh-manifests/smaug-stage/trino/base/trino-worker-dc.yaml
- odh-manifests/smaug/trino/base/trino-coordinator-dc.yaml
- odh-manifests/smaug/trino/base/trino-worker-dc.yaml
> Update trino stage configs as per odh 1.1.1

- kfdefs/overlays/moc/smaug/opf-trino-stage/kustomization.yaml
> Remove trino stage image update from kfdef on smaug.

- odh-manifests/smaug-stage/trino/base/trino-coordinator-dc.yaml
> Update trino stage image in smaug.

- kfdefs/overlays/moc/smaug/ds-ml-workflows-ws/kfdef.yaml
> Update jh for ds-ml-workflows on smaug.

- odh-manifests/smaug-stage/trino/base/trino-config-secret.yaml
- odh-manifests/smaug/trino/base/trino-config-secret.yaml
Related [#1476 ](https://github.com/operate-first/apps/issues/1476#issuecomment-999711962)
> Remove jmx javaagent metric exporter from trino stage/prod on smaug.

- cluster-scope/base/core/namespaces/training-model/kustomization.yaml
- cluster-scope/base/core/namespaces/training-model/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/octo-training-model/group.yaml
- cluster-scope/base/user.openshift.io/groups/octo-training-model/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/octo-training-model/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/octo-training-model/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Signed-off-by: Ryan Cook <rcook@redhat.com>
Closes https://github.com/operate-first/support/issues/506
> new project and admins

- acm/overlays/moc/infra/managedclusters/kustomization.yaml
- acm/overlays/moc/infra/managedclusters/morty.yaml
- alertreceiver/overlays/emea/morty/kustomization.yaml
- argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-morty.yaml
- argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/alertreceiver.yaml
- argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/cluster-resources.yaml
- argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/emea/morty/kustomization.yaml
- cluster-scope/overlays/prod/emea/morty/.sops.yaml
- cluster-scope/overlays/prod/emea/morty/groups/cluster-admins.yaml
- cluster-scope/overlays/prod/emea/morty/kustomization.yaml
- cluster-scope/overlays/prod/emea/morty/oauths/cluster_patch.yaml
- cluster-scope/overlays/prod/emea/morty/oauths/operate-first-sso-secret.enc.yaml
- cluster-scope/overlays/prod/emea/morty/secret-generator.yaml
- docs/content/acm/adding_managed_cluster_to_argocd.md
- keycloak/overlays/moc/infra/clients/morty.enc.yaml
- keycloak/overlays/moc/infra/secret-generator.yaml
Related: 
- https://github.com/operate-first/apps/pull/1466 
Resolve: 
- https://github.com/operate-first/support/issues/504
PR created using onboarding cluster notebook (+ some doc fixes)
> Onboard Morty Cluster.

- kfdefs/overlays/moc/smaug/opf-superset/secrets/superset.enc.yaml
- kfdefs/overlays/moc/smaug/opf-superset/secrets/supersetdb.enc.yaml
- odh-manifests/smaug/superset/base/secret.yaml
> Match smaug superset db name existing postgres in opf-superset.

- argocd/overlays/moc-infra/configs/argo_cm/dex.config
- argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
> Give argocd standard access to osc admins.

- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view/clusterrolebinding.yaml
Resolves https://github.com/operate-first/support/issues/501
> Give curator team permissions to view cluster metrics

- kfdefs/overlays/moc/smaug/ds-ml-workflows-ws/kfdef.yaml
> Remove Jh instance from ds-ml-worklows-ws kfdef

- cluster-scope/overlays/prod/common/alertmanager-main-secret.yaml
> Send alerts from opf-* namespaces to github

- cluster-scope/base/user.openshift.io/groups/octo-training-model/group.yaml
Need to add Jim to this namespace
Signed-off-by: Ryan Cook <rcook@redhat.com>
> training model - add additional user to project

- cert-manager/overlays/moc/infra/api/api-cert.yaml
Resolve: https://github.com/operate-first/apps/issues/1468
> Add dnsname to infra api cert.

- cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
Include new thoth-station member to thoth group
> Include new thoth-station member to thoth group

- argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/local-storage.yaml
- argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/odf.yaml
- cluster-scope/base/core/namespaces/openshift-local-storage/kustomization.yaml
- cluster-scope/base/core/namespaces/openshift-local-storage/namespace.yaml
- cluster-scope/base/operators.coreos.com/operatorgroups/openshift-local-storage/kustomization.yaml
- cluster-scope/base/operators.coreos.com/operatorgroups/openshift-local-storage/operatorgroup.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/odf-operator/kustomization.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/odf-operator/subscription.yaml
- cluster-scope/overlays/prod/emea/morty/kustomization.yaml
- cluster-scope/overlays/prod/emea/morty/subscriptions/local-storage-operator_patch.yaml
- cluster-scope/overlays/prod/emea/morty/subscriptions/odf-operator_patch.yaml
- local-storage/overlays/emea/morty/kustomization.yaml
- local-storage/overlays/emea/morty/localvolumediscovery.yaml
- local-storage/overlays/emea/morty/localvolumeset.yaml
- odf/README.md
- odf/base/kustomization.yaml
- odf/overlays/emea/morty/kustomization.yaml
- odf/overlays/emea/morty/ocs-storagecluster-storagesystem.yaml
- odf/overlays/emea/morty/ocs-storagecluster.yaml
> Install & configure openshift data foundation including argocd app

- cluster-scope/base/core/namespaces/training-model/kustomization.yaml
- cluster-scope/base/core/namespaces/training-model/resourcequota.yaml
The learning model is lagging during testing. We are attempting to add more CPU limits to resolve not having GPU
Signed-off-by: Ryan Cook <rcook@redhat.com>
> request more cpu for learning models

- kfdefs/base/jupyterhub/notebook-images/bu-cs-jupyterbook.yaml
small change to switch image source from docker.io to quay.io
> fix: switch to quay.io from docker.io

- docs/content/argocd-gitops/get_access_to_argocd.md
> updating argocd-gitops readme with how to get read and read/write access

- scripts/setup_pvs/README.md
Just added some lines on the README file in order to have some clarity on some steps mentioned for configuring PV.
> Updated the README file

- docs/content/odh/trino/trino_superset_user_guide.md
https://github.com/operate-first/apps/issues/1522
> change image formatting in doc

- docs/content/grafana/add_grafana_dashboard.md
Resolves [#1529](https://github.com/operate-first/apps/issues/1529)
> Updated Grafana Dashboard creation doc to newer file structure

- docs/content/observatorium/loki/README.md
- docs/content/observatorium/loki/request_loki_access.md
- docs/content/observatorium/thanos/request_grafana_access.md
Resolves https://github.com/operate-first/apps/issues/1539
> Update docs on requesting access to moc/smaug loki instance

- cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Adding suppathak as SRE group member
> Adding suppathak as SRE group member

- cluster-scope/base/core/namespaces/devconfcz-2022-demo/kustomization.yaml
- cluster-scope/base/core/namespaces/devconfcz-2022-demo/namespace.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Creating a temporary namespace - will be cleaned up/reverted in a day.
> feat: Add temporary a devconf.cz 2022 namespace

- cluster-scope/base/core/namespaces/devconfcz-2022-demo/kustomization.yaml
- cluster-scope/base/core/namespaces/devconfcz-2022-demo/namespace.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Devconf workshop is over. This reverts commit 4f95504016458ead9a9e262b4a87cbe6e4905924.
> Revert "feat: Add temporary a devconf.cz 2022 namespace"

- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
the secret-generator was removed accidentally from a previous PR https://github.com/operate-first/apps/pull/1559
Resolves https://github.com/operate-first/apps/issues/1566
cc @HumairAK @Gregory-Pereira
> fix secret generator in moc/smaug kustomization

- OWNERS
In response to slack thread in OPS channel
> adding greg and dylan as reviewers

- cluster-scope/base/core/namespaces/rapidast/kustomization.yaml
- cluster-scope/base/core/namespaces/rapidast/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/psse-research/group.yaml
- cluster-scope/base/user.openshift.io/groups/psse-research/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/psse-research/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/psse-research/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
> feat(onboarding): Add team psse-research

- kfp-tekton/overlays/moc/smaug/kustomization.yaml
> Change kfp tekton ns to kubeflow.

- cluster-scope/base/core/configmaps/openshift-pipelines-feature-flags/configmap.yaml
- cluster-scope/base/core/configmaps/openshift-pipelines-feature-flags/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
As per: https://github.com/operate-first/apps/tree/master/kfp-tekton#pre-reqs
> Enable custom tasks and switch api to alpha for ocp pipelines in smaug.

- cluster-scope/base/autoscaling.openshift.io/clusterautoscalers/default/clusterautoscaler.yaml
- cluster-scope/base/autoscaling.openshift.io/clusterautoscalers/default/kustomization.yaml
- cluster-scope/overlays/prod/emea/balrog/clusterautoscaler.yaml
- cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
- cluster-scope/overlays/prod/emea/balrog/machineautoscalers.yaml
So.. I wanted to try some :dollar: on AWS.. let's see how it goes :smile: 
According to docs we can autoscale like this:
https://docs.openshift.com/container-platform/4.8/post_installation_configuration/cluster-tasks.html#cluster-autoscaler-about_post-install-cluster-tasks
/cc @harshad16 @HumairAK @larsks
> feat: Autoscale balrog

- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/klusterletaddonconfig-editor/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/klusterletaddonconfig-editor/kustomization.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/klusterletaddonconfig-editor/clusterrole.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/klusterletaddonconfig-editor/kustomization.yaml
- cluster-scope/base/user.openshift.io/groups/klusterletaddonconfig-editors/group.yaml
- cluster-scope/base/user.openshift.io/groups/klusterletaddonconfig-editors/kustomization.yaml
- cluster-scope/bundles/klusterletaddonconfig-editor/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Members of the klusterletaddonconfig-editors group will be able to edit
klusterletaddonconfig resources.
This is a replacement for #1580
> Create klusterletaddonconfigs-editor RBAC and group

- acm/overlays/moc/infra/managedclustersetbindings/kustomization.yaml
Part of: https://github.com/operate-first/apps/pull/1546
> Add octo/osc cluster's clustersetbinding to argocd.

- cluster-scope/README.md
Please suggest any improvements for the documentation. Thanks!
> Adding the documentation for resource bundling

- cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Adding my GH ID to the SRE group
> added carlosGimeno to the sre group

- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
- kfdefs/base/kafka/kfdef.yaml
Let's use the same method of strimzi deployment like we do on balrog, and use olm instead.
> Switch strimzi management to argocd on smaug.

- cluster-scope/base/user.openshift.io/groups/klusterletaddonconfig-editors/group.yaml
> Provision klusteraddonconfig access to osc admin.

- acm/overlays/moc/infra/managedclusters/kustomization.yaml
- acm/overlays/moc/infra/managedclusters/osc-cl2.yaml
> Add osc-cl2 to osc clusterset.

- docs/content/cluster-scope/onboarding_to_cluster.md
- docs/content/notebooks/onboarding_project.ipynb
Just trying to add update examples to clarify onboarding instructions for newcomers, as some parts might be a little ambiguous to new users(who are not familiar with the Jupyter notebook mechanism) what to do exactly for onboarding.
Maintainers, please feel free to edit.
> Onboard project doc update to clarify instructions for newcomers

- kafka/base/opf-kafka.yaml
Resolves https://github.com/operate-first/apps/issues/1615
> Increase Opf Kafka PVC size from 40Gi to 60Gi

- docs/_toc.yml
- docs/content/reloader/README.md
- docs/content/reloader/monitoring-secrets-configmaps.md
Adding docs for how to use Reloader
> Adding Reloader docs to apps/docs/content

- odh-manifests/osc/superset/base/kustomization.yaml
> Remove unused osc superset rbac.

- kfdefs/overlays/osc/osc-cl1/superset/configmaps/superset_config.py
- kfdefs/overlays/osc/osc-cl2/superset/configmaps/superset_config.py
- odh-manifests/osc/superset/base/deployment.yaml
> Add osc superset db parameters.

- argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/argocd-notifications.yaml
> Update server to name for argocd notification app.

- argocd-notifications/base/configmap.yaml
- argocd-notifications/overlays/infra/kustomization.yaml
> Fix argocd url format for argocd notif config.

- kfdefs/overlays/osc/osc-cl2/trino/secrets/s3buckets.yaml
> Correct osc cl2 trino dev bucket name.

- kfdefs/base/jupyterhub/kfdef.yaml
- kfdefs/overlays/moc/smaug/opf-jupyterhub-stage/kustomization.yaml
And only add it to stage until it's confirmed working.
> Remove manual spark deployment for jh prod in smaug.

- OWNERS
For details see [WG meeting notes](https://docs.google.com/document/d/1uEcLGP_sBSNwTLPOo_2Nu6oTqPytOTBt0c0_pVUQJwo/edit#heading=h.jne3yyxa2fn7)
> Adding approvers as outcome of DevSecOps WG meeting Feb 15th

- cluster-scope/overlays/prod/moc/infra/groups/cluster-admins.yaml
- cluster-scope/overlays/prod/moc/smaug/groups/cluster-admins.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
Include harshad16 as cluster admin for infra, smaug, osc
> :guardsman: Include harshad16 as cluster admin for infra, smaug, osc

- cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
Related to slack conversation in `sig-operations` channel
> updating Margaret's permissions

- cluster-scope/base/core/namespaces/boatrockers/kustomization.yaml
- cluster-scope/base/core/namespaces/boatrockers/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/boatroackers/group.yaml
- cluster-scope/base/user.openshift.io/groups/boatroackers/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/boatroackers/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/boatroackers/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Addresses https://github.com/operate-first/support/issues/524
> onboarding boatroackers

- cosigned/base/configmap.yaml
- cosigned/base/deployment.yaml
- cosigned/base/kustomization.yaml
- cosigned/base/secret.yaml
- cosigned/base/service.yaml
- cosigned/base/serviceaccount.yaml
- cosigned/overlays/octo/kustomization.yaml
- cosigned/overlays/octo/public_secret.yaml
- cosigned/overlays/octo/rolebinding.yaml
Fix the namespace and separate out the overlay's content for cosigned
> Fix the namespace and separate out the overlay's content for cosigned

- cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/groups/odh-admin.yaml
Same as gage's Pr #1679  but using lowercase ghandles so no issues are created.
> adding gregory and gage to both osc-cl* odh-admin groups

- grafana/base/grafana.yaml
grafana v8.4 has capabilities to regex format values in a table panel, which can be very helpful in displaying data like [this](https://github.com/operate-first/apps/pull/1687).
> update smaug grafana instance to v8.4.3

- cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
SSIA
For issue https://github.com/operate-first/support/issues/531
> Add Shreyanand to superset users

- cluster-scope/base/operators.coreos.com/subscriptions/idp-mgmt-operator/subscription.yaml
The existing name is incorrect (does not exist in catalog).
> Correct idp-mgmt operator subscription name.

- cluster-scope/base/core/namespaces/chrisproject/kustomization.yaml
- cluster-scope/base/core/namespaces/chrisproject/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/redhat-impact/group.yaml
- cluster-scope/base/user.openshift.io/groups/redhat-impact/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/redhat-impact/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/redhat-impact/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Addresses: https://github.com/operate-first/support/issues/527.
> Onboarding Redhat-Impact team

- cluster-scope/base/core/namespaces/manageiq/kustomization.yaml
- cluster-scope/base/core/namespaces/manageiq/namespace.yaml
- cluster-scope/base/core/namespaces/manageiq/resourcequota.yaml
- cluster-scope/base/user.openshift.io/groups/manageiq/group.yaml
- cluster-scope/base/user.openshift.io/groups/manageiq/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/manageiq/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/manageiq/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Related to https://github.com/operate-first/support/issues/518.
Lets verify the custom resource quota before going through with this.
> Onboarding ManageIQ

- cluster-scope/base/core/namespaces/fedora/kustomization.yaml
- cluster-scope/base/core/namespaces/fedora/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/fedora/group.yaml
- cluster-scope/base/user.openshift.io/groups/fedora/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/fedora/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/fedora/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Related to https://github.com/operate-first/support/issues/500.
> Onboarding Fedora

- cluster-scope/base/core/namespaces/seraph-host-inventory/kustomization.yaml
- cluster-scope/base/core/namespaces/seraph-host-inventory/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/seraph/group.yaml
- cluster-scope/bundles/seraph/kustomization.yaml
- Part of AICoE/seraph#5
- Also add myself to seraph group
> Add namespace for seraph host inventory

- cluster-scope/overlays/prod/common/kustomization.yaml
> Add seraph group into overlay

- argocd/overlays/moc-infra/applications/envs/octo/gohan/cosigned.yaml
- argocd/overlays/moc-infra/applications/envs/octo/summit-cl1/cosigned.yaml
Fix the namespace cosigned in the agrocd app
Reference: https://github.com/operate-first/apps/tree/master/cluster-scope/base/core/namespaces/cosign-system
> Fix the namespace cosigned in the agrocd app

- cluster-scope/base/user.openshift.io/groups/manageiq/group.yaml
Resolves https://github.com/operate-first/support/issues/518#issuecomment-1064081221.
> updating managedIQ group with additional users

- cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
Add harshad as a argocd admins
Gain access to the moc-infra argocd
Made group alphabetical order
> Add harshad as a argocd admins

- cluster-scope/base/core/namespaces/rbo-builder/kustomization.yaml
- cluster-scope/base/core/namespaces/rbo-builder/namespace.yaml
- cluster-scope/components/project-admin-rolebindings/rbo/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/rbo/rbac.yaml
- cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Related to operate-first/support/issues/341
> Create project rbo-builder - operate-first/support/issues/341

- cluster-scope/base/core/namespaces/examples-openshift-pub/kustomization.yaml
- cluster-scope/base/core/namespaces/examples-openshift-pub/namespace.yaml
- cluster-scope/overlays/prod/emea/morty/kustomization.yaml
related to operate-first/support/issues/343
> Onboard examples.openshift.pub operate-first/support/issues/343

- docs/content/README.md
Add link to new morty cluster. Related to https://github.com/operate-first/apps/issues/1471
> Add link to morty cluster

- grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-postgresql-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-service-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-sli-slo.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-user-api-metrics.yaml
- grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/2431
> Add custom folder name for thoth dashboards

- pulp/overlays/moc/smaug/kustomization.yaml
- pulp/overlays/moc/smaug/opf-pulp-backup.yaml
- pulp/overlays/moc/smaug/opf-pulp.yaml
setup pulp backup for replication
Related-to: https://github.com/operate-first/support/issues/525
> setup pulp backup for replication

- cluster-scope/base/core/namespaces/pixel-demo/kustomization.yaml
- cluster-scope/base/core/namespaces/pixel-demo/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/team-pixel/group.yaml
- cluster-scope/overlays/prod/emea/morty/kustomization.yaml
adding a second project and new project-members to team
> feat(onboarding): Add team team-pixel

- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/acme-operator.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/cloudbeaver.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/cluster-resources.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/dex.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kfdefs.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/acme-operator.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/cloudbeaver.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/cluster-resources.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/das.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/dex.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kfdefs.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/kustomization.yaml
- argocd/overlays/moc-infra/projects/kustomization.yaml
- argocd/overlays/moc-infra/projects/os-climate.yaml
- cluster-scope/base/user.openshift.io/groups/osc-admins/group.yaml
Resolve: https://github.com/operate-first/apps/issues/1626
> Get OSC admins argocd access to all osc apps 

- argocd/overlays/moc-infra/secrets/clusters/octo-summit-cl1.enc.yaml
- argocd/overlays/moc-infra/secrets/clusters/secret-generator.yaml
Fix summit-cl1 setup secrets
Related-to: https://github.com/operate-first/apps/pull/1763#pullrequestreview-914677164
> Fix summit-cl1 setup secrets

- cluster-scope/base/user.openshift.io/groups/seraph/group.yaml
> feat: Add mimotej to Seraph group

- cluster-scope/base/core/namespaces/rh-curator-eval/kustomization.yaml
- cluster-scope/base/core/namespaces/rh-curator-eval/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/rh-curator-eval/group.yaml
- cluster-scope/base/user.openshift.io/groups/rh-curator-eval/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/rh-curator-eval/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/rh-curator-eval/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Addresses: https://github.com/operate-first/support/issues/536
/cc @HumairAK
> onboarding rh-curator-eval

- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties
Related: https://github.com/os-climate/data-platform-demo/issues/49
> Switch osc datacommons data catalog to iceberg.

- cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Part of: https://github.com/operate-first/apps/pull/1779
Adds contents of: https://github.com/operate-first/apps/blob/master/cluster-scope/bundles/kfp-tekton/kustomization.yaml
(2 crds)
> Add kfp tekton bundle to osc-cl2.

- cluster-scope/overlays/prod/common/kustomization.yaml
- docs/content/grafana/map_groups_to_roles.md
Forgot to add the `grafana-viewer` group to smaug. Also added documentation for getting read only access through that group.
/cc @HumairAK
> fixing map_groups_to_roles and adding grafana viewer group to smaug

- kfdefs/overlays/moc/smaug/opf-jupyterhub/kfdef.yaml
> adding the additional overlay for the jupyterhub notebook-images kfdef

- kfdefs/overlays/moc/smaug/opf-jupyterhub/kfdef.yaml
> Move kfdef jh parameters to appropriate app in smaug.

- grafana/overlays/moc/smaug/dashboards/cluster-management/node-feature-discovery.yaml
This will make the metrics datasource configurable so in future when we add more clusters, it should dynamically update the list
> [dashboard] Fix the node feature discovery grafana dashboard

- kafka/overlays/smaug/kustomization.yaml
- kafka/overlays/smaug/opf-kafdrop.yaml
Resolves https://github.com/operate-first/apps/issues/1811
> Add opf-kafdrop patch in opf-kafka-smaug app

- argocd/overlays/moc-infra/applications/envs/moc/infra/operate-first/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/infra/operate-first/opf-vault.yaml
- cluster-scope/base/core/namespaces/vault/kustomization.yaml
- cluster-scope/base/core/namespaces/vault/namespace.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/kustomization.yaml
- vault/base/configmaps/configmap.yaml
- vault/base/configmaps/kustomization.yaml
- vault/base/kustomization.yaml
- vault/base/policy/kustomization.yaml
- vault/base/policy/poddisruptionbudget.yaml
- vault/base/rbac.authorization.k8s.io/kustomization.yaml
- vault/base/rbac.authorization.k8s.io/rolebindings/rolebinding.yaml
- vault/base/rbac.authorization.k8s.io/roles/role.yaml
- vault/base/serviceaccounts/kustomization.yaml
- vault/base/serviceaccounts/serviceaccount.yaml
- vault/base/services/kustomization.yaml
- vault/base/services/opf-vault-active/service.yaml
- vault/base/services/opf-vault-internal/service.yaml
- vault/base/services/opf-vault-standby/service.yaml
- vault/base/services/opf-vault-ui/service.yaml
- vault/base/services/opf-vault/service.yaml
- vault/base/statefulsets/kustomization.yaml
- vault/base/statefulsets/statefulset.yaml
- vault/overlays/moc/infra/kustomization.yaml
Adding manifests to deploy a vault instance to the Operate first cluster
> add manifests to create Hashicorp Vault cluster in Operate First

- kfdefs/overlays/osc/osc-cl2/jupyterhub/profiles/singleuser-profiles-container-sizes.yaml
> update cl2 size options

- cluster-scope/base/core/namespaces/vault/kustomization.yaml
- cluster-scope/base/core/namespaces/vault/resourcequota.yaml
Adding custom resource quota to reflect the storage needs of the vault deployment.
> Adding custom resource quota for vault deployment in smaug

- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/k8s-annotations-exporter.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/k8s-annotations-exporter.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
- k8s-annotations-exporter/overlays/osc/osc-cl1/kustomization.yaml
- k8s-annotations-exporter/overlays/osc/osc-cl2/kustomization.yaml
Resolves https://github.com/operate-first/apps/issues/1819
> Add k8s-annotations-exporter to osc clusters

- acm/overlays/moc/infra/kustomization.yaml
> Add identitatem to acm build.

- acm/overlays/moc/infra/identitatem/authrealms/primary.yaml
- acm/overlays/moc/infra/identitatem/clients/github.enc.yaml
Use the  First Operator app for identitatem (similar to keycloak)
> Switch identitatem to use op1st github app.

- docs/content/reloader/monitoring-secrets-configmaps.md
Adding a list to show which clusters have a Reloader deployment.
> Update reloader docs to list reloader deployments by cluster

- cluster-scope/base/user.openshift.io/groups/psse-research/group.yaml
Adding jpweiser to the psse-research group for RapiDast operator development
> Add jpweiser to psse-research group

- cluster-scope/base/core/namespaces/sostrades-namespace/kustomization.yaml
- cluster-scope/base/core/namespaces/sostrades-namespace/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/sostrades/group.yaml
- cluster-scope/base/user.openshift.io/groups/sostrades/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/sostrades/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/sostrades/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Pull request following the guide 'How to onboard a new project to a cluster on Operate First Cloud' to integrate SosTrades Project in Operate-first.
> feat(onboarding): Add team sostrades

- cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
> include admin for osc-cl1

- cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
- kfdefs/overlays/osc/osc-cl1/dashboard/kfdef.yaml
- kfdefs/overlays/osc/osc-cl1/dashboard/kustomization.yaml
- kfdefs/overlays/osc/osc-cl1/kustomization.yaml
Point the osc-cl1 odh-dashboard to byon tag of manifests
Related-to: https://github.com/open-services-group/byon/issues/20
> Point the osc-cl1 odh-dashboard to byon tag of manifests

- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-logs-readers/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view-balrog/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/metrics/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review-opf-monitoring/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review-opf-observatorium/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/opf-cluster-metrics-federation/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-anyuid-observatorium/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-anyuid-tufts-dcc-6/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-privileged-opf-ci-pipelines-aicoe-ci/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-privileged-tufts-dcc-6/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-auth-proxy-role/clusterrole.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/metrics/clusterrole.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/oauth-token-access-review/clusterrole.yaml
> Update crb apiversion to v1.

- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/apirequest-count-reader/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/apirequest-count-reader/kustomization.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/apirequest-count-read-cr/clusterrole.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/apirequest-count-read-cr/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
@HumairAK So far I've only added the `clusterrole` to the infra and smaug cluster, I will add other clusters as needed
> Adding apirequestcount cluster read rights to sre group

- kfdefs/overlays/osc/osc-cl1/trino-dev/kfdef.yaml
- kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
- kfdefs/overlays/osc/osc-cl2/trino/kfdef.yaml
This parameter no longer exists.
> Remove invalid kfdef parameter.

- cluster-scope/base/core/namespaces/multinode-demo/kustomization.yaml
- cluster-scope/base/core/namespaces/multinode-demo/namespace.yaml
- cluster-scope/base/core/namespaces/multinode-demo/resourcequota.yaml
- cluster-scope/base/user.openshift.io/groups/multinode-demo/group.yaml
- cluster-scope/base/user.openshift.io/groups/multinode-demo/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/multinode-demo/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/multinode-demo/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Related: https://github.com/operate-first/support/issues/537
> Onboard multienode demo team.

- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/pytorchjobs-create-aggregate-to-admin/clusterrole.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/pytorchjobs-create-aggregate-to-admin/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Part of: https://github.com/operate-first/apps/pull/1881
Related: https://github.com/operate-first/support/issues/537
> Aggregate pytorchjobs creation to project admin osc-cl2.

- argocd/overlays/moc-infra/alerts.yaml
Introducing alerts for argocd in moc-infra. Re: https://github.com/operate-first/apps/issues/1677
> Adding argocd alerts in moc-infra

- cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
> Disable self provisioning projects in osc clusters.

- cluster-scope/base/core/namespaces/debezium-ui/namespace.yaml
- cluster-scope/base/core/namespaces/democratic-csi/namespace.yaml
- cluster-scope/base/core/namespaces/dex/namespace.yaml
- cluster-scope/base/core/namespaces/ds-example-project/namespace.yaml
- cluster-scope/base/core/namespaces/ds-github-labeler/namespace.yaml
- cluster-scope/base/core/namespaces/ds-ml-workflows-ws/namespace.yaml
- cluster-scope/base/core/namespaces/elyra-aidevsecops-tutorial/namespace.yaml
- cluster-scope/base/core/namespaces/enterprise-neurosystem-collaboration/namespace.yaml
- cluster-scope/base/core/namespaces/esi-operate-first-project/namespace.yaml
- cluster-scope/base/core/namespaces/fde-audio-decoder-demo/namespace.yaml
- cluster-scope/base/core/namespaces/fedora/namespace.yaml
- cluster-scope/base/core/namespaces/fybrik-applications/namespace.yaml
This commit is meant to add meta-labels to 15 namespaces for the continuation of adding labeled namespaces to the *Workload Overview dashboard*
Let me know if any docs or issues are incorrect, some I did leave empty due to not finding their docs or respective issues
> Gave 15 namespaces meta-labels

- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/apirequest-count-reader/clusterrolebinding.yaml
> Correct spirequest count crb subject apigroup.

- cluster-scope/base/core/namespaces/peribolos-as-a-service/kustomization.yaml
- cluster-scope/base/core/namespaces/peribolos-as-a-service/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/peribolos-as-a-service/group.yaml
- cluster-scope/base/user.openshift.io/groups/peribolos-as-a-service/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/peribolos-as-a-service/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/peribolos-as-a-service/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Created namespace `peribolos-as-a-service ` 
Added @tumido & @harshad16 as admins. Please let us know if others are needed to be added.
resolves https://github.com/open-services-group/peribolos-as-a-service/issues/31
> added peribolos namespace

- cluster-scope/base/core/namespaces/datahub-linkedin/kustomization.yaml
- cluster-scope/base/core/namespaces/datahub-linkedin/namespace.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Related: https://github.com/os-climate/os_c_data_commons/issues/80
> Add datahub linkedin namespace to osc-cl1.

- cluster-scope/base/core/namespaces/smart-village-view/kustomization.yaml
- cluster-scope/base/core/namespaces/smart-village-view/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/boston-university-redhat/group.yaml
- cluster-scope/base/user.openshift.io/groups/boston-university-redhat/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/boston-university-redhat/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/boston-university-redhat/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Onboarded into smart-village-view ns, done with a medium quota.
Related to: https://github.com/operate-first/support/issues/553
> onboarding boston-univeristy-redhat team

- cluster-scope/overlays/prod/osc/osc-cl2/groups/kubeflow-admin.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Add admins to help administer kubeflow components on osc-cl2.
> Add kubeflow admins to osc-cl2.

- cluster-scope/base/user.openshift.io/groups/boston-university-redhat/group.yaml
Resolves https://github.com/operate-first/support/issues/553
> Adding 2 more users to boston-university-redhat group, yqchenn and anlianni

- kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Signed-off-by: Erik Erlandson <eerlands@redhat.com>
> row/col access controls on sandbox.gppd

- argocd/overlays/moc-infra/configs/argo_cm/dex.config
- argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
- argocd/overlays/moc-infra/projects/kustomization.yaml
- argocd/overlays/moc-infra/projects/peribolos-service.yaml
For issue https://github.com/open-services-group/peribolos-as-a-service/issues/32
@harshad16 @tumido
> Add argocd project for peribolos service

- cluster-scope/base/core/namespaces/keylime/kustomization.yaml
- cluster-scope/base/core/namespaces/keylime/namespace.yaml
- cluster-scope/base/core/namespaces/opf-ci-pipelines/namespace.yaml
- cluster-scope/base/core/namespaces/opf-ci-prow/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/octo-training-model/group.yaml
- cluster-scope/overlays/prod/emea/morty/kustomization.yaml
This is to add [Keylime](https://keylime.dev/) registrar and verifier services.
Related to https://github.com/AICoE/summit-2022-octo-keynote/issues/6
> Add Keylime registrar and verifier

- cluster-scope/base/core/namespaces/sostrades-namespace/kustomization.yaml
- cluster-scope/base/core/namespaces/sostrades-namespace/limitrange.yaml
- cluster-scope/base/core/namespaces/sostrades-namespace/resourcequota.yaml
This is to add better resourcequota and limitrange to our namespace.
> Change LimitRange and Resourcequota for SoSTrades Namespace [OS-CLIMATE]

- cluster-scope/base/core/namespaces/openshift-distributed-tracing/kustomization.yaml
- cluster-scope/base/core/namespaces/openshift-distributed-tracing/namespace.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/jaeger-operator/subscription.yaml
- cluster-scope/bundles/jaeger-operator/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Related: https://github.com/operate-first/support/issues/491
> Add jaeger operator to smaug.

- cluster-scope/base/operators.coreos.com/operatorgroups/jaeger-operator/kustomization.yaml
- cluster-scope/base/operators.coreos.com/operatorgroups/jaeger-operator/operatorgroup.yaml
- cluster-scope/bundles/jaeger-operator/kustomization.yaml
Part of: https://github.com/operate-first/apps/pull/1932
> Add operatorgroup for jaeger on smaug.

- cluster-scope/base/user.openshift.io/groups/octo-otel-dev/group.yaml
> Adding user to the octo-otel-dev group

- docs/_toc.yml
- docs/content/odh/superset/add_superset_users.md
- docs/content/odh/superset/add_trino_db.md
> Add docs on how to add superset db. And osc access.

- acm/overlays/moc/infra/managedclusters/demo.yaml
- acm/overlays/moc/infra/managedclusters/kustomization.yaml
This cluster is no long active and was removed manually via acm, this syncs it with git.
> Remove demo managed cluster from acm.

- cluster-scope/base/core/namespaces/datahub-linkedin/kustomization.yaml
- cluster-scope/base/core/namespaces/datahub-linkedin/resourcequota.yaml
> Increase ns quota for datahub on osc-cl1.

- acm/overlays/moc/infra/managedclustersetbindings/base/drvbw.yaml
- acm/overlays/moc/infra/managedclustersetbindings/base/kustomization.yaml
- acm/overlays/moc/infra/managedclustersets/drvbw.yaml
- acm/overlays/moc/infra/managedclustersets/kustomization.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/open-cluster-management:managedclusterset:admin:drvbw/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/open-cluster-management:managedclusterset:admin:drvbw/kustomization.yaml
- cluster-scope/base/user.openshift.io/groups/drvbw/group.yaml
- cluster-scope/base/user.openshift.io/groups/drvbw/kustomization.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/clusterrolebindings/self-provisioners_patch.yaml
- cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Related: https://github.com/operate-first/apps/issues/1938
> Add new group with access to acm cluster provisioning.

- nfd/base/nfd.yaml
Resolve: https://github.com/operate-first/apps/issues/1950
> Remove unused field for nfd in morty.

- cluster-scope/base/core/namespaces/api-designer/kustomization.yaml
- cluster-scope/base/core/namespaces/api-designer/namespace.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Addresses: https://github.com/operate-first/support/issues/567
/cc @HumairAK
> onboarding ns api-designer for team apicurio

- cluster-scope/overlays/prod/moc/smaug/imageregistry.operator.openshift.io/configs/cluster/config_patch.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/objectbucketclaims/openshift-image-registry-bucket.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-generator.yaml
- cluster-scope/overlays/prod/moc/smaug/secrets/image-registry-private-configuration-user.enc.yaml
Resolves https://github.com/operate-first/support/issues/554
> Update container image registry in Smaug to use OBC instead of PVC

- argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/open-services-group/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/open-services-group/peribolos-as-a-service.yaml
set peribolos-as-a-service argo app for deployment
Fixes: https://github.com/open-services-group/peribolos-as-a-service/issues/53
> set peribolos-as-a-service argo app for deployment

- argocd/overlays/moc-infra/projects/peribolos-service.yaml
Fixes deployment of #1922
/cc @harshad16 @Shreyanand
> fix: Peribolos service app project server settings

- vault/base/kustomization.yaml
- vault/base/route/kustomization.yaml
- vault/base/route/route.yaml
As per title. 
Furthers: https://github.com/operate-first/support/issues/298
> Add ocp route for vault on smaug.

- dex/overlays/moc/smaug/dex-clients.enc.yaml
- dex/overlays/moc/smaug/dex-cm.yaml
- vault/base/route/route.yaml
Related: https://github.com/operate-first/support/issues/298
> Add oidc via dex to vault smaug.

- cluster-scope/overlays/prod/moc/smaug/externalsecrets/alert-manager.yaml
- cluster-scope/overlays/prod/moc/smaug/secretstores/openshift-monitoring.yaml
> Correct secretstore name in monitoring ns.

- cluster-scope/overlays/prod/moc/smaug/groups/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/groups/vault-admins.yaml
- cluster-scope/overlays/prod/moc/smaug/groups/vault-emea-admins.yaml
- cluster-scope/overlays/prod/moc/smaug/groups/vault-moc-admins.yaml
- cluster-scope/overlays/prod/moc/smaug/groups/vault-osc-admins.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Furthers: https://github.com/operate-first/apps/issues/1993
> Add ocp groups for vault access by env.

- docs/_toc.yml
- docs/content/vault/README.md
- docs/content/vault/add_cluster_to_eso_and_vault.md
Related:  https://github.com/operate-first/apps/issues/1992
> Add docs on enabling cluster with eso & vault.

- cluster-scope/base/core/namespaces/opf-obcs/kustomization.yaml
- cluster-scope/base/core/namespaces/opf-obcs/namespace.yaml
- cluster-scope/overlays/prod/emea/morty/kustomization.yaml
- docs/content/odh/trino/add_more_buckets.md
- kfdefs/overlays/moc/smaug/trino/configs/catalogs/data_science_general_morty.properties
- kfdefs/overlays/moc/smaug/trino/configs/kustomization.yaml
- kfdefs/overlays/moc/smaug/trino/hive-metastores/data_science_general_morty/kustomization.yaml
- kfdefs/overlays/moc/smaug/trino/hive-metastores/kustomization.yaml
- kfdefs/overlays/moc/smaug/trino/secrets/s3buckets.enc.yaml
- odf/overlays/emea/morty/kustomization.yaml
- odf/overlays/emea/morty/route.yaml
Related: https://github.com/operate-first/apps/issues/2014
> Add morty s3

- kfdefs/overlays/moc/smaug/trino/configs/catalogs/data_science_general_morty.properties
> Correct trino hive metastore route for morty s3 bucket.

- cluster-scope/base/core/namespaces/curator-operator/kustomization.yaml
- cluster-scope/base/core/namespaces/curator-operator/namespace.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Adding namespace resources for [https://github.com/operate-first/curator-operator](https://github.com/operate-first/curator-operator) in response to [https://github.com/operate-first/support/issues/575](https://github.com/operate-first/support/issues/575)
> Adding curator-operator namespace to smaug cluster

- cluster-scope/base/core/namespaces/chrisproject-dev/kustomization.yaml
- cluster-scope/base/core/namespaces/chrisproject-dev/namespace.yaml
- cluster-scope/base/core/namespaces/chrisproject-staging/kustomization.yaml
- cluster-scope/base/core/namespaces/chrisproject-staging/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/chris-project/group.yaml
- cluster-scope/base/user.openshift.io/groups/chris-project/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/chris-project/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/chris-project/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
For issue https://github.com/operate-first/support/issues/581
Signed-off-by: Shreekar <sshreeka@redhat.com>
> Onboarding chrisproject

- argocd/overlays/moc-infra/applications/envs/moc/smaug/apicurio/api-designer.yaml
check https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
> Enable automatic self-healing and pruning

- argocd/overlays/moc-infra/applications/envs/moc/smaug/chris/kustomization.yaml
- argocd/overlays/moc-infra/projects/chris.yaml
- cluster-scope/base/user.openshift.io/groups/chris-project/group.yaml
Fixes: https://github.com/operate-first/support/issues/584
> Added  new GH users

- cluster-scope/base/user.openshift.io/groups/curator/group.yaml
Currently a summer intern in Heidi's Team. Hence making a request.
> Added avrajath to cluster admin for curator cluster

- argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
> Add chris project to argocd apps for smaug.

- argocd/overlays/moc-infra/projects/chris.yaml
> Correct argocd chris proj ns format.

- cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml
Include another member to thoth devsecops team 
> Include another member to thoth devsecops team

- cluster-scope/base/core/namespaces/ddas-proj/kustomization.yaml
- cluster-scope/base/core/namespaces/ddas-proj/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/eldritch-team13/group.yaml
- cluster-scope/base/user.openshift.io/groups/eldritch-team13/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/eldritch-team13/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/eldritch-team13/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
For Red Hat Research project in disinformation detection at scale
Related-to: https://github.com/operate-first/support/issues/587
> feat(onboarding): Add team eldritch-team13

- docs/content/notebooks/onboarding_project.ipynb
Resolve: https://github.com/operate-first/support/issues/588
> Clarify onboading notebook push instructions.

- kfdefs/overlays/moc/smaug/superset/configmaps/superset_config.py
Resolve: https://github.com/operate-first/support/issues/589
> Disable csrf for smaug superset.

- cluster-scope/base/core/namespaces/demolab-dev/kustomization.yaml
- cluster-scope/base/core/namespaces/demolab-dev/namespace.yaml
- cluster-scope/base/core/namespaces/demolab-staging/kustomization.yaml
- cluster-scope/base/core/namespaces/demolab-staging/namespace.yaml
- cluster-scope/base/core/namespaces/demolab/kustomization.yaml
- cluster-scope/base/core/namespaces/demolab/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/demolab_team/group.yaml
- cluster-scope/base/user.openshift.io/groups/demolab_team/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/demolab_team/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/demolab_team/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
in response to: https://github.com/operate-first/support/issues/586
> onboarding demolab

- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reports.curator.operatefirst.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reports.curator.operatefirst.io/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Adding curator operator crd for Curator Team
> Add curator-operator-report-crd to Smaug Cluster

- cluster-scope/base/core/namespaces/peribolos-as-a-service/kustomization.yaml
> feat: Make peribolos visible to public in OCP

- cluster-scope/base/core/namespaces/opf-jupyterhub/resourcequota.yaml
- docs/content/odh/jupyterhub/runbook.md
resolves https://github.com/operate-first/support/issues/593
> increased jh limit and updated runbook

- cluster-scope/base/core/namespaces/curator-operator/kustomization.yaml
Addressing: https://operatefirst.slack.com/archives/C01RMPVUUK1/p1655822091027819
> increase curator-operator-system namespace resource quota

- observatorium/overlays/moc/smaug/loki/secrets/loki-objectstorage-secret.enc.yaml
- observatorium/overlays/moc/smaug/thanos/secrets/thanos-objectstorage-secret.enc.yaml
Set temp obc for observatorium components from morty
Related-to: https://github.com/operate-first/apps/issues/2064
Fixes: https://github.com/operate-first/apps/issues/2048
> Set temp obc for observatorium components from morty

- docs/content/odh/superset/runbook.md
Instructions on how to resolve issues like: https://github.com/operate-first/support/issues/594#issuecomment-1162252235
> Add docs on resolving superset perm issue.

- cluster-scope/base/core/namespaces/inception/kustomization.yaml
- cluster-scope/base/core/namespaces/inception/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/inception-admins/group.yaml
- cluster-scope/base/user.openshift.io/groups/inception-admins/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/inception-admins/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/inception-admins/rbac.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/groups/inception-admins.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Also provision a new admin group for this namespace with users. 
Furthers: https://github.com/os-climate/corporate_data_pipeline/issues/55
> Add inception namespace to osc-cl1.

- cluster-scope/base/user.openshift.io/groups/superset-admins/group.yaml
- cluster-scope/base/user.openshift.io/groups/superset-admins/kustomization.yaml
- cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- docs/content/odh/superset/add_superset_users.md
- kfdefs/overlays/moc/smaug/superset/configmaps/superset_config.py
Resolve: https://github.com/operate-first/support/issues/596
> Create superset admin group.

- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/curatorconfig.curatoroperator.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/curatorconfig.curatoroperator.io/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
> curator-operator-config-crd

- cluster-scope/base/user.openshift.io/groups/scsaol/group.yaml
We've added a new member (SuJingyu111) to our group.
> Added new member to group.yaml

- cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml
- cluster-scope/base/user.openshift.io/groups/seldon-admin/group.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- docs/content/odh/seldon/README.md
Resolve: https://github.com/operate-first/support/issues/597
> Add a new seldon admins group for smaug.

- cluster-scope/base/core/namespaces/ds-ml-workflows-ws/resourcequota.yaml
https://github.com/operate-first/support/issues/598
> increased memory limit for seldon ns

- cluster-scope/base/operators.coreos.com/subscriptions/minio-operator/kustomization.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/minio-operator/subscription.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
In response to: [https://github.com/operate-first/operations/issues/482](https://github.com/operate-first/operations/issues/482)
and 
[https://operatefirst.slack.com/archives/C01RT0S2WKX/p1656520150421829](https://operatefirst.slack.com/archives/C01RT0S2WKX/p1656520150421829)
> Add subscription for minio in smaug

- cluster-scope/base/user.openshift.io/groups/b4mad/group.yaml
> Add Alex-exe-dev to B4mad group

- docs/_toc.yml
- docs/content/vault_eso/restore_vault.md
- docs/content/vault_eso/runbook.md
- docs/content/vault_eso/vault_backup_job.md
- vault/overlays/moc/smaug/backup-job/cronjob.yaml
- vault/overlays/moc/smaug/backup-job/kustomization.yaml
- vault/overlays/moc/smaug/backup-job/pvc.yaml
- vault/overlays/moc/smaug/backup-job/rolebinding.yaml
- vault/overlays/moc/smaug/backup-job/sa.yaml
- vault/overlays/moc/smaug/backup-job/secret.yaml
- vault/overlays/moc/smaug/backup-job/task.yaml
- vault/overlays/moc/smaug/backup-job/taskrun.yaml
- vault/overlays/moc/smaug/backup-job/toolkitpod.yaml
- vault/overlays/moc/smaug/kustomization.yaml
Resolve: https://github.com/operate-first/apps/issues/2077
> Add backup job.

- cluster-scope/base/core/namespaces/bu-cs-book-dev/kustomization.yaml
- cluster-scope/base/core/namespaces/bu-cs-book-dev/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/bu-cs-book-dev/group.yaml
- cluster-scope/base/user.openshift.io/groups/bu-cs-book-dev/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/bu-cs-book-dev/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/bu-cs-book-dev/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
This namespace is being added for intern @abirami-dhayalan 
CC @hpdempsey
> Add bu-cs-book-dev namespace and group to smaug

- cluster-scope/base/core/namespaces/opf-jupyterhub/resourcequota.yaml
resolves https://github.com/operate-first/support/issues/600
> increased jh cpu resources

- docs/_toc.yml
- docs/content/cluster-scope/runbooks/emea/runbook.md
- docs/content/cluster-scope/runbooks/moc/runbook.md
- docs/content/cluster-scope/runbooks/runbook.md
To help document issues and resolution steps for issues like: 
https://github.com/operate-first/operations/issues/484
> Add cluster management runbooks to docs.

- kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
… that can be used for ingestion and open metadata prototyping.
Signed-off-by: MichaelTiemannOSC <mtiemann@os-climate.org>
> Added a publicly visible personal sandbox for @MichaelTiemannOSC

- service-catalog/components/argo.yaml
- service-catalog/components/dex.yaml
- service-catalog/components/grafana.yaml
- service-catalog/components/observatorium.yaml
- service-catalog/components/odf.yaml
- service-catalog/components/odh.yaml
Add logos to currently defined components to display them nicely on service catalog homepage
/cc @SamoKopecky
> feat: Add logos to service catalog components

- service-catalog/components/argo.yaml
- service-catalog/components/dex.yaml
- service-catalog/components/grafana.yaml
- service-catalog/components/observatorium.yaml
- service-catalog/components/odf.yaml
- service-catalog/components/odh.yaml
Adds ArgoCD widget to components in service page
Part of https://github.com/operate-first/service-catalog/issues/20
> feat: Add ArgoCD widget to components service catalog

- grafana/overlays/moc/smaug/datasources/grafanadatasource.enc.yaml
Update the new datasource sa token for grafana
Fixes: https://github.com/operate-first/support/issues/609
Related-to: https://github.com/operate-first/apps/issues/2132
> :zap: Update the new datasource sa token for grafana

- cluster-scope/base/core/namespaces/aiops-tools-workshop/kustomization.yaml
- cluster-scope/base/core/namespaces/aiops-tools-workshop/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/aiops-tools-workshop-admins/group.yaml
- cluster-scope/base/user.openshift.io/groups/aiops-tools-workshop-admins/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/aiops-tools-workshop-admins/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/aiops-tools-workshop-admins/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Furthers: 
https://github.com/operate-first/community/issues/206
https://github.com/open-services-group/scrum/issues/3
> Onboard aiops-tools workshop.

- cluster-scope/base/core/namespaces/aiops-tools-workshop/namespace.yaml
Resolve: https://github.com/operate-first/apps/pull/2143#issuecomment-1185751833
> Correct typo in namespace display name.

- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/dex/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
- docs/content/vault_eso/runbook.md
Related: https://github.com/operate-first/apps/issues/1996
> Replace secrets

- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/curatorconfig.curatoroperator.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fetchdata.curatoropertor.openshift.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mpijobs.kubeflow.org/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mxjobs.kubeflow.org/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/pytorchjobs.kubeflow.org/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reports.curator.operatefirst.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/tfjobs.kubeflow.org/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/xgboostjobs.kubeflow.org/customresourcedefinition.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-manager-role/clusterrole.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-compute-notebook.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-notebook-gpu-g.yaml
- node-labeler/serviceaccount.yaml
- openmetadata/base/openmetadata-dependencies/deployments/airflow-db-migrations.yaml
- openmetadata/base/openmetadata-dependencies/deployments/airflow-scheduler.yaml
- openmetadata/base/openmetadata-dependencies/deployments/airflow-sync-users.yaml
- openmetadata/base/openmetadata-dependencies/deployments/airflow-web.yaml
- openmetadata/base/openmetadata-dependencies/services/mysql-headless.yaml
- openmetadata/base/openmetadata-dependencies/services/mysql.yaml
- openmetadata/base/openmetadata-dependencies/statefulsets/elasticsearch.yaml
- openmetadata/base/openmetadata-dependencies/statefulsets/mysql.yaml
- openmetadata/base/openmetadata/jobs/openmetadata-db-migrations-hook.yaml
- prow/overlays/smaug/ghproxy.yaml
- prow/overlays/smaug/imagestreamtags.yaml
- vault/overlays/moc/smaug/backup-job/cronjob.yaml
This PR fixes various issues which were reported by kubeval tool. This changes were made using updated schemas which are not yet merged: https://github.com/operate-first/schema-store/pull/7
Part of: https://github.com/open-services-group/scrum/issues/6
> fix: Fix issues in manifests apps repository

- cluster-scope/base/operator.tekton.dev/tektonconfigs/config/tektonconfig.yaml
Resolves: https://github.com/operate-first/support/issues/610
> Use alpha api fields for tekton.

- cluster-scope/overlays/prod/moc/curator/externalsecrets/pull-secret.yaml
- cluster-scope/overlays/prod/moc/infra/externalsecrets/pull-secret.yaml
- cluster-scope/overlays/prod/moc/smaug/externalsecrets/pull-secret.yaml
Follow up to: https://github.com/operate-first/apps/pull/2159
> Correct pull-secret target name.

- cluster-scope/overlays/prod/moc/curator/externalsecrets/pull-secret.yaml
- cluster-scope/overlays/prod/moc/infra/externalsecrets/pull-secret.yaml
- cluster-scope/overlays/prod/moc/smaug/externalsecrets/pull-secret.yaml
> Add pull secret type dockerconfigjson for moc.

- cluster-scope/base/core/namespaces/markets-svc-dev/kustomization.yaml
- cluster-scope/base/core/namespaces/markets-svc-dev/namespace.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Related: https://github.com/os-climate/os_c_data_commons/issues/191
> Add kafka testing namespace in osc-cl2.

- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/curator-operator-manager-rb/clusterrolebinding.yaml
- cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/curator-operator-oauth-proxy-rb/clusterrolebinding.yaml
- curator-operator-system/base/rbac.authorization.k8s.io/rolebindings/rolebinding.yaml
- curator-operator-system/base/serviceaccounts/serviceaccount.yaml
Dylan trying to resolve the issue that we discussed regarding the leader election role trying to access the service account that didn't exist.
> Resolving service account naming issue from curator-operator

- cluster-scope/base/user.openshift.io/groups/aiops-tools-workshop-admins/group.yaml
Related: https://github.com/operate-first/community/issues/206
> Add aiops tools workshop admins.

- argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/workshops/aiops-tools-workshop.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/workshops/kustomization.yaml
- argocd/overlays/moc-infra/projects/workshops.yaml
Furthers: https://github.com/operate-first/community/issues/206
> Add argocd app & proj for aiops tools workshop.

- argocd/overlays/moc-infra/applications/envs/moc/smaug/workshops/aiops-tools-workshop.yaml
> Correct aiops tools workshop project name.

- cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-readers.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-readers.yaml
Related: https://github.com/os-climate/os_c_data_commons/issues/190
> Provide cluster reader for osc clusters to user.

- workshops/aiops-tools/smaug/patches/cb_resources_patch.yaml
Furthers: https://github.com/operate-first/community/issues/206
> Correct workshoip cloudbeaver's memory request.

- workshops/aiops-tools/base/odh-configs/jupyterhub/container-sizes.yaml
- workshops/aiops-tools/base/odh-configs/jupyterhub/jupyterhub-singleuser-profiles-configmap.yaml
Furthers: https://github.com/operate-first/community/issues/206
> Adjust aiops tools workshop jh sizes.

- workshops/aiops-tools/README.md
- workshops/aiops-tools/base/dex/configmaps/files/config.yaml
- workshops/aiops-tools/base/dex/configmaps/kustomization.yaml
- workshops/aiops-tools/base/dex/kustomization.yaml
- workshops/aiops-tools/base/external-secrets-operator/kustomization.yaml
- workshops/aiops-tools/base/secrets/dex-clients.yaml
- workshops/aiops-tools/base/secrets/file-auth-secret.yaml
- workshops/aiops-tools/base/secrets/kustomization.yaml
- workshops/aiops-tools/base/secrets/postgres-dbs.yaml
- workshops/aiops-tools/base/secrets/s3buckets.yaml
- workshops/aiops-tools/base/secrets/superset-custom.yaml
- workshops/aiops-tools/base/secrets/supersetdb.yaml
- workshops/aiops-tools/base/secrets/trino-oauth.yaml
Furthers: https://github.com/operate-first/community/issues/206
> Add set up docs for aiops tools workshop.

- grafana/overlays/moc/smaug/dashboards/kustomization.yaml
- grafana/overlays/moc/smaug/dashboards/workshops/aiops-tools-workshop.yaml
- grafana/overlays/moc/smaug/dashboards/workshops/kustomization.yaml
View dashboard here: 
https://grafana.operate-first.cloud/d/tW6jgRz4k/aiops-tools-workshop?orgId=1&from=now-30m&to=now
Furthers: 
https://github.com/operate-first/community/issues/206
> Add aiops-tools-workshop monitoring dashboard.

- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-notebook-gpu-p.yaml
Fixes issues in clusters which were found by kubeval
Part of: https://github.com/open-services-group/scrum/issues/6
> fix: Fix issues in clusters

- cluster-scope/base/user.openshift.io/groups/fybrik/group.yaml
Signed-off-by: mohammad-nassar10 <mohammad.nassar@ibm.com>
> Update the list of users in fybrik group.

- service-catalog/components/peribolos-as-a-service.yaml
Part of https://github.com/operate-first/service-catalog/issues/12
SSIA
> feat(service-catalog): Add k8s plugin annotation to peribolos

- cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
Working on bringing Fybrik to SOC Clusters. I'm working on the below steps
Add [Fybrik bundle](https://github.com/operate-first/apps/tree/master/cluster-scope/bundles/fybrik) to [osc-cl1 overlay](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml). See smaug example [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/moc/smaug/kustomization.yaml#L143). Feel free to inspect bundle to see what is being installed.
Groups in OSC are handled separate than Smaug and other OPF clusters, so we add them separately.
Fybrik group is [here](https://github.com/operate-first/apps/tree/master/cluster-scope/base/user.openshift.io/groups/fybrik). For ArgoCD/OCP access to Fybrik project, please add all members …
> Added ravitejamanepalli in argocd-readonly group

- cluster-scope/base/user.openshift.io/groups/okd-team/group.yaml
- cluster-scope/base/user.openshift.io/groups/okd-team/kustomization.yaml
Adds a group for use by Red Hatters working on OKD
/cc @durandom 
/cc @aleskandro
/cc @cheesesashimi
/cc @dmueller2001
/cc @lmzuccarelli
/cc @LorbusChris
/cc @sandrobonazzola
/cc @sherine-k
/cc @travier
/cc @vrutkovs
> Add okd-team group

- cluster-scope/base/user.openshift.io/groups/okd-wg/group.yaml
- cluster-scope/base/user.openshift.io/groups/okd-wg/kustomization.yaml
Adds a group for use by the OKD Working Group (includes both Red Hatters, and non-Red Hatters)
/cc @durandom 
/cc @aleskandro
/cc @bdlink
/cc @binnes
/cc @cheesesashimi
/cc @dmueller2001
/cc @JaimeMagiera
/cc @lmzuccarelli
/cc @LorbusChris
/cc @sandrobonazzola
/cc @sherine-k
/cc @travier
/cc @vrutkovs
> Add okd-wg group

- cluster-scope/base/core/namespaces/banzaicloud-vault/kustomization.yaml
- cluster-scope/base/core/namespaces/banzaicloud-vault/namespace.yaml
- cluster-scope/base/operators.coreos.com/operatorgroups/banzaicloud-vault/kustomization.yaml
- cluster-scope/base/operators.coreos.com/operatorgroups/banzaicloud-vault/operatorgroup.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/banzaicloud-vault/kustomization.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/banzaicloud-vault/subscription.yaml
- cluster-scope/bundles/banzaicloud-vault/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Sandbox namespace for testing new operators etc
> Add banzaicloud-vault ns to smaug and banzaicloud vault operator subscription

- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/fybrik/fybrik.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/fybrik/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/fybrik/vault.yaml
- argocd/overlays/moc-infra/projects/fybrik.yaml
Signed-off-by: mohammad-nassar10 <mohammad.nassar@ibm.com>
> Adding argocd apps to osc-cl2.

- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/kustomization.yaml
Left over from: https://github.com/operate-first/apps/pull/2202
> Add fybrik argocd apps to osc-cl2.

- cluster-scope/base/core/namespaces/otel-dev/kustomization.yaml
/cc @HumairAK
/cc @schwesig 
The deployment in this ns will eventually be managed by argocd, working on that now, also
> otel-dev public viewable

- slack-first/overlays/moc/smaug/config.yaml
This PR changes rotation period from `weekly` to `daily` .  It also adds members to on-call rotation
> Change on-call rotation period and add members to on-call duty

- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Related: https://github.com/os-climate/os_c_data_commons/issues/193
> Add Kafka connector to osc-cl2 trino.

- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/fx.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Resolve: https://github.com/os-climate/os_c_data_commons/issues/193
> Add fx table schema for osc-cl2 trino.

- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/stackrox/kustomization.yaml
had to fix the commit history. It should be fine now.
> added stackrox to secret management

- cluster-scope/base/user.openshift.io/groups/sre/group.yaml
- docs/content/acm/README.md
fixes https://github.com/operate-first/apps/issues/2206
@Gregory-Pereira @HumairAK can you help me with pointing me in the right direction?
> adding cooktheryan to ACM users and docs

- cluster-scope/base/operators.coreos.com/operatorgroups/banzaicloud-vault/operatorgroup.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/banzaicloud-vault/subscription.yaml
This should fix the error with the vault operator subscription and the syncing issue in argoCD
> Update vault operator catalogSource & operatorGroup

- kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
- kfdefs/base/jupyterhub/notebook-images/ope.yaml
As part of our effort to decompose the open education effort into generic and book specific infrastructure, we have created a new ope image stream
> Add ope image stream and updated ucsls

- kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
- kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml
- kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-operator-deployment.yaml
Updated the version of ray components to ray v1.13.0
> :arrow_up: Updated the version of ray components to ray v1.13.0

- argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/octo-otel-dev/hello-opentelemetry.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/octo-otel-dev/kustomization.yaml
- argocd/overlays/moc-infra/projects/kustomization.yaml
- argocd/overlays/moc-infra/projects/otel-dev.yaml
/cc @HumairAK 
let's see if this works
> add otel-dev sample otlp app to argocd

- argocd/overlays/moc-infra/applications/envs/moc/smaug/octo-otel-dev/hello-opentelemetry.yaml
@HumairAK thanks for your help!
> fix octo-otel-dev helm paramaters

- argocd/overlays/moc-infra/projects/otel-dev.yaml
> Correct wildcard in otel-dev argocd proj.

- cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml
- cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
- Removing fridex and pacospace
- adding VannTen (Max Gautier)
> update thoth members

- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_hive_ingest.properties
Follow up to: https://github.com/operate-first/apps/pull/2234
> Fix service name for hive ingest osc trino.

- docs/content/odh/trino/add_more_buckets.md
To prevent issues like: https://github.com/operate-first/apps/pull/2239
> Correct metastore uri in trino docs.

- kfdefs/overlays/osc/osc-cl2/trino/secrets/s3buckets.yaml
Follow up to: https://github.com/operate-first/apps/pull/2241
> Correct hive ingest s3 creds key/id osc-cl2.

- cluster-scope/base/core/namespaces/api-designer/kustomization.yaml
- cluster-scope/base/core/namespaces/api-designer/resourcequota.yaml
- cluster-scope/base/core/namespaces/apicurio-apicurio-registry/kustomization.yaml
- cluster-scope/base/core/namespaces/apicurio-apicurio-registry/resourcequota.yaml
Follow up on Support request:
https://github.com/operate-first/support/issues/623
> Increase ResourceQuota for Apicurio projects

- cluster-scope/base/user.openshift.io/groups/odh-admin/group.yaml
This is to add myself to the `odh-admin` group, with the goal of getting access to the osc cluster to use it for CD for the ODH CNBi functionality.
Also taking the opportunity to sort the user list in that group alphabetically.
> Add Pep to the odh-admin group

- prow/OWNERS
- prow/README.md
- prow/overlays/smaug/config.yaml
- prow/overlays/smaug/imagestreamtags.yaml
- prow/overlays/smaug/plugins.yaml
- prow/overlays/smaug/secrets.enc.yaml
- prow/update-imagestreams.py
Updated the prow config, plugin, and secrets
- cleaned the branch-protection
- removed some org-specific labels
- updated the secrets
> :hatched_chick: Updated the prow config, plugin and secrets

- prow/README.md
- prow/overlays/smaug/ghproxy.yaml
- prow/overlays/smaug/imagestreamtags.yaml
Fix the image for init contianer for prow task
This fix the issue with CI jobs.
> Fix the image for init contianer for prow task

- slack-first/overlays/moc/smaug/config.yaml
> feat: Remove max from on-call

- cluster-scope/base/core/namespaces/kvm-device-plugin/kustomization.yaml
- cluster-scope/base/core/namespaces/okd-centos/kustomization.yaml
- kvm-device-plugin/base/buildconfig.yaml
Follow up to https://github.com/operate-first/apps/pull/2219
/cc @HumairAK
> OKD infra fixups

- cluster-scope/base/core/namespaces/ds-ml-workflows-ws/resourcequota.yaml
This ns is hitting limits, cannot create seldon deployments.
> Increase quota for ds-ml-workflows ns.

- grafana/overlays/moc/smaug/grafana-oauth.yaml
- observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
Addresses: https://github.com/operate-first/support/issues/621
/cc @HumairAK 
/cc @harshad16
> giving apicurio group thanos and grafana access

- argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-jerry.yaml
- argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/emea/jerry/cluster-management/cluster-resources.yaml
- argocd/overlays/moc-infra/applications/envs/emea/jerry/cluster-management/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/emea/jerry/kustomization.yaml
- cluster-scope/overlays/prod/emea/jerry/groups/cluster-admins.yaml
- cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
@HumairAK not sure if this is needed, if we get cluster-admin via SSO?!
> add cluster-admins for jerry

- cluster-scope/overlays/prod/moc/smaug/groups/vault-admins.yaml
I will be working on https://github.com/operate-first/service-catalog/issues/59 which will allow the service catalog to access all the clusters not just smaug. For that I need access to all the clusters in our vault instance.
> feat: Add myself to vault admins

- kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Add aicoe_osc_demo_results schema in the osc_datacommons_dev Catalog. 
@erikerlandson
> Add aicoe_osc_demo_results schema

- docs/content/acm/README.md
- docs/content/argocd-gitops/get_access_to_argocd.md
Came up in the process of resolving ACM access support issue.
/cc @HumairAK
> updating documentation for getting acm acess

- kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
> Update github handle of Shreyanand

- kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
> correct aicoe_osc_demo schema group name

- cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml
> feat: Upgrade ACM operator to 2.5

- cluster-scope/base/apps/daemonsets/kepler-exporter/daemonset.yaml
> Fix unit for kepler ds memory.

- cluster-scope/bundles/grafana-operator/kustomization.yaml
- cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Related: https://github.com/os-climate/os_c_data_commons/issues/190
> Add grafana operator to morty.

- cluster-scope/base/user.openshift.io/groups/osc/group.yaml
access for debugging kfp issue.
/cc @HumairAK
> adding myself to osc group for ml-kubeflow-pipelines access

- cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
more osc acccess stuffs.
/cc @HumairAK 
/cc @redmikhail
> adding myself to osc cluster admins for ml-kubeflow-pipelines access

- cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/opf-monitoring/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/opf-monitoring/kustomization.yaml
- grafana/overlays/osc/osc-cl1/datasources/grafanadatasource.yaml
- grafana/overlays/osc/osc-cl1/kustomization.yaml
> Opf monitoring eso osc

- contributing.md
- docs/_toc.yml
- docs/content/kubeval/README.md
- docs/content/kubeval/updating_schema_store.md
> Add kubeval docs

- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/riskthinking.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Defines a catalog using trino BigQuery connector to the RiskThinking.ai BigQuery data.
> riskthinking catalog

- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/grafana.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
- grafana/overlays/osc/common/dashboards/kustomization.yaml
[Re-add kepler to grafana dashboards in osc.](https://github.com/operate-first/apps/commit/c532c50fb0439f654c39882e3a5522b67e04371a)
[Add grafana argocd app to oscl2.](https://github.com/operate-first/apps/commit/5790d433da0b5e8f8cf96cda18c2e17e45623041)
Related: https://github.com/os-climate/os_c_data_commons/issues/190
> Add configmap

- cluster-scope/base/user.openshift.io/groups/sre/group.yaml
> chore: Add myself to SRE group

- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kepler.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/machineconfigs/kepler/55-worker-kernel-devel-cgroupv2.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/machineconfigs/kepler/kustomization.yaml
- kepler/overlays/osc/osc-cl2/kustomization.yaml
Should close: https://github.com/os-climate/os_c_data_commons/issues/190
> Add kepler to osc-cl2.

- argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/fybrik/fybrik.yaml
Signed-off-by: mohammad-nassar10 <mohammad.nassar@ibm.com>
Fixes #2322
> Configure helm chart not to deploy namespaces.

- kepler/base/kustomization.yaml
related https://github.com/os-climate/os_c_data_commons/issues/190
> Remove unneeded labels from kepler service.

- kafka/overlays/osc/osc-cl2/prometheus-kafka-adapter/deployment.yaml
- kafka/overlays/osc/osc-cl2/prometheus-kafka-adapter/service.yaml
- kafka/overlays/osc/osc-cl2/prometheus-kafka-adapter/serviceaccount.yaml
> Remove labels that conflict with argocd.

- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/kepler.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Closes https://github.com/os-climate/os_c_data_commons/issues/192
> Add kepler metrics to osc-cl2 trino.

- cluster-scope/overlays/prod/osc/osc-cl1/groups/kepler-admins.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/groups/kepler-admins.yaml
Grant Vincent access to grafana for editing Kepler Garafana dashboards part of https://github.com/os-climate/os_c_data_commons/issues/190
> Adding Vincent  for Kepler Grafana on cl1 and cl2

- kfdefs/overlays/osc/osc-cl2/trino/configs/config-coordinator.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/config-worker.properties
Reverts operate-first/apps#2365
Addresses: https://operatefirst.slack.com/archives/C03LCPTPZ6J/p1662137015554229
/cc @erikerlandson
> Revert "enable debug for bq plugin, per request from trino devs"

- grafana/overlays/moc/smaug-public/dashboards/operate-first/opf-projects-overview.yaml
solves https://github.com/open-services-group/scrum/issues/40
> add grafana-public dashboard

- cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
SSIA
I am working on https://github.com/operate-first/service-catalog/issues/59 and I need to see wheter the resources added in #2344 were added correctly.
> feat: Add myself to argocd-admins

- cluster-scope/base/core/serviceaccounts/service-catalog-k8s-plugin/kustomization.yaml
- cluster-scope/base/core/serviceaccounts/service-catalog-k8s-plugin/serviceaccount.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/emea/balrog/configmaps/service-catalog-k8s-plugin.yaml
- cluster-scope/overlays/prod/moc/curator/configmaps/service-catalog-k8s-plugin.yaml
- cluster-scope/overlays/prod/moc/infra/configmaps/service-catalog-k8s-plugin.yaml
- cluster-scope/overlays/prod/moc/smaug/configmaps/service-catalog-k8s-plugin.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/configmaps/service-catalog-k8s-plugin.yaml
Part of https://github.com/operate-first/service-catalog/issues/59
SSIA
> feat(catalog): Add missing SA and namespace for config maps used by cronjobs

- cluster-scope/base/ocs.openshift.io/ocsinitializations/ocsinit/kustomization.yaml
- cluster-scope/base/ocs.openshift.io/ocsinitializations/ocsinit/ocsinitialization.yaml
- cluster-scope/base/ocs.openshift.io/storageclusters/ocs-external-storagecluster/storagecluster.yaml
- cluster-scope/base/odf.openshift.io/storagesystems/ocs-external-storagecluster-storagesystem/kustomization.yaml
- cluster-scope/base/odf.openshift.io/storagesystems/ocs-external-storagecluster-storagesystem/storagesystem.yaml
- cluster-scope/bundles/odf-external/kustomization.yaml
- cluster-scope/bundles/odf/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/externalsecrets/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/externalsecrets/rook-ceph-external-cluster-details.yaml
- cluster-scope/overlays/prod/moc/infra/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/secret-mgmt/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/secret-mgmt/openshift-storage/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/subscriptions/odf-operator_patch.yaml
Part of: https://github.com/operate-first/operations/issues/475
Depends on: https://github.com/operate-first/apps/pull/2296 https://github.com/operate-first/apps/pull/2360
/hold
Requires credentials to be created in Vault first
/cc @larsks @HumairAK
> feat: Install ODF in external mode to Infra cluster

- docs/content/cluster-scope/add_user_to_project_admin.md
created documentation for giving project ownership. This is a rough draft that should be looked at by others and modified if needed.
> documentation for project admin created

- cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/cronjob.yaml
- cluster-scope/bundles/service-catalog-k8s-plugin/kustomization.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
Changes to cronjob:
* export `VAULT_TOKEN` variable so that vault can see it
* fix secret creation
Changes to manifests:
* Create a bundle from manifests so that it is grouped in one logical part
> feat(catalog): Move manifests to a bundle, fix cronjob

- cluster-scope/base/core/namespaces/open-cluster-management-observability/kustomization.yaml
- cluster-scope/base/core/namespaces/open-cluster-management-observability/namespace.yaml
- cluster-scope/overlays/prod/moc/infra/externalsecrets/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/externalsecrets/multiclusterhub-operator-pull-secret.yaml
- cluster-scope/overlays/prod/moc/infra/externalsecrets/thanos-object-storage.yaml
- cluster-scope/overlays/prod/moc/infra/kustomization.yaml
- cluster-scope/overlays/prod/moc/infra/multiclusterobservability/observability.yaml
- cluster-scope/overlays/prod/moc/infra/secret-mgmt/open-cluster-management-observability/kustomization.yaml
Addresses most of: https://github.com/operate-first/apps/issues/2337
/cc @HumairAK
> enabling amc-mco on infra

- prow/base/statusreconciler.yaml
- prow/base/tide.yaml
- prow/overlays/smaug/config.yaml
- prow/overlays/smaug/kustomization.yaml
- prow/overlays/smaug/secrets.enc.yaml
Since the current prow configuration seems to work to some extent, I have commented out the OBC manifest in the `kustomization.yaml` and other references to it, so we may use it again whenever we wish.
/cc @harshad16
> moving prow storage to ionos s3 bucket

- prow/base/horologium.yaml
- prow/base/plank.yaml
Fix the rbac of prow for argocd sync
> :recycle: Fix the rbac of prow for argocd sync

- cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/cronjob.yaml
> feat(catalog): Replace put with patch in cronjob

- cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
> Add kafka ns to osc-cl1 in sync with osc-cl2.

- grafana/overlays/moc/smaug-public/grafana-public.yaml
- grafana/overlays/moc/smaug/grafana-oauth.yaml
> Correct grafana label.

- kfdefs/overlays/moc/smaug/trino/externalsecrets/kustomization.yaml
part of: https://github.com/operate-first/apps/pull/2405
> Include ESO secrets into smaug trino kustomization.

- openmetadata/OWNERS
> Add osc owners to openmetadata folder.

- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/nodes/oct-03-00-compute.yaml
- cluster-scope/overlays/prod/moc/smaug/nodes/oct-03-01-compute.yaml
- cluster-scope/overlays/prod/moc/smaug/nodes/oct-03-03-compute.yaml
Enables https://github.com/operate-first/apps/pull/2383
As per https://github.com/operate-first/apps/pull/2383#issuecomment-1246541156
/cc @larsks
> feat: Label nodes to enable kvm machineconfigpool

- cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/cronjob.yaml
Permit the `CronJob` to make changes to only one shared secret.
> feat(catalog): Use a common role in cronjob

- prow/overlays/smaug/config.yaml
- prow/overlays/smaug/plugins.yaml
:pray: welcome redhatet repo homomorphic to be handled by prow
- setup Tide, plugins, in-repo prowjobs for the redhatet/homomorphic repo
Related-to: https://github.com/operate-first/support/issues/627
> :pray: welcome redhatet repo homomorphic to be handled by prow

- dex/overlays/osc/osc-cl2/configmaps/files/config.yaml
- openmetadata/base/openmetadata-dependencies/configmaps/files/webserver_config.py
- openmetadata/base/openmetadata-dependencies/rolebindings/airflow.yaml
- openmetadata/overlays/osc/osc-cl2/configmaps/files/auth_roles_mapping.json
- openmetadata/overlays/osc/osc-cl2/configmaps/files/dex_provider_cfg.json
- openmetadata/overlays/osc/osc-cl2/configmaps/kustomization.yaml
- openmetadata/overlays/osc/osc-cl2/externalsecrets/dex-provider-cfg.yaml
- openmetadata/overlays/osc/osc-cl2/externalsecrets/kustomization.yaml
- openmetadata/overlays/osc/osc-cl2/kustomization.yaml
- openmetadata/overlays/osc/osc-cl2/patches/deployments/airflow-db-migrations.yaml
- openmetadata/overlays/osc/osc-cl2/patches/deployments/airflow-scheduler.yaml
- openmetadata/overlays/osc/osc-cl2/patches/deployments/airflow-sync-users.yaml
- openmetadata/overlays/osc/osc-cl2/patches/deployments/airflow-web.yaml
- openmetadata/overlays/osc/osc-cl2/patches/deployments/airlfow-triggerer.yaml
- openmetadata/overlays/osc/osc-cl2/patches/deployments/elasticsearch.yaml
- openmetadata/overlays/osc/osc-cl2/patches/deployments/mysql.yaml
Follow up to: https://github.com/os-climate/os_c_data_commons/issues/202
> Add oidc login to airflow for openmetadata.

- openmetadata/base/openmetadata-dependencies/configmaps/files/webserver_config.py
Part of: https://github.com/operate-first/apps/pull/2420
> Enable login group sync for airflow.

- argocd/overlays/moc-infra/projects/operate-first.yaml
> whitelisting external secrets for argocd op1st project

- service-catalog/groups/operate-first.yaml
- service-catalog/users/operate-first.yaml
Update Group and User with some profile details in service catalog
/cc @SamoKopecky
> chore: Update group/user in service catalog

- docs/content/vault_eso/runbook.md
Documenting here as we encountered this earlier today.
> Add docs on updating jwt for vault runbook.

- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/api-designer/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/apicurio-apicurio-registry/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
Part of: https://github.com/operate-first/support/issues/620
> feat: Add apicurio project to vault secret managament

- k8s-annotations-exporter/overlays/emea/morty/kustomization.yaml
> removing morty overlay from k8s-annotations-exporter deployment

- argocd/overlays/moc-infra/applications/envs/moc/curator/cluster-management/cert-manager.yaml
- argocd/overlays/moc-infra/applications/envs/moc/curator/cluster-management/kustomization.yaml
> adding an argocd app for cert-manager to curator under cluster-management

- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/opf-grafana-public/kustomization.yaml
> Enable secret mgmt on opf grafana public ns.

- cluster-scope/overlays/prod/moc/smaug/groups/vault-admins.yaml
> feat: Add myself as vault admin

- prow/overlays/smaug/config.yaml
Resolve https://github.com/thoth-station/core/issues/456
See [Thoth tech talk](https://docs.google.com/document/d/1jz4j07Q8gkv9H-23BgOp_4qN3uI29JsuP-_kTKEj-e8/edit#heading=h.5eiqu7cdu6o2) for context.
> Drop prow autoclosing for thoth-station

- argocd/overlays/moc-infra/externalsecrets/clusters/moc-infra.yaml
- argocd/overlays/moc-infra/externalsecrets/clusters/octo-gohan.yaml
- argocd/overlays/moc-infra/externalsecrets/clusters/octo-summit-cl1.yaml
part of : https://github.com/operate-first/apps/pull/2448
> Add argocd cluster secret annotation to identify clusters.

- kfdefs/overlays/osc/osc-cl2/superset/externalsecrets/supersetdb.yaml
current target name is incorrect.
> Corrected superset target db secret name.

- cluster-scope/overlays/prod/emea/jerry/apiserver/api_server_cert.yaml
- cluster-scope/overlays/prod/emea/jerry/apiserver/kustomization.yaml
- cluster-scope/overlays/prod/emea/jerry/ingresscontrollers/default.yaml
- cluster-scope/overlays/prod/emea/jerry/ingresscontrollers/kustomization.yaml
- cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
Should resolve the issue of certs that are added by cert-manager not being picked up by jerry.
> Add ingress/api certs to ingress-controller & apiserver config.

- argocd/overlays/moc-infra/configs/argo_cm/dex.config
- argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
> Add copilot group to argocd dex.

- openmetadata/overlays/dev/README.md
- openmetadata/overlays/dev/kustomization.yaml
- openmetadata/overlays/dev/patches/configmaps/openmetadata-dependencies-config-envs.yaml
- openmetadata/overlays/dev/patches/deployments/openmetadata.yaml
- openmetadata/overlays/dev/secret/airflow-mysql-secrets.yaml
- openmetadata/overlays/dev/secret/airflow-secrets.yaml
- openmetadata/overlays/dev/secret/kustomization.yaml
- openmetadata/overlays/dev/secret/mysql-init-scripts.yaml
- openmetadata/overlays/dev/secret/mysql-secrets.yaml
- openmetadata/overlays/dev/secret/mysql.yaml
- openmetadata/overlays/dev/secret/openmetadata-dependencies-config-envs.yaml
- openmetadata/overlays/dev/secret/openmetadata-envs.yaml
Resolve: https://github.com/operate-first/support/issues/1101
> Added openmetadata dev deployment with docs.

- cluster-scope/base/user.openshift.io/groups/grafana-viewer/group.yaml
As per a recommendation I got in operate-first/support#629
> Added roastdeer

- cluster-scope/base/core/namespaces/kaoto/kustomization.yaml
- cluster-scope/base/core/namespaces/kaoto/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/kaoto/group.yaml
- cluster-scope/base/user.openshift.io/groups/kaoto/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/kaoto/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/kaoto/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
fixes https://github.com/operate-first/support/issues/969
> onboard kaoto

- kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
These are the new schemas for ESSD, DERA and WRI data pipelines
/cc @HumairAK @erikerlandson
> Adding new pipeline schemas for osc-cl2

- cluster-scope/base/core/namespaces/kaoto/kustomization.yaml
- cluster-scope/base/core/namespaces/kaoto/namespace.yaml
wrong apiversion
/assign @mimotej 
@mimotej do you know why this hasn't been caught by the schema validator?
> fix kaoto namespace

- kafka/overlays/osc/osc-cl2/kustomization.yaml
- kafka/overlays/osc/osc-cl2/topics/ecb-fx.yaml
- kafka/overlays/osc/osc-cl2/topics/kustomization.yaml
- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/ecb-trino-schema.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
For: https://github.com/os-climate/os_c_data_commons/issues/203
> Add ecb-fx kafka topic to trino.

- cluster-scope/overlays/prod/osc/osc-cl2/configmaps/user-workload-monitoring-config.yaml
> Remove remote write kepler metrics in oscl2.

- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/ecb-trino-schema.json
see: https://github.com/os-climate/os_c_data_commons/issues/203
> Correct date format for edb-fx topic.

- service-catalog/resources.yaml
- service-catalog/resources/curator.yaml
- service-catalog/resources/jerry.yaml
- service-catalog/resources/osc-cl1.yaml
- service-catalog/resources/osc-cl2.yaml
> feat(catalog): Add rest of clusters to service catalog

- service-catalog/apis.yaml
- service-catalog/apis/github-webhooks-consumer.yaml
- service-catalog/components.yaml
- service-catalog/components/openshift-pipelines-operator-smaug.yaml
- service-catalog/components/peribolos-controller.yaml
- service-catalog/components/probot-kubernetes.yaml
- service-catalog/components/probot-metrics.yaml
- service-catalog/domains.yaml
- service-catalog/domains/community.yaml
- service-catalog/systems.yaml
- service-catalog/systems/openshift-pipelines-smaug.yaml
- service-catalog/systems/peribolos.yaml
Adds peribolos and its dependencies - Tekton and probot-extensions
/cc @SamoKopecky 
please review
> feat: Add peribolos to service catalog

- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/ecb-trino-schema.json
Resolve: https://github.com/os-climate/os_c_data_commons/issues/203
> Correct ecb-fx topic name in trino config.

- docs/_toc.yml
- docs/content/vault_eso/runbook.md
- docs/content/vault_eso/unsealing_vault.md
Instructions to resolve issues like : https://github.com/operate-first/support/issues/1107
> Add docs on how to unseal and rejoin, vault node.

- kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Signed-off-by: Erik Erlandson <eerlands@redhat.com>
> explict rule to make system catalog readable

- service-catalog/components.yaml
- service-catalog/components/prow-controller-manager.yaml
- service-catalog/components/prow-crier.yaml
- service-catalog/components/prow-deck.yaml
- service-catalog/components/prow-ghproxy.yaml
- service-catalog/components/prow-hook.yaml
- service-catalog/components/prow-horologium.yaml
- service-catalog/components/prow-needs-rebase.yaml
- service-catalog/components/prow-plank.yaml
- service-catalog/components/prow-sinker.yaml
- service-catalog/components/prow-statusreconciler.yaml
- service-catalog/components/prow-tide.yaml
- service-catalog/systems.yaml
- service-catalog/systems/prow.yaml
> feat: Add Prow to service catalog

- cluster-scope/base/core/namespaces/gingersnap/kustomization.yaml
- cluster-scope/base/core/namespaces/gingersnap/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/gingersnap/group.yaml
- cluster-scope/base/user.openshift.io/groups/gingersnap/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/gingersnap/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/gingersnap/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
fixes https://github.com/operate-first/support/issues/1105
@ryanemerson please have a look
@mimotej @HumairAK please review
> onboard gingersnap

- cluster-scope/overlays/prod/emea/jerry/groups/cluster-admins.yaml
> chore: Add tumido to jerry admins

- cluster-scope/base/core/namespaces/b4mad-racing/kustomization.yaml
- cluster-scope/base/core/namespaces/b4mad-racing/resourcequota.yaml
- grafana/overlays/moc/common/dashboards/b4mad/kustomization.yaml
- grafana/overlays/moc/common/dashboards/b4mad/telemeter.yaml
- grafana/overlays/moc/common/dashboards/kustomization.yaml
bumping resource quota
/assign @tumido 
@tumido can you approve please?
> bumping resource quota for b4mad-racing

- cluster-scope/base/core/namespaces/sostrades/resourcequota.yaml
Resolve: https://github.com/operate-first/apps/issues/2523
> Increase storage quota for sostrades.

- dex/base/deployments/dex-deployment.yaml
> updating dex container image to 2.35.1

- cluster-scope/base/core/namespaces/kepler-edge/kustomization.yaml
- cluster-scope/base/core/namespaces/kepler-edge/namespace.yaml
- cluster-scope/base/core/namespaces/kepler-edge/resourcequota.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Part of https://github.com/operate-first/apps/issues/2490
> Onboard kepler edge demo

- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kepler/kepler-edge-demo.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kepler/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kustomization.yaml
- argocd/overlays/moc-infra/configs/argo_cm/dex.config
- argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
- argocd/overlays/moc-infra/projects/kepler.yaml
- argocd/overlays/moc-infra/projects/os-climate.yaml
- cluster-scope/base/user.openshift.io/groups/kepler-admins/group.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/groups/kepler-admins.yaml
Part of: https://github.com/operate-first/apps/issues/2490
> Add kepler edge argocd app

- cluster-scope/overlays/prod/osc/osc-cl1/groups/kepler-admins.yaml
part of: https://github.com/operate-first/apps/issues/2490
> Add user to kepler admins in osc-cl1.

- cluster-scope/base/core/namespaces/kepler-edge/resourcequota.yaml
part of: https://github.com/operate-first/apps/issues/2490
> Add resourcequota.

- argocd/overlays/moc-infra/projects/kepler.yaml
part of: https://github.com/operate-first/apps/issues/2490
> Fix kepler edge namespace in kepler proj.

- cluster-scope/base/core/namespaces/highlander/kustomization.yaml
- cluster-scope/base/core/namespaces/highlander/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/highlander/group.yaml
- cluster-scope/base/user.openshift.io/groups/highlander/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/highlander/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/highlander/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
onboard highlander
/assign @tumido 
cc @guimou
> onboard highlander

- cluster-scope/base/core/namespaces/ai4cloudops/kustomization.yaml
- cluster-scope/base/core/namespaces/ai4cloudops/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/ai4cloudops/group.yaml
- cluster-scope/base/user.openshift.io/groups/ai4cloudops/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/ai4cloudops/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/ai4cloudops/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
fixes https://github.com/operate-first/support/issues/1112
cc @mtoslalibu @syedmohdqasim
/assign @tumido
> onboard ai4cloudops

- cluster-scope/overlays/prod/emea/jerry/groups/cluster-admins.yaml
Found that I am currently not able to view secrets in certain namespaces.
> adding myself to jerry cluster admins for secret acces

- grafana/overlays/osc/common/dashboards/json/data-pipeline-resources.json
- grafana/overlays/osc/common/grafana_oauth_patch.yaml
Also extend permissions to odh users/admin for osc grafana.
> Add more charts to osc resource dashboard.

- grafana/overlays/osc/common/dashboards/data-pipeline-resources.yaml
> Update osc dashboard folder destination in osc.

- grafana/overlays/osc/common/dashboards/json/data-pipeline-resources.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_osclimate.properties
- kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/co2signal-trino-schema.json
- kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Related: https://github.com/os-climate/os_c_data_commons/issues/213
> Add kafka catalog osc

- kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/co2signal-trino-schema.json
Related: https://github.com/os-climate/os_c_data_commons/issues/213
> Correct co2signal schema in osc-cl2 trino.

- prow/OWNERS
By now I feel I am familiar enough with prow to review and approve changes to its config.
As there are only a couple of approvers for it at the moment, I'm offering myself to contribute :smiley:.
> [prow] Add myself as an approver/reviewer for prow

- cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
@harshad16: that's the correct file right ? (for access working on CNBi)
> Adding myself for odh-admin (osc-cl1)

- prow/overlays/smaug/config.yaml
Enforce use of lgtm and approved for thoth org PR merges
Related-to: https://github.com/AICoE/sefkhet-abwy/issues/204
> Enforce use of lgtm and approved for thoth org PR merges

- grafana/base/grafana.yaml
> Upgrade grafana for smaug/smaug_public.

- grafana/overlays/common/dashboards/compute-resources-overview/configmaps/files/cluster-cpu-overview.json
- grafana/overlays/common/dashboards/compute-resources-overview/configmaps/files/cluster-memory-overview.json
- grafana/overlays/common/dashboards/compute-resources-overview/configmaps/files/cluster-pod-overview.json
- grafana/overlays/common/dashboards/compute-resources-overview/configmaps/files/cluster-storage-overview.json
Make the common dashboards more generic, remove cluster specific details.
> Generalize common dashboards.

- grafana/overlays/moc/common/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
- grafana/overlays/moc/common/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
- grafana/overlays/moc/common/dashboards/thoth-station/thoth-postgresql-metrics.yaml
- grafana/overlays/moc/common/dashboards/thoth-station/thoth-service-metrics.yaml
- grafana/overlays/moc/common/dashboards/thoth-station/thoth-sli-slo.yaml
- grafana/overlays/moc/common/dashboards/thoth-station/thoth-user-api-metrics.yaml
- grafana/overlays/moc/common/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
Update thoth-station grafana dashboards
Related-to: https://github.com/thoth-station/thoth-application/issues/2663
> Update thoth-station grafana dashboards

- service-catalog/apis/backstage.yaml
SSIA
How it looks:
/cc @tumido
> feat(catalog): Add cluster status API documentation

- cluster-scope/base/core/namespaces/kepler-edge/resourcequota.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
For: https://github.com/operate-first/apps/issues/2490
> Add cluster admin user to osc-cl1.

- kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/riskthinking.properties
Signed-off-by: Eric Ball <MightyNerdEric@users.noreply.github.com>
> Update project-id in riskthinking.properties

- argocd/overlays/moc-infra/projects/global_project.yaml
Resolve: https://github.com/operate-first/apps/issues/2576
> Allow all argocd projects to deploy external secret resource.

- cluster-scope/base/core/namespaces/ray-bu/kustomization.yaml
- cluster-scope/base/core/namespaces/ray-bu/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/ray-bu/group.yaml
- cluster-scope/base/user.openshift.io/groups/ray-bu/kustomization.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
@syedmohdqasim @MichaelClifford please review
/assign @HumairAK 
fixes https://github.com/operate-first/support/issues/1108
> onboard ray-bu

- cluster-scope/base/core/namespaces/wildlfy-service/kustomization.yaml
- cluster-scope/base/core/namespaces/wildlfy-service/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/wildfly/group.yaml
- cluster-scope/base/user.openshift.io/groups/wildfly/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/wildfly/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/wildfly/rbac.yaml
- cluster-scope/overlays/prod/common/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
fixes https://github.com/operate-first/support/issues/1102
> onboard wildfly

- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/okd-centos/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/okd-centos/opf-vault-store.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/okd-team/kustomization.yaml
- cluster-scope/overlays/prod/moc/smaug/secret-mgmt/okd-team/opf-vault-store.yaml
In response to: https://github.com/operate-first/support/issues/1130
/cc @HumairAK
> granting vault access to the okd-team in nses okd-centos and okd-team

- cluster-scope/base/core/namespaces/ai4cloudops/kustomization.yaml
- cluster-scope/base/core/namespaces/ai4cloudops/resourcequota.yaml
fixes https://github.com/operate-first/support/issues/1132
> increasing quota for ai4cloudops project

- argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/robozome.yaml
- robozome/base/kustomization.yaml
- robozome/overlays/moc/smaug/externalsecret.yaml
- robozome/overlays/moc/smaug/kustomization.yaml
Adds robozome manifests / argocd app to apps repo.
> Create robozome argocd app and add deployment manifests.

- robozome/overlays/moc/smaug/kustomization.yaml
> Specify images for robozome from apps repo

- kfdefs/overlays/osc/osc-cl2/jupyterhub/pvcs/kustomization.yaml
- kfdefs/overlays/osc/osc-cl2/jupyterhub/pvcs/suppathak.yaml
Re request by @suppathak in slack: 
```
Surya Pathak
[Today at 9:21 AM](https://operatefirst.slack.com/archives/C03LCPTPZ6J/p1668090101309589)
Hello everyone,
I am facing some problem spawning my jupyterhub server: https://jupyterhub-odh-jupyterhub.apps.odh-cl2.apps.os-climate.org/
I want to request for larger PVC. Thanks
```
> Increase pvc size for user in osc-cl2 jh.

- cluster-scope/base/security.openshift.io/securitycontextconstraints/apicurio-debug-scc/kustomization.yaml
- cluster-scope/base/security.openshift.io/securitycontextconstraints/apicurio-debug-scc/securitycontextconstraint.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/1136
> feat: Add apicurio SCC allowing SYS_ADMIN for debugging

- cluster-scope/base/core/namespaces/wildfly-service/kustomization.yaml
- cluster-scope/base/core/namespaces/wildfly-service/namespace.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Also fixes name of the service
Fixes https://github.com/operate-first/support/issues/1135
> Increase WildFly quota

- kfdefs/overlays/osc/osc-cl1/cnbi/kfdef.yaml
- kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml
Using odhdashboardconfig overlays for cnbi
depends-on: https://github.com/operate-first/odh-manifests/pull/49
> Using odhdashboardconfig overlays for cnbi

- cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
indentation is because I used `kustomize` to edit the file
add the registry configuration and pvc
> configure internal registry for jerry

- cluster-scope/base/user.openshift.io/groups/emporous-devs/group.yaml
Add additional admin to project
> add additional admin to emporous project

- cluster-scope/base/operators.coreos.com/operatorgroups/apex/kustomization.yaml
- cluster-scope/base/operators.coreos.com/operatorgroups/apex/operatorgroup.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/apex-rhsso-operator/kustomization.yaml
- cluster-scope/base/operators.coreos.com/subscriptions/apex-rhsso-operator/subscription.yaml
- cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
This partially reverts commit 006a2082e0f54867f80e7a9a9960e6beaf02e86c.
Resolves: https://github.com/operate-first/support/issues/1145
> Install RH SSO operator into `apex` namespace

- kfdefs/overlays/osc/OWNERS
Signed-off-by: Erik Erlandson <eerlands@redhat.com>
> add LF folks to owners

- cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
deploying tekton pipelines to jerry.
🤞 this is enough
> add openshift-pipelines to jerry

- cluster-scope/base/core/namespaces/apex/namespace.yaml
to enable TaskRun and PipelineRun objects/instances pruning.
Signed-off-by: Anil Vishnoi <vishnoianil@gmail.com>
> Add OpenShift Pipeline annotations to namespace apex

- service-catalog/apis.yaml
- service-catalog/apis/pulp.yaml
- service-catalog/components.yaml
- service-catalog/components/pulp-operator.yaml
- service-catalog/components/pulp.yaml
- service-catalog/groups.yaml
- service-catalog/groups/pulp.yaml
- service-catalog/systems.yaml
- service-catalog/systems/pulp.yaml
- service-catalog/users.yaml
- service-catalog/users/pulp.yaml
Signed-off-by: Fabricio Aguiar <fabricio.aguiar@gmail.com>
> feat: Add pulp to service catalog

- OWNERS
To optimize approval process for changes to OS-climate project resources , please add myself `redmikhail` to approvers list
> Add Mikhail Mikhailitchenko to approvers list

- cluster-scope/base/user.openshift.io/groups/ttm-as-a-service/group.yaml
Include data science members to ttm-as-a-service group
> Include data science members to ttm-as-a-service group

- cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
> Add ryanaslett (Linux Foundation) as cluster-admin

- cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
> Add ryanaslett (Linux Foundation) to cluster admins

- prow/overlays/smaug/imagestreamtags.yaml
> update imagestreamtags to point to todays release 🎄

- pulp/overlays/moc/smaug/opf-pulp.yaml
trying ingress to see if the cert works
> Adding route TLS secret to pulp

- argocd/overlays/moc-infra/projects/kruize
- argocd/overlays/moc-infra/projects/kruize.yaml
- argocd/overlays/moc-infra/projects/kustomization.yaml
adding the ArgoCD project file for Kruize HPO deployment
> Adding Kruize HPO as part of ArgoCD

- kfdefs/overlays/osc/OWNERS
I should probably have access here too.
> Add Linux Foundation user ryanaslett

- cluster-scope/base/core/namespaces/thoth-amun-inspection-prod/resourcequota.yaml
- cluster-scope/base/core/namespaces/thoth-backend-prod/resourcequota.yaml
- cluster-scope/base/core/namespaces/thoth-frontend-prod/resourcequota.yaml
- cluster-scope/base/core/namespaces/thoth-graph-prod/resourcequota.yaml
- cluster-scope/base/core/namespaces/thoth-middletier-prod/resourcequota.yaml
- cluster-scope/base/core/namespaces/thoth-test-core/resourcequota.yaml
> increase the resource quota of some thoth namespaces

- cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
This PR is to add myself to the ArgoCD admins group. From time to time I keep finding that I can't access X or Y resource in ArgoCD, and this is an attempt at fixing that. Let me know if this is overkill.
Also taking the opportunity to remove Anand, who I believe is not active anymore.
> Add Pep to ArgoCD admins

- argocd/overlays/moc-infra/projects/apex.yaml
- argocd/overlays/moc-infra/projects/kustomization.yaml
Onboards Apex to ArgoCD.
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
> Onboard Apex to ArgoCD

- argocd/overlays/moc-infra/projects/global_project.yaml
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
> argocd: Add postgres operator to global_project template

- argocd/overlays/moc-infra/projects/apex.yaml
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
> argocd: Allow apex project to deploy to apex-*

- service-catalog/apis/backstage.yaml
Change API definition for the OCM plugin, see https://github.com/janus-idp/backstage-plugins/pull/67.
> chore: Update ocm API definition

- scripts/onboarding.sh
Should resolve issue in https://github.com/operate-first/apps/pull/2697
> fix: Fix issue with rolebinding being listed as component

- .github/workflows/techdocs.yaml
> docs: Fix typo in mco entity name for docs generation

- cluster-scope/base/user.openshift.io/groups/janus-idp/group.yaml
This PR is to add schultzp2020 and myself (PatAKnight) to the Janus-IDP users group.
> Add Janus-IDP users

- cluster-scope/base/core/namespaces/aicos-osc-demo/kustomization.yaml
- cluster-scope/base/core/namespaces/aicos-osc-demo/namespace.yaml
- cluster-scope/base/user.openshift.io/groups/aicos-osc-admins/group.yaml
- cluster-scope/base/user.openshift.io/groups/aicos-osc-admins/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/aicos-osc-demo/kustomization.yaml
- cluster-scope/components/project-admin-rolebindings/aicos-osc-demo/rbac.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/groups/kubeflow-admin.yaml
- cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
> Adding new namespace for to OS-Climate cl2

- argocd/overlays/moc-infra/applications/envs/moc/smaug/janus-idp/janus-idp.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/janus-idp/kustomization.yaml
- argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
This PR is to add the Janus-IDP Showcase app to ArgoCD
> Add Janus-IDP Showcase app

- .prow.yaml
> feat: Add higher timeout for kubeval job

- cluster-scope/base/user.openshift.io/groups/aicos-osc-admins/group.yaml
- cluster-scope/overlays/prod/osc/osc-cl2/groups/odh-users.yaml
This is to add myself to OS-Climate's cl2 aicos-osc-demo team (#2734), to work together with @Shreyanand and @suppathak on the demo.
> Add Pep to the OS-Climate aicos demo team

- cluster-scope/overlays/prod/moc/infra/kustomization.yaml
This reverts commit 52309430db8814ed1e0037fffbbd9c7faac2ce48.
> Revert "fix(infra): revert ingress cert to default"

- dex/overlays/osc/osc-cl1/configmaps/files/config.yaml
I know we're closing this out soon, but getting this working here will likely help us solve issues when deploying to our new cluster.
> fix: Add openmetadata-airflow to cli1 dex config

- dex/overlays/osc/osc-cl1/configmaps/files/config.yaml
> fix: Set dex redirect uri to cl1

- cluster-scope/base/user.openshift.io/groups/janus-idp/group.yaml
> chore: add debsmita to janus idp

- cluster-scope/base/core/namespaces/janus-idp/kustomization.yaml
- cluster-scope/base/core/namespaces/janus-idp/resourcequota.yaml
The Janus-idp namespace needs a quota increase
> bump resources

- cluster-scope/base/core/namespaces/janus-idp/resourcequota.yaml
> missing G in quota defintion
