operate-first/apps

README.md
Changes requested in #3 by @Humair and pre-approved by @martinpovolny 
Sesheta was so hyped and merged it already. :smile:
=> Reword overrides/manifests

kfdef/jupyterhub/notebook-images/categorical-encoding.yaml, kfdef/jupyterhub/notebook-images/kustomization.yaml
Addresses https://github.com/operate-first/odh-moc-support/issues/2
=> Add additional JH notebook imagestreams

kfdef/jupyterhub/notebook-images/categorical-encoding.yaml
Accidentally merged some issues in #25
=> Fix pre-commit issues

.pre-commit-config.yaml, kfdef/monitoring/grafana.yaml, kfdef/monitoring/kfdef.yaml, kfdef/monitoring/kustomization.yaml, yamllint-config.yaml
=> Add grafana operator and resource

kfdef/argo/kfdef.yaml, kfdef/argo/kustomization.yaml
=> Add argo kfdef

kfdef/superset/kfdef.yaml, kfdef/superset/overrides/base/pvc.yaml
=> Add superset pvc override

kfdef/jupyterhub/notebook-images/cloud-price-analysis.yaml, kfdef/jupyterhub/notebook-images/kustomization.yaml
* Added cloud-price-analysis.yaml 
* Update kustomization.yaml
=> Add Cloud Price Analysis notebook image to notebook-images

base/kafka/kfdef.yaml, base/kafka/kustomization.yaml, overlays/crc/kafka/kustomization.yaml, overlays/moc/kafka/kustomization.yaml, overlays/moc/kafka/overrides/kafka/base/kafka-cluster.yaml, overlays/quicklab/kafka/kustomization.yaml
Add Kafka: 
related: [this](https://github.com/operate-first/odh-moc-support/issues/27) and #10 
The override is the same as the one in odh-manifests, but I suspect we want to be able to tune it further, so I include it here to give us that flexibility.
=> Added kafka component

docs/add_kafka_topics.md, overlays/crc/kafka/topics/kustomization.yaml, overlays/moc/kafka/kustomization.yaml, overlays/moc/kafka/topics/kustomization.yaml, overlays/quicklab/kafka/kustomization.yaml, overlays/quicklab/kafka/topics/kustomization.yaml
Related: [this](https://github.com/operate-first/odh-moc-support/issues/27) and #10
=> Added structure for topic creation with docs

odh/overlays/moc/kafka/topics/kustomization.yaml, odh/overlays/moc/kafka/topics/thoth-advise-justification.yaml, odh/overlays/moc/kafka/topics/thoth-adviser-re-run.yaml, odh/overlays/moc/kafka/topics/thoth-adviser-trigger.yaml, odh/overlays/moc/kafka/topics/thoth-hash-mismatch.yaml, odh/overlays/moc/kafka/topics/thoth-kebechet-trigger.yaml, odh/overlays/moc/kafka/topics/thoth-missing-package-version.yaml, odh/overlays/moc/kafka/topics/thoth-missing-package.yaml, odh/overlays/moc/kafka/topics/thoth-package-extract-trigger.yaml, odh/overlays/moc/kafka/topics/thoth-package-released.yaml, odh/overlays/moc/kafka/topics/thoth-provenance-checker-trigger.yaml, odh/overlays/moc/kafka/topics/thoth-qebhwt-trigger.yaml, odh/overlays/moc/kafka/topics/thoth-si-unanalyzed-package.yaml, odh/overlays/moc/kafka/topics/thoth-solved-package.yaml, odh/overlays/moc/kafka/topics/thoth-unresolved-package.yaml, odh/overlays/moc/kafka/topics/thoth-unrevsolved-package.yaml, odh/overlays/moc/kafka/topics/thoth-update-provides-source-distro.yaml
include project thoth kafkatopics to the kafka instance
Related-to: thoth-station/thoth-application#709
=> include project thoth kafkatopics to the kafka instance

docs/encrypting_applications.md
=> Added docs for encrypting secrets & other resources.

docs/odh/grafana/README.md, docs/odh/grafana/add_grafana_dashboard.md
Including documentation on how to add grafana dashboards
This closes #92.
=> Add grafana documentation

odh/base/monitoring/alertmanager-config.yaml, odh/base/monitoring/alertmanager-route.yaml, odh/base/monitoring/alertmanager-service.yaml, odh/base/monitoring/alertmanager.yaml, odh/base/monitoring/kustomization.yaml, odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
=> Add prometheus alertmanager

namespaces/overlays/moc/mesh-for-data/namespace.yaml, namespaces/overlays/moc/open-aiops/namespace.yaml
Labels are limited in length on values. Annotations are not. Would this work, @HumairAK ?
=> fix: move issue url from labels to annotations

namespaces/overlays/moc/mesh-for-data/group.enc.yaml
[Related](https://github.com/open-infrastructure-labs/moc-cnv-sandbox/issues/7)
=> Add user to mesh-for-data group

odh/base/monitoring/overrides/grafana-operator/base/grafana.yaml, odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-dashboard.yaml
fix JH grafana dashboard
Closes #112
=> Remove oauth proxy from grafana

observatorium/components/rbac/kustomization.yaml, observatorium/components/rbac/monitoring-role.yaml, observatorium/components/rbac/monitoring-rolebinding.yaml, odh/components/rbac/kustomization.yaml, odh/components/rbac/monitoring-role.yaml, odh/components/rbac/monitoring-rolebinding.yaml, odh/overlays/moc/monitoring/kustomization.yaml, odh/overlays/moc/monitoring/servicemonitors/kustomization.yaml, odh/overlays/moc/monitoring/servicemonitors/observatorium-servicemonitor.yaml
Add servicemonitor for Observatorium app
Close #75
=> Add monitoring role and rolebinding to all odh + observatorium namespaces

odh/overlays/moc/monitoring/datasource/thoth-station-datasource.yaml
fix and update the datasource manifest for thoth
Related-to: https://github.com/operate-first/apps/pull/117
=> fix and update the datasource manifest for thoth

namespaces/overlays/moc/opf-ci-pipelines/kustomization.yaml, namespaces/overlays/moc/opf-ci-pipelines/namespace.yaml, namespaces/overlays/moc/opf-ci-pipelines/rbac.yaml, namespaces/overlays/moc/opf-ci-prow/kustomization.yaml, namespaces/overlays/moc/opf-ci-prow/namespace.yaml, namespaces/overlays/moc/opf-ci-prow/rbac.yaml
namespace requirements for continuous integration components
Related-to: #118
=> request for namespace required for continuous integration components

cluster-scope/overlays/moc/groups/operate-first.enc.yaml
This will add the following members to the operate-first ocp group: 
- @harshad16 
- @goern 
- @pacospace 
As per discussion [here](https://github.com/operate-first/argocd-apps/pull/37/files#r561054732)
=> Add thoth members to operate-first

cluster-scope/overlays/moc/groups/open-aiops.enc.yaml
Resolves: https://github.com/open-infrastructure-labs/moc-cnv-sandbox/issues/13
=> feat: Add eranra to open-aiops group

odh/overlays/moc/jupyterhub/kustomization.yaml
=> Fix kfdef patch positioning for jh

cluster-scope/base/crds/prow.k8s.io/kustomization.yaml, cluster-scope/overlays/moc/kustomization.yaml
Making prow work with the OPF cluster-scoped resource app.
=> feat: Add prow CRD

argocd-monitoring/base/rbac/kustomization.yaml, argocd-monitoring/base/rbac/monitoring-role.yaml, argocd-monitoring/base/rbac/monitoring-rolebinding.yaml, argocd-monitoring/overlays/moc/argocd-monitoring/kustomization.yaml, odh/overlays/moc/monitoring/servicemonitors/argocd-servicemonitor.yaml, odh/overlays/moc/monitoring/servicemonitors/kustomization.yaml
Add monitoring rbacs
Add servicemonitor
Closes #135
=> Create new app for argocd-monitoring

odh/base/monitoring/github-receiver.yaml
Update github receiver args to the correct format
=> fix gh receiver args errors

odh/base/jupyterhub/notebook-images/kustomization.yaml, odh/base/jupyterhub/notebook-images/mailing-list-analysis-toolkit.yaml
Part of: https://github.com/aicoe-aiops/mailing-list-analysis-toolkit/issues/33
=> feat: Add Mailing list analysis toolkit

cluster-scope/overlays/moc/groups/thoth.enc.yaml
include @pacospace as a member of thoth group
=> include @pacospace as member of thoth group

cluster-scope/base/namespaces/m4d-blueprints/kustomization.yaml, cluster-scope/base/namespaces/m4d-blueprints/namespace.yaml, cluster-scope/base/namespaces/m4d-system/kustomization.yaml, cluster-scope/base/namespaces/m4d-system/namespace.yaml, cluster-scope/overlays/moc/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/59
=> feat: Create m4d-system and m4d-blueprints namespaces

OWNERS
Full context can be found at https://github.com/open-infrastructure-labs/ops-issues/issues/16
=> Rework owners file to utilize both approvers and reviewers

cluster-scope/base/clusterloggings/clusterLogging.yaml, cluster-scope/base/clusterloggings/kustomization.yaml, cluster-scope/base/namespaces/openshift-logging/kustomization.yaml, cluster-scope/base/namespaces/openshift-logging/namespace.yaml, cluster-scope/base/namespaces/openshift-operators-redhat/kustomization.yaml, cluster-scope/base/namespaces/openshift-operators-redhat/namespace.yaml, cluster-scope/base/operatorgroups/cluster-logging-operator/kustomization.yaml, cluster-scope/base/operatorgroups/cluster-logging-operator/operatorgroup.yaml, cluster-scope/base/operatorgroups/elastic-operator/kustomization.yaml, cluster-scope/base/operatorgroups/elastic-operator/operatorgroup.yaml, cluster-scope/base/subscriptions/cluster-logging-operator/kustomization.yaml, cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml, cluster-scope/base/subscriptions/elastic-operator/kustomization.yaml, cluster-scope/base/subscriptions/elastic-operator/subscription.yaml, cluster-scope/overlays/moc/kustomization.yaml
Including dependency on Elastic-Search-Operator
=> Deploy Cluster-Logging-Operator (CLO) 

hack/onboarding.sh
When implementing #163 I've noticed few issues with our onboarding script that are caused by the changes based in a https://github.com/operate-first/apps/pull/120#discussion_r559822617
=> fix: Onboarding script group and rbac conditions

cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml, cluster-scope/base/subscriptions/elastic-operator/subscription.yaml
=> Update channel to 4.5 for logging operator

cluster-scope/base/clusterloggings/clusterLogging.yaml
Closes #170 
Related: https://github.com/openshift/cluster-logging-operator/issues/869
=> fix storageclassname and redundancy policy

cluster-scope/README.md
Resolves: https://github.com/operate-first/apps/issues/164
Related: https://github.com/operate-first/apps/pull/180 https://github.com/operate-first/apps/pull/178
=> feat: Cluster-scope maintenance guide

odh/overlays/moc/monitoring/dashboards/thoth-station/kustomization.yaml, odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-service-metrics.yaml
Related-To: https://github.com/thoth-station/thoth-application/pull/826
=> Add Thoth Service Metrics dashboard

odh/overlays/moc/monitoring/kustomization.yaml, odh/overlays/moc/monitoring/secrets/kustomization.yaml, odh/overlays/moc/monitoring/secrets/prometheus-k8s.yaml, odh/overlays/moc/monitoring/servicemonitors/cluster-metrics-servicemonitor.yaml, odh/overlays/moc/monitoring/servicemonitors/kustomization.yaml
This will scrape the cluster monitoring prometheus every 60 seconds
=> Add servicemonitor to federate metrics from cluser-monitor prometheus

cluster-scope/overlays/moc/groups/data-science.enc.yaml
We plan to use the data-science group to work on the black flake project and have access to black flake-related resources.
So I am adding all the people from the black flake meeting.
FYI: @MichaelClifford 
Context: next steps will be to 
1) add a black-flake app to operatefirst/argocd-apps overlays/moc/data-science and have it request a CEPH bucket.
2) the manifests will be located in https://github.com/aicoe-aiops/ocp-ci-analysis manifests directory.
=> Add black flake people to data-science group.

odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-dashboard.yaml, odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-sli-slo.yaml, odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/kustomization.yaml
Renaming the JH sli/slo dashboard to maintain uniformity
=> Rename JH sli/slo dashboard

cluster-scope/base/namespaces/ds-black-flake/kustomization.yaml, cluster-scope/base/namespaces/ds-black-flake/namespace.yaml, cluster-scope/base/namespaces/ds-example-project/kustomization.yaml, cluster-scope/base/namespaces/ds-example-project/namespace.yaml, cluster-scope/components/project-admin-rolebindings/data-science/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/data-science/rbac.yaml, cluster-scope/overlays/moc/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/76
=> feat: Onboard black-flake project to data science

cluster-scope/base/operatorgroups/local-storage/kustomization.yaml
Hotfix of: https://github.com/operate-first/apps/pull/131
=> fix: Namespace for local-storage operatorgroup

kubeflow-components/base/kfdef.yaml
Temporary workaround until https://github.com/kubeflow/manifests/pull/1736 is merged
Resolves: https://github.com/operate-first/apps/issues/213
=> feat: Disable registration flow in Kubeflow

cluster-scope/base/groups/workshops/group.yaml, cluster-scope/base/groups/workshops/kustomization.yaml, cluster-scope/base/namespaces/ws-ml-prague/kustomization.yaml, cluster-scope/base/namespaces/ws-ml-prague/namespace.yaml, cluster-scope/components/project-admin-rolebindings/workshops/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/workshops/rbac.yaml, cluster-scope/overlays/moc/groups/workshops.enc.yaml, cluster-scope/overlays/moc/kustomization.yaml, cluster-scope/overlays/moc/secret-generator.yaml
Part of: https://github.com/operate-first/support/issues/77
=> feat: Onboard ML workshops group

contributing.md
Addresses #198 
This should help us get started. I've tried to keep it close to how we're already operating.
=> Add contributor docs

cluster-scope/base/clusterrolebindings/scc-privileged-opf-ci-pipelines-aicoe-ci/clusterrolebinding.yaml, cluster-scope/base/clusterrolebindings/scc-privileged-opf-ci-pipelines-aicoe-ci/kustomization.yaml, cluster-scope/overlays/moc/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/81
=> feat: Add scc:privileged for aicoe-ci

cluster-scope/base/namespaces/opf-ci-test-pods/kustomization.yaml, cluster-scope/base/namespaces/opf-ci-test-pods/namespace.yaml, cluster-scope/overlays/moc/kustomization.yaml
=> add opf-ci-test-pods namespace

docs/kubeflow/kubeflow-dashboard/README.md, docs/kubeflow/kubflow-pipelines/README.md, kubeflow-components/overlays/moc/profiles/demo-profile.yaml, kubeflow-components/overlays/moc/profiles/kustomization.yaml
since we disabled kubeflow registration in #219, I have added a demo profile with limited resources which can be accessed publicly
=> Add a demo kubeflow profile

odh/base/kafka/kfdef.yaml
=> feat: ODH v1.0.0 upgrade: Kafka

odh/base/datacatalog/kfdef.yaml
=> feat: ODH v1.0.0 upgrade: Data catalog

odh/base/superset/kfdef.yaml
Only Superset related change is https://github.com/opendatahub-io/odh-manifests/pull/212
=> feat: ODH v1.0.0 upgrade: Superset

odh/overlays/moc/jupyterhub/pvcs/secret-generator.yaml, odh/overlays/moc/jupyterhub/pvcs/user-hvee-pvc.enc.yaml
Closes #https://github.com/operate-first/support/issues/86
=> Add PVC manifest for user hvee

odh/base/jupyterhub/kfdef.yaml, odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml
=> JH add override to ignore internal cert validation

cluster-scope/overlays/moc/groups/cluster-admins.enc.yaml
Add me and @HumairAK as cluster admins on MOC
=> feat: Make OPF cluster admins

odh/overlays/moc/datacatalog/kfdef_patch.yaml
Fixes: https://github.com/operate-first/apps/pull/250#issuecomment-777744745
=> fix: Missing storage class in datacatalog

test-kustomize-build
This script could be use to test all subdirectories containing a `kustomization.yaml` and just run a `kustomize build` on them...
=> Test kustomize build

odh/base/jupyterhub/notebook-images/kustomization.yaml, odh/base/jupyterhub/notebook-images/ml-prague-workshop.yaml
jupyterlab image for ml-prague-workshop
cc: @pacospace
=> jupyterlab image for ml-prague-workshop

odh/overlays/moc/jupyterhub/pvcs/secret-generator.yaml, odh/overlays/moc/jupyterhub/pvcs/user-cdol-pvc.enc.yaml
Resolves [this request](https://github.com/operate-first/support/issues?q=pvc+in%3Atitle)
=> Expand user pvc as per request.

cluster-scope/overlays/moc-infra/groups/cluster-admins.enc.yaml, cluster-scope/overlays/moc-infra/kustomization.yaml, cluster-scope/overlays/moc-infra/oauths/cluster_patch.yaml, cluster-scope/overlays/moc-infra/oauths/moc-sso-client-secret.enc.yaml, cluster-scope/overlays/moc-infra/secret-generator.yaml
clientId and clientSecret to be filled in by @larsks
=> feat: MOC SSO for moc-infra

cluster-scope/overlays/moc-infra/groups/cluster-admins.enc.yaml
Lets be truthful to the actual cluster state
=> feat: Add mhild to infra cluster admins

cluster-scope/overlays/moc-base/groups/argocd-admins.enc.yaml
@larsks  this will add your bu account as argocd admin instead of your redhat acount.
=> Replace user with different account for argocd admins.

odh/overlays/moc/monitoring/kustomization.yaml, odh/overlays/moc/monitoring/rules/alerting/kustomization.yaml, odh/overlays/moc/monitoring/rules/alerting/openshift-monitoring-scrape-duration.yaml
Addresses https://github.com/operate-first/SRE/issues/80
=> Add alerting rule for unusually high scrape durations in cluster-monitoring

cluster-scope/overlays/moc-infra/oauths/moc-sso-client-secret.enc.yaml, cluster-scope/overlays/moc/oauths/moc-sso-client-secret.enc.yaml
Apply workaround suggested in #278
=> Update moc-sso secret to be ignored by argocd

cluster-scope/base/namespaces/opf-jupyterhub-stage/kustomization.yaml, cluster-scope/base/namespaces/opf-jupyterhub-stage/namespace.yaml, cluster-scope/overlays/moc/kustomization.yaml
This is namespace where we can test any updates to JH
example PR: https://github.com/operate-first/apps/pull/282
=> Add jupyterhub staging namespace

acm/base/kustomization.yaml, acm/base/multiclusterhub.yaml, acm/overlays/moc-infra/kustomization.yaml, cluster-scope/base/namespaces/acm/kustomization.yaml, cluster-scope/base/namespaces/acm/namespace.yaml, cluster-scope/base/operatorgroups/acm/kustomization.yaml, cluster-scope/base/operatorgroups/acm/operatorgroup.yaml, cluster-scope/base/operatorgroups/opf-auth/kustomization.yaml, cluster-scope/base/operatorgroups/opf-auth/operatorgroup.yaml, cluster-scope/base/subscriptions/advanced-cluster-management/kustomization.yaml, cluster-scope/base/subscriptions/advanced-cluster-management/subscription.yaml, cluster-scope/overlays/moc-infra/kustomization.yaml
Resolves: https://github.com/open-infrastructure-labs/ops-issues/issues/22, https://github.com/open-infrastructure-labs/ops-issues/issues/24
Should provide a closure to issues ^
Further enhancements will be needed on the ACM app. Tracked at: https://github.com/operate-first/apps/issues/283
This PR should not introduce any environment changes, ArgoCD should not want to sync any new resources.
=> Sync ACM operator subscription

cluster-scope/overlays/moc-base/groups/thoth.enc.yaml
update thoth admin users for the moc cluster
Include @fridex as a member of thoth group.
Related-to: https://github.com/operate-first/support/issues/98
=> update thoth admin users for the moc cluster

cluster-scope/base/clusterrolebindings/cluster-logs-readers/clusterrolebinding.yaml
Resolves: https://github.com/operate-first/support/issues/99
=> feat: Add data-science folks to cluster-logs-readers

odh/overlays/moc/jupyterhub/pvcs/secret-generator.yaml, odh/overlays/moc/jupyterhub/pvcs/user-oc-pvc.enc.yaml
@oindrillac's JupyterHub account is blocked, see: https://github.com/operate-first/SRE/issues/62#issuecomment-788917507 and https://github.com/operate-first/support/issues/90#issuecomment-788145822
This PR aims to unblock @oindrillac so she can work with a proper sized PVC using her other account.
=> feat: Add PVC for Oindrilla

cluster-scope/base/groups/ray/group.yaml, cluster-scope/base/groups/ray/kustomization.yaml, cluster-scope/base/namespaces/ray-odh-integration/kustomization.yaml, cluster-scope/base/namespaces/ray-odh-integration/namespace.yaml, cluster-scope/components/project-admin-rolebindings/ray/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/ray/rbac.yaml, cluster-scope/overlays/moc-base/groups/ray.enc.yaml, cluster-scope/overlays/moc-base/kustomization.yaml, cluster-scope/overlays/moc-base/secret-generator.yaml, cluster-scope/overlays/moc/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/97
=> feat: Add ray-odh-intagration

hack/set-odh-release.sh
Part of: https://github.com/operate-first/support/issues/89
Resolves: https://github.com/operate-first/toolbox/issues/10
1. Checks the latest release of ODH on GitHub
2. Loops through `kfdef.yaml`s and bumps version in all `opendatahub` resources:
- Updates `.spec.version`
- Updates the tarball `uri` pointer in `.spec.repos` where the repo `name` matches `manifests`.
Requires [`yq`](https://github.com/mikefarah/yq) to be installed:  https://github.com/operate-first/toolbox/pull/14
=> feat: Add ODH Z-stream updater script

observatorium/base/instance/kfdef.yaml, odh/base/argo/kfdef.yaml, odh/base/dashboard/kfdef.yaml, odh/base/datacatalog/kfdef.yaml, odh/base/jupyterhub/kfdef.yaml, odh/base/kafka/kfdef.yaml, odh/base/monitoring/kfdef.yaml, odh/base/superset/kfdef.yaml
Change set created via #290 script
Part of https://github.com/operate-first/support/issues/89
=> feat: ODH 1.0.2 z-stream release

contributing.md
To avoid situations like #302 :)
=> Update contributing doc with wip instructions.

odh/overlays/moc/zero/jupyterhub/pvcs/secret-generator.yaml, odh/overlays/moc/zero/jupyterhub/pvcs/user-fran-pvc.enc.yaml, odh/overlays/moc/zero/jupyterhub/pvcs/user-kach-pvc.enc.yaml, odh/overlays/moc/zero/jupyterhub/pvcs/user-ocha-pvc.enc.yaml, odh/overlays/moc/zero/jupyterhub/pvcs/user-shan-pvc.enc.yaml
These PVCs were manually expanded earlier when we did not have secrets management set up.
cc @tumido
=> Add JH PVC manifests that were previously applied manually

cluster-scope/base/subscriptions/advanced-cluster-management/subscription.yaml
Resolves: https://github.com/open-infrastructure-labs/ops-issues/issues/30
/cc @HumairAK @larsks
=> feat: Upgrade ACM to release-2.2 channel

cluster-scope/base/namespaces/ds-ml-workflows-ws/kustomization.yaml, cluster-scope/base/namespaces/ds-ml-workflows-ws/namespace.yaml, cluster-scope/overlays/moc/common/groups/data-science.enc.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
As per https://github.com/operate-first/support/issues/107#issuecomment-790981338
Onboarding user to DS group + creating a new namespace.
=> Onboard user to data science and create ml-ws ns.

odh/base/monitoring/github-receiver.yaml
Resolves #https://github.com/operate-first/SRE/issues/111
=> scale github alerts receiver down

docs/kubeflow/kubeflow-dashboard/README.md, docs/kubeflow/kubeflow-pipelines/README.md, docs/observatorium/loki/README.md, docs/observatorium/loki/add_loki_grafana_datasource.md, docs/odh/grafana/README.md, docs/odh/grafana/add_grafana_dashboard.md, docs/odh/kafka/README.md, docs/odh/kafka/add_kafka_topics.md
Part of: https://github.com/operate-first/apps/issues/306, https://github.com/operate-first/SRE/issues/108
=> docs: Update docs for CNV/Zero migration

odh/base/jupyterhub/notebook-images/ml-prague-workshop.yaml
use the appropriate tag for maintaining consistency
Reference: https://quay.io/repository/thoth-station/s2i-lab-elyra?tab=tags
=> use the appropriate tag for maintaining consistency

docs/kubeflow/kubeflow-dashboard/README.md
Part of: https://github.com/operate-first/SRE/issues/108
=> Updated links to point to new cluster routes.

cluster-scope/overlays/moc/zero/oauths/cluster_patch.yaml, cluster-scope/overlays/moc/zero/oauths/moc-sso-client-secret.enc.yaml
configure new client id and secret for zero.massopen.cloud
=> update sso configuration for zero cluster

cluster-scope/overlays/moc/zero/kustomization.yaml
Fixes #288 
/cc @4n4nd @HumairAK
=> fix: Local storage operator for zero

cluster-scope/base/storageclasses/ocs-storagecluster-cephfs/kustomization.yaml, cluster-scope/base/storageclasses/ocs-storagecluster-cephfs/storageclass.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
We should first check if we can set the default via configs before attempting to store this via this pr.
=> Added storageclass with default annotation.

observatorium/overlays/moc/zero/kustomization.yaml, observatorium/overlays/moc/zero/objectbucketclaims/kustomization.yaml, observatorium/overlays/moc/zero/objectbucketclaims/loki-obc.yaml
Once the bucket is created we will need to add secrets that are generated using this bucketclaim.
=> Add loki ObjectBucketClaim in opf-observatorium

cluster-scope/overlays/moc/zero/kustomization.yaml
=> feat: Add ACM operator to Zero cluster so we can provide Observatorium resource

odh/base/monitoring/github-receiver.yaml
Part of: https://github.com/operate-first/SRE/issues/108
=> Scale up github receiver.

cluster-scope/overlays/moc/zero/kustomization.yaml
This reverts commit 4b9e74a81208466ea33055e822e095ad12133320.
=> Revert "feat: Add ACM operator to Zero cluster so we can provide Observatorium resource

observatorium/base/instance/example-loki-objectstorage-secret.yaml, observatorium/base/instance/observatorium.yaml, observatorium/overlays/moc/zero/.sops.yaml, observatorium/overlays/moc/zero/kustomization.yaml, observatorium/overlays/moc/zero/secrets/loki-objectstorage-secret.enc.yaml, observatorium/overlays/moc/zero/secrets/secret-generator.yaml
=> Add Loki objectstorage secret for observatorium

cluster-scope/base/crds/cluster.ray.io/kustomization.yaml, cluster-scope/base/crds/cluster.ray.io/ray-cluster-crd.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
The portion of https://github.com/operate-first/support/issues/102 that addresses the ray cluster CRD
=> wire up ray cluster CRD into kustomize overlays

cluster-scope/base/crds/cluster.ray.io/ray-cluster-crd.yaml
=> Fix linting on ray crd.

cluster-scope/base/namespaces/opf-jupyterhub/kustomization.yaml
=> Give ray users permissions to jupyterhub ns.

cluster-scope/base/clusterroles/ray-aggregate-to-admin/clusterrole.yaml, cluster-scope/base/clusterroles/ray-aggregate-to-admin/kustomization.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolve: https://github.com/operate-first/apps/pull/346#issuecomment-796195609
=> Add aggregate role for Ray CR for project admin

cluster-scope/overlays/moc/common/groups/argocd-admins.enc.yaml
Reverts operate-first/apps#351
=> Revert "encrypt groups/argocd-admins.enc.yaml to ipolonsk"

cluster-scope/overlays/moc/README.md
Depends on: https://github.com/operate-first/apps/pull/353
=> docs: Add readme for MOC listing GPG key locations

odh/overlays/moc/zero/monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
Provide version label for grafana operator to update the json based on url
=> Provide version label for grafana operator to update the json based on url

cluster-scope/overlays/moc/common/groups/operate-first.enc.yaml
Added ipolonsk email address to the list of operate first users.
=> added ipolonsk email to users list

contributing.md
Small update to make the workflow obvious
=> docs: Update contributing guide

contributing.md
SSIA
Fixes: https://github.com/operate-first/blueprint/issues/49
=> fix: Address feedback on #358 Contribution doc update 

cluster-scope/base/groups/tufts-dcc-6/group.yaml, cluster-scope/base/groups/tufts-dcc-6/kustomization.yaml, cluster-scope/base/namespaces/tufts-dcc-6/kustomization.yaml, cluster-scope/base/namespaces/tufts-dcc-6/namespace.yaml, cluster-scope/components/project-admin-rolebindings/tufts-dcc-6/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/tufts-dcc-6/rbac.yaml, cluster-scope/overlays/moc/common/groups/tufts-dcc-6.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Created namespace for group 6 dcc, Deploy and collect workflow-centric traces from microservice applications. @tumido
=> [Telemetry WG] Tufts project: Setup namespace for dcc group 6

observatorium/base/instance/observatorium.yaml
Related Issue Upstream: https://github.com/observatorium/operator/issues/42
=> Change thanos query frontend version to v0.15.0

odh/overlays/moc/zero/datacatalog/.sops.yaml, odh/overlays/moc/zero/datacatalog/kustomization.yaml, odh/overlays/moc/zero/datacatalog/user-buckets/secret-generator.yaml, odh/overlays/moc/zero/datacatalog/user-buckets/user-dtuch.enc.yaml
Resolves: https://github.com/operate-first/support/issues/103
=> feat: Add user bucket in DataCatalog for xtuchyna

cluster-scope/base/namespaces/opf-alertreceiver/kustomization.yaml, cluster-scope/base/namespaces/opf-alertreceiver/namespace.yaml, cluster-scope/overlays/moc/infra/kustomization.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Part 1 of: https://github.com/operate-first/SRE/issues/56
Adds a separate namspace where the GH alert receiver will be relocated to
=> feat: Create a namespace for GH alert receiver

odh/base/monitoring/alertmanager-config.yaml
Part 4 of: https://github.com/operate-first/SRE/issues/56
Depends on: https://github.com/operate-first/apps/pull/367
=> feat: Reconnect alert receiver on Zero

cluster-scope/overlays/moc/infra/groups/cluster-admins.enc.yaml, cluster-scope/overlays/moc/zero/groups/cluster-admins.enc.yaml
We need @4n4nd to have access to cluster monitoring. Please add him to the `cluster-admin` group.
/cc @HumairAK @4n4nd
=> feat: Add Anand to cluster admins

odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-advise-justification.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-adviser-re-run.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-adviser-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-hash-mismatch.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-kebechet-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-missing-package-version.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-missing-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-package-extract-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-package-released.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-provenance-checker-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-qebhwt-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-si-unanalyzed-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-solved-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-unresolved-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-unrevsolved-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-update-provides-source-distro.yaml
update thoth kafka topics w.r.t deployment name
Related-to: https://github.com/thoth-station/thoth-application/issues/1054
=> update thoth kafka topics w.r.t deployment name

observatorium/base/instance/observatorium.yaml
=> Increase PVC size for Thanos Receive

odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
=> Allow OPF monitoring Prometheus to detect Pod Monitors

odh/base/monitoring/overrides/prometheus-operator/base/servicemonitor.yaml
Relevant upstream PR fixing Argo Metrics Scraping: https://github.com/opendatahub-io/odh-manifests/pull/349
=> Fix Metrics scraping for Argo

observatorium/base/instance/kfdef.yaml, odh/base/argo/kfdef.yaml, odh/base/dashboard/kfdef.yaml, odh/base/datacatalog/kfdef.yaml, odh/base/jupyterhub/kfdef.yaml, odh/base/kafka/kfdef.yaml, odh/base/monitoring/kfdef.yaml, odh/base/superset/kfdef.yaml
See release details [here](https://github.com/opendatahub-io/odh-manifests/releases)
=> Update Kfdefs to 1.0.4

odh/base/monitoring/alertmanager.yaml, odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
Closes https://github.com/operate-first/SRE/issues/121
=> Add external urls flag for Prometheus and Alertmanager

cluster-scope/base/groups/ai-services/group.yaml, cluster-scope/base/groups/ai-services/kustomization.yaml, cluster-scope/base/namespaces/as-pushgateway/kustomization.yaml, cluster-scope/base/namespaces/as-pushgateway/namespace.yaml, cluster-scope/components/project-admin-rolebindings/ai-services/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/ai-services/rbac.yaml, cluster-scope/overlays/moc/common/groups/ai-services.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves https://github.com/operate-first/support/issues/128
=> Onboard ai-services project, as-pushgateway namespace

alertreceiver/base/deployment.yaml
Resolves: https://github.com/operate-first/SRE/issues/215
=> feat: Change alert receiver's repo

odh/overlays/moc/zero/monitoring/servicemonitors/observatorium-servicemonitor.yaml
Closes https://github.com/operate-first/SRE/issues/127
=> Update Observatorium Servicemonitor to scrape Thanos components

docs/odh/adding_kfdefs.md, kfdefs/base/kustomization.yaml, kfdefs/overlays/dev/kustomization.yaml, kfdefs/overlays/moc/zero/ds-ml-workflows-ws/kfdef.yaml, kfdefs/overlays/moc/zero/ds-ml-workflows-ws/kustomization.yaml, kfdefs/overlays/moc/zero/kustomization.yaml, kfdefs/overlays/moc/zero/thoth-infra-prod/kfdef.yaml, kfdefs/overlays/moc/zero/thoth-infra-prod/kustomization.yaml
Related: https://github.com/operate-first/support/issues/133#issuecomment-801956856 , https://github.com/operate-first/apps/pull/398#issuecomment-801975054
=> Add untracked kfdefs to git.

knative/base/knative-eventing.yaml, knative/base/knative-serving.yaml, knative/base/kustomization.yaml, knative/overlays/moc/zero/kustomization.yaml
Part of: https://github.com/operate-first/support/issues/84
=> feat: Enable Knative Serving and Eventing

cluster-scope/base/groups/b4mad/group.yaml, cluster-scope/base/groups/b4mad/kustomization.yaml, cluster-scope/base/namespaces/b4mad-minecraft/kustomization.yaml, cluster-scope/base/namespaces/b4mad-minecraft/namespace.yaml, cluster-scope/components/project-admin-rolebindings/b4mad/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/b4mad/rbac.yaml, cluster-scope/overlays/moc/common/groups/b4mad.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
https://github.com/operate-first/support/issues/139
create the namespace and groups on zero cluster
cc @goern
=> minecraft namespace

cluster-scope/overlays/moc/curator/groups/cluster-admins.enc.yaml, cluster-scope/overlays/moc/curator/imageregistryconfigs/image-registry-storage_patch.yaml, cluster-scope/overlays/moc/curator/ingresscontrollers/default-ingress-certificate.enc.yaml, cluster-scope/overlays/moc/curator/kustomization.yaml, cluster-scope/overlays/moc/curator/oauths/cluster_patch.yaml, cluster-scope/overlays/moc/curator/oauths/moc-sso-client-secret.enc.yaml, cluster-scope/overlays/moc/curator/secret-generator.yaml, cluster-scope/overlays/moc/curator/subscriptions/web-terminal.yaml
This adds configuration for the curator cluster [1].
Closes #419
[1]: https://console-openshift-console.apps.curator.massopen.cloud/dashboards
=> Onboard curator cluster

odh/overlays/moc/zero/jupyterhub-stage/kustomization.yaml
Related https://github.com/operate-first/support/issues/140
=> Add overlay for staging jupyterhub

odh/overlays/moc/zero/monitoring/datasource/thoth-station-datasource.yaml
fix the thoth datasource url
Related-to: https://github.com/thoth-station/thoth-application/issues/1065
=> fix the thoth datasource url

cluster-scope/base/namespaces/opf-jupyterhub/kustomization.yaml, cluster-scope/components/project-logs-reader/kustomization.yaml, cluster-scope/components/project-logs-reader/role.yaml, cluster-scope/components/project-logs-reader/rolebinding.yaml
Resolves: https://github.com/operate-first/apps/issues/428
=> feat: Enable view on pods and pods/logs for opf-jupyterhub

cluster-scope/base/clusterrolebindings/self-provisioners/clusterrolebinding.yaml, cluster-scope/base/clusterrolebindings/self-provisioners/kustomization.yaml, cluster-scope/base/configs/project/kustomization.yaml, cluster-scope/base/configs/project/project.yaml, cluster-scope/overlays/moc/common/kustomization.yaml
Resolves: https://github.com/operate-first/apps/issues/432
/priority critical-urgent
=> regression: Disable project self provisioning

cluster-scope/base/namespaces/opf-argo/kustomization.yaml, cluster-scope/base/namespaces/opf-dashboard/kustomization.yaml, cluster-scope/base/namespaces/opf-datacatalog/kustomization.yaml, cluster-scope/base/namespaces/opf-jupyterhub/kustomization.yaml, cluster-scope/base/namespaces/opf-kafka/kustomization.yaml, cluster-scope/base/namespaces/opf-superset/kustomization.yaml, cluster-scope/components/odh-dashboard/kustomization.yaml, cluster-scope/components/odh-dashboard/odh-dashboard-role.yaml, cluster-scope/components/odh-dashboard/odh-dashboard-rolebinding.yaml, odh/base/dashboard/overrides/overlays/cluster-role/rbac.yaml
Fixes: https://github.com/operate-first/support/issues/132
=> fix: ODH Dashboard RBAC to show only prod namespaces

odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-groups-configmap.yaml
Resolves https://github.com/operate-first/support/issues/161
=> Add `system:authenticated` group in the allowed groups for JH access

odh/base/monitoring/overrides/grafana-operator/base/grafana.yaml
Fixes: https://github.com/operate-first/support/issues/157
=> fix(odh-monitoring): Grafana image

cluster-scope/base/groups/cnv-testing/group.yaml, cluster-scope/base/groups/cnv-testing/kustomization.yaml, cluster-scope/base/namespaces/cnv-testing/kustomization.yaml, cluster-scope/base/namespaces/cnv-testing/namespace.yaml, cluster-scope/components/project-admin-rolebindings/cnv-testing/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/cnv-testing/rbac.yaml, cluster-scope/overlays/moc/common/groups/cnv-testing.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
closes operate-first/support#160
=> onboard dkenigsb to zero cluster

cluster-scope/base/groups/fde/group.yaml, cluster-scope/base/groups/fde/kustomization.yaml, cluster-scope/base/namespaces/fde-audio-decoder-demo/kustomization.yaml, cluster-scope/base/namespaces/fde-audio-decoder-demo/namespace.yaml, cluster-scope/components/project-admin-rolebindings/fde/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/fde/rbac.yaml, cluster-scope/overlays/moc/common/groups/fde.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/164
=> feat: Onboard FDE: Audio Decoder Demo

cluster-scope/base/groups/sdap-mslsp/group.yaml, cluster-scope/base/groups/sdap-mslsp/kustomization.yaml, cluster-scope/base/namespaces/sdap/kustomization.yaml, cluster-scope/base/namespaces/sdap/namespace.yaml, cluster-scope/components/project-admin-rolebindings/sdap-mslsp/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/sdap-mslsp/rbac.yaml, cluster-scope/overlays/moc/common/groups/sdap-mslsp.enc.yaml
Resolves https://github.com/operate-first/support/issues/167
=> Onboard sdap-mslsp team

odh/overlays/moc/zero/monitoring/dashboards/kustomization.yaml, odh/overlays/moc/zero/monitoring/dashboards/thanos/kustomization.yaml, odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-compact.yaml, odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-overview.yaml, odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-query.yaml, odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-receive.yaml, odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-rule.yaml, odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-store.yaml
Resolves https://github.com/operate-first/SRE/issues/222
=> Add thanos upstream dashboards

odh/overlays/moc/zero/jupyterhub/pvcs/secret-generator.yaml, odh/overlays/moc/zero/jupyterhub/pvcs/user-izim-pvc.enc.yaml
Resolves: https://github.com/operate-first/support/issues/172
=> chore(jupyterhub/pvcs): Enlarge user PVC for izim

observatorium/base/instance/kfdef.yaml, odh-operator/base/kustomization.yaml, odh/base/argo/kfdef.yaml, odh/base/dashboard/kfdef.yaml, odh/base/datacatalog/kfdef.yaml, odh/base/jupyterhub/kfdef.yaml, odh/base/kafka/kfdef.yaml, odh/base/monitoring/kfdef.yaml, odh/base/superset/kfdef.yaml, scripts/set-odh-release.sh
Also updated the script to only update kfdefs in odh/observatorium folder.
=> Update ODH to 1.0.6 z-release.

cluster-scope/base/groups/sa-dach/group.yaml, cluster-scope/base/groups/sa-dach/kustomization.yaml, cluster-scope/base/namespaces/sa-dach-anwendertreffen/kustomization.yaml, cluster-scope/base/namespaces/sa-dach-anwendertreffen/namespace.yaml, cluster-scope/base/namespaces/sa-dach-openshift-examples/kustomization.yaml, cluster-scope/base/namespaces/sa-dach-openshift-examples/namespace.yaml, cluster-scope/components/project-admin-rolebindings/sa-dach/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/sa-dach/rbac.yaml, cluster-scope/overlays/moc/common/groups/sa-dach.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/149
@rbo, this is what I did:
1. Result of running:
```
scripts/onboarding.sh sa-dach-anwendertreffen sa-dach "SA-DACH: Anwendertreffen"
scripts/onboarding.sh sa-dach-openshift-examples sa-dach "SA-DACH: Openshift Examples"
```
2. Adding the namespace resources to the `cluster-scope/overlays/moc/zero/kustomization.yaml` (target cluster)
3. Adding the group base to `cluster-scope/overlays/moc/common/kustomization.yaml` (for all moc clusters)
4. Creating the group encrypted resource to `cluster-scope/overlays/moc/common/groups/sa-dach.enc.yaml`
5. Adding the group encrypted resource to `cluster-scope/overlays/moc/common/secret-generator.yaml`
=> feat: Onboard SA-DACH

odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/kustomization.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/zero-cluster-app-logs.yaml
Related https://github.com/operate-first/apps/issues/232#issuecomment-809645674
=> Add topic for zero cluster app logs

odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml
Enable simple authorization for KafkaUsers ([Doc](https://strimzi.io/docs/operators/0.19.0/using.html#overview-concepts-user-operator-str))
=> Add PVC to kafka resource

scripts/set-odh-release.sh
parameterized the set-odh-release script to take in tag
Related-to: 
https://github.com/operate-first/support/issues/89
https://github.com/thoth-station/thoth-application/issues/896
=> parameterized the set-odh-release script to take in tag

observatorium/base/instance/grafana.yaml
Fixes: https://github.com/operate-first/apps/issues/469
=> fix: Observatorium Grafana image

odh/overlays/moc/zero/jupyterhub/pvcs/user-shan-pvc.enc.yaml
Closes https://github.com/operate-first/support/issues/186
=> Update shan PVC to 16Gi

cluster-logging/base/clusterlogging.yaml
Fixes: https://github.com/operate-first/apps/issues/471
=> fix: Lower CPU request on openshift-logging

cluster-scope/base/groups/uky-redhat/group.yaml, cluster-scope/base/groups/uky-redhat/kustomization.yaml, cluster-scope/base/namespaces/uky-hpc-workload-generator/kustomization.yaml, cluster-scope/base/namespaces/uky-hpc-workload-generator/namespace.yaml, cluster-scope/components/project-admin-rolebindings/uky-redhat/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/uky-redhat/rbac.yaml, cluster-scope/overlays/moc/common/groups/uky-redhat.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves https://github.com/operate-first/support/issues/190
=> Onboard uky-redhat team

cluster-scope/base/namespaces/opf-trino/kustomization.yaml, cluster-scope/base/namespaces/opf-trino/namespace.yaml, cluster-scope/overlays/moc/common/groups/operate-first.enc.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Part of: https://github.com/operate-first/support/issues/119
=> feat: Add ODH Trino

cluster-scope/base/groups/apicurio/group.yaml, cluster-scope/base/groups/apicurio/kustomization.yaml, cluster-scope/base/namespaces/apicurio-apicurio-registry/kustomization.yaml, cluster-scope/base/namespaces/apicurio-apicurio-registry/namespace.yaml, cluster-scope/components/project-admin-rolebindings/apicurio/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/apicurio/rbac.yaml, cluster-scope/overlays/moc/common/groups/apicurio.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Hi @durandom !
I've followed the docs to ask for the onboarding of Apicurio team, with the initial goal of deploying an instance of Apicurio Registry.
I'm honestly not sure if I've done things properly:
1. I had no clue which cluster I should have picked and based on what criteria, ended up with `dev`
2. I haven't performed this step: https://www.operate-first.cloud/users/support/docs/onboarding_to_cluster.md#adding-users-to-plaintext-overlay-patch since it was too obscure and I also had the suspect that the example above might have performed all operations already
3. I've even had funny errors with `toolbox` that somehow didn't see the part of filesystem where I keep my gh repos.
But other than that, I hope I've put most of the right things there.
Plase let me know if I have to fix or …
=> Add apicurio namespace

cluster-scope/overlays/moc/common/groups/uky-redhat.enc.yaml
Fixes: https://github.com/operate-first/support/issues/191
=> fix: uky-redhat member username

odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml
Resolves #467 
Related #465  
After this is merged, the kafka resource needs to be recreated. This will result in tls certs being reset.
cc @harshad16
=> Add 10Gi PVCs to kafka and zookeeper

slack-first/base/configmap.yaml, slack-first/base/deployment.yaml, slack-first/base/kustomization.yaml, slack-first/base/route.yaml, slack-first/base/secret.yaml, slack-first/base/service.yaml, slack-first/overlays/moc/zero/config.yaml, slack-first/overlays/moc/zero/kustomization.yaml, slack-first/overlays/moc/zero/secret-generator.yaml, slack-first/overlays/moc/zero/secret.enc.yaml
Resolves: https://github.com/operate-first/apps/issues/483
=> feat: Add manifests for slack-first bot

cluster-scope/overlays/moc/curator/kustomization.yaml, cluster-scope/overlays/moc/curator/subscriptions/ocs-operator_patch.yaml
we are going to try getting the curator cluster connected to an
external ceph cluster for storage.
=> subscribe curator cluster to container storage operator

odh/overlays/moc/zero/jupyterhub/pvcs/user-izim-pvc.enc.yaml
Resolve: https://github.com/operate-first/support/issues/172#issuecomment-814878876
=> Update izi PVC to 16Gi

argocd/overlays/moc-infra/projects/operate-first.yaml
Related: https://github.com/operate-first/apps/pull/490/files
=> Add clusterlogforwarder to operate-first proj.

cluster-scope/overlays/moc/common/secret-generator.yaml
Resolves: https://github.com/operate-first/support/issues/194
=> fix: Lab-CICD group populate

slack-first/overlays/moc/zero/config.yaml
SSIA, as per agreement between @HumairAK @4n4nd and me
=> chore: Reorder oncall schedule

cluster-scope/base/groups/pulp/group.yaml, cluster-scope/base/groups/pulp/kustomization.yaml, cluster-scope/base/namespaces/pulp-operator/kustomization.yaml, cluster-scope/base/namespaces/pulp-operator/namespace.yaml, cluster-scope/components/project-admin-rolebindings/pulp/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/pulp/rbac.yaml, cluster-scope/overlays/moc/common/groups/pulp.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Part of: https://github.com/operate-first/support/issues/176
=> feat: Create namespace for Pulp operator

docs/cluster-scope/add_resource_quotas.md
Related: https://github.com/operate-first/blueprint/pull/65
Will follow up with a doc on the different tiers in the `operate-first/support` repo, since that's more user facing.
=> Add instructions on adding resource quotas.

docs/kubeflow/kubeflow-pipelines/README.md
minor url update
resolves #504 
cc : @4n4nd
=> update kubeflow url

cluster-logging/overlays/moc/zero/clusterlogforwarders/clusterlogforwarder.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/zero-cluster-app-logs.yaml, vector/overlays/moc/zero/opf-observatorium/configmap.yaml
Fix Max Message Size config in cluster logging topic
=> Update Cluster Logging Application Topic Name

cluster-scope/overlays/moc/README.md, cluster-scope/overlays/moc/common/groups/lab-cicd.enc.yaml
Resolves: https://github.com/operate-first/apps/issues/500
1. Adds @acidonper GPG key to the Lab-CI-CD group resource so he can update the user list
2. Lists team owned GPG keys so we can import the pubkeys properly (we need them if we want to update the resources)
@paoloantinori was asked here to share his key so it can be added to the list: https://github.com/operate-first/apps/pull/477#issuecomment-815912388
=> chore: Add list of team GPG keys and where to find them

observatorium/base/instance/observatorium.yaml
Resolves #501 
Tested this in quicklabs
=> update loki from v1.6.1 to v2.2.0

odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-advise-justification.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-adviser-re-run.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-adviser-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-hash-mismatch.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-kebechet-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-missing-package-version.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-missing-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-package-extract-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-package-released.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-provenance-checker-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-qebhwt-trigger.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-si-unanalyzed-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-solved-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-unresolved-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-unrevsolved-package.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-update-provides-source-distro.yaml
set retention time for thoth kafka messages to 1 day
Related-to: https://github.com/operate-first/apps/issues/514
https://github.com/operate-first/SRE/issues/246
=> set retention time for thoth kafka messages to 1 day

odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/zero-cluster-app-logs.yaml
Related https://github.com/operate-first/apps/issues/514
=> Change cluster logs message retention period to 6 hours

argocd/overlays/moc-infra/configs/argo_cm/dex.config, argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv, argocd/overlays/moc-infra/projects/apicurio-registry.yaml, argocd/overlays/moc-infra/projects/kustomization.yaml
Tracking feedback on the docs here:
https://github.com/operate-first/support/issues/197
=> Onboard Apicurio on ArgoCD

odh/base/jupyterhub/kfdef.yaml
Resolves https://github.com/operate-first/apps/issues/519
=> Add spark operator in opf-jupyterhub namespace

cluster-scope/base/groups/codait-advo/group.yaml, cluster-scope/base/groups/codait-advo/kustomization.yaml, cluster-scope/base/namespaces/codait-advo/kustomization.yaml, cluster-scope/base/namespaces/codait-advo/namespace.yaml, cluster-scope/components/project-admin-rolebindings/codait-advo/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/codait-advo/rbac.yaml, cluster-scope/overlays/moc/common/groups/codait-advo.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves https://github.com/operate-first/support/issues/202
=> Onboard codait-advo team

cluster-scope/overlays/moc/infra/clusterversion.yaml, cluster-scope/overlays/moc/infra/kustomization.yaml
How do we want to handle updates on the infra cluster w/r/t scheduling?
=> Upgrade infra cluster to 4.6.21

cluster-scope/base/securitycontextconstraints/uky-hpc-workload-generator-hostpath/kustomization.yaml, cluster-scope/base/securitycontextconstraints/uky-hpc-workload-generator-hostpath/securitycontextconstraint.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/201
/hold waiting for service account name from the team
=> feat: Add hostpath SCC for UKY

odh/base/jupyterhub/notebook-images/audio-decoder-demo.yaml, odh/base/jupyterhub/notebook-images/kustomization.yaml
https://github.com/operate-first/support/issues/126
=> added new jh image

odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/audio-decoder-decoded-speech.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/audio-decoder-sentiment-text.yaml, odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/kustomization.yaml
https://github.com/operate-first/support/issues/126
=> added kafka topics

cluster-scope/overlays/moc/common/groups/lab-cicd.enc.yaml
Added a new user in lab-cicd group.
I added this new user using my private GPG key and I am not sure this process worked fine. Could you check that before applying the merge?
Thanks!
=> [MOC] Added a new user in lab-cicd group

cluster-scope/base/namespaces/fde-audio-decoder-demo/kustomization.yaml
https://github.com/operate-first/support/issues/126#issuecomment-821326032
=> made audio-decoder namespace public

scripts/update-cluster-version.sh
Part of: https://github.com/operate-first/SRE/issues/216
=> feat: Add a basic script for cluster version updates

odh/overlays/moc/zero/jupyterhub/pvcs/secret-generator.yaml, odh/overlays/moc/zero/jupyterhub/pvcs/user-adug-pvc.enc.yaml
Closes https://github.com/operate-first/support/issues/213
=> Add JH PVC for user adug

docs/odh/kafka/add_kafka_topics.md, docs/odh/prometheus/add_service_monitoring.md
reflect changes in: https://github.com/operate-first/apps/pull/544
=> Update odh yaml paths for monitoring & topics doc.

scripts/set-odh-release.sh
Related to https://github.com/operate-first/apps/issues/466
=> fix: ODH release script after moving kfdefs

kfdefs/base/argo/kfdef.yaml, kfdefs/base/dashboard/kfdef.yaml, kfdefs/base/datacatalog/kfdef.yaml, kfdefs/base/jupyterhub/kfdef.yaml, kfdefs/base/kafka/kfdef.yaml, kfdefs/base/monitoring/kfdef.yaml, kfdefs/base/superset/kfdef.yaml, observatorium/base/instance/kfdef.yaml, odh-operator/base/kustomization.yaml
SSIA, manual, because the script failed due to https://github.com/operate-first/apps/pull/556
=> feat: ODH 1.0.10 z-stream release

argocd/base/kustomization.yaml, argocd/overlays/dev/configs/argo_cm/dex.config, argocd/overlays/dev/kustomization.yaml, cluster-scope/base/crds/applications.argoproj.io/crd.yaml, cluster-scope/base/crds/appprojects.argoproj.io/crd.yaml, docs/argocd/setup_argocd_dev_environment.md, docs/argocd/update_argocd.md, scripts/argocd/configure_development.sh, scripts/argocd/update_cluster_resources.sh
Context: https://github.com/operate-first/apps/issues/498
Also updated upgrade docs, and threw in a script for updating updating the cluster resources. Some minor changes to the dev deployment as well.
=> Update ArgoCD to v2.0.1, and update docs.

docs/argocd/update_argocd.md
To avoid issues like this: https://github.com/operate-first/apps/pull/561/files
=> Update argocd doc to check deployment specs.

cluster-scope/overlays/moc/common/groups/operate-first.enc.yaml
Add @vpavlin to operate-first group so he can also investigate jh issues in the future.
=> Add user to operate-first grp

kfdefs/base/jupyterhub/notebook-images/jupyterbook-test.yaml, kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
Should resolve: https://github.com/operate-first/apps/issues/565
=> Add annotations to JH images.

kfdefs/base/jupyterhub/notebook-images/jupyterbook-test.yaml, kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
Not metadata.annotaitons....but tag annotations need to be updated. 
https://github.com/operate-first/apps/issues/565#issuecomment-825802726
=> Update image tag annoations for jh images.

cluster-scope/base/groups/quarkus/group.yaml, cluster-scope/base/groups/quarkus/kustomization.yaml, cluster-scope/base/namespaces/quarkus-extension-registry/kustomization.yaml, cluster-scope/base/namespaces/quarkus-extension-registry/namespace.yaml, cluster-scope/components/project-admin-rolebindings/quarkus/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/quarkus/rbac.yaml, cluster-scope/overlays/moc/common/groups/quarkus.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/216
=> Onboard quarkus team/user.

cluster-scope/overlays/moc/zero/clusterversion.yaml
=> feat: Upgrade Zero to 4.7.7

cluster-scope/base/namespaces/thoth-amun-api-prod/kustomization.yaml, cluster-scope/base/namespaces/thoth-amun-inspection-prod/kustomization.yaml, cluster-scope/base/namespaces/thoth-amun-inspection-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-backend-prod/kustomization.yaml, cluster-scope/base/namespaces/thoth-backend-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-bots-prod/kustomization.yaml, cluster-scope/base/namespaces/thoth-deployment-examples/kustomization.yaml, cluster-scope/base/namespaces/thoth-frontend-prod/kustomization.yaml, cluster-scope/base/namespaces/thoth-frontend-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-graph-prod/kustomization.yaml, cluster-scope/base/namespaces/thoth-graph-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-infra-prod/kustomization.yaml, cluster-scope/base/namespaces/thoth-middletier-prod/kustomization.yaml, cluster-scope/base/namespaces/thoth-middletier-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-test-core/kustomization.yaml, cluster-scope/base/namespaces/thoth-test-core/resourcequota.yaml
set quota limits for thoth-* namespaces
Related-to: https://github.com/operate-first/support/issues/196
=> set quota limits for thoth-* namespaces

odh-manifests/grafana/base/grafana.yaml
Reverts https://github.com/operate-first/apps/pull/113
Related https://github.com/operate-first/SRE/issues/270
=> Add a proxy container to grafana deployment

kfdefs/base/monitoring/kfdef.yaml, odh-manifests/prometheus/operator/base/prometheus.yaml, odh-manifests/prometheus/operator/base/route.yaml, odh-manifests/prometheus/operator/overlays/openshift-proxy/kustomization.yaml, odh-manifests/prometheus/operator/overlays/openshift-proxy/service.yaml, odh-manifests/prometheus/operator/overlays/openshift-proxy/serviceaccount.yaml
Closes #575 
Related https://github.com/operate-first/SRE/issues/270
=> Add openshift oauth proxy to Prometheus

cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml, cluster-scope/base/subscriptions/elastic-operator/subscription.yaml
SSIA
Related: https://github.com/operate-first/SRE/issues/271
=> feat: Make CLO and elastic automatic

odh-manifests/prometheus/operator/base/prometheus.yaml
=> fix prometheus oauth configuration

kubeflow-components/overlays/moc/zero/rolebindings/kubeflow-tekton-view.yaml, kubeflow-components/overlays/moc/zero/rolebindings/kustomization.yaml, kubeflow-components/overlays/moc/zero/roles/kubeflow-tekton-view.yaml, kubeflow-components/overlays/moc/zero/roles/kustomization.yaml
=> Add pod view permissions for openshift-pipelines controller in kubeflow namespace

cluster-scope/base/namespaces/thoth-amun-inspection-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-backend-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-frontend-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-graph-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-middletier-prod/resourcequota.yaml, cluster-scope/base/namespaces/thoth-test-core/resourcequota.yaml
update the thoth quota resources with requests setting
=> update the thoth quota resources with requests setting

cluster-scope/base/clusterrolebindings/scc-anyuid-observatorium/clusterrolebinding.yaml, cluster-scope/base/clusterrolebindings/scc-anyuid-observatorium/kustomization.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml, observatorium/base/instance/observatorium.yaml, observatorium/base/operator/deployment.yaml
Resolves:  https://github.com/operate-first/SRE/issues/282
=> fix: Upgrade observatorium to solve memcached OOMKilled

cluster-scope/base/namespaces/opf-monitoring/kustomization.yaml, cluster-scope/components/project-view-rolebindings/data-science/kustomization.yaml, cluster-scope/components/project-view-rolebindings/data-science/rbac.yaml
Resolves: https://github.com/operate-first/support/issues/227
=> feat: Add data-science to viewers on opf-monitoring

cluster-scope/base/groups/team-pixel/group.yaml, cluster-scope/base/groups/team-pixel/kustomization.yaml, cluster-scope/base/namespaces/pixel-demos/kustomization.yaml, cluster-scope/base/namespaces/pixel-demos/namespace.yaml, cluster-scope/base/namespaces/pixel-vault/kustomization.yaml, cluster-scope/base/namespaces/pixel-vault/namespace.yaml, cluster-scope/components/project-admin-rolebindings/team-pixel/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/team-pixel/rbac.yaml, cluster-scope/overlays/moc/common/groups/team-pixel.enc.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/220
=> Onboard user.

kfdefs/base/jupyterhub/notebook-images/experimental-elyra-notebook-imagestream.yaml, kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
As per https://github.com/operate-first/support/issues/229
=> Add custom elyera image for frequent upgrades.

kubeflow-components/base/kustomization.yaml
Make Kubeflow unmanaged for now
=> fix: Remove Kubeflow kfdef for now

scripts/argocd/update_cluster_resources.sh
=> update argocd update_cluster_resources.sh script for new repo layout

cluster-scope/overlays/moc/zero/imageregistryconfigs/image-registry-storage_patch.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
For changes here: https://github.com/operate-first/apps/pull/650 
to take affect
=> Remove image registry pvc storage patch from zero, unneeded.

cluster-scope/base/core/namespaces/opf-ci-pipelines/kustomization.yaml, cluster-scope/base/core/namespaces/opf-ci-pipelines/resourcequota.yaml, cluster-scope/base/core/namespaces/opf-ci-prow/kustomization.yaml, cluster-scope/base/core/namespaces/opf-ci-prow/resourcequota.yaml
Quota setup for the opf prow and pipelines
Related-to: https://github.com/operate-first/apps/issues/574
Fixes: https://github.com/operate-first/support/issues/159
=> Quota setup for the opf prow and pipelines

cluster-scope/README.md, docs/cluster-scope/add_resource_quotas.md
Also re organized the structure view, I think this way is a bit cleaner, wdyt? 
Resolves https://github.com/operate-first/apps/issues/631#issuecomment-840578020
=> Update docs as per adr 15.

cluster-scope/base/core/namespaces/sigstore-deploy/kustomization.yaml, cluster-scope/base/core/namespaces/sigstore-deploy/namespace.yaml, cluster-scope/base/user.openshift.io/groups/sigstore/group.yaml, cluster-scope/base/user.openshift.io/groups/sigstore/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/sigstore/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/sigstore/rbac.yaml, cluster-scope/overlays/moc/common/groups/sigstore.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolve: https://github.com/operate-first/support/issues/245
=> Onboard sigstore to zero cluster.

cluster-scope/base/core/namespaces/opendatahub-operator/kustomization.yaml, cluster-scope/base/core/namespaces/opf-argo/kustomization.yaml, cluster-scope/base/core/namespaces/opf-dashboard/kustomization.yaml, cluster-scope/base/core/namespaces/opf-jupyterhub-stage/kustomization.yaml, cluster-scope/base/core/namespaces/opf-kafka/kustomization.yaml, cluster-scope/base/core/namespaces/opf-monitoring/kustomization.yaml, cluster-scope/base/core/namespaces/opf-superset/kustomization.yaml, cluster-scope/base/core/namespaces/opf-trino/kustomization.yaml, cluster-scope/base/user.openshift.io/groups/odh-admin/group.yaml, cluster-scope/base/user.openshift.io/groups/odh-admin/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/odh-admin/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/odh-admin/rbac.yaml, cluster-scope/overlays/moc/common/groups/odh-admin.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml
Resolve: https://github.com/operate-first/support/issues/244
I've also added Chad & Juana, along with others in the `operate-first` admin group that are also in the IDH team.
=> Create an odh admins group with access to odh namespaces.

cluster-scope/base/core/namespaces/openshift-insights/kustomization.yaml, cluster-scope/base/user.openshift.io/groups/ccx/group.yaml, cluster-scope/base/user.openshift.io/groups/ccx/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/ccx/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/ccx/rbac.yaml, cluster-scope/overlays/moc/common/groups/ccx.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/242
=> feat: Onboard CCX to openshift-insights namespace

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/opf-monitoring-grafana-cluster-view/clusterrolebinding.yaml, cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/opf-monitoring-grafana-cluster-view/kustomization.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml, kfdefs/overlays/moc/zero/opf-monitoring/datasource/opf-openshift-monitoring-grafanadatasource.enc.yaml, kfdefs/overlays/moc/zero/opf-monitoring/datasource/secrets-generator.yaml
Resolves: https://github.com/operate-first/SRE/issues/295 
Current RBAC was not sufficient, had to add cluster view role.
=> Connect grafana to openshift-monitoring Prometheus

cluster-scope/base/core/namespaces/opf-google-spark-operator/kustomization.yaml, cluster-scope/base/core/namespaces/opf-google-spark-operator/namespace.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml, kfdefs/base/google-spark-operator/kfdef.yaml, kfdefs/base/google-spark-operator/kustomization.yaml, kfdefs/overlays/moc/zero/opf-google-spark-operator/kustomization.yaml
Related: https://github.com/operate-first/support/issues/241
=> Deploy odh google spark operator to zero cluster.

kfdefs/overlays/moc/zero/kustomization.yaml
Forgot to add it to the root kustomization -_- 
Related: https://github.com/operate-first/apps/pull/668
=> Add google spark operator to root kfdef.

cluster-scope/base/operators.coreos.com/catalogsources/pulp-catalog/catalogsource.yaml, cluster-scope/base/operators.coreos.com/catalogsources/pulp-catalog/kustomization.yaml, cluster-scope/base/operators.coreos.com/operatorgroups/pulp-operator/kustomization.yaml, cluster-scope/base/operators.coreos.com/operatorgroups/pulp-operator/operatorgroup.yaml, cluster-scope/base/operators.coreos.com/subscriptions/pulp-operator/kustomization.yaml, cluster-scope/base/operators.coreos.com/subscriptions/pulp-operator/subscription.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Deploy via OLM from a custom catalog. Catalog definition here: https://github.com/tumido/olm-catalog
Resolves: https://github.com/operate-first/support/issues/176
Competition PR: https://github.com/operate-first/apps/pull/663
/hold until it's decided which way (this or the competition PR) is more maintainable for the Pulp team
=> feat: Add Pulp via OLM

odh-manifests/kafka/base/kafka-cluster.yaml
This will:
* Increase Kafka broker PVC size
* Disable automatic topic creation, this will force all topics to be in git
Resolves #676
=> Increase Kafka broker PVC size

cluster-scope/base/core/namespaces/thoth-pulp-experiments/kustomization.yaml, cluster-scope/base/core/namespaces/thoth-pulp-experiments/namespace.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
setting up namespace for pulp setup experiment
Fixes: https://github.com/operate-first/support/issues/252
=> setting up namespace for pulp setup experiment

cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayclusters.cluster.ray.io/customresourcedefinition.yaml, kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml, kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-node-imagestream.yaml, kfdefs/base/jupyterhub/ray-odh-integration/ray-operator-imagestream.yaml
addresses https://github.com/operate-first/support/issues/254
=> update to latest ray nightly wheel, update RayCluster CRD

kfdefs/base/monitoring/blackbox-exporter/blackbox.yaml, odh-manifests/prometheus/operator/base/prometheus.yaml
update prometheus CR to look for probe objects
Final fix required for https://github.com/operate-first/apps/pull/578
=> fix blackbox prober secret name

cluster-scope/base/core/namespaces/osc-playground/kustomization.yaml, cluster-scope/base/core/namespaces/osc-playground/namespace.yaml, cluster-scope/base/user.openshift.io/groups/osc/group.yaml, cluster-scope/base/user.openshift.io/groups/osc/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/osc/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/osc/rbac.yaml, cluster-scope/overlays/moc/common/groups/osc.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolve: https://github.com/operate-first/support/issues/257
=> Onboard OSC group.

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/kubeflow/kfp-tekton-user.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/kubeflow/kustomization.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/kustomization.yaml
Dashboard for KFP Tekton user view and profiling
/cc @4n4nd
=> feat(dashboards): Add Kubeflow Pipelines - Tekton user perspective dashboard

cluster-scope/base/core/namespaces/pulp-operator/kustomization.yaml
Part of: https://github.com/operate-first/support/issues/176
=> feat: Add thoth-devops to pulp-operator namespace

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/cluster-logs-quick-search.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/kustomization.yaml, kfdefs/overlays/moc/zero/opf-monitoring/datasource/cluster-zero-app-logs.yaml, kfdefs/overlays/moc/zero/opf-monitoring/datasource/kustomization.yaml
Add Loki Datasource for MOC/Zero app logs
Screenshot:
=> Add Loki Dashboard

cluster-scope/base/operators.coreos.com/catalogsources/pulp-catalog/catalogsource.yaml
Part of: https://github.com/operate-first/support/issues/176
=> feat: Switch pulp operator to upstream catalog source

kfdefs/overlays/moc/zero/opf-jupyterhub/kustomization.yaml
Related https://github.com/operate-first/support/issues/260
=> change opf-jupyterhub-storage class to ocs-storagecluster-cephfs

cluster-scope/overlays/moc/common/groups/osc.enc.yaml
=> Add user to osc group on zero cluster.

cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml, cluster-scope/base/core/namespaces/opf-seldon/namespace.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml, kfdefs/base/seldon/kfdef.yaml, kfdefs/base/seldon/kustomization.yaml, kfdefs/overlays/dev/kustomization.yaml, kfdefs/overlays/dev/opf-seldon/kustomization.yaml, kfdefs/overlays/moc/zero/kustomization.yaml, kfdefs/overlays/moc/zero/opf-seldon/kustomization.yaml
Resolves https://github.com/operate-first/support/issues/259
=> Add odhseldon kfdef to deploy the seldon operator

cluster-scope/overlays/moc/common/groups/pulp.enc.yaml
Part of: https://github.com/operate-first/support/issues/176#issuecomment-854702814
Adds @chambridge to our "Pulp team". Grants access to `pulp-operator` and `thoth-pulp-experiments` namespaces
=> feat: Add Chris to Pulp team

cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml
Additional filters to reduce noise in the alert repo. Feel free to suggest more.
=> Add additional filters for alerts.

cluster-scope/overlays/moc/zero/clusterversion.yaml
Part of: https://github.com/operate-first/SRE/issues/330
=> feat: Upgrade Zero to 4.7.13

kfdefs/base/jupyterhub/notebook-images/s2i-spark3.0.1-minimal-notebook.yaml
Add name tag to spark3.0.1 notebook image              
Update imagestream name
#690
=> addendum: Add spark3.0.1 notebook image

cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml
Inhibit this alert: https://github.com/operate-first/alerts/issues/8833
If this alert is firing: https://github.com/operate-first/alerts/issues/8832
Also we dont' care about this alert: https://github.com/operate-first/alerts/issues/8831
We are aware of this issue (linked in the comments next to the alert).
=> Add additional inhibit and silence alert rules.

cluster-scope/base/core/namespaces/redhat-cto-ns/kustomization.yaml, cluster-scope/base/core/namespaces/redhat-cto-ns/namespace.yaml, cluster-scope/base/user.openshift.io/groups/redhat-cto-team/group.yaml, cluster-scope/base/user.openshift.io/groups/redhat-cto-team/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/redhat-cto-team/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/redhat-cto-team/rbac.yaml, cluster-scope/overlays/moc/common/groups/redhat-cto-team.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolve: https://github.com/operate-first/support/issues/261
=> Onboard redhat-cto-team.

cluster-scope/base/core/namespaces/thoth-pulp-experiments/resourcequota.yaml
Related: https://github.com/operate-first/support/issues/176#issuecomment-857818671
=> feat: Increase CPU quota for Pulp to 8 cores

cluster-scope/base/core/namespaces/mwperf-horreum/kustomization.yaml, cluster-scope/base/core/namespaces/mwperf-horreum/namespace.yaml, cluster-scope/base/user.openshift.io/groups/mwperf/group.yaml, cluster-scope/base/user.openshift.io/groups/mwperf/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/mwperf/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/mwperf/rbac.yaml, cluster-scope/overlays/moc/common/groups/mwperf.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolve: https://github.com/operate-first/support/issues/263
=> Onboard mwperf team.

cluster-scope/base/core/namespaces/koku-metrics-operator/kustomization.yaml, cluster-scope/base/user.openshift.io/groups/curator/group.yaml, cluster-scope/base/user.openshift.io/groups/curator/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/curator/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/curator/rbac.yaml, cluster-scope/overlays/moc/common/groups/curator.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml
Part of: https://github.com/operate-first/support/issues/265
/cc @HumairAK @4n4nd
=> feat: Add curator team

observatorium/overlays/moc/zero/secrets/thanos-objectstorage-secret.enc.yaml
This will update the thanos Object Storage credentials.
The new storage was created by @larsks and the previous data has been copied to this bucket manually.
=> Update thanos object storage creds

observatorium/base/operator/deployment.yaml
=> Scale down observatorium operator.

cluster-scope/overlays/moc/infra/kustomization.yaml, cluster-scope/overlays/moc/infra/ocp-prod-provisioning-vlan.yaml
Plan is to create the MOC cluster using ACM.
=> Create interface on the MOC production openshift provisioning network.

cluster-scope/base/core/namespaces/apicurio-apicurio-registry/kustomization.yaml
Still facing some issue specifically with CPU, might downside later, but now we'd like to get more
=> Apicurio quota, bumped to large

kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml, kfdefs/overlays/moc/zero/opf-monitoring/serviceaccounts/kustomization.yaml, kfdefs/overlays/moc/zero/opf-monitoring/serviceaccounts/thoth-station.yaml
give thoth-station access to opf-monitoring
Resolves https://github.com/operate-first/support/issues/267
=> Add thoth-station SA in `opf-monitoring`

cluster-scope/base/core/namespaces/opf-datacatalog/kustomization.yaml, cluster-scope/base/core/namespaces/opf-jupyterhub/kustomization.yaml, cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml, cluster-scope/overlays/moc/common/groups/odh-admin.enc.yaml
Adding @rimolive to odh-admins, and also extending odh-admins permissions to other odh namespaces they don't currently have access to.
=> Add odh-admins to odh namespaces.

cluster-scope/base/core/namespaces/curator-engine/kustomization.yaml, cluster-scope/base/core/namespaces/curator-engine/namespace.yaml, cluster-scope/overlays/moc/common/groups/curator.enc.yaml
Related: https://github.com/operate-first/support/issues/265#issuecomment-858608619
=> Add curator ns and user.

argocd/overlays/moc-infra/configs/argo_cm/dex.config, argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv, cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml, cluster-scope/base/user.openshift.io/groups/argocd-readonly/kustomization.yaml, cluster-scope/overlays/moc/common/groups/argocd-readonly.enc.yaml
Add naved (who wants to be able to poke around) and my @redhat.com
account (for testing this out).
=> Create argocd-readonly group for read-only access to all resources

cluster-scope/base/core/namespaces/sdap/kustomization.yaml, cluster-scope/base/core/namespaces/sdap/resourcequota.yaml
This is a request made via slack by @tloubrieu-jpl 
Note the core requirement. Judging by the dashboards, I think we can accommodate this request.
Related: 
https://github.com/operate-first/support/issues/241
https://github.com/operate-first/support/issues/266
https://github.com/operate-first/support/issues/206
=> Apply custom quota to sdap namespace.

.prow.yaml
SSIA to apply https://github.com/operate-first/toolbox/pull/33
Related to:
- https://github.com/operate-first/apps/pull/748
- https://github.com/operate-first/argocd-apps/pull/151
- https://github.com/operate-first/workshop-apps/pull/32
=> chore: Use latest toolbox in CI

cluster-scope/base/core/namespaces/sdap/kustomization.yaml, cluster-scope/components/project-events-creator/sdap-mslsp/kustomization.yaml, cluster-scope/components/project-events-creator/sdap-mslsp/role.yaml, cluster-scope/components/project-events-creator/sdap-mslsp/rolebinding.yaml
Should resolve: https://github.com/operate-first/support/issues/266
=> Add events creator role to sdap.

acme-operator/base/deployment.yaml, cluster-scope/base/core/namespaces/acme-operator/kustomization.yaml
I've figured we don't need a HA for this, it should be fine to run a single replica
=> chore: Downsize ACME operator

cluster-scope/overlays/moc/infra/groups/cluster-admins.enc.yaml
Kevin needs cluster access in order to help diagnose recent ACM
problems.
This PR also removes Ilana from the admin group.
=> add kcormier

kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml
=> Add fde group to opf-monitoring-view role

cluster-scope/overlays/moc/infra/kustomization.yaml, cluster-scope/overlays/moc/infra/metal3.io/provisionings/provisioning-configuration.yaml
Resolves operate-first/SRE#341
=> Use default url for rhcos images rather than local cache

cluster-scope/base/core/namespaces/adoptium-project/kustomization.yaml, cluster-scope/base/core/namespaces/adoptium-project/namespace.yaml, cluster-scope/base/user.openshift.io/groups/adoptium/group.yaml, cluster-scope/base/user.openshift.io/groups/adoptium/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/adoptium/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/adoptium/rbac.yaml, cluster-scope/overlays/moc/common/groups/adoptium.enc.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Onboarding for Adoptium to Zero cluster
Related-to: https://github.com/operate-first/support/issues/268
Requested actions
Select all that apply:
- [ x ] Create a new ArgoCD project for existing team
- [ x ] Enlist an application to be deployed automatically via ArgoCD
**Questionnaire**
**Creating a new project**
1. **Team name**:
Please tell us your team name, which corresponds to [an already available user `Group`](https://github.com/operate-first/apps/tree/master/cluster-scope/base/groups).
- adoptium
2. **Target cluster**:
Choose an environment from [this list](https://github.com/operate-first/apps/tree/master/cluster-scope/overlays)
- Zero
3. **Managed namespaces**:
The target namespaces that should be managed by ArgoCD. Preferably using [a single (team name) …
=> inital onboarding for adoptium

kfdefs/base/jupyterhub/notebook-images/kustomization.yaml, kfdefs/base/jupyterhub/notebook-images/s2i-pytorch-py38-notebook.yaml, kfdefs/base/jupyterhub/notebook-images/s2i-spark3.0.1-minimal-notebook.yaml
Part of: https://github.com/operate-first/support/issues/276
=> Fix missing names in additional image streams

kfdefs/base/jupyterhub/notebook-images/s2i-pytorch-py38-notebook.yaml
Fixes: https://github.com/operate-first/apps/pull/775
=> fix: JH image name is not a label

odh-manifests/kafka/overlays/topics/kustomization.yaml, odh-manifests/kafka/overlays/topics/thoth-build-analysis-trigger.yaml, odh-manifests/kafka/overlays/topics/thoth-cve-provided.yaml, odh-manifests/kafka/overlays/topics/thoth-kebechet-run-url.yaml
New messages present in thoth.messaging and adviser-rerun has been removed
=> add and remove templates to reflect current state of thoth-messaging

odh-manifests/kafka/overlays/users/thoth.yaml
=> allow "thoth.*" group ids to for the thoth kafka user

acme-operator/overlays/moc/infra/issuer-letsencrypt-live.yaml, acme-operator/overlays/moc/infra/kustomization.yaml
Part of: https://github.com/operate-first/support/issues/282
=> feat: Deploy ACME to infra cluster

cluster-scope/base/core/namespaces/chi-rhug/kustomization.yaml, cluster-scope/base/core/namespaces/chi-rhug/namespace.yaml, cluster-scope/base/user.openshift.io/groups/chi-rhug/group.yaml, cluster-scope/base/user.openshift.io/groups/chi-rhug/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/chi-rhug/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/chi-rhug/rbac.yaml, cluster-scope/overlays/moc/common/groups/chi-rhug.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/279
=> feat: onboard chi-rhug

cluster-scope/base/core/namespaces/esi-operate-first-project/kustomization.yaml, cluster-scope/base/core/namespaces/esi-operate-first-project/namespace.yaml, cluster-scope/base/user.openshift.io/groups/esi-project/group.yaml, cluster-scope/base/user.openshift.io/groups/esi-project/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/esi-project/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/esi-project/rbac.yaml, cluster-scope/overlays/moc/common/groups/esi-project.enc.yaml, cluster-scope/overlays/moc/common/kustomization.yaml, cluster-scope/overlays/moc/common/secret-generator.yaml, cluster-scope/overlays/moc/zero/kustomization.yaml
Resolves https://github.com/operate-first/support/issues/272
=> onboard esi-project

slack-first/overlays/moc/zero/config.yaml, slack-first/overlays/moc/zero/secret.enc.yaml
Part of: https://github.com/operate-first/SRE/issues/345
Requires: https://github.com/tumido/slack-first/issues/115
=> feat: Add new on-call members

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
=> update thoth dashboards CRDs

argocd/overlays/moc-infra/projects/operate-first.yaml, cluster-scope/overlays/moc/infra/kustomization.yaml
Fixes: https://github.com/operate-first/support/issues/282
=> fix: Add acme-operator namespace to infra

cluster-scope/overlays/moc/infra/kustomization.yaml
SSIA Part of: https://github.com/operate-first/support/issues/282
=> fix: Acme roles on infra

kfdefs/overlays/moc/zero/opf-jupyterhub/pvcs/secret-generator.yaml, kfdefs/overlays/moc/zero/opf-jupyterhub/pvcs/user-ater-pvc.enc.yaml
Resolves https://github.com/operate-first/support/issues/286
=> increase pvc size for user ater

cluster-scope/base/core/namespaces/ds-ml-workflows-ws/kustomization.yaml, cluster-scope/base/core/namespaces/ds-ml-workflows-ws/resourcequota.yaml
Namespace needs a custom quota, Context: #809
=> Add custom quota for ds-ml-workflows-ws ns

cluster-scope/base/core/namespaces/opf-ci-prow/resourcequota.yaml
allow 2 bucket for storage use of prow
=> allow 2 bucket for storage use of prow

kfdefs/base/jupyterhub/notebook-images/ml-prague-workshop.yaml
=> Update image and description for Elyra AIDevSecOps Tutorial

cluster-scope/overlays/moc/common/groups/pulp.enc.yaml
As per: https://github.com/operate-first/support/issues/176#issuecomment-869739067
/cc @fridex @HumairAK @4n4nd
=> feat: Add gubben to pulp team

odh-manifests/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
=> Add Xskipper to pyspark packages in spark2.4 based images

cluster-scope/base/core/namespaces/prometheus-anomaly-detector/kustomization.yaml, cluster-scope/base/core/namespaces/prometheus-anomaly-detector/namespace.yaml, cluster-scope/base/user.openshift.io/groups/prometheus-anomaly-detector/group.yaml, cluster-scope/base/user.openshift.io/groups/prometheus-anomaly-detector/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/prometheus-anomaly-detector/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/prometheus-anomaly-detector/rbac.yaml, cluster-scope/overlays/prod/common/groups/prometheus-anomaly-detector.enc.yaml, cluster-scope/overlays/prod/common/kustomization.yaml, cluster-scope/overlays/prod/common/secret-generator.yaml, cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Resolves https://github.com/operate-first/support/issues/294
=> onboard prometheus-anomaly-detector project

kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml
=> Grant prometheus anomaly detector group access to monitoring

kfdefs/overlays/moc/zero/kustomization.yaml
related https://github.com/operate-first/apps/pull/737
=> add opf-trino to kfdefs kustomization

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-postgresql-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
=> Update thoth grafana dashboards CRDs

cluster-scope/base/core/namespaces/opf-superset/kustomization.yaml, cluster-scope/base/core/namespaces/opf-superset/resourcequota.yaml, cluster-scope/base/core/namespaces/opf-trino/kustomization.yaml, cluster-scope/base/core/namespaces/opf-trino/resourcequota.yaml
=> Add custom quotas for superset/trino

docs/odh/kafka/README.md, docs/odh/kafka/add_kafka_topics.md, docs/odh/kafka/add_kafka_users.md
Resolves https://github.com/operate-first/apps/issues/804
=> update kafka onboarding docs

cluster-scope/overlays/prod/common/groups/argocd-readonly.enc.yaml
=> Add user to argocd readonly group

cluster-scope/overlays/prod/common/kustomization.yaml, cluster-scope/overlays/prod/common/secret-generator.yaml
=> Add readonly group to clusters

observatorium/overlays/moc/zero/objectbucketclaims/kustomization.yaml, observatorium/overlays/moc/zero/objectbucketclaims/thanos-obc.yaml
=> Remove rgw thanos obc that is not needed.

vector/base/deployment.yaml, vector/overlays/moc/zero/opf-observatorium/configmap.yaml, vector/overlays/moc/zero/opf-observatorium/kustomization.yaml, vector/overlays/moc/zero/opf-observatorium/service.yaml
Update vector to v0.14.x
Use internal route for kafka sync
Resolves https://github.com/operate-first/apps/issues/820
=> Expose Prometheus metrics for Vector

kfdefs/overlays/moc/zero/opf-monitoring/scrape-configs/additional-scrape-configs.yaml
enlist metrics job based on service requirement
Related-to: https://github.com/thoth-station/thoth-application/issues/854
=> enlist metrics job based on service requirement

cluster-scope/base/core/namespaces/opf-trino/resourcequota.yaml
To make room for cloudbeaver as per https://github.com/operate-first/support/issues/299
=> Update resource quota for trino namespace.

cloudbeaver/base/deployment.yaml, cloudbeaver/base/kustomization.yaml, cloudbeaver/base/persistentvolumeclaim.yaml, cloudbeaver/base/route.yaml, cloudbeaver/base/service.yaml, cloudbeaver/overlays/moc/zero/add_configs.yaml, cloudbeaver/overlays/moc/zero/configs/cloudbeaver.conf, cloudbeaver/overlays/moc/zero/configs/initial-data-sources.conf, cloudbeaver/overlays/moc/zero/configs/initial-data.conf, cloudbeaver/overlays/moc/zero/configs/product.conf, cloudbeaver/overlays/moc/zero/kustomization.yaml
Resolve: https://github.com/operate-first/support/issues/299
=> Add cloudbeawever deployment to opf-trino in zero cluster.

cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml, cluster-scope/base/core/namespaces/aicoe-meteor/namespace.yaml, cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Part of: https://github.com/AICoE/meteor/issues/46
Hopefully we can bypass the onboarding hold. :crossed_fingers:
=> feat: Onboard Meteor

kfdefs/base/trino/kfdef.yaml, kfdefs/overlays/moc/zero/opf-superset/kustomization.yaml, kfdefs/overlays/moc/zero/opf-trino/kustomization.yaml, odh-manifests/trino/base/hive-config.yaml
This should match live state and thus allow us to renable auto sync on odh. 
The config is mostly the same as upstream save for this new addition: 
```
<property>
<name>fs.s3a.path.style.access</name>
<value>true</value>
</property>
```
=> Add superset image and update trino config to match live.

slack-first/overlays/moc/zero/config.yaml
Added myself as a member to slack-first config file.
=> Add new user to slack-first members

cluster-scope/base/core/namespaces/thoth-pulp-experiments/resourcequota.yaml
Resolves: https://github.com/operate-first/support/issues/321
=> feat: Double memory quota for Pulp

kfdefs/base/jupyterhub/external-services/augur.yaml, kfdefs/base/jupyterhub/external-services/kustomization.yaml, kfdefs/base/jupyterhub/kustomization.yaml
Resolves: https://github.com/operate-first/support/issues/306
=> feat: Add Augur as external service to JH

cluster-scope/overlays/prod/moc/infra/kustomization.yaml, cluster-scope/overlays/prod/moc/infra/nodenetworkconfigurationpolicies/moc-nfs-network.yaml, cluster-scope/overlays/prod/moc/infra/storageclasses/moc-nfs-csi_patch.yaml, moc-nfs-democratic-csi/overlays/moc/infra/kustomization.yaml, moc-nfs-democratic-csi/overlays/moc/infra/secret-generator.yaml, moc-nfs-democratic-csi/overlays/moc/infra/secrets/moc-nfs-democratic-csi-driver-config.enc.yaml
this commit adds the democratic-csi driver to the infra cluster along
with the appropriate network configuration to access the NFS vlan.
=> connect infra cluster to nfs server

keycloak/base/keycloak.yaml
Expecting to fix the following term signal that's being received: 
```
[0m[0;31mERROR *** JBossAS wrapper process (1) received TERM signal ***[0m
```
=> Increase keycloak resource allotment on infra.

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-postgresql-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-service-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-user-api-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
upgrade thoth-station grafana dashboards
=> upgrade thoth-station grafana dashboards

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/sre/clusterrolebinding.yaml, cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/sre/kustomization.yaml, cluster-scope/base/user.openshift.io/groups/sre/group.yaml, cluster-scope/base/user.openshift.io/groups/sre/kustomization.yaml, cluster-scope/overlays/prod/common/groups/sre.enc.yaml, cluster-scope/overlays/prod/common/kustomization.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml, cluster-scope/overlays/prod/moc/curator/kustomization.yaml, cluster-scope/overlays/prod/moc/infra/kustomization.yaml, cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Created group sre and added it to all cluster and granted it role cluster-reader (implementation of this issue https://github.com/operate-first/support/issues/318).
=> feat: Added group sre with role cluster-reader to all clusters

cluster-scope/base/core/namespaces/enterprise-neurosystem-collaboration/kustomization.yaml, cluster-scope/base/core/namespaces/enterprise-neurosystem-collaboration/namespace.yaml, cluster-scope/base/user.openshift.io/groups/enterprise-neurosystem/group.yaml, cluster-scope/base/user.openshift.io/groups/enterprise-neurosystem/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/enterprise-neurosystem/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/enterprise-neurosystem/rbac.yaml, cluster-scope/overlays/prod/common/groups/enterprise-neurosystem.enc.yaml, cluster-scope/overlays/prod/common/secret-generator.yaml, cluster-scope/overlays/prod/moc/zero/kustomization.yaml
addresses https://github.com/operate-first/support/issues/313
=> add enterprise-neurosystem group and namespace

cluster-scope/overlays/prod/common/groups/sre.enc.yaml, cluster-scope/overlays/prod/common/kustomization.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml, cluster-scope/overlays/prod/moc/curator/kustomization.yaml, cluster-scope/overlays/prod/moc/infra/kustomization.yaml, cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Merge ASAP.
Fixing cluster-scope, cause master is broken. + additional little cleanup.
=> fix: group patching

cluster-scope/base/core/namespaces/koku-metrics-operator/kustomization.yaml
=> Add quota to koku metrics operator namespace.

kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/kustomization.yaml, kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/meteor-operator-servicemonitor.yaml
Related https://github.com/AICoE/meteor/issues/51
=> Add servicemonitor for meteor-operator

odh-manifests/trino/base/trino-catalog-secret.yaml
The only new field is: ` hive.metastore-timeout=30s`
=> Increase hive timeout for requests.

cluster-scope/base/core/namespaces/koku-metrics-operator/kustomization.yaml
=> Increase koku metrics ns quota.

cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
update aicoe-meteor with the large quota resources
The resource is very scarce for the components to be added, a large quota would help with demos.
=> update aicoe-meteor with the large quota resources

cloudbeaver/base/deployment.yaml
=> Update cloud beaver to 21.1.1

cluster-scope/overlays/prod/emea/rick/groups/cluster-admins.yaml
Seems like keycloak makes it lowercase :shrug:
=> Update username on rick to be lowercase.

cluster-scope/overlays/prod/common/groups/curator.enc.yaml
=> Add curator member.

dex/overlays/moc/zero/dex-cm.yaml
=> Update dex superset client to contain op1st subdomain url.

cluster-scope/overlays/prod/common/groups/esi-project.enc.yaml, cluster-scope/overlays/prod/common/groups/odh-admin.enc.yaml, cluster-scope/overlays/prod/common/groups/open-aiops.enc.yaml, cluster-scope/overlays/prod/common/groups/prometheus-anomaly-detector.enc.yaml
prometheus-anomaly-detector 
open-aiops 
odh-admin 
esi-project
Part of #791 #841
=> fix user github handles in groups

cluster-scope/base/core/namespaces/opf-trino/resourcequota.yaml, kfdefs/overlays/moc/zero/opf-trino/kustomization.yaml
=> Increase trino memory request.

kfdefs/overlays/moc/zero/opf-jupyterhub/pvcs/secret-generator.yaml, kfdefs/overlays/moc/zero/opf-jupyterhub/pvcs/user-bkoz-pvc.enc.yaml
Resolve: https://github.com/operate-first/support/issues/352
=> Increase user's pvc size in JH

cluster-scope/base/core/namespaces/opf-trino/resourcequota.yaml
=> Update requested memory for trino.

cluster-scope/overlays/prod/moc/infra/oauths/cluster_patch.yaml, cluster-scope/overlays/prod/moc/zero/oauths/cluster_patch.yaml
Related https://github.com/operate-first/apps/pull/840#issuecomment-900586323
=> update oauth openID issuer for infra/zero cluster

keycloak/overlays/moc/infra/secret-generator.yaml
Related https://github.com/operate-first/apps/pull/901
=> fix: add keycloak clients to secre-generator

keycloak/overlays/moc/infra/clients/infra.enc.yaml
=> update redirect uri for infra keucloak client

cluster-scope/overlays/prod/moc/infra/oauths/operate-first-sso-secret.enc.yaml
=> Update Infra oauth sso secret

cluster-scope/overlays/prod/moc/zero/oauths/cluster_patch.yaml
=> fix: MOC SSO for Zero client ID

cluster-scope/overlays/prod/moc/curator/oauths/cluster_patch.yaml, cluster-scope/overlays/prod/moc/curator/oauths/operate-first-sso-secret.enc.yaml, keycloak/overlays/moc/infra/clients/curator.enc.yaml, keycloak/overlays/moc/infra/secret-generator.yaml
Part of: #791 
We forgot about the curator cluster this time... let's enable it there as well.
=> feat: Enable Operate First SSO on Curator

cluster-scope/overlays/prod/emea/rick/kustomization.yaml, cluster-scope/overlays/prod/emea/rick/subscriptions/openshift-pipelines-operator-rh_patch.yaml
SSIA, resolves https://github.com/operate-first/support/issues/340 .
=> feat:Added openshift-pipelines operator for rick

cluster-scope/base/operators.coreos.com/subscriptions/prometheus-operator/kustomization.yaml, cluster-scope/base/operators.coreos.com/subscriptions/prometheus-operator/subscription.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml, cluster-scope/overlays/prod/emea/rick/subscriptions/prometheus-operator_patch.yaml
Add subscription to deploy prometheus-operator in opf-monitoring 
namespace
=> [EMEA/Rick] Create Namespace opf-monitoring

cluster-scope/base/operators.coreos.com/operatorgroups/opf-monitoring/kustomization.yaml, cluster-scope/base/operators.coreos.com/operatorgroups/opf-monitoring/operatorgroup.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml
missing operatorgroup in the previous PR (https://github.com/operate-first/apps/pull/910)
=> Add operatorgroup for opf-monitoring

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review/clusterrolebinding.yaml, observatorium/overlays/moc/zero/deployments/thanos-receive-oauth-proxy.yaml, observatorium/overlays/moc/zero/routes/kustomization.yaml, observatorium/overlays/moc/zero/routes/thanos-receive-oauth-proxy.yaml, observatorium/overlays/moc/zero/serviceaccounts/kustomization.yaml, observatorium/overlays/moc/zero/serviceaccounts/thanos-receive-oauth-proxy.yaml, observatorium/overlays/moc/zero/services/kustomization.yaml, observatorium/overlays/moc/zero/services/thanos-receive-oauth-proxy.yaml
Related https://github.com/operate-first/apps/issues/890
=> Add Oauth Proxy for Thanos receive component

cluster-scope/overlays/prod/common/groups/superset-user.enc.yaml, docs/odh/superset/add_superset_users.md
=> Add superset users on zero cluster.

kfdefs/base/jupyterhub/notebook-images/hitchhikers-guide.yaml, kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
=> feat: add Hitchhiker's guide to jupyterhub

cluster-scope/base/core/namespaces/thoth-pulp-experiments/resourcequota.yaml
Related: https://github.com/operate-first/support/issues/362#issuecomment-904813871
Closes: https://github.com/operate-first/support/issues/362
=> Increase storage request in thoth-pulp-experiments-custom

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml, kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
=> Update dashboards Thoth

cluster-scope/overlays/prod/emea/rick/kustomization.yaml, kfdefs/overlays/emea/rick/opf-monitoring/.sops.yaml, kfdefs/overlays/emea/rick/opf-monitoring/kustomization.yaml, kfdefs/overlays/emea/rick/opf-monitoring/prometheus.yaml, kfdefs/overlays/emea/rick/opf-monitoring/secrets/kustomization.yaml, kfdefs/overlays/emea/rick/opf-monitoring/secrets/prometheus-k8s.yaml, kfdefs/overlays/emea/rick/opf-monitoring/secrets/remote-write-emea-rick-sa-token.enc.yaml, kfdefs/overlays/emea/rick/opf-monitoring/secrets/secret-generator.yaml, kfdefs/overlays/emea/rick/opf-monitoring/servicemonitors/cluster-metrics-servicemonitor.yaml, kfdefs/overlays/emea/rick/opf-monitoring/servicemonitors/kustomization.yaml, observatorium/overlays/moc/zero/serviceaccounts/remote-write-emea-rick.yaml
Enable Metrics remote write to opf observatorium Thanos instance
Resolves https://github.com/operate-first/apps/issues/890
=> Enable Cluster monitoring on EMEA/RIck Cluster

cluster-scope/overlays/prod/emea/devconfus2021/groups/cluster-admins.yaml, cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml, cluster-scope/overlays/prod/emea/devconfus2021/oauths/cluster_patch.yaml, cluster-scope/overlays/prod/emea/devconfus2021/oauths/operate-first-sso-secret.enc.yaml, cluster-scope/overlays/prod/emea/devconfus2021/secret-generator.yaml, cluster-scope/overlays/prod/emea/devconfus2021/subscriptions/openshift-pipelines-operator-rh_patch.yaml, keycloak/overlays/moc/infra/clients/devconfus2021.enc.yaml, keycloak/overlays/moc/infra/secret-generator.yaml, kfdefs/overlays/emea/devconfus2021/kustomization.yaml, kfdefs/overlays/emea/devconfus2021/opf-dashboard/kustomization.yaml, kfdefs/overlays/emea/devconfus2021/opf-jupyterhub/kustomization.yaml, kubeflow-components/overlays/emea/devconfus2021/kfdef.yaml, kubeflow-components/overlays/emea/devconfus2021/kustomization.yaml, kubeflow-components/overlays/emea/devconfus2021/profiles/demo-profile.yaml, kubeflow-components/overlays/emea/devconfus2021/profiles/kustomization.yaml, kubeflow-components/overlays/emea/devconfus2021/rolebindings/kubeflow-tekton-view.yaml, kubeflow-components/overlays/emea/devconfus2021/rolebindings/kustomization.yaml, kubeflow-components/overlays/emea/devconfus2021/roles/kubeflow-tekton-view.yaml, kubeflow-components/overlays/emea/devconfus2021/roles/kustomization.yaml, odh-manifests/devconfus2021/dashboard/overlays/cluster-role/kustomization.yaml, odh-manifests/devconfus2021/dashboard/overlays/cluster-role/rbac.yaml, odh-manifests/devconfus2021/dashboard/overlays/custom-image/deployment.yaml, odh-manifests/devconfus2021/dashboard/overlays/custom-image/kustomization.yaml, odh-manifests/devconfus2021/jupyterhub/base/jupyterhub-configmap.yaml, odh-manifests/devconfus2021/jupyterhub/base/jupyterhub-groups-configmap.yaml, odh-manifests/devconfus2021/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml, odh-manifests/devconfus2021/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml, odh-operator/overlays/emea/devconfus2021/kustomization.yaml
Part of: https://github.com/operate-first/support/issues/368
We decided to spin up a new cluster for DevConf.US workshop. This PR onboards the cluster to Operate First once available.
=> feat: Onboard DevConf.US 2021 cluster

keycloak/overlays/moc/infra/clients/devconfus2021.enc.yaml
=> update oauth client secret for devconfus2021 cluster

acm/overlays/moc/infra/klusterletaddonconfigs/alex.yaml, acm/overlays/moc/infra/klusterletaddonconfigs/curator.yaml, acm/overlays/moc/infra/klusterletaddonconfigs/devconfus2021.yaml, acm/overlays/moc/infra/klusterletaddonconfigs/local-cluster.yaml, acm/overlays/moc/infra/klusterletaddonconfigs/ocp-prod.yaml, acm/overlays/moc/infra/klusterletaddonconfigs/osc-cl1.yaml, acm/overlays/moc/infra/klusterletaddonconfigs/rick.yaml, acm/overlays/moc/infra/klusterletaddonconfigs/smaug.yaml, acm/overlays/moc/infra/klusterletaddonconfigs/zero.yaml, acm/overlays/moc/infra/kustomization.yaml, acm/overlays/moc/infra/provider-connections/kustomization.yaml, acm/overlays/moc/infra/provider-connections/secret-generator.yaml
As a part of: https://github.com/operate-first/SRE/issues/370 . 
/cc @tumido
=> feat: Convert KlusterletAddonConfigs to yaml manifests

cluster-scope/base/core/namespaces/elyra-aidevsecops-tutorial/kustomization.yaml, cluster-scope/base/core/namespaces/elyra-aidevsecops-tutorial/namespace.yaml, cluster-scope/components/project-admin-public/kustomization.yaml, cluster-scope/components/project-admin-public/rbac.yaml, cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml
Create a namespace for Devconf demo
=> feat: Add elyra-aidevsecops-tutorials namespace

cluster-scope/base/operators.coreos.com/subscriptions/opf-grafana/kustomization.yaml, cluster-scope/base/operators.coreos.com/subscriptions/opf-grafana/subscription.yaml, cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml
Added grafana to devconfus2021 cluster.
Part of issue: https://github.com/operate-first/SRE/issues/370 .
=> feat: add grafana operator to devconf cluster

grafana/base/datasource.yaml, grafana/base/grafana-datasource.yaml, grafana/base/grafana.yaml, grafana/base/kustomization.yaml, grafana/base/route.yaml, grafana/overlays/emea/devconfus2021/kustomization.yaml
Deploying grafana for devconfus2021. 
Part of issue: https://github.com/operate-first/SRE/issues/370
=> wip: feat: create grafana for devconfus cluster

cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Allow prow to be on zero and smaug
=> Allow prow to be on zero and smaug

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml, cluster-scope/overlays/prod/moc/smaug/subscriptions/openshift-pipelines-operator-rh_patch.yaml
Added openshift-pipelines operator for smaug
=> feat: Added openshift-pipelines operator for smaug

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
setup opf-ci-pipelines in the smaug clusters
=> feat: setup opf-ci-pipelines in the smaug clusters

grafana/base/grafanadatasource.enc.yaml, grafana/base/kustomization.yaml, grafana/base/secrets-generator.yaml
SSIA
Related to:https://github.com/operate-first/apps/pull/959
Part of issue: https://github.com/operate-first/SRE/issues/370
=> feat: add grafanadatasource to grafana

cluster-scope/base/core/namespaces/tekton-pipelines/kustomization.yaml
setup tekton-pipeline empty namespace
=> setup tekton-pipeline empty namespace

grafana/overlays/emea/devconfus2021/grafanadatasource.enc.yaml
the existing token didn't seem to work for some reason
=> fix oauth token for the grafana datasource in devconfus2021

odh-manifests/devconfus2021/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml
SSIA 
Part of: https://github.com/operate-first/SRE/issues/370 .
/cc @tumido
=> feat: restrict options in jupyterhub profiles

cluster-scope/base/core/namespaces/thoth-website-prod/kustomization.yaml, cluster-scope/base/core/namespaces/thoth-website-prod/namespace.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml
closes https://github.com/operate-first/support/issues/376
=> add thoth-website-prod to rick

cluster-scope/overlays/prod/common/groups/operate-first.enc.yaml
Added mimotej to Operate First group to be able to access ArgoCD console.
=> feat: add mimotej to Operate First group

cluster-scope/base/core/namespaces/openshift-pipelines/kustomization.yaml, cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
=> Add thoth devops as admins to openshift-pipelines on smaug.

dex/overlays/moc/smaug/dex-clients.enc.yaml, dex/overlays/moc/smaug/dex-cm.yaml, dex/overlays/moc/smaug/kustomization.yaml, dex/overlays/moc/smaug/secret-generator.yaml
Re-created changes from upstream master.
Original PR: https://github.com/operate-first/apps/pull/970
=> Dex migration from clean branch

cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
=> Add cluster admin rolebinding to cluster admins in osc.

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
=> Add nmstate namespace to smaug.

cluster-scope/overlays/prod/moc/smaug/subscriptions/kubernetes-nmstate-operator_patch.yaml
=> Fix: update nmstate smaug subscription channel to a string

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
=> Add dex namespace to smaug

cluster-scope/base/operators.coreos.com/operatorgroups/openshift-nmstate/kustomization.yaml, cluster-scope/base/operators.coreos.com/operatorgroups/openshift-nmstate/operatorgroup.yaml, cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
The nmstate operator does not create an operatorgroup by itself.
=> Add openshift-nmstate operatorgroup

cert-manager/smaug/certificate.yaml, cert-manager/smaug/issuer.yaml, cert-manager/smaug/kustomization.yaml, cluster-scope/overlays/prod/moc/smaug/ingresscontrollers/default.yaml, cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
in response to https://github.com/operate-first/SRE/issues/366, specifically the Smaug ingress certificates.
=> Ingress cert in response to SMAUG Onboard #366

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Accidentally introduced in: https://github.com/operate-first/apps/pull/947
=> Remove cluster-admin generator file for smaug.

cluster-scope/overlays/prod/moc/smaug/ingresscontrollers/default.yaml
=> Fix secret name for ingresscontroller in smaug.

cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml
Related: https://github.com/operate-first/support/issues/389
=> Update acm to 2.3 by updating the channel.

kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
=> Fix typo in kfdef path for trino on osc.

kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml, odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Resolve: https://github.com/os-climate/os_c_data_commons/issues/55
=> Add users and group mappings to osc trino.

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml, cluster-scope/overlays/prod/moc/smaug/storageclasses/moc-nfs-csi_patch.yaml, moc-nfs-democratic-csi/overlays/moc/smaug/kustomization.yaml, moc-nfs-democratic-csi/overlays/moc/smaug/secret-generator.yaml, moc-nfs-democratic-csi/overlays/moc/smaug/secrets/moc-nfs-democratic-csi-driver-config.enc.yaml
Enable the democratic-csi driver on the Smaug cluster.
Part of operate-first/SRE#379
See also operate-first/argocd-apps#207
=> Add Democratic CSI driver to smaug

cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml, cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
Include new members of thoth-station in group thoth
=> Include new members of thoth-station in group thoth

cluster-scope/base/operators.coreos.com/subscriptions/strimzi/kustomization.yaml, cluster-scope/base/operators.coreos.com/subscriptions/strimzi/subscription.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Related https://github.com/operate-first/support/issues/394
Enable installing strimzi operator on rick
=> Enable installing strimzi operator on rick

cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/workflow.argoproj.io/customresourcedefinition.yaml, cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/workflow.argoproj.io/kustomization.yaml, cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/workflowtemplate.argoproj.io/customresourcedefinition.yaml, cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/workflowtemplate.argoproj.io/kustomization.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Allow deploying argo workflows on rick
Facing issues while submitting resources.
```
no matches for kind "WorkflowTemplate" in version "argoproj.io/v1alpha1"
```
=> Allow deploying argo workflows on rick

cluster-scope/base/operators.coreos.com/subscriptions/strimzi/subscription.yaml
fixed the name of the strimzi subscription
=> fixed the name of the strimzi subscription

cluster-scope/base/operators.coreos.com/operatorgroups/opf-kafka/kustomization.yaml, cluster-scope/base/operators.coreos.com/operatorgroups/opf-kafka/operatorgroup.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Install opf-kafka operator group in rick cluster
=> Install opf-kafka operator group in rick cluster

kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml, odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Resolve: https://github.com/os-climate/os_c_data_commons/issues/60#issuecomment-923970769
=> Add newuser and group to osc trino.

odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
=> Convert trino user passwords to be more secure.

kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/default/kustomization.yaml, kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/kustomization.yaml, odh-manifests/osc-cl1/trino/base/kustomization.yaml, odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
The kustomization is to filter out the hive catalog deployment from odh-manifests repo.
=> Add default catalog to trino and remove original hive catalog.

odh-manifests/osc-cl1/superset/base/secret.yaml
=> Enable proxy fix for superset on ai4ci.

odh-manifests/ai4ci/superset/base/secret.yaml, odh-manifests/osc-cl1/superset/base/secret.yaml
revert: https://github.com/operate-first/apps/pull/1044
and enable it for ai4ci instead
=> Disable enable proxy for osc1 and enable for ai4ci

acme-operator/overlays/emea/balrog/issuer-letsencrypt-live.yaml, acme-operator/overlays/emea/balrog/kustomization.yaml
Should have been a part of https://github.com/operate-first/apps/pull/1046
=> Add acme to balrog.

kfdefs/overlays/moc/smaug/kustomization.yaml
=> Add kustomization for kfdefs app in the moc/smaug overlay

cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
setup balrog cluster with thoth namespace, kafka and prometheus
=> feat: setup balrog cluster with thoth namespace, kafka and prometheus

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
=> Add koku metrics operator to smaug.

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
=> Add grafana operator subscription to moc/smaug

kfdefs/overlays/osc/osc-cl1/jupyterhub/profiles/singleuser-profiles-container-sizes.yaml, odh-manifests/osc-cl1/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml
xref: https://github.com/os-climate/os_c_data_commons/issues/65
=> add memory size options to os-climate cluster

odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml, odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
=> Fix endpoints, add oauth aud, and adjust perms for osc trino.

cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml, cluster-scope/overlays/prod/moc/smaug/kustomization.yaml, kfdefs/overlays/moc/smaug/opf-seldon/kustomization.yaml
=> Add seldon operator to opf-seldon in moc/smaug

grafana/base/kustomization.yaml, grafana/base/servicemonitor.yaml, kfdefs/base/argo/kustomization.yaml, kfdefs/base/argo/servicemonitor.yaml, kfdefs/base/jupyterhub/kustomization.yaml, kfdefs/base/jupyterhub/servicemonitor.yaml, kfdefs/base/kafka/kafka-podmonitors.yaml, kfdefs/base/kafka/kustomization.yaml, odh-operator/base/kustomization.yaml, odh-operator/base/servicemonitor.yaml
this will let openshift user workload monitoring monitor some of the applications
=> Add servicemonitors for various components

kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/kustomization.yaml
=> Rename osc catalogs in kustomization

kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/OSC_DataCommons_Dev/kustomization.yaml
=> Fix osc hive dev k8s resource naming scheme.

odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
=> Update osc trino dev catalog uri.

odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
=> Update osc trino group perms casing.

cluster-scope/overlays/prod/emea/balrog/kustomization.yaml, cluster-scope/overlays/prod/emea/common/kustomization.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml
=> fix: Emea is missing common

acm/overlays/moc/infra/managedclusters/demo.yaml, acm/overlays/moc/infra/managedclusters/kustomization.yaml, alertreceiver/overlays/emea/demo/kustomization.yaml, argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-demo.yaml, argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml, argocd/overlays/moc-infra/applications/envs/emea/demo/cluster-management/alertreceiver.yaml, argocd/overlays/moc-infra/applications/envs/emea/demo/cluster-management/cluster-resources.yaml, argocd/overlays/moc-infra/applications/envs/emea/demo/cluster-management/kustomization.yaml, argocd/overlays/moc-infra/applications/envs/emea/demo/kustomization.yaml, cluster-scope/overlays/prod/emea/demo/groups/cluster-admins.yaml, cluster-scope/overlays/prod/emea/demo/kustomization.yaml, cluster-scope/overlays/prod/emea/demo/oauths/cluster_patch.yaml, cluster-scope/overlays/prod/emea/demo/oauths/operate-first-sso-secret.enc.yaml, cluster-scope/overlays/prod/emea/demo/secret-generator.yaml, keycloak/overlays/moc/infra/clients/demo.enc.yaml, keycloak/overlays/moc/infra/secret-generator.yaml
Please add this cluster to Operate First.
=> feat(onboarding): Add cluster demo

keycloak/overlays/moc/infra/secret-generator.yaml
=> fix: secret name KeycloakClient for Demo

keycloak/overlays/moc/infra/clients/demo.enc.yaml
=> fix: KeycloakClient apiversion for Demo

cluster-scope/base/core/namespaces/ushift-dev/kustomization.yaml, cluster-scope/base/core/namespaces/ushift-dev/namespace.yaml, cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/group.yaml, cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/octo-ushift-dev/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/octo-ushift-dev/rbac.yaml, cluster-scope/overlays/prod/common/kustomization.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>
=> feat(onboarding): Add team octo-ushift-dev

argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/kubevirt-hyperconverged.yaml, argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/kustomization.yaml, cluster-scope/overlays/prod/emea/rick/kustomization.yaml, cluster-scope/overlays/prod/emea/rick/subscriptions/kubevirt-hyperconverged_patch.yaml, kubevirt-hyperconverged/overlays/emea/rick/kustomization.yaml
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>
Closes https://github.com/operate-first/support/issues/397
=> Deploy CNV operator on Rick cluster

cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Resolves: https://github.com/operate-first/SRE/issues/396
=> fix: Rick is missing alertreceiver namespace

OWNERS
=> feat: Add larsks to approvers

argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/kubevirt-hyperconverged.yaml
I've messed up review on #1101 and we tried to deploy the CNV to Zero instead of Rick :facepalm:
=> fix: CNV app placement

cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml
closes #1105 
https://operatefirst.slack.com/archives/C01RMPVUUK1/p1633099271262000?thread_ts=1633092437.256000&cid=C01RMPVUUK1
=> add limit range for seldon namespace

cluster-scope/overlays/prod/emea/demo/groups/cluster-admins.yaml
=> Add users to cluster admins for demo cluster.

cluster-scope/overlays/prod/emea/demo/groups/cluster-admins.yaml
=> Change demo username to lowercase.

cluster-scope/base/operators.coreos.com/subscriptions/opendatahub-operator/kustomization.yaml, cluster-scope/base/operators.coreos.com/subscriptions/opendatahub-operator/subscription.yaml, cluster-scope/overlays/prod/emea/demo/kustomization.yaml
=> Add OpenDataHub Subscription to the Demo Cluster

cluster-scope/base/core/namespaces/ushift-dev/kustomization.yaml
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>
=> Increase Quota for octo-ushift-dev team

grafana/overlays/moc/smaug/grafana-oauth.yaml
Formatting and updating the Grafana rules so anyone in SRE has editor privileges.
=> Updating Grafana access rules

cluster-scope/base/user.openshift.io/groups/curator/group.yaml
Add Leihao Chen to curator team on opf
=> Add Leihao Chen to curator team on opf

cluster-scope/base/core/namespaces/ushift-dev/kustomization.yaml
Increasing quota from **medium** to **large**
=> Increase quota for ushift-dev project

cloudbeaver/overlays/moc/smaug/add_configs.yaml, cloudbeaver/overlays/moc/smaug/configs/cloudbeaver.conf, cloudbeaver/overlays/moc/smaug/configs/initial-data-sources.conf, cloudbeaver/overlays/moc/smaug/configs/initial-data.conf, cloudbeaver/overlays/moc/smaug/configs/product.conf, cloudbeaver/overlays/moc/smaug/kustomization.yaml
the namespace will be added by prod and staging Jupyterhub migration pull request.
=> migrating cloudbeaver to smaug

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml, kfdefs/overlays/moc/smaug/opf-superset/kustomization.yaml, kfdefs/overlays/moc/smaug/opf-superset/secrets/kustomization.yaml, kfdefs/overlays/moc/smaug/opf-superset/secrets/oauth-client-secret.enc.yaml, kfdefs/overlays/moc/smaug/opf-superset/secrets/secret-generator.yaml, kfdefs/overlays/moc/smaug/opf-superset/secure-route.yaml, kfdefs/overlays/moc/smaug/opf-trino/.sops.yaml, kfdefs/overlays/moc/smaug/opf-trino/kustomization.yaml, kfdefs/overlays/moc/smaug/opf-trino/secrets/file-auth-secret.enc.yaml, kfdefs/overlays/moc/smaug/opf-trino/secrets/kustomization.yaml, kfdefs/overlays/moc/smaug/opf-trino/secrets/oauth-client-secret.enc.yaml, kfdefs/overlays/moc/smaug/opf-trino/secrets/opf-datacatalog-bucket.enc.yaml, kfdefs/overlays/moc/smaug/opf-trino/secrets/secret-generator.yaml, kfdefs/overlays/moc/smaug/opf-trino/secure-route.yaml
Not sure about namespaces that go with this, I checked on the cluster and couldn't find any there that related to any of these 3. Also now that PVCs are set up, we should double-check the memory request patches.
=> migration of kfdefs: opf-superset, and opf-trino to smaug

argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/alertreceiver.yaml, argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml, cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
adding Alertmanager to Argocd for Smaug.
=> migrating alertreciever to smaugs

odh-manifests/osc-cl1/superset/base/secret.yaml
Resolve: https://github.com/os-climate/os_c_data_commons/issues/78
=> Update authenticated users to alpha on osc superset.

kfdefs/overlays/moc/smaug/opf-trino/secrets/postgres-dbs.enc.yaml, kfdefs/overlays/moc/smaug/opf-trino/secrets/secret-generator.yaml, odh-manifests/smaug/trino/base/trino-catalog-secret.yaml, odh-manifests/smaug/trino/base/trino-coordinator-dc.yaml, odh-manifests/smaug/trino/base/trino-worker-dc.yaml
For: https://github.com/operate-first/support/issues/431
=> Add curator postgres db to trino on smaug.

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view/clusterrolebinding.yaml, cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view/kustomization.yaml, cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Also gives metrics access to the `operate-first` group
Related https://github.com/operate-first/support/issues/379
=> Give cluster metrics access to logs-insights group

acm/overlays/moc/infra/managedclustersetbindings/octo-ushift-dev.yaml, acm/overlays/moc/infra/managedclustersets/octo-ushift-dev.yaml, acm/overlays/moc/infra/placements/argocd-managed-clusters.yaml, cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/open-cluster-management:managedclusterset:admin:octo-ushift-dev/clusterrolebinding.yaml, cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/open-cluster-management:managedclusterset:admin:octo-ushift-dev/kustomization.yaml, cluster-scope/overlays/prod/moc/infra/kustomization.yaml, docs/acm/adding_users_to_acm.md
Should resolve: https://github.com/operate-first/support/issues/414
=> Add team to acm, along with docs for future instructions.

.pre-commit-config.yaml
As per: https://github.com/thoth-station/thoth-application/issues/2111#issuecomment-957617546
=> Switch to https for precommit config.

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml, cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Requested: https://github.com/operate-first/SRE/issues/382#issuecomment-944386332
Supports: https://github.com/operate-first/SRE/issues/382
=> chore: Migrate apicurio to smaug

cluster-scope/base/core/namespaces/openshift-vertical-pod-autoscaler/kustomization.yaml, cluster-scope/components/project-view-rolebindings/neu-students/kustomization.yaml, cluster-scope/components/project-view-rolebindings/neu-students/rbac.yaml
Changes:
* Gives `openshift-vertical-pod-autoscaler` namespace access to `neu-students` group. This helps in accessing logs of the operator for debugging purposes.
=> Get openshift-vpa ns access to group neu-students

cluster-scope/base/noobaa.io/backingstores/kustomization.yaml, cluster-scope/base/noobaa.io/backingstores/noobaa-default-backing-store.yaml, cluster-scope/overlays/prod/moc/smaug/backingstores/noobaa-default-backing-store_patch.yaml, cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Related https://github.com/operate-first/SRE/issues/405
=> Add nooba.io/backingstore to increase ceph storage

grafana/base/dashboards/cluster-management/cluster-memory-overview.yaml
ATM it's the same as the cpu one.
=> Make memory overview dashboard uid unique.

docs/odh/trino/add_more_buckets.md, docs/odh/trino/add_more_postgress_catalogs.md
=> Add instructions on adding postgresql connector to trino on smaug.

cluster-scope/overlays/prod/moc/infra/kustomization.yaml
related: https://github.com/operate-first/SRE/issues/414#issuecomment-952996914
=> Add cnv ns to infra.

grafana/overlays/moc/smaug/grafanadatasource.enc.yaml
=> update smaug grafana datasource to include balrog,infra,rick clusters

cluster-scope/overlays/prod/moc/curator/kustomization.yaml
=> Bind cluster admin grp to admin role in curator.

kfdefs/overlays/osc/osc-cl1/jupyterhub/pvcs/kustomization.yaml, kfdefs/overlays/osc/osc-cl1/jupyterhub/pvcs/oindrillac.yaml
=> Increase oindrilla's PVC on OS Climate Jupyterhub

docs/odh/trino/access_public_bucket.md
Related: https://github.com/operate-first/support/issues/165
=> Document public bucket in smaug.

docs/odh/trino/access_public_bucket.md
=> Reformat public bucket docs.

cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
To help with: https://github.com/os-climate/aicoe-osc-demo/issues/87
=> Add user to osc odh admin group.

cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/batchtransfers.motion.fybrik.io/customresourcedefinition.yaml, cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml, cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml, cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml, cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml, cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/streamtransfers.motion.fybrik.io/customresourcedefinition.yaml
This PR updates the Fybrik CRD manifest files
@ronenkat @HumairAK
=> Updating Fybrik CRD manifests

argocd/overlays/moc-infra/applications/envs/moc/smaug/thoth/prod/kustomization.yaml
Resolves Operate-first PR 2 for [this issue](https://github.com/thoth-station/thoth-application/issues/2029)
=> enabling argocd for thoth-monitoring in overlay

observatorium/overlays/moc/smaug/kustomization.yaml, observatorium/overlays/moc/smaug/loki/kustomization.yaml, observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-chunk-cache.yaml, observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-compactor.yaml, observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-distributor.yaml, observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-index-query-cache.yaml, observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-ingester.yaml, observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-querier.yaml, observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-query-frontend.yaml, observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-results-cache.yaml
=> update `app.kubernetes.io/instance` label in loki to match argocd

cluster-scope/base/core/namespaces/otel-dev/kustomization.yaml, cluster-scope/base/core/namespaces/otel-dev/namespace.yaml, cluster-scope/base/user.openshift.io/groups/octo-otel-dev/group.yaml, cluster-scope/base/user.openshift.io/groups/octo-otel-dev/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/octo-otel-dev/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/octo-otel-dev/rbac.yaml, cluster-scope/overlays/prod/common/kustomization.yaml, cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Adding Project for OTEL development to Smaug
```
ns: otel-dev
group: octo-otel-dev
```
cc: @tumido @HumairAK  - let me know what I'm missing
=> Adding Project OTEL-DEV to Smaug

docs/odh/trino/add_more_buckets.md, kfdefs/overlays/moc/smaug/opf-trino/hive-metastores/kustomization.yaml, kfdefs/overlays/moc/smaug/opf-trino/hive-metastores/operate-first_general/kustomization.yaml, kfdefs/overlays/moc/smaug/opf-trino/secrets/s3buckets.enc.yaml, odh-manifests/smaug/trino/base/trino-catalog-secret.yaml
Furthers: https://github.com/operate-first/support/issues/165#issuecomment-954836520
As per docs [here](https://github.com/operate-first/apps/blob/master/docs/odh/trino/add_more_buckets.md).
=> Add public bucket to trino on Smaug.

argocd/overlays/moc-infra/applications/envs/moc/infra/operate-first/cluster-logging.yaml
=> [Fix] target cluster name infra logging argocd app

cluster-scope/base/core/namespaces/opf-kafka/resourcequota.yaml, odh-manifests/smaug/kafka/base/kafka-cluster.yaml
Resolves https://github.com/operate-first/apps/issues/1301
=> Set kafka/zookeeper resources in smaug

cluster-logging/overlays/emea/balrog/clusterlogforwarders/clusterlogforwarder.yaml, cluster-logging/overlays/emea/rick/clusterlogforwarders/clusterlogforwarder.yaml, cluster-logging/overlays/moc/infra/clusterlogforwarders/clusterlogforwarder.yaml
=> [Fix] kafka broker url in CLO configs

argocd/overlays/moc-infra/applications/envs/moc/smaug/b4mad/racing.yml, cluster-scope/base/user.openshift.io/groups/b4mad/group.yaml
* add @ppatierno as a contributor
* change the argocd repourl to https://github.com/b4mad/racing
=> b4mad-racing: add paolo / change argocd repoURL

cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
Currently working on an issue in ocp-ci-analysis that requires me to have access to superset for testing
=> Adding myself to the superset users group

kfdefs/overlays/moc/smaug/opf-trino/secrets/postgres-dbs.enc.yaml, odh-manifests/smaug/trino/base/trino-catalog-secret.yaml
Related to: https://github.com/sandiego-rh/sandiego/issues/87
=> Add OSPO's project San Diego postgresql db to trino on smaug

cluster-scope/base/user.openshift.io/groups/prometheus-ai/group.yaml, cluster-scope/base/user.openshift.io/groups/prometheus-ai/kustomization.yaml, cluster-scope/overlays/prod/common/kustomization.yaml
Hey,
I've added prometheus-ai group to operate-first/apps
This is second PR, the last one aborted.
Thanks,
Ben
=> prometheus-ai group added

cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
Related to [issue #474 on operate-first/support](https://github.com/operate-first/support/issues/474#issuecomment-966459339)
=> Added my GitHub username to thoth group in group.yaml

cluster-scope/base/core/namespaces/seraph-ingress/kustomization.yaml, cluster-scope/base/core/namespaces/seraph-ingress/namespace.yaml, cluster-scope/base/core/namespaces/seraph-platform-mq/kustomization.yaml, cluster-scope/base/core/namespaces/seraph-platform-mq/namespace.yaml, cluster-scope/base/user.openshift.io/groups/seraph/group.yaml, cluster-scope/base/user.openshift.io/groups/seraph/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/seraph/kustomization.yaml, cluster-scope/components/project-admin-rolebindings/seraph/rbac.yaml, cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Please welcome Project Seraph to Operate First platform! :slightly_smiling_face: 
Resolves: https://github.com/AICoE/seraph/issues/7
=> feat: Onboard Project Seraph

grafana/overlays/moc/smaug/grafana-oauth.yaml
Permission to access grafana dashboard.
=> Provide access to curator team for Grafana.

grafana/overlays/moc/smaug/grafana-oauth.yaml
=> Provide curator team editor access to Grafana

grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-cpu-overview.yaml, grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-memory-overview.yaml, grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-pod-overview.yaml, grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-storage-overview.yaml, grafana/overlays/moc/smaug/dashboards/cluster-management/namespace_cpu_and_memory_overview.yaml
=> Add grafana piechart plugin to cluster-mgmt dashboards on smaug.

observatorium/base/instance/thanos/common/example-thanos-objectstorage-secret.yaml, observatorium/base/instance/thanos/common/kustomization.yaml, observatorium/base/instance/thanos/kustomization.yaml, observatorium/base/instance/thanos/receive-controller/configmap.yaml, observatorium/base/instance/thanos/receive-controller/deployment.yaml, observatorium/base/instance/thanos/receive-controller/kustomization.yaml, observatorium/base/instance/thanos/receive-controller/role.yaml, observatorium/base/instance/thanos/receive-controller/rolebinding.yaml, observatorium/base/instance/thanos/receive-controller/service.yaml, observatorium/base/instance/thanos/receive-controller/serviceaccount.yaml, observatorium/base/instance/thanos/receive/kustomization.yaml, observatorium/base/instance/thanos/receive/services/default-hashring.yaml, observatorium/base/instance/thanos/receive/services/kustomization.yaml, observatorium/base/instance/thanos/receive/services/service.yaml, observatorium/base/instance/thanos/receive/statefulset.yaml, observatorium/overlays/moc/smaug/kustomization.yaml, observatorium/overlays/moc/smaug/thanos/kustomization.yaml, observatorium/overlays/moc/smaug/thanos/secrets/secrets-generator.yaml, observatorium/overlays/moc/smaug/thanos/secrets/thanos-objectstorage-secret.enc.yaml, observatorium/overlays/moc/smaug/thanos/servicemonitors/kustomization.yaml, observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-receive-controller.yaml, observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-receive.yaml
Related https://github.com/operate-first/apps/issues/1327
=> Add thanos receive deployment to moc smaug
