operate-first/apps

kfdef/jupyterhub/kustomization.yaml
kfdef/superset/kustomization.yaml

The suggestion here is that the default namespaces for components  use the `opf-` prefix with the format opf-< component >

Update namespaces to use opf- prefix

---

.aicoe-ci.yaml
.pre-commit-config.yaml
kfdef/jupyterhub/kfdef.yaml
kfdef/jupyterhub/kustomization.yaml
kfdef/superset/kfdef.yaml
kfdef/superset/kustomization.yaml
operator/base/kustomization.yaml
operator/base/operator_group.yaml
operator/base/subscription.yaml

Fixes #4 
- Consolidate `pre-commit-hooks` hooks into single version reference
- `pre-commit autoupdate` to newest versions
- Format YAMLs to make pre-commit happier

Make pre-commit happy

---

kfdef/jupyterhub/kfdef.yaml

This is a basic deployment of the Prometheus operator for the JH namespace.
We will still need to add a [servicemonitor](https://github.com/opendatahub-io/odh-manifests/blob/master/prometheus/operator/base/jupyterhub-servicemonitor.yaml) for the JH service to get scraped.

Add monitoring components for Jupyterhub deployment

---

kfdef/monitoring/kfdef.yaml
kfdef/monitoring/kustomization.yaml
kfdef/monitoring/prometheus-route.yaml
kfdef/monitoring/prometheus.yaml

Will need to add a route for public access
This will read metrics from opf-jupyterhub prometheus using remote read

Add opf-monitoring namespace with Prometheus instance

---

kfdef/jupyterhub/notebook-images/kustomization.yaml
kfdef/jupyterhub/notebook-images/ocp-ci-analysis.yaml

This PR updates `kfdef/jupyterhub/notebook-images/kustomization.yaml` and added `kfdef/jupyterhub/notebook-images/ocp-ci-analysis.yaml` so that this [repo](https://github.com/aicoe-aiops/ocp-ci-analysis) would be included and available as a deployable image on MOC JH.

Updated "notebook-images/" to include ocp-ci-analysis project

---

kfdef/jupyterhub/notebook-images/ceph-drive-failure.yaml
kfdef/jupyterhub/notebook-images/kustomization.yaml

Since all the data, models, and notebooks are already open source for the hard drive failure prediction project, we could make the image available in public facing JH as well.

Add hard drive failure prediction notebook img to notebook-images

---

kfdef/jupyterhub/notebook-images/configuration-files-analysis.yaml
kfdef/jupyterhub/notebook-images/kustomization.yaml

This is related to [issue](https://github.com/aicoe-aiops/configuration-files-analysis/issues/14)
This PR updates kfdef/jupyterhub/notebook-images/kustomization.yaml and added kfdef/jupyterhub/notebook-images/configuration-files-analysis.yaml so that config file analysis repo would be included and available as a deployable image on MOC JH.

added notebook images for configuration file analysis project

---

kfdef/datacatalog/kfdef.yaml
kfdef/datacatalog/kustomization.yaml

Resolves: #15
Requires: https://github.com/opendatahub-io/odh-manifests/pull/227, https://github.com/opendatahub-io/odh-manifests/pull/228, https://github.com/opendatahub-io/odh-manifests/pull/250, https://gitlab.com/opendatahub/opendatahub-images/-/merge_requests/4, https://gitlab.com/opendatahub/opendatahub-images/-/merge_requests/5
Deploy full data catalog:
- Hue
- Thrift server
- Minimal spark cluster for Thrift server
- Ceph
It also interconnects:
- Hue -> Thrift Server
- Hue -> Ceph
- Thrift Server -> Spark
- Thrift Server -> Ceph

feat(datacatalog): Deploy Thrift Server, Hue, Ceph into a single namespace

---

kfdef/dashboard/kfdef.yaml
kfdef/dashboard/kustomization.yaml
kfdef/dashboard/overrides/overlays/cluster-role/kustomization.yaml
kfdef/dashboard/overrides/overlays/cluster-role/rbac.yaml
kfdef/dashboard/overrides/overlays/custom-image/kustomization.yaml

Resolves: #12 
Deploys a **fork** of the ODH Dashboard with following patches applied:
- https://github.com/opendatahub-io/odh-dashboard/pull/32
- https://github.com/opendatahub-io/odh-dashboard/pull/31
- https://github.com/opendatahub-io/odh-dashboard/pull/27
This is baked into a custom image at https://quay.io/repository/tcoufal/odh-dashboard
Additionally to that it deploys a `ClusterRole` with a `ClusterRoleBinding`, allowing `odh-dashboard` service account to look up all the namespaces and consume `kfdef` resouces from them.
Example:
Here you can see Argo running at `opf-argo` and Hue with Thrift server running at `opf-datacatalog`. All located successfully, with routes as well.

feat: Add dashboard

---

kfdef/monitoring/grafana.yaml
kfdef/monitoring/kfdef.yaml
kfdef/monitoring/prometheus-route.yaml
kfdef/monitoring/prometheus.yaml

Adding these annotations will make argocd deploy the kfdef first (wave 0)
and then rest of the resources will be created (wave 1)
Closes #44

[Monitoring] Add argocd wave annotations for monitoring resources

---

base/jupyterhub/kfdef.yaml

Was accidentally removed in #46 
This also happened to break the `kustomize build` for JH because the overlays index had changed.

Add JH monitoring back in and fix kustomize build error for jh

---

docs/add_kafka_topics.md

Based on the following statement: `Replace my-topic with a preferred name.`
the example component name should be `my-topic`.
correct the example name referenced

correct the example name referenced

---

observatorium/grafana-data-sources/kustomization.yaml
observatorium/grafana-data-sources/opf-test-loki-source.yaml
observatorium/grafana.yaml
observatorium/kfdef.yaml
observatorium/kustomization.yaml
observatorium/observatorium.yaml

The Observatorium CR consists a lot of thanos configuration because it is required, but all of thanos stuff has been scaled down.

Add Loki Stack using Observatorium

---

observatorium/base/instance/example-loki-objectstorage-secret.yaml
observatorium/base/instance/grafana-data-sources/kustomization.yaml
observatorium/base/instance/grafana-data-sources/opf-test-loki-source.yaml
observatorium/base/instance/grafana.yaml
observatorium/base/instance/kfdef.yaml
observatorium/base/instance/kustomization.yaml
observatorium/base/instance/observatorium.yaml
observatorium/base/operator/kustomization.yaml

Add Grafana deployment using ODH 
Add example Grafana Datasource for Loki 
Trim down the Observatorium CR to just loki and required component values
This disables the Observatorium API and we can interact with Loki directly 
Later we can update it to deploy Observatorium and API and Thanos

Add the Observatorium CR to deploy Loki 

---

observatorium/base/instance/kustomization.yaml
observatorium/base/instance/loki-routes.yaml

This will expose the loki frontend and distributor services
Frontend is to query logs from loki
Distributor is to push logs into loki

Add routes to access loki distributor and frontend api

---

odh/base/monitoring/overrides/dashboards/jupyterhub-dashboard.yaml

Adding `GrafanaDashboard` resource to include the Jupyterhub dashboard created at: https://github.com/operate-first/SRE/pull/17.

Add jupyterhub grafana dashboard resource

---

odh/base/jupyterhub/notebook-images/kustomization.yaml
odh/base/jupyterhub/notebook-images/openshift-anomaly-detection.yaml

This PR defines an ImageStream in a yaml and adds it as a resource to jupyterhub kustomization.yaml. This image is of the public facing (no customer data) version of the [openshift-anomaly-detection](https://github.com/aicoe-aiops/openshift-anomaly-detection) project.

Add openshift-anomaly-detection notebook image to notebook-images

---

odh/base/datacatalog/kfdef.yaml

Resolves: #41 
Data catalog has been fully merged to ODH upstream. Let's point our manifests to ODH `master` branch instead of individual PR branches.

feat: Datacatalog manifests point to ODH master

---

odh/base/jupyterhub/kustomization.yaml

This will also sync all the notebook images along with the jupyterhub kfdef in the [argocd app](https://github.com/operate-first/argocd-apps/blob/main/odh/jupyterhub.yaml)

[JH] add notebook-images to jh kustomization

---

observatorium/components/rbac/kustomization.yaml
observatorium/components/rbac/rolebinding.yaml
observatorium/overlays/moc/kustomization.yaml
odh/components/rbac/kustomization.yaml
odh/components/rbac/rolebinding.yaml
odh/overlays/moc/argo/kustomization.yaml
odh/overlays/moc/dashboard/kustomization.yaml
odh/overlays/moc/datacatalog/kustomization.yaml
odh/overlays/moc/jupyterhub/kustomization.yaml
odh/overlays/moc/kafka/kustomization.yaml
odh/overlays/moc/monitoring/kustomization.yaml
odh/overlays/moc/superset/kustomization.yaml

Fixes #97 
I'm using components here so I don't have to copy paste the same rolebinding everywhere. However, I do copy/paste it once for observatorium and odh, as they seem like different entities, open to changing this however and having a broader shared components folder at the root.

Add operate-first project admin rbac to as components

---

odh/base/monitoring/github-receiver-service.yaml
odh/base/monitoring/github-receiver.yaml
odh/base/monitoring/kustomization.yaml
odh/overlays/crc/monitoring/example-github-secret.yaml
odh/overlays/crc/monitoring/kustomization.yaml
odh/overlays/moc/monitoring/.sops.yaml
odh/overlays/moc/monitoring/secrets/github-secret.enc.yaml
odh/overlays/moc/monitoring/secrets/secret-generator.yaml
odh/overlays/quicklab/monitoring/example-github-secret.yaml
odh/overlays/quicklab/monitoring/kustomization.yaml

Adding [GitHub Alertmanager](https://github.com/m-lab/alertmanager-github-receiver) for incident management. The GitHub alertmanager receiver will create new issues in a given repository for triggered Prometheus alerts. See https://github.com/operate-first/SRE/issues/19 for more details.

Add github alertmanager receiver

---

odh/base/jupyterhub/notebook-images/kustomization.yaml
odh/base/jupyterhub/notebook-images/time-series.yaml

In this PR, I add the [time-series project](https://github.com/aicoe-aiops/time-series) [image](https://quay.io/repository/aicoe/time-series) to the notebook-images.
Confirmed locally, the image runs without any errors.

Add time series notebook imagestream to notebook-images

---

odh/base/monitoring/overrides/prometheus-operator/base/prometheus-rules.yaml
odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml

Adding basic availability alerts for the operate first services (currently, we have the `up` metric available only for the prometheus service)
This closes #101

Add prometheus availability alerts

---

namespaces/overlays/moc/argocd/kustomization.yaml
namespaces/overlays/moc/argocd/rbac.yaml

I've intentionally left out the group/namespace for now. I don't have permissions to see the namespace so I can't see what the current annotations (and other fields) are there just yet, once I have permissions to do that I will update with the namespace. 
I've left the group out because, I'd like argocd to create these permissions first so I can add secret management capabilities, as it stands argocd won't be able to decrypt this group.
[Related](https://github.com/open-infrastructure-labs/moc-cnv-sandbox/issues/1)

Add argocd admins

---

odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-dashboard.yaml

Fix jupyterhub dashboard name to follow the correct format:
`metadata.name: Invalid value: \"Jupyterhub\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

Fix jh dashboard name

---

odh/overlays/moc/monitoring/dashboards/kustomization.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/common-patch.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/kustomization.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-postgresql-metrics.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-user-api-metrics.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
odh/overlays/moc/monitoring/datasource/kustomization.yaml
odh/overlays/moc/monitoring/datasource/thoth-station-datasource.yaml
odh/overlays/moc/monitoring/kustomization.yaml

include thoth grafana dashboard to the moc monitoring
Depends-On: https://github.com/thoth-station/thoth-application/pull/752
Related-to: https://github.com/operate-first/apps/issues/108
Questions:
How to introduce the datasource along with this? 
Referencing this https://github.com/operate-first/apps/issues/59, should i also include the datasource manifest along with these.

include thoth grafana dashboard to the moc monitoring

---

odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
odh/base/monitoring/overrides/prometheus-operator/base/servicemonitor.yaml

Override the [odh servicemonitor](https://github.com/opendatahub-io/odh-manifests/blob/master/prometheus/operator/base/servicemonitor.yaml) to include opf namespaces
Also remove the remote read config from Prometheus since we won't need it after the JH service monitor is available

Add servicemonitor to monitor ODH deployed components

---

odh/base/jupyterhub/kfdef.yaml

these changes are related to #123

Remove unused Prometheus from opf-jupyterhub

---

odh/base/monitoring/github-receiver-service.yaml
odh/base/monitoring/github-receiver.yaml

This will:
1. Update the github receiver to enable auto closing of issues for resolved alerts
2. Add the metrics port for the github receiver service so that prometheus can monitor it

Update github receiver

---

odh/base/monitoring/github-receiver-service.yaml

should fix `Service "github-receiver-service" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value]`

fix gh alert receiver service port names

---

odh/base/monitoring/github-receiver.yaml

Should fix the error:
`flag provided but not defined: -auth-token`

fix gh receiver auth-token arg

---

odh/base/argo/kfdef.yaml

Updates Argo to 2.12.3
Requires: https://github.com/opendatahub-io/odh-manifests/pull/208 and https://github.com/operate-first/odh-dashboard/pull/4

feat: Update ODH Argo to latest

---

cluster-scope/overlays/moc/kustomization.yaml

this enables sync for the [argocd namespace](https://github.com/operate-first/apps/tree/master/cluster-scope/base/namespaces/argocd)

Add argocd to moc cluster-scope overlay

---

cluster-scope/base/clusterroles/prow.k8s.io/aggregate-to-admin.yaml
cluster-scope/base/clusterroles/prow.k8s.io/aggregate-to-edit.yaml
cluster-scope/base/clusterroles/prow.k8s.io/aggregate-to-view.yaml
cluster-scope/base/clusterroles/prow.k8s.io/kustomization.yaml
cluster-scope/base/crds/prow.k8s.io/crd.yaml
cluster-scope/base/crds/prow.k8s.io/kustomization.yaml
cluster-scope/overlays/moc/kustomization.yaml

Fixes: https://github.com/operate-first/apps/issues/146
Also make the CRD static and not pulling it from Thoth (they can put anything in that file actually...) This locks it down.

feat: make Prow CRD static and add aggregate cluster roles

---

.pre-commit-config.yaml
hack/onboarding.sh

Related: #120 
Required by: https://github.com/operate-first/support/pull/40
Pre commit will fail, because of TABs instead of spaces, but HEREDOC requires TABS. :exploding_head:

feat: Add onboarding script

---

odh/base/monitoring/overrides/prometheus-operator/overlays/alerts/prometheus-rules.yaml

Adding basic "up" alerts for available opf services, based on grafana dashboard created [here](https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/r7WqgaBMk/operatefirst-availability?orgId=1&refresh=1m)
This closes https://github.com/operate-first/SRE/issues/33

Add basic up alerts for opf services

---

odh/overlays/moc/monitoring/kustomization.yaml

Including the GitHub alertmanager receiver secret in kustomize, as secret management is now in place
Related to #77

Adding github secret to kustomize

---

odh/overlays/moc/monitoring/servicemonitors/kustomization.yaml
odh/overlays/moc/monitoring/servicemonitors/thoth-station-servicemonitor.yaml

servicemonitor setup for thoth-station component monitoring
Related-to: https://github.com/operate-first/apps/issues/108

servicemonitor setup for thoth-station component monitoring

---

cluster-scope/base/clusterrolebindings/metrics/kustomization.yaml
cluster-scope/base/clusterrolebindings/metrics/metrics-clusterrolebinding.yaml
cluster-scope/base/clusterroles/metrics/kustomization.yaml
cluster-scope/base/clusterroles/metrics/metrics-clusterrole.yaml
cluster-scope/base/namespaces/openshift-monitoring/kustomization.yaml
cluster-scope/overlays/moc/kustomization.yaml

Closes #160 
once this is pushed, we can add servicemonitors to monitor kube-state-metrics and node-exporter metrics
ping @tumido @larsks

Add monitoring rbc for openshift-monitoring namespace

---

cluster-scope/base/clusterrolebindings/metrics/cluster-metrics-federation-clusterrolebinding.yaml
cluster-scope/base/clusterrolebindings/metrics/kustomization.yaml

According to the [openshift monitoring docs](https://docs.openshift.com/container-platform/4.5/monitoring/cluster_monitoring/prometheus-alertmanager-and-grafana.html#monitoring-accessing-prometheus-alertmanager-grafana-directly_accessing-prometheus), we need to add a clusterrolebinding for opf prometheus to be able to access (federate) metrics from openshift-monitoring prometheus

Add clusterrolebinding for opf prometheus to get clustermetrics

---

odh/base/dashboard/overrides/overlays/custom-image/kustomization.yaml

This will allow us to apply https://github.com/operate-first/odh-dashboard/pull/4 which is already available as: `quay.io/operate-first/odh-dashboard:latest`
https://quay.io/repository/operate-first/odh-dashboard/manifest/sha256:fe8ee3c51b922bf7a4f1b242d4b9ed727a017cd3c9b85804c746210f10e32ad0

feat: Update ODH Dashboard downstream to latest

---

odh/base/dashboard/overrides/overlays/custom-image/deployment.yaml
odh/base/dashboard/overrides/overlays/custom-image/kustomization.yaml

This scale down the ODH Dashboard from unnecessary 2 replicas to a single one for now. I don't think there's any need for 2, they are idle all the time anyways.
Also specifies a `ImagePullPolicy` to `Always` so in case we update the `quay.io/operate-first/odh-dashboard:latest` openshift can update the image on a new pod rollout.

feat: Scale down and always fetch ODH Dashboard 

---

odh/base/monitoring/kfdef.yaml
odh/base/monitoring/overrides/grafana-operator/base/grafana.yaml
odh/base/monitoring/overrides/grafana-operator/overlays/datasources/kustomization.yaml
odh/base/monitoring/overrides/grafana-operator/overlays/datasources/odh-datasource.yaml

Add odh grafana datasource
This will enable anonymous users to see our dashboards and edit them, but they won't be able to save their changes.
So no need for people to login to view existing dashboards.
Closes #59

Enable anonymous access to grafana

---

odh/base/monitoring/alertmanager-config.yaml
odh/base/monitoring/github-receiver.yaml

This addresses:
- https://github.com/operate-first/SRE/issues/37 - ensuring proper issue title gets added when an alert is triggered, based on the suggestions discussed here: https://github.com/m-lab/alertmanager-github-receiver/issues/50#issuecomment-769996613
- adds a `resolved` label to the issue once the alert is resolved

Fix alerting

---

odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml

This should enable metrics to persist for 2 weeks
Just to be clear because the number of replicas are set to 2, this will create 2 10gig PVCs
I am planning to let this run over the weekend and see how much storage is used by these metrics for 2 days. Using that information, we can adjust the size of the PVC

Add storage to opf prometheus to retain metrics for 2 weeks

---

odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml

This should resolve issues:
https://github.com/operate-first/SRE/issues/38 to https://github.com/operate-first/SRE/issues/49
The reason these issues were created is because the current Prometheus instance is out of storage and cannot collect new metrics. Because the metrics for the services are absent, the alerts are triggered.

Increase Prometheus Storage and reduce Metrics Retention

---

OWNERS

As per discussion [here](https://github.com/open-infrastructure-labs/ops-issues/issues/16#issuecomment-769881670). We are storing various cluster manifests here, so it stands to reason the environment owners should be reviewers as well.

Added moc infra members to owners

---

odh/overlays/moc/monitoring/servicemonitors/thoth-station-servicemonitor.yaml

service monitor added for metrics scraping from thoth-deployment-examples
Related-to: https://github.com/thoth-station/elyra-aidevsecops-tutorial/issues/43

service monitor added for metrics scraping from thoth-deployment-examples

---

cluster-scope/base/namespaces/cert-manager/kustomization.yaml
cluster-scope/base/namespaces/istio-system/kustomization.yaml
cluster-scope/base/namespaces/istio-system/namespace.yaml
cluster-scope/base/namespaces/knative-serving/kustomization.yaml
cluster-scope/base/namespaces/knative-serving/namespace.yaml
cluster-scope/base/namespaces/kube-system/kustomization.yaml
cluster-scope/base/namespaces/kubeflow/kustomization.yaml
cluster-scope/base/namespaces/kubeflow/namespace.yaml
cluster-scope/base/namespaces/tekton-pipelines/kustomization.yaml
cluster-scope/base/namespaces/tekton-pipelines/namespace.yaml
cluster-scope/overlays/moc/kustomization.yaml

This will create 4 new namespaces:
1. kubeflow
2. knative-serving
3. tekton-pipelines
4. istio-systems
And add 2 existing namespaces:
1. cert-manager
2. kube-system
These namespaces are intended for installation of kubeflow and it's components: kubeflow-pipeline, istio, Tekton pipelines, knative
Related: https://github.com/operate-first/support/issues/62 https://github.com/operate-first/support/issues/63

Add kubeflow component namespaces

---

odh/overlays/moc/monitoring/dashboards/operate-first/jupyterhub-usage.yaml
odh/overlays/moc/monitoring/dashboards/operate-first/kustomization.yaml
odh/overlays/moc/monitoring/dashboards/operate-first/opf-availability.yaml

Adding the following dashboards:
1. [JupyterHub usage dashboard](https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/YuYfkHYMk/jupyterhub-usage?orgId=1) (related to https://github.com/operate-first/support/issues/61)
2. [Opf availability dashboard](https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/r7WqgaBMk/operatefirst-availability?orgId=1)

Add monitoring dashboards

---

ceph/README.md
ceph/base/kustomization.yaml
ceph/base/storagecluster.yaml
ceph/overlays/crc/kustomization.yaml
ceph/overlays/moc/kustomization.yaml
ceph/overlays/quicklab/kustomization.yaml

Related to: https://github.com/operate-first/apps/pull/131
Syncs down the Ceph provider from MOC CNV in `openshift-storage` namespace

feat: Add a Rook/Noobaa standalone application

---

local-storage/README.md
local-storage/base/kustomization.yaml
local-storage/base/localstorage.yaml
local-storage/overlays/crc/kustomization.yaml
local-storage/overlays/moc/kustomization.yaml
local-storage/overlays/moc/localstorage_patch.yaml
local-storage/overlays/quicklab/kustomization.yaml

Related to: https://github.com/operate-first/apps/pull/131
Syncs down the local storage provider from MOC CNV in `local-storage` namespace

feat: Add a local storage standalone application

---

kubevirt-hyperconverged/README.md
kubevirt-hyperconverged/base/hyperconverged.yaml
kubevirt-hyperconverged/base/kustomization.yaml
kubevirt-hyperconverged/overlays/crc/kustomization.yaml
kubevirt-hyperconverged/overlays/moc/kustomization.yaml
kubevirt-hyperconverged/overlays/quicklab/kustomization.yaml

Related to: https://github.com/operate-first/apps/pull/131
Syncs down the Kubevirt deployment and resources in `openshift-cnv` namespace

feat: Add a kubevirt standalone application

---

kubeflow-components/base/kfdef.yaml
kubeflow-components/base/kustomization.yaml
kubeflow-components/overlays/crc/kustomization.yaml
kubeflow-components/overlays/moc/kustomization.yaml
kubeflow-components/overlays/quicklab/kustomization.yaml

This includes Istio/Knative/Kfpipeline/tekton
The main purpose of this kfdef is to deploy kf-pipeline and it's dependencies
The source of this kfdef is from [upstream kubeflow](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_openshift.master.kfptekton.yaml)
Closes https://github.com/operate-first/support/issues/6 https://github.com/operate-first/support/issues/63

Add kubeflow-components

---

cluster-scope/base/clusterrolebindings/cluster-logs-readers/clusterrolebinding.yaml
cluster-scope/base/clusterrolebindings/cluster-logs-readers/kustomization.yaml
cluster-scope/base/clusterroles/cluster-logs-reader/clusterrole.yaml
cluster-scope/base/clusterroles/cluster-logs-reader/kustomization.yaml
cluster-scope/overlays/moc/kustomization.yaml

Replaces: https://github.com/operate-first/apps/pull/175
Related: https://github.com/operate-first/apps/issues/193
Resolves: https://github.com/operate-first/apps/issues/171
Grants read access to all `pods` and `pods/log` in all namespaces on a cluster. This PR unblocks @eranra and team to access `infra-*` and other apps in cluster logging ElasticSearch and [Kibana](https://kibana-openshift-logging.apps.cnv.massopen.cloud/)
~~Question is if we care that people have `cluster-reader` access... I vote "I don't care, let people see things".~~
I've end up creating a new clusterrole - in the end it turned out that it only requires `pods` and `pods/log` access on `default`, `kube-*` and `openshift-*` namespaces. Since there's no easy way how to take into account all these namespaces via `Role`s, …

feat: Grant cluster-logs-reader ClusterRole to user groups

---

cluster-scope/base/clusterroles/cluster-logs-reader/clusterrole.yaml

fix: ClusterRole api group for cluster logs reader

---

docs/odh/grafana/add_grafana_dashboard.md
odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-sli-slo.yaml
odh/overlays/moc/monitoring/dashboards/operate-first/argocd.yaml
odh/overlays/moc/monitoring/dashboards/operate-first/jupyterhub-usage.yaml
odh/overlays/moc/monitoring/dashboards/operate-first/opf-availability.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-postgresql-metrics.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-service-metrics.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-user-api-metrics.yaml
odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml

Remove `spec.name` from dashboards and docs, as it is not used in grafana operator `GrafanaDashboard` CRDs.
Related-To: https://github.com/integr8ly/grafana-operator/pull/344

Adjust grafana dashboards and documentation

---

odh/overlays/moc/jupyterhub/.sops.yaml
odh/overlays/moc/jupyterhub/kustomization.yaml
odh/overlays/moc/jupyterhub/pvcs/secret-generator.yaml
odh/overlays/moc/jupyterhub/pvcs/user-mcli-pvc.enc.yaml

Adds an encrypted PVC manifest to be used in the `opf-jupyterhub` namespace by Jupyterhub.
Closes https://github.com/operate-first/support/issues/79

Add PVC manifest for user mcli

---

odh/base/argo/kfdef.yaml

Tested locally, there's no change in manifests, since we were already using the master for argo

feat: ODH v1.0.0 upgrade: Argo

---

odh/base/monitoring/kfdef.yaml

The only difference in the manifests is:
- change in `odh-kafka` dashboard (https://github.com/opendatahub-io/odh-manifests/pull/272)
- removed `jupyterhub-metrics` service monitor (https://github.com/opendatahub-io/odh-manifests/pull/271)

feat: ODH v1.0.0 upgrade: Monitoring

---

odh/base/jupyterhub/kfdef.yaml

The only important difference in `jupyterhub/jupyterhub` app is image change from https://github.com/opendatahub-io/odh-manifests/pull/245
```diff
547c547
<       name: quay.io/odh-jupyterhub/jupyterhub-img:3.0.7-b7db22b
---
>       name: quay.io/odh-jupyterhub/jupyterhub-img:v0.1.4
```

feat: ODH v1.0.0 upgrade: Jupyterhub

---

cluster-logging/overlays/moc/configmaps/curator.yaml
cluster-logging/overlays/moc/configmaps/kustomization.yaml

Set default log retention to 7 days. 
Docs: https://docs.openshift.com/container-platform/4.5/logging/config/cluster-logging-curator.html#cluster-logging-curator-yaml_cluster-logging-curator
Currently the 200Gig PVC for cluster logging is at >90% usage. This is resulting in Elasticsearch not pushing in any new logs.
Related #https://github.com/operate-first/support/issues/83

Add curator config for CLO

---

cluster-logging/base/clusterlogging.yaml

This will create 2 nodes for elasticsearch and create 2 PVCs (size 300Gig) for each node.
With `ZeroRedundancy` policy, there won't be any copies of data. ([Docs](https://github.com/openshift/cluster-logging-operator/blob/master/docs/configuration.md#data-redundancy))

Update CLO nodeCount to 2 and PVC size to 300Gig

---

cluster-logging/base/clusterlogging.yaml

We found that fluentd was facing issues when pushing logs 
Error:
```
2021-02-10 22:00:37 +0000 [warn]: [retry_clo_default_output_es] failed to flush the buffer. retry_time=3 next_retry_seconds=2021-02-10 22:00:40 +0000 chunk="5bb000f818cb4d2b2de49ad5112baf1c" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch.openshift-logging.svc.cluster.local\", :port=>9200, :scheme=>\"https\", :user=>\"fluentd\", :password=>\"obfuscated\"}): Server returned nothing (no headers, no data)"
```
These errors were reduced when we increased the CPU resources for elasticsearch. We were also able to see more recent logs using kibana
Related: https://github.com/operate-first/support/issues/83

Update CPU requests for Elasticsearch to 6 cpus

---

odh/base/jupyterhub/kfdef.yaml
odh/overlays/moc/jupyterhub/kustomization.yaml

Fixes storage class issue from: https://github.com/operate-first/apps/pull/241#issuecomment-777565070

fix: Move ODH JH params and overlays to the overriding app

---

cluster-scope/base/namespaces/ws-ml-prague/kustomization.yaml
cluster-scope/components/project-view-public/kustomization.yaml
cluster-scope/components/project-view-public/rbac.yaml

Part of: https://github.com/operate-first/support/issues/77
Grants public view access to a namespace via a reusable component.

feat: Enable public access to ws-ml-prague namespace

---

odh/base/datacatalog/kfdef.yaml
odh/overlays/crc/datacatalog/kfdef_patch.yaml
odh/overlays/crc/datacatalog/kustomization.yaml
odh/overlays/moc/datacatalog/bucket.yaml
odh/overlays/moc/datacatalog/kfdef_patch.yaml
odh/overlays/moc/datacatalog/kustomization.yaml
odh/overlays/quicklab/datacatalog/kfdef_patch.yaml
odh/overlays/quicklab/datacatalog/kustomization.yaml

Resolves: https://github.com/operate-first/apps/issues/143
Related to: https://github.com/operate-first/support/issues/23
CRC and Quicklab:
- No functional difference in the manifetst
- In `kfdef`, the order of application is now changed: ceph nano is added to the end in the overlay, instead of being in the middle
MOC:
- A OCS bucket is created via `opf-datacatalog-bucket` claim
- Ceph nano is not used anymore
- Hue and Thriftserver points to Rook endpoint and use the bucket's credentials
MOC setup was not tested, since I don't have a cluster with Rook available, we'll see how it works...

feat: Use OCS bucket for Data catalog on MOC

---

odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml

Related https://github.com/operate-first/SRE/issues/59
After this is merged, let's wait for the https://github.com/operate-first/SRE/issues/60 issue to close automatically by the alertmanager

JH exclude path /metrics from being protected by the proxy

---

cluster-scope/base/namespaces/opf-auth/kustomization.yaml
cluster-scope/base/namespaces/opf-auth/namespace.yaml
cluster-scope/overlays/moc/kustomization.yaml

Part of: https://github.com/operate-first/apps/issues/65
Preparation step, let's have the namespace first.

feat: Create namespace for Dex

---

cluster-logging/overlays/moc/.sops.yaml
cluster-logging/overlays/moc/kustomization.yaml
cluster-logging/overlays/moc/routes/route.enc.yaml
cluster-logging/overlays/moc/routes/secret-generator.yaml

This is related to the issue [here](https://github.com/operate-first/apps/issues/229). Though more work needs to be done to allow individual users that are not cluster-admin to be able to use it.

Add route for elasticsearch external access.

---

cluster-scope/overlays/crc/kustomization.yaml
cluster-scope/overlays/quicklab/kustomization.yaml

Atm these builds are broken due to the odh-operator being recently removed.

Remove odh-operator namespace from crc/quicklab

---

odh/overlays/moc/monitoring/servicemonitors/cluster-metrics-servicemonitor.yaml

Currently the scrape time exceeds the scrape time-out.  
[Related](https://github.com/operate-first/SRE/issues/80)

Update prom cluster metrics timeout

---

cluster-scope/base/namespaces/istio-system/kustomization.yaml
cluster-scope/base/namespaces/istio-system/namespace.yaml
cluster-scope/base/namespaces/knative-serving/kustomization.yaml
cluster-scope/base/namespaces/knative-serving/namespace.yaml
cluster-scope/base/namespaces/tekton-pipelines/kustomization.yaml
cluster-scope/base/namespaces/tekton-pipelines/namespace.yaml

Currently kubeflow will over-write these apps, thus fighting with argocd to sync them. We cannot keep an exact copy because argocd will always add a new label which it uses to match what argocd app the resource belongs to. So just removing them all together for now.

Remove kubeflow managed namespaces.

---

cluster-scope/base/clusterrolebindings/argocd-manager/clusterrolebinding.yaml
cluster-scope/base/clusterrolebindings/argocd-manager/kustomization.yaml
cluster-scope/overlays/moc-infra/kustomization.yaml
cluster-scope/overlays/moc/kustomization.yaml

The `argocd-manager` SA is what argocd will be using to deploy apps to both `moc-cnv` and `moc-infra` clusters, as such this SA exists in both clusters and will require cluster admin in both of these clusters.
[Related](https://github.com/operate-first/SRE/issues/83).

Give ArgoCD SA argocd-manager cluster admin

---

odh/base/jupyterhub/kfdef.yaml
odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml

The 1.0.1 release updates the jupyterhub image so we no longer need to
skip cert validation. More context at https://github.com/opendatahub-io/odh-manifests/pull/312

Update Jupytyerhub kfdef manifest version to 1.0.1

---

.aicoe-ci.yaml
.prow.yaml

This uses Prow to run the unit tests.

reconfgured CI/CD to use prow and aicoe-ci

---

cluster-logging/base/clusterlogging.yaml

This is in order to prevent a networking bottleneck and hopefully solve network timeout issues with Elasticsearch.
Related https://github.com/operate-first/SRE/issues/98

[CLO] Increase the ES node count to 5

---

odh/base/jupyterhub/notebook-images/kustomization.yaml
odh/base/jupyterhub/notebook-images/ray-ml-notebook.yaml

This PR will address https://github.com/operate-first/support/issues/102, by porting the following integration onto MOC ODH:
https://github.com/erikerlandson/ray-odh-demo
The following components will need to be added to the overlays:

integrate ray into MOC ODH

---

cluster-scope/overlays/moc/infra/kustomization.yaml

this subscribes to the cnv operator in order to get nmstate [1]
support, which gives us a declarative mechanism for describing network
interface configuration. It looks like nmstate will be available by
defaultin 4.7 [2].
[1]: https://docs.openshift.com/container-platform/4.6/virt/node_network/virt-updating-node-network-config.html
[2]: https://docs.openshift.com/container-platform/4.7/networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.html

add cnv to infra cluster for nmstate support

---

cluster-scope/base/subscriptions/kubevirt-hyperconverged/subscription.yaml

this should be the latest version of this operator, preventing argocd
and the automatic upgrades from fighting eachother.

upgrade cnv subscription to 2.5.4

---

cluster-scope/overlays/moc/infra/crc-provisioning-vlan.yaml
cluster-scope/overlays/moc/infra/kustomization.yaml
cluster-scope/overlays/moc/infra/zero-provisioning-vlan.yaml

Creates eno1.307 on all nodes and configures a different static
address for each node.
ACM requires access to the provisioning network of the target cluster
in order to communicate with the Ironic API. In 4.8 (and in future 4.7
releases) this communication will happen on the API network and these
cross-cluster links will no longer be necessary.

Add network interfaces on crc provisioning network

---

cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml
cluster-scope/base/subscriptions/elastic-operator/subscription.yaml
cluster-scope/base/subscriptions/kubevirt-hyperconverged/subscription.yaml
cluster-scope/base/subscriptions/local-storage-operator/subscription.yaml
cluster-scope/base/subscriptions/metering-ocp/subscription.yaml
cluster-scope/base/subscriptions/ocs-operator/subscription.yaml
cluster-scope/base/subscriptions/openshift-pipelines-operator-rh/subscription.yaml
cluster-scope/overlays/moc/infra/kustomization.yaml
cluster-scope/overlays/moc/infra/subscriptions/kubevirt-hyperconverged_patch.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml
cluster-scope/overlays/moc/zero/subscriptions/cluster-logging-operator_patch.yaml
cluster-scope/overlays/moc/zero/subscriptions/elastic-operator_patch.yaml
cluster-scope/overlays/moc/zero/subscriptions/kubevirt-hyperconverged_patch.yaml
cluster-scope/overlays/moc/zero/subscriptions/local-storage-operator_patch.yaml
cluster-scope/overlays/moc/zero/subscriptions/metering-ocp_patch.yaml
cluster-scope/overlays/moc/zero/subscriptions/ocs-operator_patch.yaml
cluster-scope/overlays/moc/zero/subscriptions/openshift-pipelines-operator-rh_patch.yaml

We need to prepare CNV manifests to be deployable on OpenShift 4.7
**Do not merge while: 1) autosync on cluster-resources is on, 2) CNV cluster is not yet on OCP 4.7**
Part of: https://github.com/open-infrastructure-labs/ops-issues/issues/21
/hold
Update: Resolves https://github.com/operate-first/apps/issues/323

feat: Prepare subscription for MOC CNV 4.7 upgrade

---

odh/overlays/moc/zero/kafka/kustomization.yaml
odh/overlays/moc/zero/superset/kustomization.yaml

Due to the restructuring, the location of these overrides change, we need to update the kfdefs to reflect that.

Update path for kafka/superset for override in zero cluster.

---

cluster-scope/base/clusterrolebindings/observatorium-operator/clusterrolebinding.yaml
cluster-scope/base/clusterrolebindings/observatorium-operator/kustomization.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml
observatorium/base/operator/deployment.yaml

Once the clusterrolebinding is pushed, we need to create a argocd app to deploy [the operator](https://github.com/operate-first/apps/tree/master/observatorium/base/operator).
Fix the operator deployment to an older tested image. This is because I was facing issues testing the newer versions.

Add clusterrolebinding for observatorium operator

---

cluster-scope/base/subscriptions/advanced-cluster-management/subscription.yaml
cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml
cluster-scope/base/subscriptions/elastic-operator/subscription.yaml
cluster-scope/base/subscriptions/local-storage-operator/subscription.yaml
cluster-scope/base/subscriptions/metering-ocp/subscription.yaml
cluster-scope/base/subscriptions/ocs-operator/subscription.yaml
cluster-scope/base/subscriptions/opendatahub-operator/subscription.yaml
cluster-scope/base/subscriptions/openshift-pipelines-operator-rh/subscription.yaml

This prevents situations in which the running cluster ends up
out-of-sync with our repository due to automatic updates. We've seen
at least one situation where the interaction between the automatic
updates and argocd prevented the successful installation of an
operator.
Closes #227

modify subscriptions to set installPlanApproval to Manual

---

odh/base/jupyterhub/kustomization.yaml
odh/base/jupyterhub/ray-odh-integration/kustomization.yaml
odh/base/jupyterhub/ray-odh-integration/ray-operator-deployment.yaml
odh/base/jupyterhub/ray-odh-integration/ray-operator-imagestream.yaml
odh/base/jupyterhub/ray-odh-integration/ray-operator-role.yaml
odh/base/jupyterhub/ray-odh-integration/ray-operator-rolebinding.yaml
odh/base/jupyterhub/ray-odh-integration/ray-operator-serviceaccount.yaml

Adds ray operator components to the jupyterhub namespace. This should merge after #321.

add ray operator objects to ofp-jupyterhub

---

cluster-scope/base/subscriptions/web-terminal/kustomization.yaml
cluster-scope/base/subscriptions/web-terminal/subscription.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml
cluster-scope/overlays/moc/zero/subscriptions/web-terminal.yaml

The web terminal operator adds a web cli to the openshift console. See
[1] for more details.
[1]: https://www.openshift.com/blog/a-deeper-look-at-the-web-terminal-operator-1

Add web terminal operator to zero cluster

---

observatorium/base/instance/example-thanos-objectstorage-secret.yaml
observatorium/base/instance/observatorium.yaml
observatorium/overlays/moc/zero/objectbucketclaims/kustomization.yaml
observatorium/overlays/moc/zero/objectbucketclaims/thanos-obc.yaml
observatorium/overlays/moc/zero/secrets/secret-generator.yaml
observatorium/overlays/moc/zero/secrets/thanos-objectstorage-secret.enc.yaml

Closes #74 
Once this is deployed, I will need to update the opf-monitoring prometheus instance to remote-write metrics to this instance 
And also add a grafana datasource for this thanos instance.
Explaining Retention Policies:
`retentionResolution1h: 0d    # forever` Store downsampled values for 1h resolution forever
`retentionResolution5m: 30d` Store downsampled values for 5m resolution for 30 days
`retentionResolutionRaw: 7d` Store downsampled values for raw (original) resolution for 7 days

Add thanos to Observatorium CR for metrics long term storage

---

odh/base/jupyterhub/ray-odh-integration/kustomization.yaml
odh/base/jupyterhub/ray-odh-integration/ray-cluster-template-cm.yaml
odh/base/jupyterhub/ray-odh-integration/ray-jh-rolebinding.yaml
odh/base/jupyterhub/ray-odh-integration/ray-ml-node-imagestream.yaml
odh/base/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml

addresses https://github.com/operate-first/support/issues/102 - adding ray cluster template and a singleuser profile for ray ML notebook backed by a ray cluster

add ray ml singleuser profile to overlays

---

alertreceiver/base/deployment.yaml
alertreceiver/base/kustomization.yaml
alertreceiver/base/service.yaml
alertreceiver/overlays/moc/common/github-secret.enc.yaml
alertreceiver/overlays/moc/common/kustomization.yaml
alertreceiver/overlays/moc/common/secret-generator.yaml
alertreceiver/overlays/moc/infra/kustomization.yaml
alertreceiver/overlays/moc/zero/kustomization.yaml

Part 2 of: https://github.com/operate-first/SRE/issues/56
Depends on:  https://github.com/operate-first/apps/pull/366
Adds a standalone GH alert receiver deployment
Changes:
- labels applied on an alert - no `in progress` label, since all open issues are in progress, but rather adds an `environment/moc/CLUSTER_NAME` label
- added `spec/resources/{requests,limits}` based on observation from `opf-monitoring` deployment

feat: Add a separate GH alert receiver deployment

---

odh/overlays/moc/zero/datacatalog/bucket.yaml
odh/overlays/moc/zero/datacatalog/kfdef_patch.yaml

Resolves: https://github.com/operate-first/support/issues/117
/hold requires manual sync after merge (because we're re-defining the storage class - original bucket has to be deleted first)

fix: Datacatalog bucket

---

odh/base/dashboard/overrides/overlays/custom-image/kustomization.yaml

Fixes https://github.com/operate-first/odh-dashboard/issues/9
After upgrade it simply wasn't using our image. I have no idea why it didn't fail earlier.

fix: ODH Dashboard image replace

---

odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml

Fixes: https://github.com/operate-first/support/issues/116
Override of https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
Adding a new size: **Large - memory intensive**:
- https://github.com/operate-first/apps/pull/381/files#diff-60cff131ed8817563fe2d0ab7ccc61958aef4f5e7e3439766914ae1648b14ce3R83-R90
- CPU request and limit stays the same as in **Large**
- Memory has 16GiB request, 32GiB limit

feat: Add memory intensive user profile

---

cluster-scope/overlays/moc/infra/alertmanager-main-secret.yaml
cluster-scope/overlays/moc/infra/kustomization.yaml

Part of: https://github.com/operate-first/SRE/issues/56
Depends on: https://github.com/operate-first/argocd-apps/pull/100
~Requires some more testing first.~
Tested against quicklab https://console-openshift-console.apps.testtcoufal.lab.upshift.rdu2.redhat.com/
and https://github.com/tumido/test/issues repo

feat: Enable GH alert receiver for Cluster Monitoring on MOC Infra

---

cluster-scope/overlays/moc/zero/subscriptions/kubevirt-hyperconverged_patch.yaml

There's an update available for 2.6.0 waiting for manual approval. We
talked about seeing what the behavior is if we update the subscription
with a startingCSV attribute matching the new version. This commit is
that test.

attempt to upgrade cnv to 2.6.0

---

cluster-scope/overlays/moc/zero/subscriptions/kubevirt-hyperconverged_patch.yaml

This reverts commit 9fcda0a5a62e276479f8120ae30d561359dda91e.
Setting startingCSV doesn't have any impact (at least when there is a
pending installplan waiting for approval).

Revert "attempt to upgrade cnv to 2.6.0"

---

cluster-scope/base/namespaces/opendatahub-operator/kustomization.yaml
cluster-scope/base/namespaces/opendatahub-operator/namespace.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml
odh-operator/base/kustomization.yaml

Given that odh is manually deployed w/o OLM, it makes more sense to be consistent with our own philosophy and deploy it to its own namespace.

Move ODH deployment to its own ns.

---

cluster-scope/base/namespaces/openshift-serverless/kustomization.yaml
cluster-scope/base/namespaces/openshift-serverless/namespace.yaml
cluster-scope/base/operatorgroups/openshift-serverless/kustomization.yaml
cluster-scope/base/operatorgroups/openshift-serverless/operatorgroup.yaml
cluster-scope/base/subscriptions/serverless-operator/kustomization.yaml
cluster-scope/base/subscriptions/serverless-operator/subscription.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml
cluster-scope/overlays/moc/zero/subscriptions/serverless-operator_patch.yaml

Resolves: https://github.com/operate-first/support/issues/84
Note: Once merged requires manual approval
Serverless docs demand `openshift-serverless` namespace:
https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-openshift-serverless.html#serverless-install-web-console_installing-openshift-serverless

feat: Subscribe to OpenShift Serverless

---

kfdefs/overlays/moc/zero/ds-ml-workflows-ws/kfdef.yaml
kfdefs/overlays/moc/zero/thoth-infra-prod/kfdef.yaml
observatorium/base/instance/kfdef.yaml
odh-operator/base/kustomization.yaml
odh/base/argo/kfdef.yaml
odh/base/dashboard/kfdef.yaml
odh/base/datacatalog/kfdef.yaml
odh/base/jupyterhub/kfdef.yaml
odh/base/kafka/kfdef.yaml
odh/base/monitoring/kfdef.yaml
odh/base/superset/kfdef.yaml

See release change log here: https://github.com/opendatahub-io/odh-manifests/releases
I've also updated the operator image along with this patch. 
All kfdefs were updated in this repo, included user provisioned.

Update odh to 1.0.5

---

odh-operator/base/kustomization.yaml

Fixes: https://github.com/operate-first/apps/issues/413
We're patching wrong image: 
https://github.com/operate-first/apps/blob/1b042ed6650f069f2ed0aabe69d1250488897afb/odh-operator/base/deployment.yaml#L32
This should fix it
/cc @HumairAK

fix: Operator image override

---

odh/base/jupyterhub/notebook-images/kustomization.yaml
odh/base/jupyterhub/notebook-images/pet-image-detection.yaml

This PR will address [operatefirst/support#107](https://github.com/operate-first/support/issues/107), by adding the pet-image-detection image so that it is exposed on the JH launcher menu.

pet-image-detection imagestream

---

cluster-scope/base/clusterrolebindings/metallb-allow-privileged/clusterrolebinding.yaml
cluster-scope/base/clusterrolebindings/metallb-allow-privileged/kustomization.yaml
cluster-scope/base/clusterrolebindings/metallb-system-controller/clusterrolebinding.yaml
cluster-scope/base/clusterrolebindings/metallb-system-controller/kustomization.yaml
cluster-scope/base/clusterrolebindings/metallb-system-speaker/clusterrolebinding.yaml
cluster-scope/base/clusterrolebindings/metallb-system-speaker/kustomization.yaml
cluster-scope/base/clusterroles/metallb-system-controller/clusterrole.yaml
cluster-scope/base/clusterroles/metallb-system-controller/kustomization.yaml
cluster-scope/base/clusterroles/metallb-system-speaker/clusterrole.yaml
cluster-scope/base/clusterroles/metallb-system-speaker/kustomization.yaml
cluster-scope/base/namespaces/metallb-system/kustomization.yaml
cluster-scope/base/namespaces/metallb-system/namespace.yaml
cluster-scope/base/podsecuritypolicy/metallb-system-controller/kustomization.yaml
cluster-scope/base/podsecuritypolicy/metallb-system-controller/podsecuritypolicy.yaml
cluster-scope/base/podsecuritypolicy/metallb-system-speaker/kustomization.yaml
cluster-scope/base/podsecuritypolicy/metallb-system-speaker/podsecuritypolicy.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml
metallb/base/daemonset.yaml
metallb/base/deployment.yaml
metallb/base/kustomization.yaml
metallb/base/role.yaml
metallb/base/rolebinding.yaml
metallb/base/serviceaccount.yaml
metallb/overlays/moc/zero/config.yaml
metallb/overlays/moc/zero/kustomization.yaml
metallb/overlays/moc/zero/memberlist.enc.yaml
metallb/overlays/moc/zero/secret-generator.yaml

the cnv cluster was running metallb to provide public ip for services
that don't work with the ingress router (e.g. for running ssh in a pod
or virtual machine).
This commit adds the basic manifests.

add metallb

---

odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml

only one user can be added as admin for some reason, so I will manually add @HumairAK and @tumido as admins.

Add asanmukh as Jupyterhub admin

---

odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml
odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-groups-configmap.yaml

* Revert changes made in https://github.com/operate-first/apps/pull/431
* This PR overrides the `jupyterhub-default-groups-configmap` from [upstream](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/jupyterhub/base/jupyterhub-groups-configmap.yaml).
Resolves https://github.com/operate-first/support/issues/69

Add operate-first group as jupyterhub admins

---

cluster-scope/components/limitranges/default/kustomization.yaml
cluster-scope/components/limitranges/default/limitrange.yaml
cluster-scope/components/resourcequotas/large/kustomization.yaml
cluster-scope/components/resourcequotas/large/resourcequotas.yaml
cluster-scope/components/resourcequotas/medium/kustomization.yaml
cluster-scope/components/resourcequotas/medium/resourcequotas.yaml
cluster-scope/components/resourcequotas/small/kustomization.yaml
cluster-scope/components/resourcequotas/small/resourcequotas.yaml

Related: #438 
The `resourcequotas` aren't included in any of the namespaces yet, this is one way we can go about this. The idea is to include these like we do every other component within the cluster-scope/base/namespaces.
We don't have to use tiers if there are good arguments against it, this is a suggestion. 
I just willy nilly picked amounts for each tier and `limitrange`. We can discuss what amounts are reasonable. 
WDYT?

Add resourcequotas and limitrange components.

---

observatorium/base/instance/observatorium.yaml

Scale up Thanos Receiver to 3 from 1
Because resource usage in the thanos receive component seems to be pretty high
Scale up Thanos Query to 2 from 1
I was seeing some timeout errors when querying thanos from grafana, when queries were a little big.

Scale up Observatorium Thanos Receiver and Thanos Query

---

cluster-scope/base/groups/lab-cicd/group.yaml
cluster-scope/base/groups/lab-cicd/kustomization.yaml
cluster-scope/base/namespaces/lab-cicd-1-jump-app-cicd/kustomization.yaml
cluster-scope/base/namespaces/lab-cicd-1-jump-app-cicd/namespace.yaml
cluster-scope/base/namespaces/lab-cicd-1-jump-app-dev/kustomization.yaml
cluster-scope/base/namespaces/lab-cicd-1-jump-app-dev/namespace.yaml
cluster-scope/base/namespaces/lab-cicd-2-jump-app-cicd/kustomization.yaml
cluster-scope/base/namespaces/lab-cicd-2-jump-app-cicd/namespace.yaml
cluster-scope/base/namespaces/lab-cicd-2-jump-app-dev/kustomization.yaml
cluster-scope/base/namespaces/lab-cicd-2-jump-app-dev/namespace.yaml
cluster-scope/base/namespaces/lab-cicd-3-jump-app-cicd/kustomization.yaml
cluster-scope/base/namespaces/lab-cicd-3-jump-app-cicd/namespace.yaml
cluster-scope/base/namespaces/lab-cicd-3-jump-app-dev/kustomization.yaml
cluster-scope/base/namespaces/lab-cicd-3-jump-app-dev/namespace.yaml
cluster-scope/base/namespaces/lab-cicd-4-jump-app-cicd/kustomization.yaml
cluster-scope/base/namespaces/lab-cicd-4-jump-app-cicd/namespace.yaml
cluster-scope/base/namespaces/lab-cicd-4-jump-app-dev/kustomization.yaml
cluster-scope/base/namespaces/lab-cicd-4-jump-app-dev/namespace.yaml
cluster-scope/components/project-admin-rolebindings/lab-cicd/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/lab-cicd/rbac.yaml
cluster-scope/overlays/moc/common/groups/lab-cicd.enc.yaml
cluster-scope/overlays/moc/common/kustomization.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml

Part of: https://github.com/operate-first/support/issues/113
@acidonper, sorry for the delay, let me know if this PR is what you need. It creates an user group `lab-cicd` which you are set to be the sole user for now. This group is the project admin on all the namespaces.
Additionally it creates namespaces:
- `lab-cicd-1-jump-app-cicd`
- `lab-cicd-1-jump-app-dev`
- `lab-cicd-2-jump-app-cicd`
- `lab-cicd-2-jump-app-dev`
- `lab-cicd-3-jump-app-cicd`
- `lab-cicd-3-jump-app-dev`
- `lab-cicd-4-jump-app-cicd`
- `lab-cicd-4-jump-app-dev`
Each of this namespaces is available to be viewed (`view` cluster role) by any authenticated or unauthenticated user
Will this work for you or are any changes needed?

feat: Onboard RH Labs - CI/CD

---

cluster-scope/overlays/moc/zero/clusterversion.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml

Update the zero cluster to 4.7.2.
The `ClusterVersion` resource includes a `clusterID` attribute that I have omitted from this update, since if we were to reinstall the cluster the ID would be different.

Upgrade zero cluster to 4.7.2

---

cluster-scope/components/project-logs-reader/role.yaml

Fixes: https://github.com/operate-first/support/issues/156
Allows user to see the namespace/project listed as an available in web console along with some additional goods like events (that are also propagated to JH spawner so why to hide it in the console)

fix(odh-jupyterhub): Viewing pods/log in a namespace

---

odh/overlays/moc/zero/datacatalog/kfdef_patch.yaml

Resolves: https://github.com/operate-first/support/issues/117
The https://github.com/operate-first/support/issues/131 issue still persists
Additionally it was required to grant S3 permissions to the `default` user group:

fix(hue): Set proper endpoint for S3 file explorer

---

odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml

Reverts operate-first/apps#465
This is because, this will remove access from the `ANONYMOUS` user and every existing user will need a corresponding `KafkaUser`. I'll create a new PR later with all the KafkaUsers defined. 
Docs: https://strimzi.io/docs/operators/0.19.0/using.html#ref-kafka-authorization-deployment-configuration-kafka

Revert "Add PVC to kafka resource"

---

odh/base/jupyterhub/notebook-images/jupyterbook-test.yaml
odh/base/jupyterhub/notebook-images/kustomization.yaml

support jupyter book in the jupyter notebook image
Related-to: https://github.com/operate-first/support/issues/189
This is just a test image for the users, once the users verify the content, then the package would be installed in the base image itself.

support jupyter book in the jupyter notebook image

---

cluster-scope/overlays/moc/common/kustomization.yaml
cluster-scope/overlays/moc/common/secret-generator.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml

Resolves https://github.com/operate-first/support/issues/188
The required manifests were created but were not added to the respective kustomizations

Fix onboarding sdap team

---

cluster-logging/overlays/moc/zero/clusterlogforwarders/clusterlogforwarder.yaml
cluster-logging/overlays/moc/zero/clusterlogforwarders/kustomization.yaml
cluster-logging/overlays/moc/zero/kustomization.yaml
odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/zero-cluster-app-logs.yaml

Related https://github.com/operate-first/apps/issues/232
This will forward app-logs to kafka topic `zero-prod.cluster.app-logs`
Update max message size bytes for that topic to 10MB ([slack discussion on size](https://coreos.slack.com/archives/CB3HXM2QK/p1617720645002700))
More docs on log forwarding to kafka: https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-kafka_cluster-logging-external

Add clusterlogforwarder to forward app-logs to kafka

---

cluster-scope/overlays/moc/common/secret-generator.yaml

Follow up on #485
I've missed it in the review
/cc @harshad16 @HumairAK @4n4nd

fix: Thoth devops group not propagated properly

---

odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml

Kafka PVCs are full, increasing them to 100Gi from 30Gi

Increase kafka pvc to 100Gi

---

cluster-scope/base/namespaces/opf-alertreceiver/kustomization.yaml
cluster-scope/base/namespaces/opf-argo/kustomization.yaml
cluster-scope/base/namespaces/opf-auth/kustomization.yaml
cluster-scope/base/namespaces/opf-ci-test-pods/kustomization.yaml
cluster-scope/base/namespaces/opf-dashboard/kustomization.yaml
cluster-scope/base/namespaces/opf-datacatalog/kustomization.yaml
cluster-scope/base/namespaces/opf-slack-first/kustomization.yaml
cluster-scope/base/namespaces/opf-superset/kustomization.yaml
cluster-scope/base/namespaces/opf-trino/kustomization.yaml
cluster-scope/components/resourcequotas/x-small/kustomization.yaml
cluster-scope/components/resourcequotas/x-small/resourcequotas.yaml

Adding quotas to most `opf-*` namespaces, the ones currently omitted are: 
- opf-ci-pipelines
- opf-ci-prow
- opf-jupyterhub
- opf-jupyterhub-stage
- opf-kafka
- opf-monitoring
- opf-observatorium
I am open to suggestions if we should add quotas to these namespace, and what they should be set to. 
I have also added a nother tier "x-small" because for some of these, "small" seemed overkill, and I suspect we will see more of such situations. We will need to update the support doc accordingly.

Add quotas to opf-* namespaces

---

cluster-scope/base/namespaces/opf-datacatalog/kustomization.yaml
cluster-scope/base/namespaces/opf-datacatalog/resourcequota.yaml

Spark operator reporting errors with small quota: 
```
pods "spark-operator-7c9964f4fb-k9rmg" is forbidden: exceeded quota: small, requested: limits.cpu=500m,limits.memory=1000Mi,requests.cpu=300m,requests.memory=400Mi, used: limits.cpu=7900m,limits.memory=11864Mi,requests.cpu=1900m,requests.memory=3748Mi, limited: limits.cpu=1,limits.memory=4Gi,requests.cpu=1,requests.memory=4Gi
```

Incrase opf-datacatalog quota to custom quota.

---

odh/base/jupyterhub/notebook-images/jupyterbook-test.yaml

ArgoCd is not happy with these fields.

Remove unnecessary imgstream fields for jupyter-book.

---

observatorium/base/instance/observatorium.yaml

Related https://github.com/operate-first/alerts/issues/2870

Increase thanos shard PVC size to 50 Gi

---

cluster-scope/base/hostpathprovisioners/hostpath-provisioner/hostpathprovisioner.yaml
cluster-scope/base/hostpathprovisioners/hostpath-provisioner/kustomization.yaml
cluster-scope/base/namespaces/hostpath-provisioner/kustomization.yaml
cluster-scope/base/namespaces/hostpath-provisioner/namespace.yaml
cluster-scope/overlays/moc/curator/kustomization.yaml
cluster-scope/overlays/moc/curator/subscriptions/kubevirt-hyperconverged_patch.yaml

install the cnv operator on the curator cluster in order to enable
the hostpathprovisioner for local storage.

enable hostpath-provisioner on curator cluster

---

odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-sli-slo.yaml
odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/kustomization.yaml
odh/overlays/moc/zero/monitoring/dashboards/operate-first/jupyterhub-usage.yaml
odh/overlays/moc/zero/monitoring/dashboards/operate-first/kustomization.yaml

Since we now have the dashboards available in `ODH v1.0.9` we can remove the old CRs
(related: https://github.com/operate-first/SRE/pull/257)

Remove JH dashboard CRs

---

vector/overlays/moc/zero/opf-observatorium/configmap.yaml

This will format the incoming logs better for Loki consumption and querying.
Incoming kafka message format:
```yaml
{
"docker": {
"container_id": "15ca5404857de22c33270c00e7e5e33aee7221aae62b1cfd45521f9d9be8e221"
},
"kubernetes": {
"container_name": "audio-decoder",
"namespace_name": "fde-audio-decoder-demo",
"pod_name": "audio-decoder-6cf644b8b6-gzlx5",
"container_image": "quay.io/xxxx/docker-py-kaldi-asr@sha256:d6a8b45a5c763589a5fb2a8916399036e1e2b0cb90391a6591761e87c13f14bc",
"container_image_id": "quay.io/xxxxxx/docker-py-kaldi-asr@sha256:d6a8b45a5c763589a5fb2a8916399036e1e2b0cb90391a6591761e87c13f14bc",
"pod_id": "737eb6dd-4b5e-4ee7-98da-c570051a566a",
"host": "os-sto-0",
"master_url": "https://kubernetes.default.svc",
"namespace_id": "d1df7a09-7d50-47e8-ac5a-326089e55a62", …
```

Update Vector Config

---

cluster-scope/base/machineconfigs/hostpath-provisioner-selinux/kustomization.yaml
cluster-scope/base/machineconfigs/hostpath-provisioner-selinux/machineconfig.yaml
cluster-scope/overlays/moc/curator/kustomization.yaml
cluster-scope/overlays/moc/curator/storageclasses/hostpath-provisioner.yaml

Ensure that the directory used by the hostpath-provisioner (a)
exists and (b) has an appropriate selinux context.
Deploying a machineconfig will trigger a rolling reboot of cluster
nodes.

Add machineconfig to manage selinux context for /var/hpvolumes

---

docs/odh/prometheus/README.md
docs/odh/prometheus/add_service_monitoring.md

Add a basic README similar to other components ([here](https://github.com/operate-first/apps/tree/master/docs))
This will make it easier to add this doc on the operatefirst website. (Just need to link the docs [here](https://github.com/operate-first/operate-first.github.io/blob/master/config/users.yaml))

Move Prometheus docs from support repo to apps repo

---

docs/odh/prometheus/add_service_monitoring.md

Improper formatting on the operate-first website:

Fix Prometheus doc formatting on operate-first.cloud

---

odh-manifests/kafka/base/kafka-cluster.yaml
odh-manifests/kafka/overlays/topics/audio-decoder-decoded-speech.yaml
odh-manifests/kafka/overlays/topics/audio-decoder-sentiment-text.yaml
odh-manifests/kafka/overlays/topics/thoth-advise-justification.yaml
odh-manifests/kafka/overlays/topics/thoth-adviser-re-run.yaml
odh-manifests/kafka/overlays/topics/thoth-adviser-trigger.yaml
odh-manifests/kafka/overlays/topics/thoth-hash-mismatch.yaml
odh-manifests/kafka/overlays/topics/thoth-kebechet-trigger.yaml
odh-manifests/kafka/overlays/topics/thoth-missing-package-version.yaml
odh-manifests/kafka/overlays/topics/thoth-missing-package.yaml
odh-manifests/kafka/overlays/topics/thoth-package-extract-trigger.yaml
odh-manifests/kafka/overlays/topics/thoth-package-released.yaml
odh-manifests/kafka/overlays/topics/thoth-provenance-checker-trigger.yaml
odh-manifests/kafka/overlays/topics/thoth-qebhwt-trigger.yaml
odh-manifests/kafka/overlays/topics/thoth-si-unanalyzed-package.yaml
odh-manifests/kafka/overlays/topics/thoth-solved-package.yaml
odh-manifests/kafka/overlays/topics/thoth-unresolved-package.yaml
odh-manifests/kafka/overlays/topics/thoth-unrevsolved-package.yaml
odh-manifests/kafka/overlays/topics/thoth-update-provides-source-distro.yaml
odh-manifests/kafka/overlays/topics/zero-cluster-app-logs.yaml

Since the Strimzi Kafka Operator will be updated in the upcoming z-stream release for ODH, we need to update the CRs to the new version as well .
Related https://github.com/opendatahub-io/odh-manifests/pull/405
Closes https://github.com/operate-first/apps/issues/552

Update Strimzi Kafka CRs to kafka.strimzi.io/v1beta2

---

cluster-scope/base/subscriptions/openshift-pipelines-operator-rh/subscription.yaml
cluster-scope/base/subscriptions/web-terminal/subscription.yaml

`Manual` install plan strategy is messing with other operators with automated install plans installed to the same namespace.
`Automatic` strategy is respected only if all operators use it. Otherwise it acts as manual.
This is causing troubles updating Strimzi provided via ODH as `Automatic`.

fix: Turn subscriptions in openshift-operators to automatic

---

argocd/base/kustomization.yaml
argocd/overlays/dev/configs/argo_cm/envs
argocd/overlays/moc-infra/configs/argo_cm/envs

ArgoCD switched default images to quay from dockerhub - our `kustomization.yaml` failed to replace it
Additionally new kustomize uses `--enable-alpha-plugins` flag now

fix: Argo CD image replacement and kustomize flag

---

argocd/overlays/moc-infra/projects/operate-first.yaml

SSIA, similar to: https://github.com/operate-first/apps/pull/563
Part of https://github.com/operate-first/SRE/issues/267

fix: ArgoCD Cluster resource for Kubeflow

---

argocd/overlays/moc-infra/projects/cluster-management.yaml

As per argocd 1.8.7 notes: 
```
This release fixed a regression regarding which cluster resources are permitted on the AppProject level. Previous to this fix, after #3960 has been merged, all cluster resources were allowed on project level when neither of the allow or deny lists was defined. However, the correct behavior is to block all resources in this case.
If you have Projects with empty allow and deny lists, but want the associated applications be able to sync cluster resources, you will have to adapt your cluster resources allow lists to explicitly allow the resources.
```

Add explicit allow list for cluster management argocd proj.

---

odh-manifests/grafana/grafana/base/grafana.yaml
odh-manifests/grafana/grafana/base/route.yaml

Resolves https://github.com/operate-first/support/issues/218
I tried creating a route named `grafana-route` but grafana-operator kept deleting it.
And I did not want to change the grafana url in the docs everywhere so I manually set the host in the route spec to the old host.

Add grafana proxy route

---

kubevirt-hyperconverged/base/hyperconverged.yaml

`version` is managed by the operator, causing ArgoCD and Openshift Virtualization operator to fight. This PR should leave the version string to be managed by the operator only.

fix: Ommit version for HyperConverged

---

cluster-scope/base/clusterrolebindings/oauth-token-access-review/clusterrolebinding.yaml
cluster-scope/base/clusterrolebindings/oauth-token-access-review/kustomization.yaml
cluster-scope/base/clusterroles/oauth-token-access-review/clusterrole.yaml
cluster-scope/base/clusterroles/oauth-token-access-review/kustomization.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml
odh-manifests/prometheus/operator/base/prometheus.yaml

The current Prometheus proxy does not allow access to the Prometheus API because the Proxy does not have permissions to check the validity of oauth tokens.
This will give the `prometheus-k8s` serviceaccount in `opf-monitoring` namespace permissions to review oauth tokens.

Add ClusterRole/Binding to enable Opf prometheus oauth token review

---

kfdefs/overlays/moc/zero/opf-monitoring/.sops.yaml
kfdefs/overlays/moc/zero/opf-monitoring/datasource/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/datasource/opf-observatorium-thanos-datasource.yaml
kfdefs/overlays/moc/zero/opf-monitoring/datasource/opf-prom-datasource.enc.yaml
kfdefs/overlays/moc/zero/opf-monitoring/datasource/secrets-generator.yaml
kfdefs/overlays/moc/zero/opf-monitoring/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml
kfdefs/overlays/moc/zero/opf-monitoring/roles/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/roles/opf-monitoring-view.yaml
kfdefs/overlays/moc/zero/opf-monitoring/serviceaccounts/grafana-datasource.yaml
kfdefs/overlays/moc/zero/opf-monitoring/serviceaccounts/kustomization.yaml
odh-manifests/grafana/grafana/base/datasource.yaml

Change opf-observatorium Thanos instance to be the default datasource
Add serviceaccount, role/binding so that the serviceaccount token can be used by grafana to access Prometheus via the oauth proxy.

Update Grafana to use Prometheus Proxy Route

---

metallb/overlays/moc/zero/config.yaml

There was a typo in the metallb configuration that rendered the
default address range invalid.

fix typo in metallb configuration

---

.pre-commit-config.yaml
docs/odh/prometheus/add_service_monitoring.md
scripts/enable-monitoring.sh

Part of: [operate-first/SRE#216](https://github.com/operate-first/SRE/issues/216 )
fix: https://github.com/operate-first/SRE/issues/277 
The script accepts a namespace and applies '- ../../../components/monitoring-rbac' line to 'components' field with a kustomize cli.
On success print nothing, and on failure print relevant error from kustomize cli. 
Notice that kustomize editing the file and uses specific annotation while listing the components, the '-' is at the first char and not the second on each line.

Enable monitoring on a namespace

---

cluster-scope/overlays/moc/common/kustomization.yaml

part of: https://github.com/operate-first/apps/pull/595
not including it broke the kustomize build, it should have been caught

Add team-pixel grp to common.

---

kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/apicurio-registry-servicemonitor.yaml

`name` is not a valid field in `v1.ServiceMonitor.spec.endpoints`, I think `port` was intended here.

Rename endpoint.name to endpoint.port for apicurio-monitor.

---

kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml

enable thoth-devops group to view the opf-monitoring grafana dashboard

enable thoth-devops group to view the opf-monitoring grafana dashboard

---

cluster-scope/base/namespaces/quarkus-extension-registry/kustomization.yaml

I need more resources to deploy more pods and support the PostgreSQL DB

Change quarkus-extension-registry quota to large

---

cluster-scope/overlays/moc/zero/kustomization.yaml
cluster-scope/overlays/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml

Add network interfaces for access to nfs server
This adds vlan interfaces to provide access to an nfs server for
additional storage. We use node labels to select the appropriate
interface for a given node.

Add network interfaces for access to nfs server

---

cluster-scope/overlays/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml

on second thought, we'd like to move the storage connection to the
non-public interface in order to avoid competition with other traffic
on the public interfaces.

swap interfaces for storage connection

---

cluster-scope/base/namespaces/openshift-cnv/namespace.yaml

the openshift-cnv namespace.yaml had an incorrect namespace name

fix openshift-cnv namespace

---

cluster-logging/base/clusterlogging.yaml

Part of: https://github.com/operate-first/SRE/issues/286
The actual proven usage is much lower than the requested space.

chore: Move CLO PVCs from OCS to NFS and downsize

---

odh-manifests/kafka/base/kafka-cluster.yaml

Relocate and shrink PVCs for kafka
1. Kafka from 3x 200Gi to 3x20Gi
2. Zookeeper from 3x10Gi to 3x2Gi

chore: Move Kafka PVCs from OCS to NFS and downsize

---

observatorium/overlays/moc/zero/deployments/thanos-query-frontend-oauth-proxy.yaml

Related #638 
The current serviceaccount being used does not have enough permissions

fix serviceaccount name for thanos oauth proxy

---

acme-operator/base/deployment.yaml
acme-operator/base/kustomization.yaml
acme-operator/base/serviceaccount.yaml
acme-operator/overlays/dev/issuer-letsencrypt-staging.yaml
acme-operator/overlays/dev/kustomization.yaml
acme-operator/overlays/moc/zero/issuer-letsencrypt-live.yaml
acme-operator/overlays/moc/zero/kustomization.yaml
cluster-scope/base/core/namespaces/acme-operator/kustomization.yaml
cluster-scope/base/core/namespaces/acme-operator/namespace.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/acme-operator/clusterrole.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/acme-operator/kustomization.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml
docs/issuing_certificates.md

Resolves: https://github.com/operate-first/support/issues/237
Part of: https://github.com/operate-first/support/issues/199
I've renamed most of the resources from `openshift-acme` to `acme-operator` since most things with `openshift-*` prefix usually refer to OpenShift-owned resources.Hopefully this lowers the confusion here.
It turned out that we can't use CertManager to secure OpenShift routes, since they don't want to support vendor specific resource (`Route`) and OpenShift can't make the routes to load certs from secrets for many years, so we need 2 different solutions in place - one for routes and another one for the rest.
References in the issue above.

Acme operator

---

argocd/overlays/moc-infra/projects/operate-first.yaml

SSIA
Part of: https://github.com/operate-first/support/issues/237

fix: Allow ACME operator namespace in argocd

---

scripts/argocd/update_cluster_resources.sh

While editing the update-cluster-resources script, I noticed that
we're using both `curl` and `wget` in the same script. This commits
settles on using `curl` in all cases.

use curl instead of both wget and curl in the same script

---

cluster-scope/base/core/namespaces/acme-operator/kustomization.yaml

ACME operator requires 2 pods to be running for HA - where CPU limit is 500m on each. `x-small` doesn't allow for the second pod to start successfully.
Note this is just for HA, doesn't have any effect on basic functionality.
Part of: https://github.com/operate-first/support/issues/237

fix: ACME quota for HA

---

cluster-scope/base/core/persistentvolumeclaims/image-registry-storage/persistentvolumeclaim.yaml

Explicitly select the moc-nfs-csi storageclass for the image registry
pv.
Part of #312

Move image registry pv to nfs storage

---

kfdefs/overlays/moc/zero/opf-jupyterhub/kustomization.yaml

Tested this in the staging env and it doesn't affect existing PVCs.
New PVCs created were with the new `moc-nfs-csi` storageclass

Update Jupyterhub StorageClass to moc-nfs-csi

---

jupyterhub-idle-culler/base/buildconfig.yaml
jupyterhub-idle-culler/base/deploymentconfig.yaml
jupyterhub-idle-culler/base/imagestream.yaml
jupyterhub-idle-culler/base/kustomization.yaml
jupyterhub-idle-culler/overlays/moc/zero/.sops.yaml
jupyterhub-idle-culler/overlays/moc/zero/deploymentconfig_patch.yaml
jupyterhub-idle-culler/overlays/moc/zero/kustomization.yaml
jupyterhub-idle-culler/overlays/moc/zero/secrets/secret-generator.yaml
jupyterhub-idle-culler/overlays/moc/zero/secrets/secret.enc.yaml

Resolves: https://github.com/operate-first/SRE/issues/229
Using buildconfig/deployment configs here, which may be controversial. Not opposed to adding a Dockerfile and pushing to quay, though we'd need to decide where that would go. This just seemed like a quick and easy way to get it this out the door. 
I've set idle timeout to 3 days, open to suggestions here. 
The jupyterhub token is created via Jupyterhub UI using my (admin) account. The docs for jupyterhub-idle-culler also seemed to suggest this. 
I think we should try to encourage upstream to introduce this as a [jupyterhub managed service](https://jupyterhub.readthedocs.io/en/stable/reference/services.html#launching-a-hub-managed-service) so we don't have to rely on our api tokens.

Add jupyterhub-idle-culler 

---

jupyterhub-idle-culler/overlays/moc/zero/deploymentconfig_patch.yaml

For some reason the patch is removing the container list item, not sure why it's happening but this should fix the final build.

Add missing patch fields for idle culler.

---

kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml

I've mimicked this PR: https://github.com/operate-first/apps/pull/593/files
What I'm after is: getting access to the Apicurio team members to Graphana and Prometheus

feat: add Apicurio to viewers on opf-monitoring

---

observatorium/base/instance/observatorium.yaml

Related https://github.com/operate-first/SRE/issues/287
This PR will
* sync the Observatorium Thanos version to the current deployed version (v0.20.1)
* Increase the thanos receiver PVC size from 50Gi to 100Gi

Expand thanos receive pvc

---

cluster-scope/base/core/namespaces/opf-ci-pipelines/resourcequota.yaml

Remove the pod limit for the ofp-ci-pipelines
This is causing issues on the cleanup job to start.

Remove the pod limit for the ofp-ci-pipelines

---

observatorium/overlays/moc/zero/rolebindings/opf-observatorium-view.yaml

This will add `apicurio` openshift group to the `opf-observatorium-view` rolebinding, giving the team access to Loki.

Give apicurio team permissions to access loki

---

observatorium/overlays/moc/zero/rolebindings/opf-observatorium-view.yaml

This will give the data-science permissions to query logs from opf-observatorium loki instance
cc @Shreyanand 
Resolves https://github.com/operate-first/support/issues/250

Add data-science team to the opf-observatorium-view rolebinding

---

cluster-scope/overlays/moc/zero/kubeletconfigs/increase-worker-system-reserved-memory.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml

We've been seeing a number of errors of the form:
System memory usage of 1.209G on os-ctrl-1 exceeds 90% of the
reservation...
See e.g. [1]. According to [2], we can adjust the system reserved
memory by creating a custom Kubeletconfig resource. This commit
adds the necessary resource and applies it to the worker nodes.
According to [3], this may or may not take effect immediately:
> If dynamically updating this field, consider that it may not be
> possible to increase the reserved resources, because this requires
> resizing cgroups. Always look for a NodeAllocatableEnforced event
> after updating this field to ensure that the update was successful.
[1]: https://github.com/operate-first/alerts/issues/7738
[2]: https://docs.openshift.com/container-platform/4.7/nodes/nodes/nodes-nodes-managin …

Increase system reserved memory for worker nodes

---

kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/thoth-station-servicemonitor.yaml

switch the targetport with port name for thoth service monitor

switch the targetport with port name for thoth service monitor

---

cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml
cluster-scope/base/operators.coreos.com/subscriptions/kubevirt-hyperconverged/subscription.yaml
cluster-scope/base/operators.coreos.com/subscriptions/local-storage-operator/subscription.yaml
cluster-scope/base/operators.coreos.com/subscriptions/metering-operator/subscription.yaml
cluster-scope/base/operators.coreos.com/subscriptions/ocs-operator/subscription.yaml
cluster-scope/base/operators.coreos.com/subscriptions/serverless-operator/subscription.yaml

I believe we had previously determined to switch all our operator
subscriptions to automatic approval. This takes care of the few cases
that were still configured for Manual approval.

Switch all Subscriptions to automatic approval

---

cluster-scope/base/core/namespaces/thoth-pulp-experiments/namespace.yaml

Fixes: https://github.com/operate-first/apps/pull/678
`aicoe-thoth-devops` is not a team in Operate First. `thoth-devops` is.

fix(#678): Pulp experiments requester

---

cluster-scope/base/core/namespaces/thoth-pulp-experiments/kustomization.yaml
cluster-scope/base/core/namespaces/thoth-pulp-experiments/resourcequota.yaml

Part of https://github.com/operate-first/support/issues/176
Changes the medium tier quota to a custom - diff:
```diff
-     requests.storage: 40Gi
+     requests.storage: 60Gi
```
Based on: https://github.com/operate-first/support/issues/176#issuecomment-848703442
/cc @fridex @harshad16 @4n4nd

feat(thoth-pupl-experiments): Update quota

---

kfdefs/base/jupyterhub/ray-odh-integration/ray-cluster-template-cm.yaml
kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml

to support slightly larger use cases, this PR proposes to increase the memory for ray cluster nodes to 3Gi.  This corresponds roughly to a working mem of 2.1Gi and object-store mem of 0.9Gi.  Additionally, it increases the node timeout to 30 minutes to reduce churn of ray cluster pods.
I am submitting this somewhat as part of https://github.com/operate-first/support/issues/254 but as a separate PR since it is not an image update, just a resourcing change.

increase ray node mem to 3Gi, idle-timeout to 30min

---

cluster-scope/overlays/moc/infra/kubeletconfigs/increase-worker-system-reserved-memory.yaml
cluster-scope/overlays/moc/infra/kustomization.yaml

This is the same as #673, but for the moc-infra cluster.
Part of #671.

overlays/infra: Increase system reserved memory for worker nodes

---

kfdefs/base/monitoring/blackbox-exporter/kustomization.yaml

Fixes #578 that broke the `kfdef-zero` ArgoCD app

fix(blackbox-exporter): Secret generator is not a resource

---

kfdefs/base/jupyterhub/ray-odh-integration/ray-cluster-template-cm.yaml
kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml

Adds a `Route` for the Ray dashboard, and exposes an environment var `RAY_DASH_URL` that jupyter users can display to get the dashboard URL for their browser.

expose ray dashboard

---

kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
kfdefs/base/jupyterhub/notebook-images/s2i-spark3.0.1-minimal-notebook.yaml

Current spark base notebook image is 2.4.5 which is not up to date.
Adds spark3.0.1 base notebook image. Spark version configurable Image created by @anishasthana and Landon (https://github.com/opendatahub-io/odh-manifests/issues/293)
Next up is adding xskipper sample use ipynb to it, and perhaps configure the pyspark jars to include needed jars automatically.
* I wonder if it should be added to https://github.com/aicoe-aiops or to opendatahub-io/odh-manifests instead

Add spark3.0.1 notebook image

---

cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml

I've updated our alertmanager config to use the one provided by SRE-P, basically everything that goes to pagerduty for them would go to github for us. We are being a bit more selective on what routes go to github rather then sending everything. 
Also looking for more suggestions on what alerts we ought to include/exclude.

Apply sre-p alertmanager config to openshift-monitoring's prometheus.

---

kfdefs/overlays/moc/zero/kustomization.yaml
kfdefs/overlays/moc/zero/osc-playground/kustomization.yaml

Add Jupyterhub for OS-C playground. A separate environment is needed to allow for experimentation with JH itself if needed, and some flexibility.

Add Jupyterhub to osc playground.

---

cluster-scope/overlays/moc/zero/kustomization.yaml
cluster-scope/overlays/moc/zero/machinehealthchecks/work-healthcheck.yaml

This defines a healthcheck for the worker nodes such that they will be
rebooted in they are unavailable (NotReady or state unknown) for more
than 10 minutes.
Closes #operate-first/SRE#112

Define MachineHealthCheck for worker nodes

---

cluster-scope/base/core/namespaces/osc-playground/kustomization.yaml

Medium is apparently not enough for the full JH deployment we define in the base kfdef. CPU seems to require >2 cores.

Update osc quota to large.

---

cluster-scope/base/core/namespaces/osc-playground/kustomization.yaml
cluster-scope/base/core/namespaces/osc-playground/resourcequota.yaml

Large quota is not enough, need at least 8 + 2 cores for a large notebook + the jh pods.

Add custom resourcequota for osc.

---

.prow.yaml

kustomize build tests are taking > 20mins to run. This should increase the available cpu for it and make them faster.

Increase kustomize-build test prow cpu resource

---

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/dashboards/odh/jupyterhub-user.yaml
kfdefs/overlays/moc/zero/opf-monitoring/dashboards/odh/kustomization.yaml

Add a dashboard for Jupyter Hub from a single user perspective:
/cc @4n4nd
critique welcomed

feat(dashboards): Add JH user perspective dashboard

---

cluster-scope/overlays/moc/zero/clusterversion.yaml

As a preparation for https://github.com/operate-first/SRE/issues/330 we need to switch from `stable-4.7` to `fast-4.7`.

feat: Switch Zero OCP channel to `fast`

---

scripts/update-cluster-version.sh

Just a quick update to the cluster version updater script, before it gets eventually converted to the golang version.
Offer a choice if there are multiple updates available:

chore: Update cluster version updater script when multiple updates are available

---

cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml

Need this label to add properly title issue in alerts repo. Otherwise we get this: https://github.com/operate-first/alerts/issues/8791

Add alertname group by label to alert config.

---

odh-manifests/prometheus/operator/base/service-monitors/application-service-monitor.yaml
odh-manifests/prometheus/operator/base/service-monitors/operator-service-monitor.yaml
odh-manifests/prometheus/operator/overlays/alerts/prometheus-rules.yaml

The [upstream directory](https://github.com/opendatahub-io/odh-manifests/tree/master/prometheus/operator/base/service-monitors) for servicemonitor manifests has changed, they need to be changed here as well.
This has resulted into multiple servicemonitors looking for same services.
Resolves https://github.com/operate-first/apps/issues/641

Update odh servicemonitors

---

odh-manifests/prometheus/operator/base/service-monitors/application-service-monitor.yaml

After the oauth proxy was added, the service was changed to https from http, this needs to be reflected in the servicemonitor as well.
Resolves https://github.com/operate-first/apps/issues/641

fix: change scheme for prometheus serviemonitor

---

cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml

https://github.com/operate-first/apps/pull/718 introduced a duplicity in attempt to correct SRE-P rule - this made both `ClusterOperatorDown` and `ClusterOperatorDegraded` alerts suppressed. And we don't want that. I hope this will correct things.

fix(alerts): ClusterOperatorDown/Degraded inhibit rule dedup

---

cluster-scope/base/core/namespaces/koku-metrics-operator/kustomization.yaml
cluster-scope/base/core/namespaces/koku-metrics-operator/namespace.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/koku-metrics-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/koku-metrics-operator/operatorgroup.yaml
cluster-scope/base/operators.coreos.com/subscriptions/koku-metrics-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/koku-metrics-operator/subscription.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml

Created via https://github.com/operate-first/opfcli/pull/22
Part of: https://github.com/operate-first/support/issues/265
Install and enables operator on Curator cluster
/cc @skanthed

feat: Install Koku operator to Zero cluster

---

cluster-scope/base/core/namespaces/apicurio-apicurio-registry/kustomization.yaml
cluster-scope/base/core/namespaces/as-pushgateway/kustomization.yaml
cluster-scope/base/core/namespaces/cnv-testing/kustomization.yaml
cluster-scope/base/core/namespaces/ds-black-flake/kustomization.yaml
cluster-scope/base/core/namespaces/ds-example-project/kustomization.yaml
cluster-scope/base/core/namespaces/ds-ml-workflows-ws/kustomization.yaml
cluster-scope/base/core/namespaces/fde-audio-decoder-demo/kustomization.yaml
cluster-scope/base/core/namespaces/lab-cicd-1-jump-app-cicd/kustomization.yaml
cluster-scope/base/core/namespaces/lab-cicd-1-jump-app-dev/kustomization.yaml
cluster-scope/base/core/namespaces/lab-cicd-2-jump-app-cicd/kustomization.yaml
cluster-scope/base/core/namespaces/lab-cicd-2-jump-app-dev/kustomization.yaml
cluster-scope/base/core/namespaces/lab-cicd-3-jump-app-cicd/kustomization.yaml
cluster-scope/base/core/namespaces/lab-cicd-3-jump-app-dev/kustomization.yaml
cluster-scope/base/core/namespaces/lab-cicd-4-jump-app-cicd/kustomization.yaml
cluster-scope/base/core/namespaces/lab-cicd-4-jump-app-dev/kustomization.yaml
cluster-scope/base/core/namespaces/m4d-blueprints/kustomization.yaml
cluster-scope/base/core/namespaces/m4d-system/kustomization.yaml
cluster-scope/base/core/namespaces/mesh-for-data/kustomization.yaml
cluster-scope/base/core/namespaces/open-aiops/kustomization.yaml
cluster-scope/base/core/namespaces/ray-odh-integration/kustomization.yaml
cluster-scope/base/core/namespaces/sa-dach-anwendertreffen/kustomization.yaml
cluster-scope/base/core/namespaces/sa-dach-openshift-examples/kustomization.yaml
cluster-scope/base/core/namespaces/sdap/kustomization.yaml
cluster-scope/base/core/namespaces/tufts-dcc-6/kustomization.yaml
cluster-scope/base/core/namespaces/uky-hpc-workload-generator/kustomization.yaml
cluster-scope/base/core/namespaces/ws-ml-prague/kustomization.yaml

Applied quotas to namespaces as specified: https://github.com/operate-first/apps/issues/574#issuecomment-827497979
I didn't touch `openshift-*` or `opf-*` namespaces. 
I also tried to peek in to some of the namespaces to see if they are active/maintained, and tried to approximate a quota that's better fitting then just `x-small`, if it was either unclear, or a namespace not in use, then I defaulted to `x-small`.

Apply resource quotas to namespaces that are without one.

---

cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml

Partially reverts #722 
Looking back at the source
https://github.com/openshift/configure-alertmanager-operator/blob/c9032fd13a9dcd7d374d1491db4b23af1120ba11/pkg/controller/secret/secret_controller.go#L349-L350
It seems there's a reason why `ClusterOperatorDegraded` is favored over `ClusterOperatorDown`
/cc @HumairAK

fix: Semi-revert #722

---

cluster-scope/base/core/namespaces/apicurio-apicurio-registry/kustomization.yaml

Just noticed the new Quota requirements.
We are currently still in active exploration on our namespace so our needs might vary in the future (with a possibility to split namespaces in more specialized ones).
This is a screenshot of today's status. I've picked the Medium tier but please advise if you feel we could calibrate it more accurately.

Increase Apicurio Registry quota

---

cluster-scope/base/core/namespaces/curator-engine/kustomization.yaml
cluster-scope/base/core/namespaces/koku-metrics-operator/kustomization.yaml

Caused by: https://github.com/operate-first/opfcli/issues/38
Causing project admin roles not to propagate to a namespaces (ArgoCD uses `open-cluster-management-agent`)

fix: team access to namespaces

---

kfdefs/base/google-spark-operator/kfdef.yaml

The added change is here: https://github.com/HumairAK/odh-manifests/blob/spark-operator/google-spark-operator/operator/base/clusterrole.yaml#L93
Transferred from: https://github.com/operate-first/apps/pull/746

Update spark operator fork destination.

---

kfdefs/overlays/moc/zero/opf-kafka/kustomization.yaml
odh-manifests/kafka/base/kafka-cluster.yaml
odh-manifests/kafka/overlays/topics/kustomization.yaml
odh-manifests/kafka/overlays/users/audio-decoder.yaml
odh-manifests/kafka/overlays/users/kustomization.yaml
odh-manifests/kafka/overlays/users/thoth.yaml

Resolves #482 
This:
* sets up simple tls authentication for Operate First Kafka cluster
* adds 2 example users for thoth team (@harshad16) and for fde audio decoder demo (@Gkrumbach07)
More documentation on how the tls authentication works: https://strimzi.io/docs/operators/0.22.0/using.html#tls_client_authentication

Add tls authentication for opf-kafka with example users

---

cluster-scope/base/operators.coreos.com/operatorgroups/mwperf-horreum/kustomization.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/mwperf-horreum/operatorgroup.yaml
cluster-scope/base/operators.coreos.com/subscriptions/horreum-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/horreum-operator/subscription.yaml
cluster-scope/overlays/moc/zero/kustomization.yaml

Created through
```
opfcli install-operator horreum-operator community-operators -n mwperf-horreum -s -c alpha
```
@HumairAK Please review.
I hope that as a project admin I'll have the necessary privileges to create a CR brought by the operator (if not I'll try file another PR).

Install Horreum operator to mwperf-horreum namespace

---

cluster-scope/base/core/namespaces/hostpath-provisioner/kustomization.yaml
cluster-scope/base/core/namespaces/metallb-system/kustomization.yaml
cluster-scope/base/core/namespaces/opf-google-spark-operator/kustomization.yaml

Before https://github.com/operate-first/opfcli/issues/38 was fixed it got propagated to `opf-google-spark-operator` namespace (and now to https://github.com/operate-first/apps/pull/757 as well).
Setting `namespace:` for `hostpath-provisioner` and `metallb-system` for house keeping.

fix: missing namespace in kustomization

---

odh-manifests/kafka/overlays/users/audio-decoder.yaml
odh-manifests/kafka/overlays/users/thoth.yaml

this should fix the incorrect topic name prefixes assigned to kafka users

fix topic prefix for kafka users

---

cluster-scope/overlays/moc/common/groups/thoth.enc.yaml

This will add @Gregory-Pereira to the `thoth` openshift group giving him access to the `thoth-*` namespaces

add user grpereir to thoth group

---

odh-manifests/kafka/overlays/topics/thoth-adviser-trigger.yaml
odh-manifests/kafka/overlays/topics/thoth-provenance-checker-trigger.yaml

If messages are still around after cache expires they will no longer provide info to users. Cache retention time is 4hours, I adjusted topic retention time to match this.

update retention to match cache time for advises and provenance

---

cluster-scope/overlays/moc/common/kustomization.yaml

This was missed here: https://github.com/operate-first/apps/pull/752
Probably missed by CI because we ignore the secrets.

Added group adoptium to common kustomization.

---

kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-node-imagestream.yaml
kfdefs/base/jupyterhub/ray-odh-integration/ray-operator-imagestream.yaml

Recent versions of ray 1.x (e.g. the latest, 1.4) support the ray client-server connect, and so I am updating all the images to use ray 1.4.0 instead of nightly wheel builds.  I have also included IBM's codeflare, which they released to pypi this week.

update ray images to use ray 1.4 and include ibm codeflare

---

acme-operator/overlays/moc/zero/issuer-letsencrypt-live.yaml

Resolves: https://github.com/operate-first/apps/issues/783

fix: Don't sync acme operator configmap

---

vector/overlays/moc/zero/opf-observatorium/configmap.yaml

We need to use the public kafka url for tls authentication
Related https://github.com/operate-first/apps/pull/770

Fix Kafka bootstrap url in Vector configmap

---

cluster-scope/base/core/namespaces/opf-ci-pipelines/resourcequota.yaml
cluster-scope/base/core/namespaces/opf-ci-prow/resourcequota.yaml
cluster-scope/base/core/namespaces/opf-datacatalog/resourcequota.yaml
cluster-scope/base/core/namespaces/osc-playground/resourcequota.yaml
cluster-scope/base/core/namespaces/thoth-amun-inspection-prod/resourcequota.yaml
cluster-scope/base/core/namespaces/thoth-backend-prod/resourcequota.yaml
cluster-scope/base/core/namespaces/thoth-frontend-prod/resourcequota.yaml
cluster-scope/base/core/namespaces/thoth-graph-prod/resourcequota.yaml
cluster-scope/base/core/namespaces/thoth-middletier-prod/resourcequota.yaml
cluster-scope/components/resourcequotas/large/resourcequotas.yaml
cluster-scope/components/resourcequotas/medium/resourcequotas.yaml
cluster-scope/components/resourcequotas/small/resourcequotas.yaml
cluster-scope/components/resourcequotas/x-small/resourcequotas.yaml

~Resolve: https://github.com/operate-first/SRE/issues/324~
I also added a cap of 1 objectbucketclaim for each quota. I also updated existing user custom quotas, a brief skim through indicated they already respected these restrictions so it should not affect them. 
Reference: https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota

Prevent usage of rgw storage class for buckets.

---

odh-manifests/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml

Workaround for: https://github.com/operate-first/support/issues/240
Part of: https://github.com/operate-first/SRE/issues/346
Eyeballing the JH profile sizes before we have the final usage analysis

feat: Downsize JH profiles on CPU

---

cluster-scope/base/operators.coreos.com/subscriptions/jaeger-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/jaeger-operator/subscription.yaml
cluster-scope/base/operators.coreos.com/subscriptions/kiali-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/kiali-operator/subscription.yaml
cluster-scope/base/operators.coreos.com/subscriptions/servicemesh-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/servicemesh-operator/subscription.yaml

Part of: https://github.com/operate-first/support/issues/111
Installs Service Mesh and it's prerequisites according to:
https://docs.openshift.com/container-platform/4.7/service_mesh/v2x/installing-ossm.html

Install Service Mesh operator

---

cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml

Resolves https://github.com/operate-first/support/issues/259

Add data-science group as project admins for the opf-seldon namespace

---

cluster-scope/base/core/namespaces/thoth-middletier-prod/resourcequota.yaml

increase limit to better utilize the namespace
we are working on optimizing our usage in the `thoth-middletier-namespace`, we have reduce our requests requirement and matched our limit to the `peak` , with this pr we would be able to utilize more efficiently.
Related-to: https://github.com/operate-first/SRE/issues/346

increase limit to better utilize the namespace

---

odh-manifests/kafka/base/kafka-cluster.yaml

I have been seeing some issues in kafka producers
for example, in the cluster log forwarding fluentd pods:
```
2021-06-24 16:48:20 +0000 [warn]: failed to flush the buffer. retry_time=0 next_retry_seconds=2021-06-24 16:48:21 +0000 chunk="5c585c9c198761b415ab0b5c05102be0" error_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://odh-message-bus-kafka-bootstrap-opf-kafka.apps.zero.massopen.cloud:443: Connection timed out"
2021-06-24 16:48:20 +0000 [warn]: suppressed same stacktrace
2021-06-24 16:48:21 +0000 [warn]: Send exception occurred: Could not connect to any of the seed brokers:
- kafka://odh-message-bus-kafka-bootstrap-opf-kafka.apps.zero.massopen.cloud:443: Connection timed out
2021-06-24 16:48:21 +0000 [warn]: retry succeeded. …
```

increase kafka and zookeeper replicas from 3 to 5

---

cluster-scope/base/core/namespaces/ds-ml-workflows-ws/kustomization.yaml

Context: 
> **Isabel Zimmerman wrote:**
> Hi gang-- Looking into the `ds-ml-workflows-ws` namespace and my JH server keeps getting HTTP 500 (when trying to spawn default/large/medium sized servers) and HTTP 403 (when trying to spawn small server) errors. All of the errors have the HTTP response body of `{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"jupyterhub-nb-izimmerm-40redhat-2ecom\" is forbidden: exceeded quota: medium, requested: limits.cpu=1, used: limits.cpu=1500m, limited: limits.cpu=2","reason":"Forbidden","details":{"name":"jupyterhub-nb-izimmerm-40redhat-2ecom","kind":"pods"},"code":403}` any help would be appreciated :disguised_face:
> 
> **1st Operator wrote:**
> Hey Tom Coufal, can you please help Isabel Zimmerman?
> 
> **Humair Khan …

Upgrade quota for ns ds-ml-workflows-ws.

---

cluster-scope/base/core/namespaces/thoth-graph-prod/resourcequota.yaml

increase the resource limit for the graph namespace
Require some cushion in resource quota for newer deployments.

increase the resource limit for the graph namespace

---

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/odh/jupyterhub-user.yaml

In the odh Jupyterhub dashboard, the query for CPU usage percentage should have ```usage / limit``` instead of ```usage / resource```  to be  consistent with the title of the graph and the graph for memory usage percentage.

Update the CPU limit graph

---

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/cpu_usage.yaml
kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/kustomization.yaml

Resolve: https://github.com/operate-first/SRE/issues/241
see it live [here](https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/vBauwggnk/cluster-cpu-usage?orgId=1&var-datasource=opf-prometheus&var-namespace=openshift-storage)

Add cpu usage dashboard to grafana.

---

cluster-scope/overlays/prod/moc/zero/configmaps/cluster-monitoring-config.yaml
cluster-scope/overlays/prod/moc/zero/kustomization.yaml

This will attach PVCs to openshift-monitoring prometheus instances.
There are 2 replicas of openshift-monitoring prometheus so this will create 2 PVCs of size 100Gi each.

Add cluster-monitoring-config 

---

odh-manifests/kafka/overlays/users/audio-decoder.yaml

I am using KafkaJS which requires kafka consumers to have a consumer group (compared to something like kafka-python). Therefore I am getting an error: `Not authorized to access group: Group authorization failed` when i try to connect a consumer.
So this pull request is adding that group to my user yaml.

added group authorization for kafka user

---

kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/cpu_usage.yaml

The change adds load averages for all nodes on the zero cluster. Need to use thanos datasource for accurate results until we install querier in the `opf-monitoring` namespace.

Update grafana dashbaord for cpu usage in zero cluster.

---

cluster-logging/base/clusterlogging.yaml
cluster-logging/overlays/moc/zero/clusterlogforwarders/clusterlogforwarder.yaml
observatorium/base/instance/grafana.yaml
observatorium/overlays/moc/zero/grafana-data-sources/kustomization.yaml
observatorium/overlays/moc/zero/grafana-data-sources/opf-moc-zero-loki-source.yaml
observatorium/overlays/moc/zero/routes/grafana-oauth-proxy.yaml
observatorium/overlays/moc/zero/routes/kustomization.yaml
vector/overlays/moc/zero/opf-observatorium/configmap.yaml

Update Log Forwarding to send logs to Kafka instead of Elasticsearch
Update Vector Config to consume logs from kafka and push to Loki
Add grafana dataources for the newly added logging tenants (infra/audit)
Also add an oauth proxy for observatorium grafana. Only accounts that have access to the `openshift-logging` namespace can view infra and audit logs.

Disable sending logs Elasticsearch and send logs to Loki

---

cluster-scope/overlays/prod/moc/infra/kustomization.yaml

this was missing from the previous commit and is necessary for access
to the nfs server

add missing nodenetworkconfigurationpolicy

---

cluster-scope/overlays/prod/moc/zero/configmaps/cluster-monitoring-config.yaml

Openshift Monitoring Prometheus Instance PVCs are full, we need to increase their size.

Increase cluster-monitoring storage size to 150Gi

---

cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/meteor-servicemonitor.yaml

This addresses https://github.com/AICoE/meteor/issues/51
We want to enable prometheus monitoring for the meteor web application: http://meteor-shower-aicoe-meteor.apps.zero.massopen.cloud/

Add service monitor for meteor

---

cluster-scope/overlays/prod/common/secret-generator.yaml

Added fix because sre group was missing in secret-generator file. (issue https://github.com/operate-first/support/issues/318)

fix: add sre to secret generator

---

cluster-scope/overlays/prod/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml

There is a failing NodeNetworkConfigurationPolicy on the zero cluster:
$ oc get nncp
NAME                          STATUS
moc-nfs-network-eno2          SuccessfullyConfigured
moc-nfs-network-enp4s0f1      ConfigurationProgressing
moc-nfs-network-enp4s0f1np1   SuccessfullyConfigured
This causes us to lose network connectivity when an affected node
reboots. According to case 02961182 [1], this is caused by
RHBZ#1967771 [2]. The resolution is described in a knowedgebase
article [3].
In order to clear the condition, we will need to delete and re-create
the affected policies. Once this change merges we will delete the
resources and allow ArgoCD to re-create them.
[1]: https://access.redhat.com/support/cases/#/case/02961182
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1967771
[3]: …

Resolve failing NodeNetworkConfigurationPolicy

---

kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/openshift-pipelines-servicemonitor.yaml

scrape metrics from openshift pipelines services
openshift-pipelines exposes metrics on the port http-metrics.
It would be great to scrape them.

scrape metrics from openshift pipelines services

---

cluster-scope/overlays/prod/emea/rick/oauths/cluster_patch.yaml

We were encountering the following errors: 
```
E0811 16:33:27.517143       1 base_controller.go:250] "ConfigObserver" controller failed to sync "key", err: failed to apply IDP operate-first config: x509: certificate signed by unknown authority
I0811 16:33:27.518051       1 status_controller.go:213] clusteroperator/authentication diff {"status":{"conditions":[{"lastTransitionTime":"2021-08-05T21:47:01Z","message":"OAuthServerConfigObservationDegraded: failed to apply IDP operate-first config: x509: certificate signed by unknown authority","reason":"AsExpected","status":"False","type":"Degraded"},{"lastTransitionTime":"2021-08-09T09:28:15Z","message":"All is well","reason":"AsExpected","status":"False","type":"Progressing"},{"lastTransitionTime":"2021-08-10T03:46:41Z","message":"OAuthServer …
```

Update rick oidc oauth config CA and issuer url.

---

dex/base/dex-sa.yaml
dex/overlays/dev/dex-cm.yaml
dex/overlays/moc/zero/dex-cm.yaml
docs/observatorium/loki/README.md
docs/odh/grafana/README.md
docs/odh/grafana/add_permissions_to_grafana.md
kfdefs/base/monitoring/blackbox-exporter/probe.yaml
kfdefs/overlays/moc/zero/opf-monitoring/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/secrets/kustomization.yaml
kfdefs/overlays/moc/zero/opf-monitoring/secrets/oauth-client-secret.enc.yaml
kfdefs/overlays/moc/zero/opf-monitoring/secrets/secret-generator.yaml
observatorium/base/instance/example-oauth-client-secret.enc.yaml
observatorium/base/instance/grafana.yaml
observatorium/base/instance/kustomization.yaml
observatorium/overlays/moc/zero/routes/grafana-route.yaml
observatorium/overlays/moc/zero/routes/kustomization.yaml
observatorium/overlays/moc/zero/secrets/oauth-client-secret.enc.yaml
observatorium/overlays/moc/zero/secrets/secret-generator.yaml
odh-manifests/grafana/grafana/base/grafana.yaml
odh-manifests/grafana/grafana/base/route.yaml

Resolve: #37 
Also does a few other things: 
- Remove hue client from dex 
- Fix dex redirect/issuer paths
- Fix dex SA namesspace
- Change Grafana route to match route metadata.name
- Add doc on how to give ocp groups grafana roles 
Those in the ocp groups `cluster-admins` / `operate-first` have Admin in Grafana, while those in `data-science` group have `viewer`

Add auth via dex to grafana on zero.

---

cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
cluster-scope/base/user.openshift.io/groups/superset-user/kustomization.yaml
cluster-scope/overlays/prod/common/groups/odh-admin.enc.yaml
cluster-scope/overlays/prod/common/groups/superset-user.enc.yaml
cluster-scope/overlays/prod/common/kustomization.yaml
cluster-scope/overlays/prod/common/secret-generator.yaml
dex/overlays/moc/zero/dex-cm.yaml
odh-manifests/superset/base/secret.yaml

Should also resolve: https://github.com/operate-first/support/issues/354
Added a new `superset-user` group, fill follow up with docs on how to get onboarded to superset for access. I just gave them 'Gamma' level access, that seemed sufficient. Not sure if we need a more robust mapping set up, but I figured we'd do that if/when the need arises. 
Reference: 
https://superset.apache.org/docs/security#provided-roles
https://superset.apache.org/docs/installation/configuring-superset#custom-oauth2-configuration

Update superset oauth configs and rbac access.

---

cluster-scope/overlays/prod/moc/zero/oauths/cluster_patch.yaml
cluster-scope/overlays/prod/moc/zero/oauths/operate-first-sso-secret.enc.yaml
cluster-scope/overlays/prod/moc/zero/secret-generator.yaml
keycloak/overlays/moc/infra/clients/zero.enc.yaml

Part of: https://github.com/operate-first/apps/issues/790
Onboard Infra cluster to Keycloak providing Operate First's SSO as an additional option to MOC SSO for now.
/hold 
1. until Keycloak is deployed (https://github.com/operate-first/apps/issues/789) and until groups are imported
2. requires `KeycloakClient` to be added into `keycloak/overlays/moc/infra/secret-generator.yaml` to unwip

feat: Onboard Zero cluster to Keycloak

---

cluster-scope/overlays/prod/moc/infra/oauths/cluster_patch.yaml
cluster-scope/overlays/prod/moc/infra/oauths/operate-first-sso-secret.enc.yaml
cluster-scope/overlays/prod/moc/infra/secret-generator.yaml
keycloak/overlays/moc/infra/clients/infra.enc.yaml

Part of: https://github.com/operate-first/apps/issues/790
Onboard Infra cluster to Keycloak providing Operate First's SSO as an additional option to MOC SSO for now.
/hold 
1. until Keycloak is deployed (https://github.com/operate-first/apps/issues/789)
2. requires `KeycloakClient` to be added into `keycloak/overlays/moc/infra/secret-generator.yaml` to unwip

feat: Onboard Infra cluster to Keycloak

---

odh-manifests/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
odh-manifests/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml

Adopts: https://github.com/opendatahub-io/odh-manifests/pull/398 
`sizes` and `profiles` were split into 2 different configmaps which are later merged.
CM `odh-jupyterhub-sizes` respects the [upstream manifest](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml) and sets our custom values.
CM `jupyter-singleuser-profiles` remains the same (without sizes) because of https://github.com/operate-first/apps/pull/744

fix: JupyterHub single user profile sizes split

---

cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
cluster-scope/base/core/namespaces/aicoe-meteor/limitrange.yaml

Tekton pipelines uses default limitranges for default settings. This change will make tekton steps use better and larger limits by default.
/cc @4n4nd @HumairAK

feat: Set better meteor limit range

---

cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
cluster-scope/base/core/namespaces/aicoe-meteor/resourcequota.yaml

I think I need to request bigger quota limit for the meteor namespace.
Together with #911 the default cumulative limit went up, because each container has 4 CPU limit by default. So if a pod has 3 containers it's limit is 6 cores now. It will probably never use it but we need to be able to schedule it. This should keep requests low and raise limits for now. I'll look into better way to influnce those limits in future.

feat: Up meteor quota limit

---

cluster-scope/base/core/namespaces/opf-trino/resourcequota.yaml
kfdefs/overlays/moc/zero/opf-trino/kustomization.yaml
odh-manifests/trino/base/trino-worker-dc.yaml

Using overrides here to change resource usages (cpu:8, mem: 16Gi), and adds the toleration/node selectors to run on os-wrk-1

Schedule trino workers to os-wrk-1 on zero.

---

odh-manifests/zero/prometheus/operator/base/prometheus.yaml

This will add a label `prometheus: moc/zero` to all the metrics exported using remotewrite

add external label to moc/zero prometheus

---

kfdefs/overlays/moc/zero/opf-trino/kustomization.yaml

To solve ODH errors: 
```
E0825 14:07:43.403996       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.KfDef: v1.KfDefList.Items: []v1.KfDef: v1.KfDef.Spec: v1.KfDefSpec.Applications: []v1.Application: v1.Application.KustomizeConfig: v1.KustomizeConfig.Parameters: []v1.NameValue: v1.NameValue.v1.NameValue.Value: ReadString: expects " or n, but found 4, error found in #10 byte of ...|,"value":4},{"name":|..., bigger context ...|lue":"16Gi"},{"name":"trino_cpu_request","value":4},{"name":"trino_cpu_limit","value":8}],"repoRef":|...
```

Change trino compute to str.

---

cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml

fix: Odh operator namespace missing on Devconf cluster

---

cluster-scope/overlays/prod/emea/devconfus2021/configmaps/cluster-monitoring-config.yaml
cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml

Adding user workload monitoring to devconfus2021 cluster as a part of https://github.com/operate-first/SRE/issues/370 .

feat: add user workload monitoring to devconfus2021 cluster

---

argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv

App of apps lives in operate first project for security reasons (deploys to argocd namespace), we need users to be able to see the app. It probably deserves it's own project, but this is quick and dirty solution for now

feat: Allow operate-first project apps to be listed by public

---

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/moc/zero/kustomization.yaml

Moving namespace of ci-prow from zero cluster to smaug.
Related: https://github.com/operate-first/argocd-apps/pull/186

feat: move ci-prow namespace to smaug

---

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-interceptor-opf-ci-pipelines/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-interceptor-opf-ci-pipelines/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

setup clusterbinding required for ofp-ci-pipelines
smaug cluster is on openshift 4.8, with which the openshift-pipelines v0.15.0 is shipped
the application ofp-ci-pipelines requires these crb setups to function properly.

feat: setup clusterbinding required for ofp-ci-pipelines

---

argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv

Add SRE group to policy.csv so they can use ArgoCD web interface.

feat: add sre to argocd-group

---

odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml

Related: https://github.com/os-climate/os_c_data_commons/issues/52#issuecomment-917076509 
Dashes were causing issues with trino client.

Rename osc phys landing trino catalog.

---

cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/extensions.dashboard.tekton.dev/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/extensions.dashboard.tekton.dev/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-dashboard/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-dashboard/tekton-dashboard-backend.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-dashboard/tekton-dashboard-extensions.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-dashboard/tekton-dashboard-tenant.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-backend.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-dashboard.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-extensions.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-pipelines.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-tenant.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-triggers.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

setup cluster resources required for tekton dashboard
Tekton dashboard is a one-stop place to view all the openshift pipelines running. 
https://github.com/tektoncd/dashboard/blob/main/docs/install.md

feat: setup cluster resources required for tekton dashboard

---

cluster-scope/base/core/namespaces/openshift-nmstate/kustomization.yaml
cluster-scope/base/core/namespaces/openshift-nmstate/namespace.yaml
cluster-scope/base/operators.coreos.com/subscriptions/kubernetes-nmstate-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/kubernetes-nmstate-operator/subscription.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/subscriptions/kubernetes-nmstate-operator_patch.yaml

Part of operate-first/SRE#379
This adds the nmstate operator to smaug so that we have a declarative network configuration mechanism available.
This PR does not create an operatorgroup because many operators seem to do that automatically. If you think it needs one, please let me know.

Add nmstate subscription

---

kfdefs/base/jupyterhub/notebook-images/experimental-elyra-notebook-imagestream.yaml

Experimental should allow for testing latest changes in the image.

Use latest for experimental elyra notebook image

---

cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Added user workoad monitoring config map as a base for deployment of monitoring on smaug.
Resolves operate-first/SRE#294

feat: add user workload monitoring to smaug cluster

---

odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml

Seems like this catalog is required for some reason, otherwise workers will not boot up, possibly coordinator as well though not tested.

Re-add hive.properties to osc trino catalog.

---

cluster-scope/base/core/namespaces/thoth-test-core/resourcequota.yaml
cluster-scope/overlays/prod/emea/rick/kustomization.yaml
cluster-scope/overlays/prod/moc/zero/kustomization.yaml

Migrate thoth-station test namespace to rick cluster
Fixes: https://github.com/operate-first/support/issues/372

Migrate thoth-station test namespace to rick cluster

---

cluster-scope/overlays/prod/moc/curator/secret-generator.yaml

The curator cluster was still configured to use Ilana's expired pull
secret.

Update curator to use common pull-secret

---

kfdefs/overlays/osc/osc-cl1/jupyterhub/profiles/kustomization.yaml
kfdefs/overlays/osc/osc-cl1/jupyterhub/profiles/singleuser-profiles-gpu-ui.yaml

enable gpu ui on the odh launcher for the os-climate cluster

add singleuser-profiles-gpu-ui.yaml

---

cert-manager/base/ingress-certificate.yaml
cert-manager/base/kustomization.yaml
cert-manager/overlays/moc/common/clouddns-dns01-na-svc-acct.enc.yaml
cert-manager/overlays/moc/common/kustomization.yaml
cert-manager/overlays/moc/common/openshift-ingress-issuer.yaml
cert-manager/overlays/moc/common/secret-generator.yaml
cert-manager/overlays/moc/smaug/certificate.yaml
cert-manager/overlays/moc/smaug/kustomization.yaml

/cc @Gregory-Pereira @HumairAK @4n4nd 
So, I've synced up the live state from the Smaug cluster and split up the cert manager configs per env. The idea is to make the setup robust for multi-cluster deployments:
1. Have a single `Certificate` spec for all ingresses
2. Overlay the issued dns name per cluster
3. Use the same `Issuer` definition for all clusters in the same region, including the DNS service account secret
This manifests render 0 diff against live state on Smaug.

feat: Cleanup cert-manager config and sync from live state

---

kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml

Updates trino image version so we can get this change: https://github.com/trinodb/trino/pull/8641/commits 
There's some deprecated configs I had to remove to support this upgrade @rimolive for your reference. 
The upgrade also required us to identify the oauth issuer.

Update trino version for osc cluster.

---

acm/overlays/moc/infra/gitopsclusters/argocd-managed.yaml
acm/overlays/moc/infra/gitopsclusters/kustomization.yaml
acm/overlays/moc/infra/klusterletaddonconfigs/kustomization.yaml
acm/overlays/moc/infra/kustomization.yaml
acm/overlays/moc/infra/managedclusters/balrog.yaml
acm/overlays/moc/infra/managedclusters/curator.yaml
acm/overlays/moc/infra/managedclusters/kustomization.yaml
acm/overlays/moc/infra/managedclusters/ocp-prod.yaml
acm/overlays/moc/infra/managedclusters/osc-cl1.yaml
acm/overlays/moc/infra/managedclusters/rick.yaml
acm/overlays/moc/infra/managedclusters/smaug.yaml
acm/overlays/moc/infra/managedclustersetbindings/argocd-managed.yaml
acm/overlays/moc/infra/managedclustersetbindings/kustomization.yaml
acm/overlays/moc/infra/managedclustersets/argocd-managed.yaml
acm/overlays/moc/infra/managedclustersets/kustomization.yaml
acm/overlays/moc/infra/placements/argocd-managed-clusters.yaml
acm/overlays/moc/infra/placements/kustomization.yaml

Okay so the way they are doing integration with argocd seems to have changed.
Old way: [here](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/manage_applications/managing-applications#gitops-pattern) where we just update the one field `applicationManager.argocdCluster`. When onboarding balrog, this didn't add the argocd secret. That's because...
The new way: [here](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html/applications/managing-applications#gitops-config) 
Which requires you to have a cluster-set, which is in tech preview, but I set it up on live to test it out and it indeed added balrog to the argocd cluster list (i.e. created the secret). 
This required adding …

Add clustersets and gitops mgmt as per acm 2.3

---

cluster-scope/base/core/persistentvolumeclaims/image-registry-storage/persistentvolumeclaim.yaml
cluster-scope/overlays/prod/emea/rick/kustomization.yaml

Resolves: https://github.com/operate-first/support/issues/377
Also uses the default storage class now.

feat: Add imageregistry storage to Rick

---

odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml

Trino does not allow uppercase catalog names apparently: 
```
2021-09-29T20:39:21.615Z	ERROR	main	io.trino.server.Server	catalogName is not lowercase: OSC_DataCommons_Prod
java.lang.IllegalArgumentException: catalogName is not lowercase: OSC_DataCommons_Prod
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
at io.trino.metadata.MetadataUtil.checkLowerCase(MetadataUtil.java:92)
at io.trino.metadata.MetadataUtil.checkCatalogName(MetadataUtil.java:67)
at io.trino.metadata.Catalog.<init>(Catalog.java:51)
at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:257)
at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:210)
at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:196)
at …
```

Converted osc catalog names to lowercase.

---

acm/overlays/moc/infra/managedclusters/kustomization.yaml
argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
keycloak/overlays/moc/infra/secret-generator.yaml

With hitchhikers guide switching over to the `kustomize edit` via https://github.com/operate-first/hitchhikers-guide/pull/103 let's format the modified files beforehand (before the webinar recording).
Make the changeset of https://github.com/tumido/apps/commit/e4157cfe670122b43e2a7cc0c8fd44eded3a1eca a tiny bit smaller

chore: Fix formatting for kustomize edit

---

cluster-scope/overlays/prod/emea/rick/kustomization.yaml
cluster-scope/overlays/prod/emea/rick/storageclasses/ocs-storagecluster-cephfs_patch.yaml

Follow up to https://github.com/operate-first/apps/pull/1075
Without specifying a storageclass, the PVC won't bound, since there's no default.

fix: Mark cephfs storageclass default on rick

---

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Allow deploying argo workflows on Smaug
Facing issues while submitting resources, same as on rick cluster.
```
no matches for kind "WorkflowTemplate" in version "argoproj.io/v1alpha1"
```
in response to: https://github.com/thoth-station/thoth-application/issues/1971

enabling workflow and workflow template CRDs

---

cluster-scope/overlays/prod/common/alertmanager-main-secret.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/alerts.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml

This will add PVC full alerts for jupyterhub users. These alerts will be sent to the github alertreceiver.
In these alerts, the Jupyterhub runbook is linked so that users can try to fix the issue by themselves.
Also, users will be tagged in the alert issue using their github handle.
Example alert issue: https://github.com/operate-first/alerts/issues/22570

Add PVC full alerts for Jupyterhub users

---

argocd/overlays/moc-infra/configs/argo_cm/resource.exclusions

Next patch to https://github.com/operate-first/SRE/issues/391 
This should fix the `ManagedClusterInfo` pruning. This PR makes ArgoCD ignore those resources completely, so they should never appear on the app screen again.

fix: Diffing in ACM ArgoCD app

---

cluster-scope/base/core/namespaces/demo-jupyterhub/kustomization.yaml
cluster-scope/base/core/namespaces/demo-jupyterhub/namespace.yaml
cluster-scope/base/user.openshift.io/groups/demo-team/group.yaml
cluster-scope/base/user.openshift.io/groups/demo-team/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/demo-team/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/demo-team/rbac.yaml
cluster-scope/overlays/prod/emea/demo/kustomization.yaml

This will add @4n4nd and @HumairAK as project admins for namespace `demo-jupyterhub` on emea/demo cluster

feat(onboarding): Add team demo-team

---

kfdefs/overlays/osc/osc-cl1/jupyterhub/kustomization.yaml
kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/aicoe-osc-demo.yaml
kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/kustomization.yaml

- Created a `notebook-images` directory for any custom notebook images
- Added imagestream for [demo notebooks](https://github.com/os-climate/aicoe-osc-demo) created for OS-Climate

Add imagestream for aicoe osc demo notebooks image.

---

kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/aicoe-osc-demo.yaml

This PR changes the tag from `v.10` to `latest` in the ImageStream for AICoE OSC demo, so that jupyterhub (on the OS-Climate cluster) has the latest image.

Fix AICoE OSC demo ImageStream

---

argocd/base/kustomization.yaml
argocd/cluster-resources/kustomization.yaml
argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-ocp-prod.yaml
argocd/overlays/moc-infra/kustomization.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/applications.argoproj.io/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/applicationsets.argoproj.io/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/applicationsets.argoproj.io/kustomization.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/appprojects.argoproj.io/customresourcedefinition.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

Resolve https://github.com/operate-first/SRE/issues/385
Upgrade for ArgoCD to 2.1.3. 
Not sure why argocd resources were being imported from the cluster-resources-infra app, but I moved them to be bundled by the argocd-infra app. I also added application sets as part of this bundle. 
Also snuck in a change to declarative ocp prod app of apps to sync with live state, which has automated syncs enabled.

Update argocd to 2.1.3, add application sets

---

argocd/base/deployments/argocd-application-controller_patch.yaml
argocd/base/deployments/argocd-repo-server_patch.yaml
argocd/base/kustomization.yaml

For app controller we need to update the image to use user `999` to avoid: https://github.com/argoproj/argo-cd/issues/6851 
```
Error: container has runAsNonRoot and image has non-numeric user (argocd), cannot verify user is non-root
```
For now I just disabled this. 
For repo-server, we need the gpg folder writeable so I disabled their read only protection for root. The error this resolves is: 
```
Exec lifecycle hook ([/bin/sh -c gpg --import /key/*]) for Container "argocd-repo-server" in Pod "argocd-repo-server-84bf4ccc88-9qr7c_argocd(91b1ef75-50dd-429a-bdb9-608d995e0491)" failed - error: command '/bin/sh -c gpg --import /key/*' exited with 2: gpg: Fatal: can't create directory '/home/argocd/.gnupg': Read-only file system , message: "gpg: Fatal: can't create directory …
```

Update security context perms for argocd.

---

kfdefs/overlays/moc/smaug/opf-trino/obcs/opf-datacatalog.yaml

Seems like this gets replaced by ocs, not sure if it's auto-generated but matching it with what's on live all the same.

Fix opf-datactalog objectbucketName to match auto generated name.

---

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/subscriptions/kubernetes-nmstate-operator_patch.yaml

Since CNV is deployed to Smaug, we should remove nmstate operator to avoid both nmstate deployments fighting over it.
/cc @larsks @HumairAK 
/hold

fix: Remove nmstate from Smaug, revert to CNV

---

cluster-scope/overlays/prod/moc/curator/secret-generator.yaml

Operate First SSO on the Curator cluster is missing the necessary
client secret. This was erroneously omitted from 0bdc9bd.

Include operate-first-sso-secret in generated manifests

---

cluster-scope/base/storage.k8s.io/storageclasses/ocs-external-storagecluster-ceph-rbd/kustomization.yaml
cluster-scope/base/storage.k8s.io/storageclasses/ocs-external-storagecluster-ceph-rbd/storageclass.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/storageclasses/ocs-external-storagecluster-ceph-rbd.yaml

This adds the ocs-external-storagecluster-ceph-rbd storageclass to the
repository and makes it the default on smaug.
Part of operate-first/sre#416

Make ocs-external-storagecluster-ceph-rbd the default storage class

---

argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml

Keeping it around for future use, but removing it from the build so it doesn't show up in argocd.

Remove demo app of apps from argocd.

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/pulp.yaml
argocd/overlays/moc-infra/projects/global_project.yaml
cluster-scope/base/core/namespaces/opf-pulp/kustomization.yaml
cluster-scope/base/core/namespaces/opf-pulp/namespace.yaml
cluster-scope/base/core/namespaces/opf-pulp/resourcequota.yaml
cluster-scope/base/core/namespaces/thoth-pulp-experiments/namespace.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/opf-pulp/kustomization.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/opf-pulp/operatorgroup.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/moc/zero/kustomization.yaml
pulp/base/kustomization.yaml
pulp/base/opf-pulp.yaml
pulp/overlays/moc/smaug/kustomization.yaml
pulp/overlays/moc/smaug/opf-pulp-route.yaml
pulp/overlays/moc/smaug/opf-pulp.yaml

setup pulp instance and track it in git
Fixes: https://github.com/operate-first/support/issues/437
Related-to: https://github.com/operate-first/support/issues/176
Details:
Manage pulp instance via git.
Post Merge:

setup pulp instance and track it in git

---

cluster-scope/overlays/prod/moc/curator/kustomization.yaml
cluster-scope/overlays/prod/moc/curator/machineconfigs/50-ipmi-route.yaml

The baremetal operator was complaining because it was unable to reach
the ipmi addresses of the cluster nodes. This adds the necessary
routes for access to the ipmi network.

Add routes for ipmi access to curator cluster

---

docs/development/setup_quicklab.md

Otherwise the impression is that one ought to always pick 4.6.1

Add instructions on selecting ocp ver in quiclab docs.

---

cluster-scope/overlays/prod/moc/curator/configmaps/admin-acks.yaml
cluster-scope/overlays/prod/moc/curator/kustomization.yaml

This adds the necessary admin-ack for the 4.8 -> 4.9 upgrade
described in KB 6329921 [1].
[1]: https://access.redhat.com/articles/6329921

Configure curator cluster to allow 4.8 -> 4.9 upgrade

---

argocd/overlays/moc-infra/projects/global_project.yaml

Addresses part 3 of [thoth-station/thoth-application issue 2029](https://github.com/thoth-station/thoth-application/issues/2029#issuecomment-961310030)
no
Enabling prometheus rule in argocd in the global_project for the MOC-infra overlay.

enabling prometheus rule to argocd in moc-infra overlay

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/fybrik.yaml

This PR adds the `applicationNamespace` Helm parameter to the Fybrik ArgoCD application
@ronenkat @HumairAK

Adding Helm parameter to Fybrik ArgoCD application

---

odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml

Original goal: define a group to confine lseg data access to users known to be covered under NDA
New Goal: resync user groups with github teams, which will include `..._developer` user groups for each project. These `developer` groups should have access to LSEG data.
cc @caldeirav @MichaelTiemannOSC

re-sync trino user groups with github teams

---

cluster-scope/base/core/namespaces/opf-observatorium/resourcequota.yaml
docs/observatorium/vector/README.md
observatorium/overlays/moc/smaug/vector/balrog/configmap.yaml
observatorium/overlays/moc/smaug/vector/balrog/deployment.yaml
observatorium/overlays/moc/smaug/vector/balrog/kustomization.yaml
observatorium/overlays/moc/smaug/vector/balrog/service.yaml
observatorium/overlays/moc/smaug/vector/infra/configmap.yaml
observatorium/overlays/moc/smaug/vector/infra/deployment.yaml
observatorium/overlays/moc/smaug/vector/infra/kustomization.yaml
observatorium/overlays/moc/smaug/vector/infra/service.yaml
observatorium/overlays/moc/smaug/vector/rick/configmap.yaml
observatorium/overlays/moc/smaug/vector/rick/deployment.yaml
observatorium/overlays/moc/smaug/vector/rick/kustomization.yaml
observatorium/overlays/moc/smaug/vector/rick/service.yaml
observatorium/overlays/moc/smaug/vector/smaug/configmap.yaml
observatorium/overlays/moc/smaug/vector/smaug/deployment.yaml
observatorium/overlays/moc/smaug/vector/smaug/kustomization.yaml
observatorium/overlays/moc/smaug/vector/smaug/service.yaml

Related https://github.com/operate-first/apps/issues/1210
Deploy Vector in Smaug to forward logs from Rick/Infra/Balrog/Smaug clusters to the Smaug Loki instance.

Add Vector deployment for multiple clusters

---

odh-manifests/smaug/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml

This PR updates the tiers for single user profiles using result from usage analysis in [notebooks](https://github.com/aicoe-aiops/operate-first-jupyterhub-analysis/blob/master/notebooks/resource_allocation/) here. 
We found three triers: Small, Medium, and Large based on clustering of user consumption. 
Based on observation of just spawned pods, the minimum CPU and memory were set to 100m and 0.5gi respectively. 
Related Issue https://github.com/aicoe-aiops/operate-first-jupyterhub-analysis/issues/12
Continuation of this [PR](https://github.com/operate-first/apps/pull/1156)

Add Jupyterhub resource tiers based on usage analysis

---

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault-server-binding/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault-server-binding/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

This PR adds the cluster role binding required to deploy Vault on the Smaug cluster. 
See reasoning below:
`vault-server-binding` is part of the Helm deployment of vault when using Kubernetes auth method https://wanwenli.com/kubernetes/2019/08/28/k8s-tokenreview-api-vault.html 
The Vault Kubernetes auth method (https://www.vaultproject.io/docs/auth/kubernetes#kubernetes-auth-method) is used to authenticate Kubernetes services against Vault using their Service Account Token. To enable it Vault needs to access Kubernetes TokenReview API to validate the service JWT.
For this reason Vault Service Account should be granted permissions to access this API with this cluster role binding.
@roee88 @ronenkat @HumairAK

Fybrik - adding cluster role binding for Vault

---

cluster-scope/base/core/namespaces/tekton-chains/kustomization.yaml
cluster-scope/base/core/namespaces/tekton-chains/namespace.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-chains/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-chains/tekton-chains-controller-cluster-access.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-chains/tekton-chains-controller-tenant-access.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-chains/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-chains/tekton-chains-controller-cluster-access.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-chains/tekton-chains-controller-tenant-access.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

setup namespace, rbac and roles for the tekton chains
Related-to: https://github.com/operate-first/support/issues/438
Tekton chains provide security to our pipeline supply chains.
It would sign the images based on the secrets. 
https://github.com/tektoncd/chains#installation

setup namespace, rbac and roles for the tekton chains

---

argocd/overlays/moc-infra/projects/apicurio-registry.yaml

Apicurio is still not being deployed, I checked argocd
https://argocd.operate-first.cloud/applications/opf-app-of-apps-smaug?resource=&node=argoproj.io%2FApplication%2Fargocd%2Fregistry-smaug%2F0
and found the error 
```
message: >-
application destination {https://api.smaug.na.operate-first.cloud:6443
apicurio-apicurio-registry} is not permitted in project 'apicurio'
```
Then I noticed the apicurio AppProject must point to the same destination as the Application. This PR changes that, however, is the value `smaug` correct? or should I use the api url? 
In this docs https://github.com/operate-first/apps/blob/master/docs/argocd-gitops/onboarding_to_argocd.md#create-the-argocd-project it says to use the cluster `metadata.name` value

apicurio: fix AppProject

---

grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-cpu-overview.yaml
grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-memory-overview.yaml

This updates the charts here: 
https://grafana.operate-first.cloud/d/ucHWsaF7i/cluster-memory-overview?orgId=1
https://grafana.operate-first.cloud/d/nA4fwtvnzzdf3e/cluster-cpu-overview?orgId=1

Add multi-cluster support to graf overview dashboards.

---

cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-users.yaml
odh-manifests/osc-cl1/superset/base/secret.yaml

This will allow issues [like this](https://github.com/os-climate/os_c_data_commons/issues/103?notification_referrer_id=NT_kwDOAKZlh7MyNzM5MDc2NjA4OjEwOTA0OTY3#event-5676223043) to be self serviced by those in the `odh-admin` group.

Use odh admin group for superset admins over cluster admins group.

---

cluster-scope/base/core/namespaces/prometheus-ai-project/kustomization.yaml
cluster-scope/base/core/namespaces/prometheus-ai-project/namespace.yaml
cluster-scope/components/project-admin-rolebindings/prometheus-ai/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/prometheus-ai/rbac.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Hey,
I've added a project for our group (that was added earlier) following [this](https://github.com/operate-first/hitchhikers-guide/blob/main/pages/onboarding_project.ipynb) guide.

Add prometheus-ai-project for team promethues-ai

---

pulp/overlays/moc/smaug/opf-pulp.yaml

Related-to: https://github.com/operate-first/support/issues/456
Epic: https://github.com/operate-first/support/issues/176
The ceph storage in smaug doesn't allow volume mode: file system with the ReadWriteMany mode.
Alternative this was suggested to use ReadWriteOnce mode, to allow many pods to attach to this kinda storage the pods must be on the same node. Hence added the node affinity which the pulp operator allows
https://github.com/pulp/pulp-operator/blob/c3fb814aa6685e14d5b016830e680c908550b559/config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml#L230

Patch the pulp instance with node affinity to allow RDX storage mode

---

pulp/overlays/moc/smaug/opf-pulp.yaml

Fix the image tags for the pulp instance
Epic: https://github.com/operate-first/support/issues/176
stable tag is added automatically by pulp-operator

Fix the image tags for the pulp instance

---

observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml

This PR can be used as an example PR in the docs
Related https://github.com/operate-first/support/issues/454#issuecomment-981831163

Give `prometheus-ai` group access to thanos metrics

---

cluster-scope/base/user.openshift.io/groups/data-science/group.yaml

Adding user @suppathak to the data science group.
Resolves https://github.com/operate-first/support/issues/483 
Tag: @MichaelClifford

Adding suppathak to Data-Science group

---

cluster-scope/overlays/prod/moc/curator/kustomization.yaml

This operator wasn't being used and was causing problems.
Closes operate-first/curator#165

Remove web-terminal operator from curator cluster

---

.github/workflows/book.yml

Yaml looks a bit weird, but seems it's valid, not specifically mentioned in the docs, but you can see it in use here: 
https://github.com/operate-first/operate-first.github.io/blob/master/.github/workflows/build_job.yaml#L6

Add manual trigger for jbook action.

---

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

This shouldn't introduce any changes to the live environment, it's simply reformatting the file so that we don't see large diffs when people use `kustomize edit add`. It also fixes some of misplaced entries and places the alphabetically.

Reformat smaug kustomization to fit the kustomize cli format.

---

kfdefs/overlays/moc/smaug/opf-trino/kustomization.yaml
kfdefs/overlays/moc/smaug/opf-trino/vpa/kustomization.yaml
kfdefs/overlays/moc/smaug/opf-trino/vpa/vpa-custom-resource.yaml

@HumairAK / @4n4nd Current opf-trino (prod) request and limits are:
CPU: Request- 4 core, Limit- 8 core
Memory: Request: 9 GB, Limit: 16 GB
Based on this, min and max values that VPA can operate are configured in this PR. VPA UpdatePolicy will be set to Off for prod initially. Let me know if you think we should tune values differently.
```
maxAllowed:
cpu: 8000m
memory: 16Gi
minAllowed:
cpu: 1000m
memory: 4Gi
```
These min/max values are per container of trino-worker. Ref: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L165

Configure VPA custom resource for opf-trino namespace's trino-worker

---

cluster-scope/overlays/prod/emea/rick/.sops.yaml
cluster-scope/overlays/prod/emea/rick/configmaps/cluster-monitoring-config.enc.yaml
cluster-scope/overlays/prod/emea/rick/oauths/operate-first-sso-secret.enc.yaml

This will allow @rbo to encrypt/decrypt emea/rick kustomizations using sops/ksops. 
I also removed other gpg keys besides the op1st key, don't think we need them.

Add new gpg key and remove unneeded ones for emea rick cluster-scope.

---

pulp/overlays/moc/smaug/opf-pulp.yaml

Fixed the label used for the node affinity
Fixes: https://github.com/operate-first/support/issues/456
Epic: https://github.com/operate-first/support/issues/176
This would set the node for pulp.

Fixed the label used for the node affinity

---

cluster-scope/overlays/prod/moc/infra/clusterversion.yaml

Resolve: https://github.com/operate-first/apps/issues/1432

Revert clusterID for infra to it's original cluster id

---

docs/content/argocd-gitops/onboarding_to_argocd.md

previous link to onboarding doc is dead -- long live the link to onboarding doc
https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md -> https://github.com/operate-first/hitchhikers-guide/blob/main/pages/onboarding_project.ipynb

update onboarding guide link

---

cert-manager/overlays/moc/common/openshift-ingress-issuer.yaml

https://github.com/operate-first/apps/issues/1439

Rename certmanager issuer secret for private key due to conflict.

---

argocd/overlays/moc-infra/configs/argo_cm/dex.config
argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
argocd/overlays/moc-infra/projects/kustomization.yaml
argocd/overlays/moc-infra/projects/tremor-demo.yaml

following [this guide](https://www.operate-first.cloud/apps/content/argocd-gitops/onboarding_to_argocd.html) i've made changes that should allow the tremor-demo team to make use of argo-cd. Could have missed something, happy for any feedback / changes / other processes we need to follow here.

tremor-demo argocd onboarding

---

grafana/overlays/moc/smaug/grafana-oauth.yaml

There are a few Grafana dashboards for the Thoth team, but the team is not explicitly listed as a group with access.
In particular, as I am not part of any of the current groups, this means I don't have access to Grafana :innocent: 
This PR is to add the `thoth` team to Grafana.

Add access to Grafana for the thoth team

---

odh-manifests/smaug/kafka/base/kafka-cluster.yaml

Due to: https://github.com/operate-first/SRE/issues/416#issue-1041404796

Set default storage class for kafka on smaug.

---

kfdefs/base/argo/kfdef.yaml
kfdefs/base/dashboard/kfdef.yaml
kfdefs/base/kafka/kfdef.yaml
kfdefs/base/seldon/kfdef.yaml

Argo: minor route ssl config change
odh-dashboard: minor [changes](https://github.com/opendatahub-io/odh-manifests/commits/v1.1.1/odh-dashboard)
Kafka: no changes
Seldon: no changes
Related #1476

Update Argo, odhdashboard, kafka, seldon kfdefs to 1.1.1

---

kfdefs/overlays/moc/smaug/kustomization.yaml

Kfdefs for argo, odh-dashboard and seldon were not added to the Smaug kustomization. This PR fixes that.

Add argo, dashboard, seldon to smaug kfdef kustomization

---

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

These are being managed by ODH operator:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
annotations:
kfctl.kubeflow.io/kfdef-instance: opendatahub.opf-argo
name: cronworkflows.argoproj.io
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
annotations:
kfctl.kubeflow.io/kfdef-instance: opendatahub.opf-argo
name: workflows.argoproj.io
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
annotations:
kfctl.kubeflow.io/kfdef-instance: opendatahub.opf-argo
name: workflowtemplates.argoproj.io
```

Remove unneeded argoproj crds from smaug.

---

OWNERS

We expect this change will prevent sesheta from randomly assigning reviewers from approvers list.

Add empty reviewers list in owners. And add new approver.

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/vault.yaml

This PR changes the repo url in the `vault` ArgoCD application manifest to point to the [fybrik/charts](https://github.com/fybrik/charts/tree/master/charts) repo so it stays in sync with the latest release of Fybrik
@revit13 @roytman @HumairAK

Change vault ArgoCD application to point to different repository

---

docs/content/odh/README.md

In response to [issue 1513](https://github.com/operate-first/apps/issues/1513).
Changes:
- adding to documentation of ODH readme for cloudbeaver component

adding cloudbeaver ui route to docs

---

cluster-scope/overlays/prod/common/alertmanager-main-secret.yaml

Addresses Operate-first/apps pr 3 for alerting rules for [Thoth issue 2029](https://github.com/thoth-station/thoth-application/issues/2029)
Prometheus alerting rule updates:
- inhibit_rules.source_match, inhibit_rules.source_match_re and inhibit_rules.target_match and inhibit_rules.target_match_re have been depricated, use source_matchers and target_matchers, [see docs](https://prometheus.io/docs/alerting/latest/configuration/#inhibit_rule)
- route.match and route.match_re have been depricated, use route.matchers, [see docs](https://prometheus.io/docs/alerting/latest/configuration/#route)
- matches configuration defined, [see docs](https://prometheus.io/docs/alerting/latest/configuration/#matcher)

updating the alerting rules with prometheus standard and thoth rules

---

docs/_toc.yml
docs/content/argocd-gitops/onboarding_to_argocd.md
docs/content/cluster-scope/create_ocp_group.md

While this portion is mentioned in the onboarding docs, and/or in the notebook. There are situations where teams /users may want to create an OCP group after onboarding, or without also requiring a namespace.

Add instructions on how to add an ocp group.

---

cluster-scope/base/core/namespaces/opf-ci-pipelines/kustomization.yaml

The training model group needs access to opf-ci-pipelines to allow for the creation and modification of pipelines and pipeline runs
Signed-off-by: Ryan Cook <rcook@redhat.com>

permissions to add the training model group

---

kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
kfdefs/base/jupyterhub/notebook-images/operate-first-jupyterhub-analysis.yaml

This PR adds yaml file to add Operate First Jupyterhub Analysis project image as a spawn option in Opf Jupyterhub instance.

Add opf jh analysis notebook image yaml

---

reloader/base/deployment.yaml

SSIA -- Kubeval flagged this as not valid. Not sure if it will break anything.

fix: Remove null value from deployment of reloader securityContext

---

grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-cpu-overview.yaml

Previously by default the `Cluster CPU overview` dashboard did not show data on any visualization.
This PR now changes the time frame to display the dashboards data at a 15 minute range interval

Changed default time range of the Cluster CPU dashboard

---

cluster-scope/base/core/namespaces/tekton-chains/kustomization.yaml

I would like to add our team to access tekton-chains.
If it helps: this would match the existing access to the [opf ci pipelines access](https://github.com/operate-first/apps/blob/9d082291740f45154d58f62b601fd62f062ba172/cluster-scope/base/core/namespaces/opf-ci-pipelines/kustomization.yaml#L3).
Tekton chains are integrated with the pipelines and I believe this access makes sense.

Grant thoth-devops access to tekton-chains

---

scripts/fake-ksops.sh

We have a number of new co-ops working on this project. Testing out
changes by running `kustomize build` is complicated by our use of ksops.
Rather than distributing decryption keys to all and sundry, we can ease
the testing process by providing a wrapper that sets up a fake ksops
plugin.
The script is used like this:
./scripts/fake-ksops.sh kustomize build --enable-alpha-plugins ...
That permits one to test changes that do not involve modifications to
encrypted data.

Add scripts/fake-ksops.sh to ease testing w/o ksops

---

.pre-commit-config.yaml
kfdefs/overlays/osc/osc-cl1/trino-dev/configs/rules.json
kfdefs/overlays/osc/osc-cl1/trino-dev/configs/trino-acl-dsl.yaml
kfdefs/overlays/osc/osc-cl1/trino/configs/rules.json
kfdefs/overlays/osc/osc-cl1/trino/configs/trino-acl-dsl.yaml

This PR adds a DSL management layer to the `rules.json` files for trino deployments.
The motivation is that `rules.json` rules are:
- difficult to read
- conducive to errors, since one has to scan down all rules to identify first-match in all relevant circumstances
- easy to break, because adding a rule in one place can shadow lower rules if one is not careful
- do not support human readable comments
I implemented a simplified DSL-like yaml format to try and make these configurations easier:
https://github.com/os-climate/osc-trino-acl-dsl
The basic concept is that one creates configurations in this DSL format, and it is translated into a `rules.json` file.
The DSL is declarative - one does NOT have to figure out which entries apply "first": they are order independent.
It can also be …

add DSL management for trino rules.json files

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kfp-tekton.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/scheduledworkflows.kubeflow.org/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/scheduledworkflows.kubeflow.org/kustomization.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/viewers.kubeflow.org/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/viewers.kubeflow.org/kustomization.yaml
cluster-scope/bundles/kfp-tekton/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
kfp-tekton/README.md
kfp-tekton/base/kfp-tekton.yaml
kfp-tekton/base/kustomization.yaml
kfp-tekton/overlays/moc/smaug/kustomization.yaml
kfp-tekton/overlays/moc/smaug/secret-generator.yaml
kfp-tekton/overlays/moc/smaug/secrets/mlpipeline-ceph-artifact.enc.yaml

Closes https://github.com/operate-first/support/issues/435

Add Tekton-backed Kubeflow Pipelines

---

kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/ofir-shechtman.yaml

This is the actual pvc: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-jupyterhub/persistentvolumeclaims/jupyterhub-nb-ofir-2dshechtman-pvc

Correct smaug jh user pvc with actual pvc on live.

---

acm/overlays/moc/infra/managedclusters/osc-cl1.yaml
acm/overlays/moc/infra/managedclustersetbindings/osc.yaml
acm/overlays/moc/infra/managedclustersets/osc.yaml
acm/overlays/moc/infra/placements/argocd-managed-clusters.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/open-cluster-management:managedclusterset:admin:osc/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/open-cluster-management:managedclusterset:admin:osc/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

This will create a new `manageclusterset` called `osc`, and add the `os-cl1` cluster to it. In the future we will be adding the prod OSC cluster to this cluster set as well. I have left out the provisioner role for the [osc admins group](). 
This will result in the following [issue](https://github.com/operate-first/support/issues/436) -- but based on the comments on the jira we should be able to just create a namespace via gitops to workaround it (we can test this when importing the osc prod cluster).

Add osc-cl1 cluster to osc clusterset.

---

cluster-scope/bundles/nfd/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
cluster-scope/overlays/prod/emea/rick/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

I had kept the resource bundling changes in a separate PR for the smaug cluster. 
This PR has resource bundling for the infra cluster. 
Besides these two clusters, I searched for other clusters in moc and I couldn't find any other place in the moc where we can do resource bundling. 
Edit: Will bundle the acme in EMEA cluster in this PR itself.

bundling resources in emea, infra and smaug clusters

---

kfp-tekton/base/kfp-tekton.yaml
kfp-tekton/overlays/moc/smaug/secrets/mlpipeline-ceph-artifact.enc.yaml

This will fix the failing ml-pipeline pod which could not create a minio client. 
The issue was that the configuration defaults try to connect to some default minio host, we need to manually set these if we are not deploying our own minio instance: 
References: 
- https://github.com/kubeflow/kfp-tekton/blob/6166c7c2cc62531f3edf1446dc96d9bb20aa2a1e/backend/src/apiserver/client/minio.go#L65
- https://github.com/kubeflow/kfp-tekton/blob/6166c7c2cc62531f3edf1446dc96d9bb20aa2a1e/backend/src/apiserver/client_manager.go#L384-L405

Correct artifact object storage config for kfp-tekton on smaug.

---

argocd-notifications/base/configmap.yaml
argocd-notifications/base/kustomization.yaml
argocd-notifications/overlays/infra/kustomization.yaml
argocd-notifications/overlays/infra/secret-generator.yaml
argocd-notifications/overlays/infra/secret.enc.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/cluster-resources.yaml
docs/_toc.yml
docs/content/argocd-gitops/argocd_notifications.md

Waiting on rebasing until I get some feedback with this as I am sure I am missing some things here.
Related to [Investigating ArgoCD-Notifications issue](https://github.com/operate-first/SRE/issues/410). Meant to be the smallest slice towards a solution here.
Also waiting on removing some slack attachments from `argocd-notifications-cm` for all templates that are not `on-sync-running` because I could not access quick lab for most of today, so I couldn't test changes to the templates. We want to do this to reduce extra noise, so the initial notification would be the information on the sync running, and then each other condition as a small message with the resolved status.

Argocd notifications slack integration

---

cluster-scope/base/user.openshift.io/groups/thoth/group.yaml

In Response to [Trouble accessing the grafana dashboard](https://github.com/operate-first/apps/issues/1511). Once this gets merged we can test and see if this works. Another possible workaround that could be tried, if this is not an issue, is adding the [`fde` group](https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/fde/group.yaml) to the [`grafana-oauth.yaml` file](https://github.com/operate-first/apps/blob/master/grafana/overlays/moc/smaug/grafana-oauth.yaml#L38-39).

removing capitals from thoth group

---

cert-manager/overlays/moc/common/api-issuer/openshift-api-issuer.yaml
cert-manager/overlays/moc/common/ingress-issuer/openshift-ingress-issuer.yaml
cert-manager/overlays/moc/smaug/api/kustomization.yaml

PR #1571 was mistakenly using the route53 issuer for the smaug api
certificate. This corrects it to use the google cloud issuer.

Previous commit used the wrong issue for the api certificate

---

volsync/overlays/moc/smaug/kustomization.yaml

The smaug overlay for the volsync app didn't match the expectations of
the argocd application.

Fix volsync smaug overlay path

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/vault.yaml

This PR adds parameter to argocd vault application.
By disabling vault.server.authDelegator the clusterRoleBinding `vault-server-binding` is not created by this helm deployment which currently causes the deployment to fail.
Moreover, `vault-server-binding` resource already [exists ](https://github.com/operate-first/apps/tree/master/cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault-server-binding)in the cluster.

Add parameter to argocd vault application.

---

odh-manifests/osc/superset/base/kustomization.yaml

Accidentally added the ODH 1.1.1 version, but osc is still on 1.1.0.

Correct osc superset kustomization to 1.1.0 version.

---

argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/argocd-notifications.yaml
argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/kustomization.yaml

Related to [Investigate Argocd-notifications Issue in Operate-first/SRE](https://github.com/operate-first/SRE/issues/410).
Every other piece was deployed in #1520, short of the argocd-notifications application manifest itself, which has been addressed here.

adding argocd-notifications argocd application manifests

---

kfdefs/overlays/moc/smaug/ds-ml-workflows-ws/kfdef.yaml
kfdefs/overlays/moc/smaug/opf-seldon/kustomization.yaml
odh-manifests/osc-cl1/odhseldon/cluster/base/kustomization.yaml
odh-manifests/osc-cl1/odhseldon/cluster/base/subscription.yaml
odh-manifests/smaug/odhseldon/cluster/base/kustomization.yaml
odh-manifests/smaug/odhseldon/cluster/base/subscription.yaml

Similar to: https://github.com/operate-first/apps/pull/1606 
This will make seldon compatible with ocp 4.9
We can remove this addition once either of these prs is merged upstream: 
https://github.com/opendatahub-io/odh-manifests/pull/522
https://github.com/opendatahub-io/odh-manifests/pull/521

Remove starting csv from odhseldon subscription in odh.

---

kfdefs/base/jupyterhub/kfdef.yaml
odh-manifests/smaug/radanalyticsio/spark/cluster/base/crds.yaml
odh-manifests/smaug/radanalyticsio/spark/cluster/base/deployment.yaml
odh-manifests/smaug/radanalyticsio/spark/cluster/base/kustomization.yaml
odh-manifests/smaug/radanalyticsio/spark/cluster/base/role.yaml
odh-manifests/smaug/radanalyticsio/spark/cluster/base/rolebinding.yaml
odh-manifests/smaug/radanalyticsio/spark/cluster/base/serviceaccount.yaml

While we wait for https://github.com/opendatahub-io/odh-manifests/pull/509 to merge. 
Could also help illustrate the PR is in working order. 
Note: this slightly violates the "crds in `cluster-scope/base` rule, but that's because the ODH operator is deploying these manifests, and they are effectively part of ODH platform (not something argocd manages/deploys).

Make sparkoperator in jh ocp 4.9 compatible.

---

grafana/overlays/moc/smaug/grafana-oauth.yaml

Giving admin permissions so the opf-alerting group can have access to the alerting metrics and the jupyterhub namespace to be able to test the alerts

Giving Grafana Admin permissions to opf-alerting group

---

observatorium/overlays/moc/smaug/loki/kustomization.yaml
observatorium/overlays/moc/smaug/loki/obcs/kustomization.yaml
observatorium/overlays/moc/smaug/loki/obcs/opf-observatorium-logs.yaml
observatorium/overlays/moc/smaug/thanos/kustomization.yaml
observatorium/overlays/moc/smaug/thanos/obcs/kustomization.yaml
observatorium/overlays/moc/smaug/thanos/obcs/opf-observatorium-metrics.yaml

Currently our buckets are hosted on the MOC NFS server which is not being maintained anymore.
The goal is to create two Object Bucket Claims in the `opf-observatorium` namespace, and migrate the metrics and logs from our current buckets into the new ones
Related [#1465 ](https://github.com/operate-first/apps/issues/1465)
Feel free to request changes!
- Name of manifest filename is subject to change along with bucketName

Add two OBCs for Observatorium storage move to ceph

---

.pre-commit-config.yaml
kfdefs/overlays/osc/osc-cl1/trino-dev/configs/rules.json
kfdefs/overlays/osc/osc-cl1/trino/configs/rules.json
kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json

Updating the output of the Trino ACL DSL to test some theories about why file-based-acl is not behaving as expected
cc @caldeirav @rimolive @HumairAK

apply v0.2.5 of osc-trino-acl-dsl

---

cluster-scope/base/operators.coreos.com/catalogsources/operatorhubio-catalog/catalogsource.yaml
cluster-scope/base/operators.coreos.com/catalogsources/operatorhubio-catalog/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

This PR adds a catalogsource for https://operatorhub.io/ and enables it on the smaug cluster.

Allow smaug to install operatorhub.io operators

---

scripts/setup_pvs/README.md
scripts/setup_pvs/playbook.yaml
scripts/setup_pvs/requirements.yaml

- Since [community.kubernetes](https://galaxy.ansible.com/community/kubernetes) got renamed to [kubernetes.core](https://galaxy.ansible.com/kubernetes/core) a change was needed in the ansible playbook
- Added `requirements.yaml` file for easier ansible collections installation
- Moved python dependency `openshift` install to the playbook

Fix setup for NFS pvs on local node using ansible

---

cluster-scope/base/core/namespaces/opf-jupyterhub-stage/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/opf-alerting/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/opf-alerting/rbac.yaml

This will give Admin Privileges to the opf-alerting group in which the alerts will be tested. cc @4n4nd

Giving Admin Privileges to the opf-alerting group

---

cluster-scope/base/operators.coreos.com/subscriptions/snapscheduler/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/snapscheduler/subscription.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Related to https://github.com/operate-first/operations/issues/431
In order to use snapscheduler to take snapshots of the Nooba db, we first need to install snapscheduler. This pr subscribes to the snapscheduler operator and pulls that resource into the smaug cluster.
cc: @larsks

Add subscription to snapscheduler operator

---

cluster-scope/base/operators.coreos.com/subscriptions/snapscheduler/kustomization.yaml

The previous PR https://github.com/operate-first/apps/pull/1644 had the namespace set as snapscheduler-system, which doesn't exist. This PR corrects the namespace to openshift-operators in accordance with other operators installed in the cluster.
cc: @larsks

Corrected namespace for snapscheduler

---

cluster-scope/overlays/prod/moc/smaug/clusterversion.yaml

I've changed the stable channel to 4.9 and determined the most recent 4.9 version that we can upgrade to using the tool: [here](https://access.redhat.com/labs/ocpupgradegraph/update_path?channel=stable-4.8&arch=x86_64&is_show_hot_fix=false&current_ocp_version=4.8.23&target_ocp_version=4.9.21)
I am unsure about where the rest of the hash value comes from so for now I've only added the the obvious hash using the current clusterversion.yaml as a guide.

Updating Smaug clusterversion.yaml to upgrade to OCP 4.9

---

cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml

Part of: https://github.com/operate-first/apps/pull/1658

Remove manual kfdef resource mgmt from odh-cl2.

---

cluster-scope/overlays/prod/moc/smaug/backingstores/noobaa-default-backing-store_patch.yaml

Update num of volume in pvPool for noobaa storage
Related-to: https://github.com/operate-first/operations/issues/454
All the PVC in storage have reached its limits
https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/openshift-storage/persistentvolumeclaims
This is failing all the object bucket using noobaa
https://console-openshift-console.apps.smaug.na.operate-first.cloud/monitoring/alerts/672853483?alertname=NooBaaSystemCapacityWarning85&container=core&endpoint=mgmt&instance=10.129.1.236%3A8080&job=noobaa-mgmt&namespace=openshift-storage&pod=noobaa-core-0&service=noobaa-mgmt&severity=warning
https://console-openshift-console.apps.smaug.na.operate-first.cloud/monitoring/alerts/3605660105?alertname=KubePersistent …

:fire: Update num of volume in pvPool for noobaa storage

---

cluster-scope/overlays/prod/emea/morty/kustomization.yaml

setup a thoth namespace in morty cluster
Related-to: https://github.com/operate-first/operations/issues/454
The objective here is to have the thoth namespace setup in Morty, so we can create a OBC in there, for use of the ci-prow bucket.
in this way, we can fix the current issue with prow ci for time being.

setup a thoth namespace in morty cluster

---

cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml

Related to #1511 https://github.com/operate-first/apps/issues/1511, I think users need to not be capitalized. Trying this change before an issue is created.

moving to lowercase

---

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/snapshotschedules/schedule.yaml

This PR creates a snapshotschedule in smaug that will take daily snapshots of the noobaa database PVC within a 1-week retention time. 
Resolves https://github.com/operate-first/operations/issues/431

Add snapshotschedule to take daily snapshots of noobaa db

---

docs/content/argocd-gitops/get_access_to_argocd.md

related to #1667
related to #1668 
When using our current git-ops setup all GitHub handles must be added to groups in lowercase.

updating access to argocd docs

---

kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/config-map.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/deployment.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/kustomization.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/route.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/service.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml

Blackbox exporter is for gathering metrics which we're not getting from the Prometheus exporter directly. 
The specific metrics details are discussed in this Issue. https://github.com/operate-first/operations/issues/444
This adds a deployment of [Prometheus Blackbox Exporter](https://github.com/prometheus/blackbox_exporter) in the namespace `opf-jupyterhub`
/cc @4n4nd

Adding Blackbox deployment

---

kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/deployment.yaml

there was a typo in the blackbox-exporter name which is being corrected in this commit

Fixing the blackbox exporter Name in JupyterHub

---

cosigned/base/kustomization.yaml

Remove the namespace field to allow for the user or argocd to define the namespace creation at launch

Remove the namespace field

---

acm/overlays/moc/infra/identitatem/authrealms/kustomization.yaml
acm/overlays/moc/infra/identitatem/authrealms/primary.yaml
acm/overlays/moc/infra/identitatem/clients/github.enc.yaml
acm/overlays/moc/infra/identitatem/clients/kustomization.yaml
acm/overlays/moc/infra/identitatem/clients/secret-generator.yaml
acm/overlays/moc/infra/identitatem/kustomization.yaml
acm/overlays/moc/infra/placements/primary-auth.yaml
cluster-scope/base/core/namespaces/idp-mgmt-config/kustomization.yaml
cluster-scope/base/core/namespaces/idp-mgmt-config/namespace.yaml
cluster-scope/base/identityconfig.identitatem.io/idpconfigs/idpconfig/idpconfig.yaml
cluster-scope/base/identityconfig.identitatem.io/idpconfigs/idpconfig/kustomization.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/idp-mgmt-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/idp-mgmt-operator/operatorgroup.yaml
cluster-scope/base/operators.coreos.com/subscriptions/idp-mgmt-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/idp-mgmt-operator/subscription.yaml
cluster-scope/bundles/idp-mgmt-operator/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

Related: https://github.com/operate-first/operations/issues/432
This change will deploy the identity mgmt operator (identitatem) to the
Infra cluster. Identitatem allows us to manage authentication via ACM.
This is in contrast to our current implementation of using Keycloak.
This commit does not affect existing OAUTHs for any clusters yet, but
lays the groundwork so that enabling Identitatem to manage any clusters
managed by ACM is as simple as adding required label to a ManagedCluster.
With this commit you will find an Authrealm that is configured to
authenticate any enrolled manageclusters via the Operate First github
org.
For reference docs: 
- https://identitatem.github.io/idp-mgmt-docs-upstream/install_connected.html#installing-while-connected-online
- …

Add identity mgmt operator to infra cluster.

---

argocd/overlays/moc-infra/secrets/clusters/octo-gohan.enc.yaml
argocd/overlays/moc-infra/secrets/clusters/secret-generator.yaml

Set up summit cluster to be handled with opf argocd
Related-to: https://github.com/AICoE/summit-2021-octo-keynote/issues/69
we would like to set up a summit cluster to be managed via argocd for easy deployment of the application.
AS opf argocd take the account of the cluster from the opf ACM, this pr is adding the cluster to be managed via opf ACM.
this pr was generated following these docs: https://www.operate-first.cloud/apps/content/acm/adding_users_to_acm.html

Set up summit cluster to be handled with opf argocd

---

cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-rs-aggregate-to-admin/clusterrole.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-rs-aggregate-to-admin/kustomization.yaml
cluster-scope/bundles/volsync/kustomization.yaml

Currently project admins cannot deploy replication sources for
volsync. The addition of this clusterrole will aggregate
read/write permissions to the project admin.

Give admin replicationsource read/write perms.

---

cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
docs/content/odh/superset/add_superset_users.md

Change "Shreyanand" to "shreyanand" and update docs to make sure usernames are always lowercase.
For issue https://github.com/operate-first/support/issues/531

Add lowercase constraint for Superset users

---

kfdefs/overlays/osc/osc-cl1/jupyterhub/kfdef.yaml
kfdefs/overlays/osc/osc-cl1/seldon/kfdef.yaml
kfdefs/overlays/osc/osc-cl1/superset/kfdef.yaml
kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml

Redirect to: https://github.com/operate-first/odh-manifests/tree/osc-cl1-v1.1.0 
We'll be keeping this cluster around for a bit longer so it's only appropriate that it points to it's own branch.

Redirect oscl1 kfdefs to oscl1 odh-manifests branch.

---

grafana/overlays/moc/smaug/blackbox-exporter/kustomization.yaml

Adding the service monitor to the kustomization file. Related http://operate-first/operations#444
/cc @4n4nd 
Continuation of https://github.com/operate-first/apps/pull/1701

Adding service monitor to the grafana/blackbox-exporter kustomization file in Smaug

---

kfdefs/overlays/osc/osc-cl2/trino/configs/jvm-coordinator.config
kfdefs/overlays/osc/osc-cl2/trino/configs/jvm-worker.config
kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
kfdefs/overlays/osc/osc-cl2/trino/kfdef.yaml

This update will use the odh manifests for trino from version 1.1.2.
Functionally nothing should change for trino, except that worker and
coordinator jvm configs are not separated.

Update trino kfdef in osc-cl2.

---

kfdefs/overlays/osc/osc-cl2/jupyterhub/kfdef.yaml

This change will update JupyterHub kfdef to deploy JH manifests using
odh version 1.1.2, upgrading from 1.1.0. No significant changes
introduced.
Dependent on: https://github.com/operate-first/odh-manifests/pull/4

Update jupyterhub kfdef in osc-cl2.

---

kfdefs/overlays/osc/osc-cl2/seldon/kfdef.yaml

Update seldon kfdef to odh 1.1.2 in osc-cl2.

---

kfdefs/overlays/moc/smaug/opf-jupyterhub/alerts.yaml

JH PVC alerts have the incorrect runbook url. ([Example](https://github.com/operate-first/alerts/issues/27665))

fix runbook url in smaug Jupyterhub PVC alerts

---

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/sudoers/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/sudoers/kustomization.yaml
cluster-scope/base/user.openshift.io/groups/sudoers/group.yaml
cluster-scope/base/user.openshift.io/groups/sudoers/kustomization.yaml
cluster-scope/overlays/prod/emea/morty/groups/sudoers.yaml
cluster-scope/overlays/prod/emea/morty/kustomization.yaml

- Add group sudoers and clusterrolebinding to clusterrole sudoer
- Remove  rbo from cluster-admins
- Add rbo to sudoers
I don't want to be a cluster admin all the time. Next week in sig-ops meeting I will present and show how it works.

Introduce sudoers on morty

---

cluster-scope/base/user.openshift.io/groups/sre/group.yaml

Add rbo to sre group to get access to grafana dashboards.
https://operatefirst.slack.com/archives/C01TLUB9X6Y/p1647010862350739
https://github.com/operate-first/support/issues/342

Add rbo to sre group

---

cluster-scope/base/core/namespaces/acm/namespace.yaml
cluster-scope/base/core/namespaces/acme-operator/namespace.yaml
cluster-scope/base/core/namespaces/opf-jupyterhub/namespace.yaml
cluster-scope/base/core/namespaces/opf-kafka/namespace.yaml
cluster-scope/base/core/namespaces/opf-observatorium/namespace.yaml

Related #1661 
These labels will store project information which will be used in the Workload Dashboard.
**Labels:**
- Owner of project (group)
- The issue which the project/workload was onboarded
- A link the projects documentation
- This is a draft PR, we are still figuring the link logistics
- Observatorium onboarding link is most likely not the right one

Meta labels added to the project namespace manifests

---

kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml

Deploy ray operator and images on smaug jupyterhub
Related-to:
https://github.com/operate-first/support/issues/102
https://github.com/thoth-station/core/issues/311
https://github.com/thoth-station/core/issues/372
https://github.com/orgs/thoth-station/projects/37
This would get ray operator and image get deployed on smaug jupyterhub.

Deploy ray operator and images on smaug jupyterhub

---

kfdefs/overlays/osc/osc-cl2/jupyterhub/kfdef.yaml

This change will instruct ODH on osc-cl2 to intiate cuda image builds
which will produce GPU enabled Jupyterhub images, and display them in
the JH spawner.

Add cuda buildchain to osc-cl2 jupyterhub.

---

cluster-scope/base/core/namespaces/acme-operator/namespace.yaml

This PR is a quick fix to recent PR #1687 
The `op1st/docs` link for acme-operator had a scroll to [text fragment](https://chromestatus.com/feature/4733392803332096) attached to it. This PR removes that fragment
https://github.com/operate-first/apps/pull/1687#discussion_r829198891

Remove highlight-text fragment from docs link

---

kfdefs/base/jupyterhub/ray-odh-integration/ray-cluster-template-cm.yaml
kfdefs/base/jupyterhub/ray-odh-integration/ray-operator-deployment.yaml

Fix the execution directories for ray operator and node
Fixes:  ![entry_dir_ray](https://user-images.githubusercontent.com/14028058/158985868-79b4f7f1-fe4f-4e64-aa8a-ff22b1a5341a.png)
Related-to:
https://github.com/operate-first/support/issues/102
https://github.com/thoth-station/core/issues/311
https://github.com/thoth-station/core/issues/372
https://github.com/orgs/thoth-station/projects/37

Fix the execution directories for ray operator and node

---

pulp/overlays/moc/smaug/opf-pulp-backup.yaml

Fix the version typo for pulp backup
Related-to: https://github.com/operate-first/support/issues/525

Fix the version typo for pulp backup

---

argocd/overlays/moc-infra/projects/global_project.yaml

Include pulp backup and restore to be deployed via argocd
Fixes: 
Related-to: https://github.com/operate-first/support/issues/525

Include pulp backup and restore to be deployed via argocd

---

argocd/overlays/moc-infra/secrets/clusters/secret-generator.yaml

The secret is breaking the build, this is a quick fix. We should update the secret if we still need it and re-encrypt.

Remove invalid argocd cluster secret.

---

kfdefs/overlays/osc/osc-cl1/trino/configs/jvm-coordinator.config
kfdefs/overlays/osc/osc-cl1/trino/configs/jvm-worker.config
kfdefs/overlays/osc/osc-cl1/trino/configs/kustomization.yaml
kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml

Related to: https://github.com/operate-first/apps/pull/1721 but for `osc-cl1` instead of `osc-cl2`.

Update trino kfdef in osc-cl1 to ODH v1.1.2

---

kfdefs/overlays/osc/osc-cl1/jupyterhub/kfdef.yaml

This change will update the Jupyterhub kfdef to point to 'operate-first/odh-manifests' branch 'osc-cl1-v1.1.2' which will bump ODH version.
Related to: https://github.com/operate-first/apps/pull/1723
holding for `operate-first/odh-manifests` branch `osc-cl1-v1.1.2` being created.
/hold

Update jupyterhub kfdef to ODH v1.1.2 in osc-cl1

---

kfdefs/overlays/osc/osc-cl1/seldon/kfdef.yaml

Related to: https://github.com/operate-first/apps/pull/1724
Holding for `operate-first/odh-manifests` branch `osc-cl1-v1.1.2` to exist.
/hold

Update seldon kfdef to odh 1.1.2 in osc-cl1

---

kfdefs/overlays/osc/osc-cl2/jupyterhub/kfdef.yaml

Spark operator subscribed to via ODH is not compatible with OCP 4.9
As such it's blocking the upgrade to 4.9 for osc cluster from 4.8. It
does not seem like anyone is using this operator, so we are removing it.

Remove spark operator from osc-cl2 odh.

---

grafana/overlays/moc/smaug/dashboards/kustomization.yaml
grafana/overlays/moc/smaug/dashboards/pulp/kustomization.yaml
grafana/overlays/moc/smaug/dashboards/pulp/pulp-metrics.yaml

This is to add a `GrafanaDashboard` CR for the pulp metrics dashboard.
I was looking at https://github.com/thoth-station/pulp-metrics-exporter/issues/17#issuecomment-1031244059 and could not find the dashboard that is mentioned in that comment.
Looking at the instructions on https://github.com/thoth-station/thoth-application/tree/master/grafana-dashboard#create-new-dashboards I believe that steps 1 and 2 of dashboard creation (i.e. create a JSON file for the dashboard) were implemented in https://github.com/thoth-station/thoth-application/pull/2326, but step 3 (the grafana CR) is still missing. This PR is to add that.
I am not fully sure of the proper location for the dashboard, or if I missed something else.

[grafana] Add the pulp-metrics dashboard

---

cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/group.yaml

This PR is to add myself to the `octo-ushift-dev` group.
The main goal is to get access to the resources managed through ArgoCD for the `octo-ushift` project.
Context: I was trying to troubleshoot current sync problems between Argo and the microshift clusters involved in the octo summit demo, and I am missing part of the picture without that access.

Add myself to the microshift group

---

grafana/overlays/moc/smaug/blackbox-exporter/recording-rules.yaml
grafana/overlays/moc/smaug/blackbox-exporter/service-monitor.yaml

Adding operate first, thanos, trino, cloudbeaver to the service monitor to check the liveness probe with the help of blackbox exporter. Also, adding the recording rules for different periods of time (1h, 2h, and so on). Related to this issue: https://github.com/operate-first/operations/issues/444 and https://github.com/operate-first/apps/

Adding recording rules to blackbox exporter and adding more services to service monitor in blackbox

---

cluster-scope/base/operators.coreos.com/subscriptions/openshift-pipelines-operator-rh/subscription.yaml
cluster-scope/bundles/openshift-pipelines/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/subscriptions/openshift-pipelines-operator-rh_patch.yaml
cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml

Add oc pipelines to osc-cl2. This commit also bundles the manifests that
currently exist in the base dir and switches to bundle reference in the
smaug cluster as well. No change to live deployment to the smaug cluster
is introduced here. The patch for the subscription was removed since the
channel remains the same for both clusters, it just adds an unecessary
step otherwise.

Add oc pipelines as a bundle to os-cl2.

---

argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kfp-tekton.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
kfp-tekton/overlays/osc/osc-cl2/kustomization.yaml
kfp-tekton/overlays/osc/osc-cl2/params.yaml
kfp-tekton/overlays/osc/osc-cl2/secret-generator.yaml
kfp-tekton/overlays/osc/osc-cl2/secrets/mlpipeline-ceph-artifact.enc.yaml

This emulates the kfp-tekton deployment from smaug onto osc-cl2.
The bucket being used is one created in the smaug cluster via odf. Once confirmed working we can switch to a more permanent solution.

Add kfp-tekton app to osc-cl2.

---

argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/k8s-annotations-exporter.yaml
argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/emea/morty/operate-first/k8s-annotations-exporter.yaml
argocd/overlays/moc-infra/applications/envs/emea/morty/operate-first/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/moc/infra/operate-first/k8s-annotations-exporter.yaml
argocd/overlays/moc-infra/applications/envs/moc/infra/operate-first/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/k8s-annotations-exporter.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-reader-k8s-annotations-exporter/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-reader-k8s-annotations-exporter/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
cluster-scope/overlays/prod/emea/morty/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
k8s-annotations-exporter/base/deployment.yaml
k8s-annotations-exporter/base/kustomization.yaml
k8s-annotations-exporter/base/service.yaml
k8s-annotations-exporter/base/serviceaccount.yaml
k8s-annotations-exporter/base/servicemonitor.yaml
k8s-annotations-exporter/overlays/emea/balrog/kustomization.yaml
k8s-annotations-exporter/overlays/emea/morty/kustomization.yaml
k8s-annotations-exporter/overlays/moc/infra/kustomization.yaml
k8s-annotations-exporter/overlays/moc/smaug/kustomization.yaml

This will deploy the [k8s-annotations-exporter](https://github.com/4n4nd/k8s-annotations-exporter) app on Smaug, Infra, Balrog and Morty clusters.
Resolves https://github.com/operate-first/apps/issues/1780

Add k8s annotations exporter app 

---

kfp-tekton/overlays/osc/osc-cl2/secret-generator.yaml
kfp-tekton/overlays/osc/osc-cl2/secrets/mlpipeline-minio-artifact.enc.yaml

The copy artifact archival step in kfp-tekton requires the existence of
this secret. For more details read the description annotation included
in this commit. Description is added as an annotation since sops will
purge yaml comments upon encryption/decryption.

Add minio artifact secret to osc-cl2 kfptekton.

---

cluster-scope/base/user.openshift.io/groups/sre/group.yaml

Mainn is working on some openshift integration for the MOC and the NERC and
needs read-access to a running cluster just to explore metrics and other
aspects.

Add tzumainn to sre group

---

cluster-scope/base/core/namespaces/aicoe-meteor/namespace.yaml
cluster-scope/base/core/namespaces/boatrockers/namespace.yaml
cluster-scope/base/core/namespaces/chrisproject/namespace.yaml
cluster-scope/base/core/namespaces/curator-engine/namespace.yaml

As per recent PR #1784 , 15 namespaces have been given meta-labels to be displayed in the Workload Overview dashboard. This PR adds missing `openshift.io/display-name` tag to namespaces that didn't have one

Added missing display names to Namespace manifests

---

cluster-scope/base/user.openshift.io/groups/grafana-viewer/group.yaml
cluster-scope/base/user.openshift.io/groups/grafana-viewer/kustomization.yaml
grafana/overlays/moc/smaug/grafana-oauth.yaml

Related to slack conversation in `operate-first#support` channel. Creating `grafana-viewer` group and adding viewer permissions on the grafana-oauth for smaug overlay.
/cc @HumairAK

creating grafana-viewer group and adding to smaug grafana oauth

---

kfdefs/overlays/moc/smaug/opf-dashboard/kfdef.yaml
kfdefs/overlays/moc/smaug/opf-dashboard/kustomization.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/kfdef.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/servicemonitor.yaml
kfdefs/overlays/moc/smaug/opf-seldon/kfdef.yaml
kfdefs/overlays/moc/smaug/opf-seldon/kustomization.yaml
kfdefs/overlays/moc/smaug/opf-superset/kfdef.yaml
kfdefs/overlays/moc/smaug/opf-superset/kustomization.yaml
kfdefs/overlays/moc/smaug/opf-trino/kfdef.yaml
kfdefs/overlays/moc/smaug/opf-trino/kustomization.yaml

Removed old kfdefs for smaug, as they have been migrated instead to operate-first/odh-manifests. 
Updating the kfdef overlay for smaug to include the kfdefs themselves and any supporting manifests.
Modifying the kfdefs directly rather than patching them with kustomization now that they live in the same overlay.
Related to: https://github.com/operate-first/odh-manifests/pull/7
Addresses: #1745 
/cc @HumairAK @4n4nd

pointing kfdefs to odh-manifests migration

---

.github/sync.yml
.github/workflows/sync.yml

This will enable automated syncs via gh actions whenever a notebook is
updated. This is because we can only configure one image build per repo,
and it does not make sense to dedicate the apps repo for a notebook
image build. So instead we'll have a separate repo where we initiate our
builds from, and this action will ensure that while notebooks can be
committed to this repo, they will continue to initiate new image builds
by auto syncing with the build repository.
Alternative to: https://github.com/operate-first/apps/pull/1446

Add auto sync of notebooks to hitchhiker repo.

---

.github/sync.yml

As per: https://github.com/marketplace/actions/repo-file-sync-action#sync-entire-directories

Fix typo in sync action.

---

grafana/overlays/moc/smaug/blackbox-exporter/service-monitor.yaml

This commit adds the opf-instance label in the service monitor of blackbox in the smaug cluster. Re: https://github.com/operate-first/operations/issues/444

adding opf-instance label in blackbox-service monitor

---

kfdefs/overlays/moc/smaug/kustomization.yaml

Part of: https://github.com/operate-first/apps/pull/1675
Breaking build of kfdef app: 
```
rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build /tmp/https___github.com_operate-first_apps/kfdefs/overlays/moc/smaug --enable-alpha-plugins` failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from 'opf-kafka': evalsymlink failure on '/tmp/https___github.com_operate-first_apps/kfdefs/overlays/moc/smaug/opf-kafka' : lstat /tmp/https___github.com_operate-first_apps/kfdefs/overlays/moc/smaug/opf-kafka: no such file or directory': evalsymlink failure on '/tmp/https___github.com_operate-first_apps/kfdefs/overlays/moc/smaug/opf-kafka' : lstat /tmp/https___github.com_operate-first_apps/kfdefs/overlays/moc/smaug/opf-kafka: no …
```

Remove opf-kafka from smaug kfdef root kustomization.

---

kfdefs/overlays/dev/kustomization.yaml

Related to: https://github.com/operate-first/apps/pull/1675
/cc @HumairAK

removing opf-kafka from dev kfdefs overlay

---

vault/base/statefulsets/statefulset.yaml

Some of the volume claim templates got cut off at some point causing the vault deployment to fail in smaug. I've added the necessary volume claim templates so that the deployment should complete successfully.

Fixing vault statefulset.yaml to include missing volume claims

---

kfdefs/overlays/moc/smaug/opf-jupyterhub/kfdef.yaml

kfdef is missing the repo ref for this entry.

Add reporef to smaug jh kfdef.

---

argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/reloader.yaml
cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
reloader/overlays/osc/osc-cl2/kustomization.yaml

In response to #1778 adding reloader deployment to osc-cl2 cluster to track trino pods.

add: Reloader deployment to osc-cl2 cluster

---

cluster-scope/base/core/namespaces/vault/resourcequota.yaml
vault/base/statefulsets/statefulset.yaml

I didn't account for the deployment being HA so I did not designate enough storage in the resource quota initially. I've also scaled down the volume claims a bit.

adjust vault pod volume claims and namespace resource quota

---

cluster-scope/bundles/opf-monitoring/grafana-serviceaccount.yaml
cluster-scope/bundles/opf-monitoring/kustomization.yaml
cluster-scope/overlays/prod/common/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
cluster-scope/overlays/prod/emea/morty/kustomization.yaml
cluster-scope/overlays/prod/emea/rick/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Add opf-monitoring bundle to the common cluster directory
this `grafana-serviceaccount` will be given privileges to access the openshift-monitoring prometheus

Add opf-monitoring cluster-scope bundle

---

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/opf-monitoring-grafana-cluster-view/clusterrolebinding.yaml

Upgrade api version for grafana viewer crb.

---

cluster-scope/overlays/prod/emea/morty/kustomization.yaml

This is a leftover from a previous pr where we switched over to using
identitatem to manage auth for morty cluster. #1835

Remove oauth base resource from morty cluster.

---

acm/overlays/moc/infra/identitatem/authrealms/primary.yaml

We found that using the "claim" mapping method results in user identity
conflicts. Instead we'll use the "add" method which allows for the
mapping of a username to any existing user on the cluster.
Further reading: 
https://docs.openshift.com/container-platform/4.7/authentication/understanding-identity-provider.html#identity-provider-parameters_understanding-identity-provider

Update mapping method for idp authrealm.

---

cluster-logging/base/kustomization.yaml
cluster-logging/base/rolebindings/kustomization.yaml
cluster-logging/base/rolebindings/prometheus-k8s.yaml
cluster-logging/base/roles/kustomization.yaml
cluster-logging/base/roles/prometheus-k8s.yaml

Resolves https://github.com/operate-first/apps/issues/1355
The role `prometheus-k8s` is a general role that has been copied from other namespaces which `openshift-monitoring` can monitor

Add role/rolebind for cluster-monitoring prom to see openshift-logging namespace

---

kfdefs/overlays/moc/smaug/opf-jupyterhub/alerts.yaml

Introducing burn rate based alerts for JupyterHub in the Smaug Cluster. Related: operate-first/operations#444

Adding burn rate based alerts for JupyterHub in Smaug cluster

---

grafana/overlays/moc/smaug/blackbox-exporter/service-monitor.yaml
kfdefs/overlays/moc/smaug/opf-jupyterhub/alerts.yaml

`opf-instance` is not a valid label name and is being replaced  by `opf-instance`
This is because `-` is not an accepted character, it needs to be replaced with `_`

fix `opf_instance` label in Jupyterhub alerts and blackbox servicemonitor

---

argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/opf-kafka.yaml
cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
kafka/overlays/balrog/kafka-podmonitors.yaml
kafka/overlays/balrog/kustomization.yaml
kafka/overlays/balrog/opf-kafdrop.yaml
kafka/overlays/balrog/topics/kustomization.yaml
kafka/overlays/balrog/topics/thoth-advise-justification.yaml
kafka/overlays/balrog/topics/thoth-adviser-trigger.yaml
kafka/overlays/balrog/topics/thoth-build-analysis-trigger.yaml
kafka/overlays/balrog/topics/thoth-cve-provided.yaml
kafka/overlays/balrog/topics/thoth-hash-mismatch.yaml
kafka/overlays/balrog/topics/thoth-kebechet-run-url.yaml
kafka/overlays/balrog/topics/thoth-kebechet-trigger.yaml
kafka/overlays/balrog/topics/thoth-missing-package-version.yaml
kafka/overlays/balrog/topics/thoth-missing-package.yaml
kafka/overlays/balrog/topics/thoth-package-extract-trigger.yaml
kafka/overlays/balrog/topics/thoth-package-released.yaml
kafka/overlays/balrog/topics/thoth-provenance-checker-trigger.yaml
kafka/overlays/balrog/topics/thoth-qebhwt-trigger.yaml
kafka/overlays/balrog/topics/thoth-si-unanalyzed-package.yaml
kafka/overlays/balrog/topics/thoth-solved-package.yaml
kafka/overlays/balrog/topics/thoth-unresolved-package.yaml
kafka/overlays/balrog/topics/thoth-unrevsolved-package.yaml
kafka/overlays/balrog/topics/thoth-update-provides-source-distro.yaml
kafka/overlays/balrog/users/kustomization.yaml
kafka/overlays/balrog/users/thoth.yaml

manage the kafka for balrog cluster via operate-first
- Reduced the resource for opf-kafka, as it not being to its capacity as of now.
- set all the manifest for kafka w.r.t balrog setup

manage the kafka for balrog cluster via operate-first

---

.pre-commit-config.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/training-operator.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mpijobs.kubeflow.org/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mpijobs.kubeflow.org/kustomization.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mxjobs.kubeflow.org/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mxjobs.kubeflow.org/kustomization.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/pytorchjobs.kubeflow.org/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/pytorchjobs.kubeflow.org/kustomization.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/tfjobs.kubeflow.org/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/tfjobs.kubeflow.org/kustomization.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/xgboostjobs.kubeflow.org/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/xgboostjobs.kubeflow.org/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/training-operator/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/training-operator/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/training-operator/clusterrole.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/training-operator/kustomization.yaml
cluster-scope/bundles/training-operator/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
training-operator/base/deployment.yaml
training-operator/base/kustomization.yaml
training-operator/base/service.yaml
training-operator/base/serviceaccount.yaml
training-operator/overlays/osc/osc-cl1/kustomization.yaml

Adds various crds/rbac to cluster-scope base folder, and also adds a new
argocd app to deploy the training operator onto the osc-cl1 cluster.
One of the crds was over default "large file" size limit set by the
"check-added-large-files" hook, so I increased this maximum to 600kb.
Related: https://github.com/operate-first/support/issues/537

Add training operator.

---

kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties

The default query.max-length=1000000.  For datasets such as SEC_DERA, the 1M limit allows for approx 1500 rows per insertion.  When there are millions of rows, this not only creates thousands of snapshots, but each snapshot file also references the chain of snapshots, growing these files from a few K to several MB per snapshot.
By increasing the max-length parameter to 10M, we not only cut down the number of objects in the metastore, but we also decrease the number of snapshots each of these objects needs to reference, reducing storage requirements by a factor of 100 (10*10).

Set query.max-length=10M (overriding 1M default)

---

kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties

This reverts commit 56e3a56c7d1e3c4411260a82943ede20e6c57fb8.
Resolve: 
https://github.com/operate-first/operations/issues/466

Revert "Set query.max-length=10M (overriding 1M default) (#1883)"

---

grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-storage-overview.yaml

With this PR we'll now have a more detailed and *enhanced* Cluster Storage Overview Dashboard
**New Panels/Content**
- Percentage of Free space left on cluster
- PV space metrics (Used, Available, and Capacity in the context of space)
- Bar gauge which displays space remaining
- PV Count metrics, number of PVs (for all clusters)
- Table of 20 worst PVCs by capacity remaining (per cluster)
- Top 20 namespaces by file system usage 
*Previous Version*
*New Version*
All comments and feedback is greatly appreciated!

Added enhanced Cluster Storage Overview Dashboard

---

kfdefs/overlays/osc/osc-cl2/trino/configs/config-coordinator.properties
kfdefs/overlays/osc/osc-cl2/trino/configs/config-worker.properties

Per guidance from Trino slack channel:
"Everything unless mentioned needs to be set in both coordinators and workers. Only things like security configs and global system level things (like overall cluster memory) are required only on coordinator."

Set query.max-length=10M in correct files

---

kfdefs/overlays/osc/osc-cl1/dashboard/kfdef.yaml
kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml

Related to: https://github.com/open-services-group/byon/issues/20
Requires: https://github.com/operate-first/odh-manifests/pull/19
- Deploying ODH Dashboard to `jupyterhub-stage`: Upstream of ODH Dashboard has no notion of namespaces and treats everything like it's in the same namespace, that means BYON pipelines needs to live in the same namespace as JupyterHub and Dashboard, that's the only way how Dashboard is able to trigger the pipelines and JH to see the resulting imagestreams.
- Reverting the `odh-dashboard` namespace to `v1.1.2` tag.
- Deploying BYON from JH overlay
/cc @harshad16

feat(osc-cl1): Fix BYON deployment

---

cluster-scope/base/core/namespaces/democratic-csi/namespace.yaml
cluster-scope/base/core/namespaces/fedora/namespace.yaml
cluster-scope/base/core/namespaces/fybrik-applications/namespace.yaml

This commit addresses the issue where some namespaces shown in the **Workload Overview dashboard** have an empty **project title**. This is fixed by adding `openshift.io/display-name` annotation to these namespaces

Added display-name to namespaces

---

argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/odh-operator.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/odh-operator.yaml
cluster-scope/bundles/opendatahub-operator-manual/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
odh-operator/overlays/osc/osc-cl1/kustomization.yaml
odh-operator/overlays/osc/osc-cl2/kustomization.yaml

In this cluster we have handed out project admin permissions to some
users so we are forced to remove odh from olm management due to security
reasons. Otherwise these users will be able to deploy kfdefs.

Switch to manual odh deploy on osc clusters.

---

cluster-scope/base/core/namespaces/multinode-demo/resourcequota.yaml

The pods deployed for the demo kept failing with OOMKilled message due to lack of sufficient resources. Increasing the resource quotas to address the issue.

Increasing resource limitations for the demo

---

kfdefs/overlays/moc/smaug/seldon/kustomization.yaml
kfdefs/overlays/moc/smaug/seldon/servicemonitor.yaml
kfdefs/overlays/moc/smaug/trino/kustomization.yaml
kfdefs/overlays/moc/smaug/trino/servicemonitor.yaml

Introducing the servicemonitors for Trino and Seldon that expose their metrics to prometheus. Re: https://github.com/operate-first/apps/issues/1677

Adding service monitors for Trino and seldon to expose their metrics to prometheus.

---

cluster-scope/base/operators.coreos.com/operatorgroups/b4mad-racing/kustomization.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/b4mad-racing/operatorgroup.yaml
cluster-scope/bundles/b4mad-racing/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

@4n4nd @HumairAK I'm trying to install a grafana instance in my namespace and would like to use the operator for that.
Are there any reasons for making it not cluster wide?

add grafana operator to b4mad-racing namespace

---

grafana/overlays/moc/smaug/grafana-oauth.yaml

This will prevent argocd and grafana-operator in smaug to fight over adding the instance label to `grafana-serviceaccount` in `opf-monitoring` namespace
A better fix would be to change the name of the serviceaccount being created in the opf-monitoring bundle, but because we are adding that bundle to all the clusters we manage, we would need to update credentials (oauth tokens) for all the renamed serviceaccounts. And this issue is seen only in smaug. So to save engineering effort I made this quick fix.

[Smaug][Grafana] Add instance label to grafana-serviceaccount smaug

---

pulp/overlays/moc/smaug/opf-pulp.yaml

upgrade pulp image pull policy to always
This is for having  upgrade of component whenever operator upgrades.

:recycle: upgrade pulp image pull policy to always

---

cluster-scope/base/core/namespaces/opf-ci-pipelines/namespace.yaml
cluster-scope/base/core/namespaces/opf-ci-prow/namespace.yaml
cluster-scope/base/core/namespaces/opf-pulp/namespace.yaml
cluster-scope/base/core/namespaces/thoth-amun-api-prod/namespace.yaml
cluster-scope/base/core/namespaces/thoth-amun-inspection-prod/namespace.yaml
cluster-scope/base/core/namespaces/thoth-backend-prod/namespace.yaml
cluster-scope/base/core/namespaces/thoth-bots-prod/namespace.yaml
cluster-scope/base/core/namespaces/thoth-deployment-examples/namespace.yaml
cluster-scope/base/core/namespaces/thoth-frontend-prod/namespace.yaml
cluster-scope/base/core/namespaces/thoth-graph-prod/namespace.yaml
cluster-scope/base/core/namespaces/thoth-infra-prod/namespace.yaml
cluster-scope/base/core/namespaces/thoth-middletier-prod/namespace.yaml

Include the following projects in workload website
- project thoth 
- opf-pulp
- opf-ci-prow
- opf-ci-pipelines

:city_sunrise: Include project thoth and opf-pulp on the opf workload website

---

acm/overlays/moc/infra/managedclusters/kustomization.yaml
acm/overlays/moc/infra/managedclusters/local-cluster.yaml
acm/overlays/moc/infra/managedclusters/rick.yaml

This should have been a part of commit
f8d52e7016bf85c09da97b374c017eba39342888.
See commit message for above for more details.
Corresponding PR: https://github.com/operate-first/apps/pull/1943
Note that `local-cluster` refers to infra.

Add cluster authprimary label to cur/infra/rick.

---

cluster-scope/overlays/prod/emea/rick/kustomization.yaml
cluster-scope/overlays/prod/moc/curator/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

This should have been a part of commit
f8d52e7.
See commit message for above for more details.

Remove oauths inherited from base for idp clusters

---

acm/overlays/moc/infra/managedclusters/kustomization.yaml
acm/overlays/moc/infra/managedclusters/local-cluster.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/oauth/clients/github.enc.yaml
cluster-scope/overlays/prod/moc/infra/oauth/clients/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/oauth/clients/secret-generator.yaml
cluster-scope/overlays/prod/moc/infra/oauth/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/oauth/oauth.yaml

Removing moc-infra from identitatem as it doesn't seem possible to use
it for the hub cluster. Moc-infra can be a special case for now where we
redirect directly from github back to moc infra.

Switch moc infra auth.

---

cluster-scope/overlays/prod/moc/infra/clusterrolebindings/klusteraddonconfig-editor.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

These permissions are needed for teams to be able to add clusters to
acm.
Part of: https://github.com/operate-first/apps/pull/1947

Add kluster addon config editor rolebinding.

---

cluster-scope/base/operators.coreos.com/subscriptions/external-secrets-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/external-secrets-operator/subscription.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Furthers: https://github.com/operate-first/support/issues/298
Adding external secrets operator to smaug for use with vault deployment

Adding external secrets operator subscription and deploying to smaug

---

cluster-scope/overlays/prod/moc/smaug/backingstores/noobaa-pool-01.yaml
cluster-scope/overlays/prod/moc/smaug/bucketclasses/noobaa-pool-01-bucket-class.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Create noobaa-pool-01 backing store with an initial 10 * 100GB allocation
(can grow up to 20 * 100GB). Include an associated BucketClass
(noobaa-pool-01-bucket-class) that can be used to place buckets on this
pool explicitly, e.g:
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
name: example-obc
spec:
generateBucketName: example-obc
storageClassName: openshift-storage.noobaa.io
additionalConfig:
bucketclass: noobaa-pool-01-bucket-class
Part of operate-first/operations#474

Add a second noobaa backing store and associated bucketclass

---

kfdefs/overlays/osc/osc-cl2/trino/configs/config-coordinator.properties
kfdefs/overlays/osc/osc-cl2/trino/configs/config-worker.properties
kfdefs/overlays/osc/osc-cl2/trino/secrets/secret-generator.yaml
kfdefs/overlays/osc/osc-cl2/trino/secrets/shared-secret.yaml

The osc-cl2 trino update to v380 required a shared secret to be shared
between all nodes on the trino cluster. This commit adds this secret for
the deployments for both coordinator and worker nodes to leverage.
Related: 
- https://github.com/operate-first/odh-manifests/pull/23
- https://github.com/operate-first/odh-manifests/pull/22
Docs: 
https://trino.io/docs/current/security/internal-communication.html

Add shared secret to trino.

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/external-secrets.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml
cluster-scope/base/core/namespaces/external-secrets-operator/kustomization.yaml
cluster-scope/base/core/namespaces/external-secrets-operator/namespace.yaml
cluster-scope/bundles/external-secrets-operator/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
docs/_toc.yml
docs/content/external-secrets/README.md
docs/content/external-secrets/add_eso_to_cluster.md
external-secrets/base/eso.yaml
external-secrets/base/kustomization.yaml
external-secrets/overlay/moc/smaug/kustomization.yaml

This commit addes an operator config + namespace to the smaug cluster.
The addition will result in an instance of external secrets being
deployed and managed via argocd.

Add External Secrets instance to smaug.

---

cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/extensions.dashboard.tekton.dev/customresourcedefinition.yaml

Fix the crd of extension tekton dashboard
Fixes: https://github.com/operate-first/apps/issues/1936
The openshift-pipelines operator is not creating the dashboard CRD.
The CRD itself was added in the repo with label `app.kubernetes.io/instance: default` which is checked by agrocd for instance duplication.

Fix the crd of extension tekton dashboard

---

kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml
kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-operator-deployment.yaml

upgrade the ray jupyterhub instance with the latest ray
Description:
- Upgraded the image of the ray instance to get the latest ray 
- Changed the reference to the absolute path of imagestream instead of short-hand, as jupyterhub is not recognizing the short-hand https://github.com/harshad16/apps/blob/db9cec12bdc3a64d8229e506e96157004e008828/kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml#L12
This has been tested :heavy_check_mark:

upgrade the ray jupyterhub instance with latest ray

---

cluster-scope/overlays/prod/moc/smaug/bucketclasses/noobaa-default-bucket-class.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Rather than adding a new bucketclass, it makes more sense to add a new
backing store to the existing default bucket class. With a "Spread"
configuration [1], noobaa will start allocating space for existing buckets
from the new pool.
This removes the bucketclass created in 19f2b87566.
[1]: https://github.com/noobaa/noobaa-operator/blob/master/doc/bucket-class-crd.md

Add pool to default bucket class

---

cluster-scope/base/core/configmaps/openshift-pipelines-feature-flags/configmap.yaml

Fix the labels of cm feature flags and patch strategy
Related-to: https://github.com/operate-first/apps/issues/1958
- the cm feature flag is already installed via openshift pipeline operator https://github.com/tektoncd/pipeline/blob/main/config/config-feature-flags.yaml, it need to be patched
- the label instance is to be patched by the argocd

Fix the labels of cm feature flags

---

cluster-scope/overlays/prod/moc/smaug/externalsecrets/alert-manager.yaml
cluster-scope/overlays/prod/moc/smaug/secretstores/openshift-monitoring.yaml

This is to reflect some changes to how secrets are organized. Instead of
using multiple engines for each clusters, it makes more sense to use one
kv secrets engine and have subdirectories for each env/cluster.
Related: https://github.com/operate-first/apps/issues/1993

Change path for slack api url in smaug.

---

kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml

Update the ray worker and notebook to v0.2.0 version
update contains inclusion of following packages:
- ray[data]
- tensorflow
- pytorch

Update the ray worker and notebook to v0.2.0 version

---

cluster-scope/base/operators.coreos.com/catalogsources/rapidast/catalogsource.yaml
cluster-scope/base/operators.coreos.com/catalogsources/rapidast/kustomization.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/rapidast/kustomization.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/rapidast/operatorgroup.yaml
cluster-scope/base/operators.coreos.com/subscriptions/rapidast/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/rapidast/subscription.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Adds a catalog source, operator group, and subscription to deploy the RapiDAST operator to the smaug cluster.

Add resources needed to deploy rapidast-operator to smaug cluster

---

grafana/overlays/moc/smaug/grafana-oauth.yaml

Addresses: https://github.com/operate-first/apps/issues/2054
`serviceaccount` should be a part of spec: https://github.com/grafana-operator/grafana-operator/blob/master/documentation/deploy_grafana.md#configuring-the-serviceaccount
instead of part of `config`.

fixing grafana_oauth spec labels

---

cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/acme-operator/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/base/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/base/opf-vault-store.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/base/vault-secret-fetcher.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-config/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-ingress/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-logging/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-monitoring/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-user-workload-monitoring/kustomization.yaml
docs/content/vault_eso/add_external_secrets_to_ns.md

This furthers: #1996 
Trying it out for balrog first. This just adds secret stores, does not change any secrets yet. 
Keeping it in cluster-scope reduces a lot of repetition, and since it only requires that this be done once, it will make it easier to incorporate as part of onboarding in the future(when adding a new namespace) without having to create a separate project/app.

Add secret stores balrog cluster

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/service-catalog.yaml
argocd/overlays/moc-infra/projects/operate-first.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/service-catalog/kustomization.yaml
cluster-scope/base/operators.coreos.com/operatorgroups/service-catalog/operator-group.yaml
cluster-scope/base/operators.coreos.com/subscriptions/service-catalog/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/service-catalog/subscription.yaml
cluster-scope/bundles/service-catalog/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Part of #2036 
- Create ArgoCD app for service-catalog
- Create prostgres-db bundle required by the service-catalog
Right now blocked by [#2](https://github.com/operate-first/service-catalog/pull/2).

feat(service-catalog): Create ArgoCD app

---

cluster-scope/base/core/namespaces/service-catalog/kustomization.yaml

A bigger resource quota is needed for the `service-catalog` postgres operator.

fix(service-catalog): Increase resource quota

---

cluster-scope/overlays/prod/osc/osc-cl1/externalsecrets/api-certs.yaml
cluster-scope/overlays/prod/osc/osc-cl2/externalsecrets/api-certs.yaml

API certs get copied over by an external controller onto another secret
named "user-serving-cert-000", including the annotation that's added by
argocd to indicate a resource belongs to an argocd app. This results in
argocd wanting to prune this new secret that's created, because it
assumes this new copy used to be (and is no longer) part of this argocd
app. So we add these annotations to ignore sync of these certs in this
case. We also add an annotation to prevent argocd from reporting OOS
status when this specific secret is OOS, and thus prevent if from
entering an infinte cycle of synchronizations.

Disable argocd prune on osc api certs.

---

cluster-scope/base/core/namespaces/sostrades/kustomization.yaml
cluster-scope/base/core/namespaces/sostrades/limitrange.yaml
cluster-scope/base/core/namespaces/sostrades/namespace.yaml
cluster-scope/base/core/namespaces/sostrades/resourcequota.yaml
cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml

Pull request following the guide 'How to onboard a new project to a cluster on Operate First Cloud' to integrate SosTrades Project in Operate-first on os-cli2 cluster.
Sostrades Project is already in os-cli2 cluster but following discussion with Michel Tiemann, he advised us to migrate to the 2nd cluster made available for OS-Climate.
(sos-trades is a 6-repo contribution fromt Airbus for their "System of Systems" (SOS) platform. See https://github.com/os-climate/sostrades-core)
Here is a description of the project : SoSTrades is the tool used for the implementation of WITNESS or Transition Tool within OS-Climate. We plan to connect with Pysical risk and Data commons in the near future. SoSTrades is a web-based, multi-user, interactive publication-quality graph simulation platform. It …

feat(onboarding): Add team sostrades in os-cli2

---

cluster-scope/base/user.openshift.io/groups/operate-first/group.yaml

This is to add myself to the `operate-first` group.
The trigger was that I meant to take a closer look at the images(treams) available in Jupyterhub, but I believe this membership will help me in future tasks as well.

Add Pep to the operate-first group

---

cluster-scope/base/operators.coreos.com/subscriptions/minio-operator/subscription.yaml

The catalog source in the original PR was mis-spelled; the catalog name for
OperatorHub is `operatorhubio-catalog`, not `operathub.io-operators`.
However, it turns out that the `certified-operators` catalog has a more
recent version.

Fix minio operator source

---

cluster-scope/base/operators.coreos.com/subscriptions/strimzi-global-operator/kustomization.yaml
cluster-scope/base/operators.coreos.com/subscriptions/strimzi-global-operator/subscription.yaml
cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml

Existing subscription targeting specific namespace opf-kafka with associated quotas and settings. In some cases default configuration is more preferable. `strimzi-global-operator` subscription config will deploy operator to default namespace.
This PR is to address issue https://github.com/os-climate/os_c_data_commons/issues/160

Strimzi operator subscription targeting default openshift-operators ns  

---

grafana/overlays/moc/smaug/datasources/.sops.yaml
grafana/overlays/moc/smaug/datasources/grafanadatasource.enc.yaml

This addresses a broken encryption preventing kustomize builds for
grafana in smaug.

Reencrypt grafana datasource in smaug.

---

kfp-tekton/base/deployments/ml-pipeline.yaml
kfp-tekton/base/kustomization.yaml
kfp-tekton/base/secrets/mlpipeline-minio-artifact.yaml
kfp-tekton/overlays/moc/smaug/kustomization.yaml
kfp-tekton/overlays/moc/smaug/params.yaml
kfp-tekton/overlays/moc/smaug/secrets/mlpipeline-minio-artifact.enc.yaml
kfp-tekton/overlays/osc/osc-cl2/kustomization.yaml
kfp-tekton/overlays/osc/osc-cl2/params.yaml
kfp-tekton/overlays/osc/osc-cl2/secrets/mlpipeline-minio-artifact.enc.yaml

Mlpipeline seems like it hardcodes the secret used for artifact passing
as shown here: https://github.com/kubeflow/kfp-tekton/blob/v1.2.1/backend/src/apiserver/template/tekton_template.go#L319
As such we must update the original "mlpipeline-minio-artificat" secret.
In this change we manually add the secret itself as whole in the overlay
without patching it instead.
Related: https://github.com/operate-first/community/issues/206

Fix artifact passing in kfp on osc-cl2 & smaug.

---

service-catalog/components/argo.yaml
service-catalog/components/dex.yaml
service-catalog/components/grafana.yaml
service-catalog/components/observatorium.yaml
service-catalog/components/odf.yaml
service-catalog/components/odh.yaml

Resolves [#44](https://github.com/operate-first/service-catalog/issues/44)
I am not sure whether to put `opearate-first/apps` in the `odh` component, since ArgoCD plugin references this repo, or leave it like this using `opendatahub-io/odh-manifests`.

feat(service-catalog): Add github slugs to components

---

service-catalog/all-components.yaml
service-catalog/components/peribolos-as-a-service.yaml
service-catalog/components/probot-extensions.yaml

Part of [#25](https://github.com/operate-first/service-catalog/issues/25)
Add two components to the service catalog:
- `Peribolos-as-a-service`
- `Probot-extensions`
A dependency is added:
- `Peribolos-as-a-service` is dependent on `Probot-extensions`
Add tags for `Peribolos-as-a-service` to show which probot extensions it is using.

feat(service-catalog): Add peribolos-as-a-service and probot-extensions to service catalog

---

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-k8s-plugin/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-k8s-plugin/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin/clusterrole.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Part of [#12](https://github.com/operate-first/service-catalog/issues/12)
Backstage k8s plugin requires `clusterrole` for proper functionality. See docs [here](https://backstage.io/docs/features/kubernetes/configuration#role-based-access-control).

feat(service-catalog): Add clusterrolebinding and clusterrole required for k8s plugin in backstage

---

cluster-scope/base/core/namespaces/kafka/kustomization.yaml
cluster-scope/base/core/namespaces/kafka/namespace.yaml
cluster-scope/base/core/namespaces/openshift-operators/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/strimzi-aggregate-to-admin/clusterrole.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/strimzi-aggregate-to-admin/kustomization.yaml
cluster-scope/base/user.openshift.io/groups/kafka-admins/group.yaml
cluster-scope/base/user.openshift.io/groups/kafka-admins/kustomization.yaml
cluster-scope/base/user.openshift.io/groups/openshift-operators-admin/group.yaml
cluster-scope/base/user.openshift.io/groups/openshift-operators-admin/kustomization.yaml
cluster-scope/base/user.openshift.io/groups/openshift-operators-view/group.yaml
cluster-scope/base/user.openshift.io/groups/openshift-operators-view/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/kafka-admins/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/kafka-admins/rbac.yaml
cluster-scope/components/project-admin-rolebindings/openshift-operators-admin/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/openshift-operators-admin/rbac.yaml
cluster-scope/components/project-view-rolebindings/openshift-operators-view/kustomization.yaml
cluster-scope/components/project-view-rolebindings/openshift-operators-view/rbac.yaml
cluster-scope/overlays/prod/osc/osc-cl2/groups/kafka-admins.yaml
cluster-scope/overlays/prod/osc/osc-cl2/groups/openshift-operators-admin.yaml
cluster-scope/overlays/prod/osc/osc-cl2/groups/openshift-operators-view.yaml
cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
kafka/overlays/osc/osc-cl2/kustomization.yaml

The PR allows for a role in osc-cl2 that will grant all project admins
the ability to create kafka resources in any namespace they have project
admin in. It also allows for a view/admin group, wherein if a user is
added, they have view/admin permissions to openshift-operators
namespace respectively.
These roles are added to base so they may be used elsewhere going
forward.
The commit also sets up kafka structure for osc-cl2 for future
manifests.
Furthers: https://github.com/os-climate/os_c_data_commons/issues/191 
closes: https://github.com/operate-first/support/issues/613

Add project admin and view options for strimzi.

---

cluster-scope/base/user.openshift.io/groups/osc-admins/group.yaml
cluster-scope/overlays/prod/moc/smaug/groups/vault-osc-admins.yaml
cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml

Ryan (rynofinn) and I (mightynerderic) have joined the team on
behalf of the Linux Foundation.
Please see operate-first/operations#488
Signed-off-by: Eric Ball <eball@linuxfoundation.org>

Add Eric Ball and Ryan Day to OSC and Smaug admin

---

workshops/aiops-tools/base/acme-operator/issuer-letsencrypt-live.yaml
workshops/aiops-tools/base/acme-operator/kustomization.yaml
workshops/aiops-tools/base/administration/namespace/kustomization.yaml
workshops/aiops-tools/base/administration/rbac/kustomization.yaml
workshops/aiops-tools/base/cloudbeaver/kustomization.yaml
workshops/aiops-tools/base/kfp-tekton/kustomization.yaml
workshops/aiops-tools/base/minio/deployment.yaml
workshops/aiops-tools/base/minio/kustomization.yaml
workshops/aiops-tools/base/minio/minio.yaml
workshops/aiops-tools/base/minio/pvc.yaml
workshops/aiops-tools/base/minio/svc.yaml
workshops/aiops-tools/base/odh-kfdefs/kustomization.yaml
workshops/aiops-tools/base/odh-operator/kustomization.yaml
workshops/aiops-tools/base/openshift-pipelines/kustomization.yaml
workshops/aiops-tools/smaug/configmaps/kustomization.yaml
workshops/aiops-tools/smaug/externalsecrets/kustomization.yaml
workshops/aiops-tools/smaug/kustomization.yaml
workshops/aiops-tools/smaug/patches/cb_resources_patch.yaml
workshops/aiops-tools/smaug/patches/dex-clients_patch.yaml

As per title. 
Minio deployment added as a soft dependency. Namespaces updated as kubeflow needs to be deployed within the kubeflow namespace, so each component has their namespace specified separately, rather than together in the overlay.

Adjust aiops tools namespaces and add minio.

---

observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml

Followed steps from [documentation](https://github.com/operate-first/apps/blob/master/docs/content/observatorium/thanos/request_thanos_access.md) to request access for @SuJingyu111 to view thanos metrics.
/CC @HumairAK

adding scsaol group to opf-observatorium-view rolebinding

---

cluster-scope/base/core/serviceaccounts/schemastore-ci/kustomization.yaml
cluster-scope/base/core/serviceaccounts/schemastore-ci/serviceaccount.yaml
cluster-scope/overlays/prod/common/kustomization.yaml

This PR creates schema-store service account and adds it to `common` so that it is accessible in all clusters. This service account is needed for `schema-store` cronjob to be able to access `/openapi/v2` endpoints and update schemas of CRDs.
Part of https://github.com/open-services-group/scrum/issues/19 and https://github.com/open-services-group/scrum/issues/6

feat(schema-store):  Add service account for schema store

---

kfdefs/overlays/moc/smaug/seldon/alerts.yaml
kfdefs/overlays/moc/smaug/seldon/kustomization.yaml
kfdefs/overlays/moc/smaug/seldon/seldon-servicemonitor.yaml
kfdefs/overlays/moc/smaug/trino/alerts.yaml
kfdefs/overlays/moc/smaug/trino/kustomization.yaml

Added Container memory, CPU and UP alerts and configured service monitor for seldon. 
[https://github.com/operate-first/apps/issues/1677](url). 
CPU alert [https://github.com/google/cadvisor/issues/2026](url).

Configured alerts for Seldon and Trino 

---

cluster-scope/base/core/namespaces/openmetadata/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/openmetadata-admins/kustomization.yaml
cluster-scope/components/project-admin-rolebindings/openmetadata-admins/rbac.yaml
cluster-scope/overlays/prod/osc/osc-cl2/groups/openmetadata-admins.yaml
openmetadata/base/openmetadata-dependencies/persistentvolumeclaims/airflow-logs.yaml

Allowing group openmetada-admins access to the openmetadata namespace on OS-Climate cluster osc-cl2. Increased pvc size for airflow logs to 5Gi in the same namespace . Latter related to https://github.com/operate-first/operations/issues/489

Add openmetadata-admins group to the openmetadata namespace

---

cluster-scope/overlays/prod/emea/morty/groups/cluster-admins.yaml

I need cluster admin access to view secrets in the `openshift-monitoring` namespace on morty to debug why loki on other clusters cannot connect to S3 on morty.
/cc @HumairAK

adding myself to morty cluster admins and removing 4n4nd

---

argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/kustomization.yaml

Currently we put all argocd apps under the osc argocd project. This was
done to allow some separate between osc argocd apps, and the other
argocd apps deployed within the operate-first cloud. This was useful for
provisioning access to only osc argocd project. But we now have a
situation where we have an existing argocd project (fybrik), that we
would like to leverage for fybrik apps deployed on osc-cl2. So for now
we will make an exception and have fybrik apps within argocd be under
the fybrik argocd project until a more robust structure/format is found.

Adjust osc-cl2 argocd project structure.

---

kfdefs/overlays/osc/osc-cl2/trino/secrets/s3buckets.yaml

The accesskey/bucket name values were switched for hive ingest catalog, this commit corrects that.

Correct s3 hive ingest keys for osc-cl2.

---

kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml

Declares the new catalog: `osc_datacommons_hive_ingest`, and a dedicated schema `ingest` intended for use with the osc-ingest-tools method `fast_pandas_ingest_via_hive`
also declares a privileged user group `hive_ingest` that has access to this schema.

hive "ingest" schema on CL2

---

prow/overlays/smaug/imagestreamtags.yaml
prow/update-imagestreams.py

Empty annotation is causing issue in argo sync

:recycle: Empty annotation is causing issue in argo sync

---

prow/overlays/smaug/config.yaml

The [periodic prow jobs](https://prow.operate-first.cloud/?type=periodic) for issue lifecycle management are currently failing with:
``` json
{
"component": "entrypoint",
"error": "could not start the process: fork/exec /app/robots/commenter/app.binary: no such file or directory",
"file": "prow/entrypoint/run.go:80",
"func": "k8s.io/test-infra/prow/entrypoint.Options.Run",
"level": "error",
"msg": "Error executing test process",
"severity": "error",
"time": "2022-08-17T06:56:09Z"
}
```
The entry point for the images [changed on February 22nd, 2022](https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md#breaking-changes). This PR updates the path to the command based on the announcement.

[prow] Fix command path for prow commenter image

---

cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml

This is to add myself to the `odh-admin` group, with the goal of getting access to the osc cluster 1 to use it for CD for the ODH CNBi functionality.
Also taking the opportunity to sort the user list in that group alphabetically.
It seems that #2248 did not have the effect I expected - I modified a different odh-admin group there. Let me know if I should revert that change, thanks.

Add pep to osc-cl1 odh-admin group

---

slack-first/base/deployment.yaml

Quick PR. This adds the annotation for using reloader to watch the `slack-first` configmap, which we discovered should be done when updating the operator to use a daily schedule. It should be noted that this change will need to be synced manually in argocd the first time.
/cc @HumairAK

add reloader annotation to slack first operator

---

cluster-scope/base/apps/daemonsets/kvm-device-plugin/daemonset.yaml

/cc @HumairAK
I'm not sure how many nodes there are in `smaug`, but I think we can try requesting only 100m CPU for the kvm-device-plugin container.

Specify resource limits and requests on kvm-device-plugin containers in DS

---

prow/overlays/smaug/config.yaml
prow/overlays/smaug/secrets.enc.yaml

Switch to morty obc for temp fix.
Fixes: https://github.com/operate-first/support/issues/615
Related-to: https://github.com/operate-first/apps/issues/2064
- Move obc to morty.
- Removed private repo for the fix of branch protection.

:recycle: Switch to morty obc for temp fix.

---

acm/overlays/moc/infra/managedclusters/jerry.yaml
acm/overlays/moc/infra/managedclusters/kustomization.yaml

I added jerry to ACM via the ACM web ui and it successfully got imported.
Now following https://www.operate-first.cloud/apps/content/notebooks/onboarding_new_cluster.html#enable-argocd-management-in-acm
Not sure what this does. 🤷 
@HumairAK @tumido can you explain why we need to add it here too? Is this just for state keeping?

adding jerry to acm managedclusters

---

cluster-scope/overlays/prod/moc/infra/clusterversion.yaml

Part one of upgrade path.
Partially Addresses: https://github.com/operate-first/apps/issues/2270
Full upgrade path: 4.8.13 (stable-4.8) --> 4.8.47 (stable-4.8) --> 4.9.45 (stable-4.9) --> 4.10.26 (stable-4.10)
/cc @HumairAK

upgrading openshift on infra cluster to version 4.8.47

---

cluster-scope/overlays/prod/moc/infra/clusterversion.yaml

Part two of upgrade path.
Partially Addresses: https://github.com/operate-first/apps/issues/2270
Full upgrade path: 4.8.13 (stable-4.8) --> 4.8.47 (stable-4.8) --> 4.9.45 (stable-4.9) --> 4.10.26 (stable-4.10)
/cc @HumairAK

upgrading openshift on infra cluster to version 4.9.45

---

cluster-scope/overlays/prod/moc/infra/clusterversion.yaml

Part three of upgrade path.
Partially Addresses: https://github.com/operate-first/apps/issues/2270
Full upgrade path: 4.8.13 (stable-4.8) --> 4.8.47 (stable-4.8) --> 4.9.45 (stable-4.9) --> 4.10.26 (stable-4.10)
/cc @HumairAK

upgrading openshift on infra cluster to version 4.10.26

---

.prow.yaml

Temporarily addresses: https://github.com/operate-first/apps/issues/2288
/cc @HumairAK 
/cc @mimotej

doubling kubeval check memory limits and requires

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/cluster-resources.yaml

This is to ignore the image value change when OCP replaces it with the registry path. For context it's [this resource](https://github.com/operate-first/apps/blob/master/cluster-scope/base/apps/daemonsets/kvm-device-plugin/daemonset.yaml#L32).

Exclude kvm daemonset img field in argocd app.

---

cluster-scope/base/security.openshift.io/securitycontextconstraints/kepler-scc/securitycontextconstraints.yaml

Argocd seems to really not want to work with ocp's ordering on this:

Roeorder volumes in kepler scc.

---

cluster-scope/overlays/prod/moc/infra/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/subscriptions/web-terminal_patch.yaml

Web terminal is already present on Infra cluster, but it's manifests are not tracked... (How come?)
This PR:
1. adds the manifests to this repo
2. changes install approval to `Automatic`
3. changes `alpha` channel to the only currently available `fast` one.
Resolves https://github.com/operate-first/operations/issues/495

fix: Add web terminal already present on infra and change to Automatic

---

cluster-scope/base/rbac.authorization.k8s.io/rolebindings/kvm-device-plugin/rolebinding.yaml

I'm guessing this will resolve: https://github.com/operate-first/apps/issues/2305

Correct apigroup for kvm device plugin rbac.

---

kepler/base/service.yaml

Otherwise the service does not work, at least not on morty.

Remove none cluster ip for kepler.

---

argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/grafana.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
cluster-scope/base/user.openshift.io/groups/grafana-admin/group.yaml
cluster-scope/base/user.openshift.io/groups/grafana-admin/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/groups/grafana-admin.yaml
cluster-scope/overlays/prod/osc/osc-cl1/groups/grafana-editor.yaml
cluster-scope/overlays/prod/osc/osc-cl1/groups/grafana-viewer.yaml
cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl2/groups/grafana-admin.yaml
cluster-scope/overlays/prod/osc/osc-cl2/groups/grafana-editor.yaml
cluster-scope/overlays/prod/osc/osc-cl2/groups/grafana-viewer.yaml
cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
dex/overlays/osc/osc-cl1/configmaps/files/config.yaml
dex/overlays/osc/osc-cl2/configmaps/files/config.yaml
grafana/base/grafana-route.yaml
grafana/overlays/moc/smaug/route_patch.yaml
grafana/overlays/osc/osc-cl1/dashboards/kepler/kepler.yaml
grafana/overlays/osc/osc-cl1/dashboards/kepler/kustomization.yaml
grafana/overlays/osc/osc-cl1/dashboards/kustomization.yaml
grafana/overlays/osc/osc-cl1/datasources/grafanadatasource.yaml
grafana/overlays/osc/osc-cl1/externalsecrets/grafana-secret-config.yaml
grafana/overlays/osc/osc-cl1/externalsecrets/kustomization.yaml
grafana/overlays/osc/osc-cl1/grafana_oauth_patch.yaml
grafana/overlays/osc/osc-cl1/kustomization.yaml
grafana/overlays/osc/osc-cl1/landingpage.yaml

This PR deploys grafana operator to osc-cl1 and osc-cl2 clusters. It
also setups up a grafana instance in osc-cl1, with a datasource backed
by openshift-monitoring prometheus instance. It also has a basic landing
page and the kepler dashboards starting out.
Related:
* https://github.com/os-climate/os_c_data_commons/issues/190
* https://github.com/operate-first/apps/pull/1841
* https://github.com/operate-first/support/issues/502

Add grafana operator to osc, and grafana to osccl1

---

kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/kustomization.yaml
kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/trino-secret-env.yaml

Adding an external secret where we can provision secrets for trino configurations using `${ENV:SECRET_ENV_VAR}` to inject them, via Vault

add trino-secret-env

---

.prow.yaml

Trying to solve https://github.com/operate-first/apps/pull/2273#issuecomment-1230027023
Make Prow skip `kubeval`/`kustomize build` on:
- `docs/` changes
- Markdown changes
- `OWNERS` changes
- `LICENSE` changes
- Files in repo root starting with `.` like `.prow.yaml`, `.pre-commit-config.yaml` etc.

chore: Set prow to skip yaml checks on docs/aux files

---

grafana/overlays/osc/osc-cl1/grafana_oauth_patch.yaml

Atm grafana is still configured with openshift-monitoring namespace as I've been unsuccessfull in adding data source directly from UWM (thus a little bit more isolated from cluster-wide metrics). As such kepler-admins will have access to openshift-monitoring metrics (more than UWM), we can address this afterwards. 
Rellated: https://github.com/os-climate/os_c_data_commons/issues/190

Give kerpler admins access to osc-cl1 grafana.

---

docs/content/about/intro.md

Resolves #1766 
We decided to remove this page since it is outdated. I put a link to the websites getting started page until we recreate this page on our own.
/cc @HumairAK

docs: Remove getting started page

---

vault/overlays/moc/smaug/obc.yaml

this value differs from the currently deployed bucket, bringing it in sync.

Correct vault's smaug backup bucket name.

---

prow/overlays/smaug/config.yaml

I noticed that the merge strategy for the thoth-station org switched from `merge` to `squash` recently (commit 24c9bc53e5c5623caabf019a3663a8d9dc8c5b11 from #2251) and I could not identify the reason why.
Assuming that it was an oversight, this PR sets the merge strategy back to `merge`.

[prow] Switch the merge strategy for thoth-station back to 'merge'

---

cluster-scope/overlays/prod/emea/balrog/groups/cluster-admins.yaml

This is to add myself as cluster admin for the balrog cluster (where Thoth prod runs).
Removing Anand from the list too.
The trigger for this request was for me to get access to argo workflows running on the cluster, as I currently do not have access to them. 
I know cluster-admin is overkill for that, but... on one hand I could not locate specific group(s) for that specific access (happy to get pointers), and on the other hand I thought it could be handy anyway for other tasks :innocent:

Add Pep to balrog cluster admins, replacing Anand

---

argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kafka.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/kafka/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/kepler-monitoring/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl2/configmaps/cluster-monitoring-config.yaml
cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/kafka/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/kepler-monitoring/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/kustomization.yaml
kafka/overlays/osc/osc-cl2/kafka/kustomization.yaml
kafka/overlays/osc/osc-cl2/kafka/my-cluster.yaml
kafka/overlays/osc/osc-cl2/prometheus-kafka-adapter/deployment.yaml
kafka/overlays/osc/osc-cl2/prometheus-kafka-adapter/external-secret.yaml
kafka/overlays/osc/osc-cl2/prometheus-kafka-adapter/kustomization.yaml
kafka/overlays/osc/osc-cl2/prometheus-kafka-adapter/service.yaml
kafka/overlays/osc/osc-cl2/prometheus-kafka-adapter/serviceaccount.yaml
kafka/overlays/osc/osc-cl2/topics/kepler-metrics.yaml
kafka/overlays/osc/osc-cl2/topics/kustomization.yaml
kafka/overlays/osc/osc-cl2/topics/my-topic.yaml
kepler/overlays/osc/osc-cl2/CO2Signal-producer/external-secret-dot-env.yaml
kepler/overlays/osc/osc-cl2/CO2Signal-producer/kafka-producer.yaml
kepler/overlays/osc/osc-cl2/CO2Signal-producer/kustomization.yaml
kepler/overlays/osc/osc-cl2/kustomization.yaml

This change adds the deployed kafka resources in osc-cl2 to git.
It also adds a prometheus-to-kafka producer, OCP monitoring configs are
updated to remote write kepler metrics to this producer, and the
producer sends these to the kepler-metrics topic.
The commit also adds `CO2Signal-producer` producer, but is not currently deployed, as this will be next.

Add prometheus to kafka pipeline configs for osc.

---

cluster-scope/overlays/prod/osc/osc-cl2/configmaps/cluster-monitoring-config.yaml
cluster-scope/overlays/prod/osc/osc-cl2/configmaps/user-workload-monitoring-config.yaml

Incorrectly added to openshift-monitoring, added to uwm instead.

Switch remotewrite configs to uwm in osc.

---

cluster-scope/overlays/prod/moc/infra/nodenetworkconfigurationpolicies/vlan-211-nese.yaml

Resolves: https://github.com/operate-first/operations/issues/496
Turn on ArgoCD autosync back on after merge: https://argocd.operate-first.cloud/applications/cluster-resources-infra

fix(infra): eno1 connection renamed on node/ctrl-1

---

kfdefs/overlays/osc/osc-cl2/trino/configs/config-coordinator.properties
kfdefs/overlays/osc/osc-cl2/trino/configs/config-worker.properties

Trying to debug why the riskthinking catalog is failing on reading data from tables with "table not found" errors

enable debug for bq plugin, per request from trino devs

---

cluster-scope/bundles/odf-external/kustomization.yaml

This is causing problems on Infra, since this is a Smaug specific Storage Class (why is it in the base?, further cleanup necessary...). For now I need to remove it from Infra asap.
Related to: https://github.com/operate-first/apps/issues/2386

fix: Unlist Smaug specific storage class from a bundle

---

cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/cronjob.yaml
cluster-scope/base/core/serviceaccounts/vault-secret-writer/kustomization.yaml
cluster-scope/base/core/serviceaccounts/vault-secret-writer/serviceaccount.yaml
cluster-scope/overlays/prod/common/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/kustomization.yaml
cluster-scope/overlays/prod/emea/balrog/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
cluster-scope/overlays/prod/moc/curator/secret-mgmt/kustomization.yaml
cluster-scope/overlays/prod/moc/curator/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/secret-mgmt/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml

Changes to `CronJob`:
* Save the final vault token to an env variable instead of a file by default
* Change role to one that allows writing of secrets
* Switch from `jq` to `yq` which is installed in toolbox image
* Switch from running as `vault-secret-fetcher` to `vault-secret-writer`
Changes to manifests:
* Add `service-catalog-k8s-plugin` config map for moc/smaug to kustomization file
* Remove the addition of `vault-secret-fetcher` SA from clusters other then smaug
* Create `vault-secret-writer` SA for all clusters

feat(catalog): Allow CronJob to write secrets to vault

---

argocd/overlays/moc-infra/projects/b4mad.yaml

otherwise, I get 
`Resource integreatly.org:Grafana is not permitted in project b4mad.`

whitelist grafana resources for b4mad

---

kfdefs/overlays/osc/osc-cl1/trino/configs/catalogs/osc_datacommons_iceberg_dev.properties
kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties

- increase maximum partitions from 100 to 300
- set `iceberg.unique-table-location=true`
note: `unique-table-location` defaults to `true` in newer releases, but it does no harm.

set uniq table loc and increase max partitions

---

cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml

Part of #2401 
Since the [this common overlay](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/common/kustomization.yaml) is not added to osc, the `service-catalog-k8s-plugin` bundle needs to be added separately.
/cc @HumairAK

feat(catalog): Add k8s plugin bundle to osc clusters

---

cluster-scope/base/apps/daemonsets/kvm-device-plugin/daemonset.yaml
cluster-scope/base/machineconfiguration.openshift.io/machineconfigpools/mcp-kvm-device-plugin/kustomization.yaml
cluster-scope/base/machineconfiguration.openshift.io/machineconfigpools/mcp-kvm-device-plugin/machineconfigpool.yaml
cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/80-enable-nested-virt/kustomization.yaml
cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/80-enable-nested-virt/machineconfig.yaml
cluster-scope/bundles/kvm-device-plugin/kustomization.yaml

Add machineconfig and machineconfigpool to enable nested-virtualization on nodes where kvm-device-plugin daemonset is deployed, so that the okd-team tekton pipeline for SCOS build runs faster.

Add machineconfig and machineconfigpool to enable nested-virtualization 

---

cluster-scope/overlays/prod/moc/smaug/subscriptions/nfd_patch.yaml

Since Smaug is on OCP 4.9, there's no `4.8` channel for NFD operator... There are `4.9` and `stable` channels. I think switching to `stable` gives us more recent version and is also more future proof.

fix: NFD channel '4.8' no longer exist on Smaug, use 'stable' instead

---

cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml

The [custom notebook image functionality for ODH](https://github.com/thoth-station/opendatahub-cnbi/) is being developed based on [meteor-operator](https://github.com/AICoE/meteor-operator/).
This work is the continuation of the [Bring your own notebook (BYON)](https://github.com/open-services-group/byon/) effort.
The `opf-jupyterhub-stage` namespace in the *odh-cl1* cluster is hosting the staging environment for this development.
This PR adds the `spike-cnbi-crd` branch of the `meteor-operator` repo as a source for deployment configuration, and adds the default operator configuration to the `KfDef`.
Related to: https://github.com/open-services-group/scrum/issues/37
Should be documented in https://github.com/open-services-group/scrum/issues/32

Add the Custom Notebook Image (CNBi) operator to osc-cl1 stage

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/b4mad/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/b4mad/minecraft.yml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

this was not migrated to smaug. It's becoming active again and also added to argocd
I also change the metadata name for the racing namespace

add b4mad-minecraft to smaug

---

cluster-scope/overlays/prod/moc/curator/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/configmaps/service-catalog-k8s-plugin.yaml
cluster-scope/overlays/prod/osc/osc-cl2/configmaps/service-catalog-k8s-plugin.yaml

The `service-catalog-k8s-plugin` bundle is missing from the curator overlay since it doesn't import the `common` overlay.
ConfigMaps for OSC clusters contain a typo.
/cc @tumido

fix(catalog): Add bundle and change configmap

---

.prow.yaml

pre-commit is heavily parallelized
the other jobs exceed 1cpu a bit
I tested locally with `docker stats` and just looking at mem and CPU usage
cc @Gregory-Pereira

bumping resource requests for prow jobs

---

cluster-scope/overlays/prod/moc/smaug/secret-mgmt/api-designer/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/api-designer/opf-vault-store.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/apicurio-apicurio-registry/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/apicurio-apicurio-registry/opf-vault-store.yaml

Addresses https://github.com/operate-first/apps/pull/2430#issuecomment-1252897561
Use `apicurio` role in Vault once it's created. Requires a Vault role and Vault policy for `apicurio` team.

fix: Change apicurio Vault role

---

cluster-scope/overlays/prod/moc/smaug/secret-mgmt/copilot-ops/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/copilot-ops/opf-vault-store.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml

Adds project Copilot ops to vault secret management
Part of: https://github.com/operate-first/support/issues/973

feat: Add copilot-ops to vaul secret management

---

argocd/overlays/moc-infra/kustomization.yaml

Accidentally removed here: https://github.com/operate-first/apps/pull/2448/files#diff-825202f32a50d376d91bcb81d562f0d9d3b36580ce2871d387b6689bd5262596

Add dex oauth sa annotations to argocd dex.

---

cluster-scope/overlays/prod/moc/infra/clusterroles/service-catalog-k8s-plugin.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

Part of https://github.com/operate-first/service-catalog/issues/102
Add the required permissions to query ACM for cluster status.

feat(catalog): Add extra permisions to SA on infra

---

cluster-scope/overlays/prod/emea/jerry/configmaps/service-catalog-k8s-plugin.yaml
cluster-scope/overlays/prod/emea/jerry/kustomization.yaml

Part of https://github.com/operate-first/service-catalog/issues/113
Add a ConfigMap that is needed for the cronjob on jerry cluster for uploading secrets to vault so that the service catalog can query this cluster.

feat(catalog): Add ConfigMap for jerry in service catalog

---

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-k8s-plugin-acm/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-k8s-plugin-acm/kustomization.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin-acm/clusterrole.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin-acm/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

Fixes: https://github.com/operate-first/apps/pull/2439
Previous PR merged the `ClusterRoles` by replacing the `rules` list. We want to join those - hence we rather create a separate role + a binding.

fix: Backstage cluster role for ACM on Infra

---

prow/overlays/smaug/imagestreamtags.yaml

Update the prow entrypoint image to work with new standards
Fixes: https://github.com/operate-first/apps/issues/2460

Update the prow entrypoint image to work with new standards

---

cert-manager/overlays/emea/jerry/api/issuer.yaml
cert-manager/overlays/emea/jerry/ingress/issuer.yaml

Resolved #2508 
Since we are integrating jerry to the service-catalog (https://github.com/operate-first/service-catalog/issues/113), a prod certificate is needed.
/cc @tumido @HumairAK @durandom

chore: Change cert manager server to prod server

---

cluster-scope/base/rbac.authorization.k8s.io/clusterroles/monitors-create-aggregate-to-admin/clusterrole.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterroles/monitors-create-aggregate-to-admin/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Related: https://github.com/operate-first/support/issues/621 
Seems like admins can't create servicemonitors in smaug.

Aggregate servicemonitor write access to admins.

---

cluster-scope/overlays/prod/moc/infra/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/nodes/os-ctrl-0.moc-infra.massopen.cloud.yaml
cluster-scope/overlays/prod/moc/infra/nodes/os-ctrl-1.moc-infra.massopen.cloud.yaml
cluster-scope/overlays/prod/moc/infra/nodes/os-ctrl-2.moc-infra.massopen.cloud.yaml
cluster-scope/overlays/prod/moc/infra/storageclasses/ocs-external-storagecluster-ceph-rbd.yaml

1. NooBaa requires nodes to be labeled (will be part of our ODF documentation) otherwise it's stuck in pending
This is obscurely documented here: https://github.com/red-hat-storage/ocs-operator#prerequisites 
Not in the official ODF docs
2. Set `ocs-external-storagecluster-ceph-rbd` storage class as default.

feat(infra): ODF - set default storage class and enable NooBaa scheduling

---

kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/uwm_prometheus.properties
kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/kustomization.yaml
kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/trino-secret-files.yaml

This catalog will allow trino users to query against metrics exposed by openshift-monitoring.
An external route is used intentionally instead of internal cluster service url. When attempting to use internal cluster route -- cert errors were encountered.

Add uwm prometheus connector to osc-cl2 trino.

---

cluster-scope/base/core/namespaces/aicoe-meteor/namespace.yaml
kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml
prow/overlays/smaug/config.yaml

The [meteor-operator repository](https://github.com/thoth-station/meteor-operator) moved from the AICoE org to the thoth-station org.
This updates references accordingly.

Update after meteor-operator repo move

---

cluster-scope/overlays/prod/moc/infra/externalsecrets/multiclusterhub-operator-pull-secret.yaml
cluster-scope/overlays/prod/moc/infra/externalsecrets/thanos-object-storage.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/objectbucketclaims/thanos.yaml
cluster-scope/overlays/prod/moc/infra/secret-mgmt/kustomization.yaml

- Adds `SecretStore` to `open-cluster-management-observability` namespace (was missing in `kustomization.yaml`
- Adds namespace to `ExternalSecrets` which should be in `open-cluster-management-observability` instead of default `open-cluster-management-agent`
- Adds `ObjectBucketClaim` for Thanos - its creds are already [synced in Vault](https://vault-ui-vault.apps.smaug.na.operate-first.cloud/ui/vault/secrets/k8s_secrets/show/moc/infra/open-cluster-management-observability/thanos-object-storage)
Note: Due to the missing External Secrets the MCO is using some [old obscure pull secret](https://console-openshift-console.apps.moc-infra.massopen.cloud/k8s/ns/open-cluster-management-observability/secrets/multiclusterhub-operator-pull-secret) (using ipolonsk's email) which should have been …

fix: Thanos storage on Infra

---

openmetadata/base/openmetadata-dependencies/configmaps/files/pod_template.yaml
openmetadata/base/openmetadata-dependencies/configmaps/mysql-init-scripts.yaml
openmetadata/base/openmetadata-dependencies/configmaps/openmetadata-dependencies-config-envs.yaml
openmetadata/base/openmetadata-dependencies/deployments/airflow-db-migrations.yaml
openmetadata/base/openmetadata-dependencies/deployments/airflow-scheduler.yaml
openmetadata/base/openmetadata-dependencies/deployments/airflow-sync-users.yaml
openmetadata/base/openmetadata-dependencies/deployments/airflow-web.yaml
openmetadata/base/openmetadata-dependencies/deployments/airlfow-triggerer.yaml
openmetadata/base/openmetadata-dependencies/poddisruptionbudgets/elasticsearch-pdb.yaml
openmetadata/base/openmetadata-dependencies/poddisruptionbudgets/kustomization.yaml
openmetadata/base/openmetadata-dependencies/statefulsets/mysql.yaml
openmetadata/base/openmetadata/configmaps/files/openmetadata.yaml
openmetadata/base/openmetadata/deployments/openmetadata.yaml
openmetadata/overlays/osc/osc-cl2/kustomization.yaml
openmetadata/overlays/osc/osc-cl2/patches/deployments/openmetadata.yaml

Resolves:  https://github.com/operate-first/support/issues/1110 https://github.com/operate-first/support/issues/1109
helm chart used is 0.0.39 from here:  https://github.com/open-metadata/openmetadata-helm-charts

Upgrade openmetadata to 0.12.1

---

prow/overlays/smaug/config.yaml

Follows: thoth-station/thoth-application#2605
Fixes thoth-station/prescriptions-refresh-job#172
Just a deployment of the updated prow config.
This configures the `branchcleaner` [prow plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/branchcleaner) so that source branches for merged PRs between two branches on the same repository are automatically deleted.
This can help with e.g. Kebechet PRs or prescription-refresh-job runs.
There was a suggestion in thoth-station/thoth-application#2605 to restrict this configuration to the thoth-station org. However, if I understand the [configuration of the plugin](https://github.com/kubernetes/test-infra/blob/e831f6aee73552c33fdc07c5b5ba7dedb29497b4/prow/plugins/plugin-config-documented.yaml#L73-L84) correctly, there is no way …

[prow] Add branch cleaner plugin configuration

---

cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin/clusterrole.yaml

Part of https://github.com/operate-first/service-catalog/issues/86
New resource permissions are required for an updated k8s plugin in the service catalog.
/cc @tumido

feat(catalog): Add new resource permissions for k8s plugin

---

kfdefs/overlays/osc/osc-cl1/cnbi/kfdef.yaml
kfdefs/overlays/osc/osc-cl1/cnbi/kustomization.yaml
kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml
kfdefs/overlays/osc/osc-cl1/kustomization.yaml

Deploy cnbi component on aicoe-meteor namespace
Related-to: https://github.com/thoth-station/meteor-operator/issues/88
Explicitly separated the cnbi deployment kfdef

Deploy cnbi component on aicoe-meteor namespace

---

grafana/overlays/osc/common/dashboards/data-pipeline-resources.yaml
grafana/overlays/osc/common/dashboards/json/data-pipeline-resources.json
grafana/overlays/osc/common/dashboards/kustomization.yaml
kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
kfdefs/overlays/osc/osc-cl2/trino/configs/jvm-coordinator.config
kfdefs/overlays/osc/osc-cl2/trino/configs/jvm-worker.config
kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/co2signal-trino-schema.json
kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/ecb-trino-schema.json
kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
kfdefs/overlays/osc/osc-cl2/trino/configs/monitoring-config.yaml
kfdefs/overlays/osc/osc-cl2/trino/kfdef.yaml
kfdefs/overlays/osc/osc-cl2/trino/kustomization.yaml
kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/OSC_DataCommons_Dev.yaml
kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/kustomization.yaml
kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/osc_datacommons_hive_ingest.yaml
kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/trino-coordinator.yaml
kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/trino-workers.yaml

This change adds servicemonitors to the hive metastores and trino, this will allow us to monitor the JMX metrics exposed by these components. Trino's jmx java agent exporter is also enabled in this PR.
To help better visualize these metrics, a grafana dashaboard is also provided.
Possibly related: https://github.com/operate-first/support/issues/1113
Also adds a fix to ecb-fx kafka topic and converts it to lower case for: https://github.com/os-climate/os_c_data_commons/issues/203
also adds co2signal topic to kafka connector: https://github.com/os-climate/os_c_data_commons/issues/213

Apply trino optimizations and monitoring visuals.

---

acm/overlays/moc/infra/managedclusters/osc-cl1.yaml
acm/overlays/moc/infra/managedclusters/osc-cl2.yaml

As per office hour discussions, os-climate cluster data moving out of these clusters should require approval from the cluster maintainers/stakeholders
Documentation:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html-single/observability/index#disable-observability-on-a-single-cluster

Disable observability for os-climate clusters.

---

grafana/overlays/moc/smaug/landingpage-dashboard-configmap.yaml
grafana/overlays/osc/common/dashboards/json/landingpage.json

Fixes the UUID error that occurs when hitting the landing page in grafana.

Fix grafana invalid uid error for landing page.

---

grafana/overlays/common/dashboards/compute-resources-overview/cluster-node-resource-consumption.yaml
grafana/overlays/common/dashboards/compute-resources-overview/configmaps/files/cluster-node-resource-consumption.json
grafana/overlays/common/dashboards/compute-resources-overview/configmaps/kustomization.yaml
grafana/overlays/common/dashboards/compute-resources-overview/kustomization.yaml

Will be deployed on all clusters that deploy grafana. Allows us to monitor resources consumption by node. 
E.g: 
* https://grafana-opf-monitoring.apps.odh-cl2.apps.os-climate.org/d/SVWrmEIVk/node-compute-resources-copy?orgId=1 
* https://grafana.operate-first.cloud/d/257HWES4k/node-compute-resources-copy?orgId=1

Add node resource usage dashboard.

---

service-catalog/apis/backstage.yaml

I missed this while I was updating the API component, these are the correct endpoints.
/cc @tumido

fix: Correctly reference API endpoints

---

service-catalog/components/prow-needs-rebase.yaml
service-catalog/systems/prow.yaml

- `needs-rebase` entity was not showing up because it didn't have a description.
- Add useful link for prow PR interaction sequence
/cc @tumido

fix(catalog): Add description to needs-rebase component

---

cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
cluster-scope/base/user.openshift.io/groups/okd-wg/group.yaml

Give @GeoEducator access to the `okd-wg` namespace

Add GeoEducator to OKD WG group

---

cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml

add goern to odh-admin group on osc cl1

---

docs/content/vault_eso/onboard_team_to_vault.md

Current documentation does not include permissions to be able to delete secrets from a vault team's kv path. The updated docs include the delete permissions to allow for this.

Update vault onboard docs.

---

cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
cluster-scope/base/user.openshift.io/groups/okd-team/group.yaml
cluster-scope/base/user.openshift.io/groups/okd-wg/group.yaml

Give @cgwalters access to the `okd-team` and `okd-wg` namespaces.
@cgwalters you'll be able to log onto https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects/okd-team after accepting the invitation to the `operate-first` GH org.

Add cgwalters to okd-team and okd-wg groups

---

kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml

The new dev version of the odh-dashboard in the _stage_ namespace in osc's odh-cl1 (ref https://github.com/operate-first/odh-manifests/pull/40) is failing to start:
``` text
Environment:
DEV_MODE=false
NODE_ENV=production
DEBUG_PORT=5858
Launching via npm...
npm info it worked if it ends with ok
npm info using npm@6.14.17
npm info using node@v14.20.0
npm info lifecycle ods-dashboard@1.0.0~prestart: ods-dashboard@1.0.0
npm info lifecycle ods-dashboard@1.0.0~start: ods-dashboard@1.0.0
> ods-dashboard@1.0.0 start /opt/app-root/src
> run-p start:*
npm info it worked if it ends with ok
npm info using npm@6.14.17
npm info using node@v14.20.0
npm info it worked if it ends with ok
npm info using npm@6.14.17
npm info using node@v14.20.0
npm info lifecycle ods-dashboard@1.0.0~prestart:frontend: …
```

Add authentication overlay to odh-dashboard in osc cl1 CNBi stage

---

cluster-scope/base/core/namespaces/okd-team/limits.yaml

Limit cpu and memory was too high and often blocking new pod creations

Fix limitRanges for okd-team defaults

---

service-catalog/apis/backstage.yaml

We are renaming `cluster-status` plugin to `rhacm` so the API endpoints need to updated.
/cc @tumido

fix(catalog): RHACM plugin API endpoint

---

cluster-scope/base/core/namespaces/robozome/kustomization.yaml
cluster-scope/base/core/namespaces/robozome/namespace.yaml
cluster-scope/base/core/namespaces/robozome/resourcequota.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/robozome/kustomization.yaml
scripts/jsonnet/group.jsonnet
scripts/jsonnet/namespace.jsonnet
scripts/jsonnet/rbac.jsonnet
scripts/offboarding.sh
scripts/onboarding.sh
scripts/payload_examples/offboarding.yaml
scripts/payload_examples/onboarding.yaml

This PR adds robozome namespace, and some starter scripts for onboarding/offboarding projects. The scripts are an alternative implementation to: https://github.com/operate-first/apps/pull/2380 
But still use jsonnet for templating. 
The scripts here are simplified to one script per task (onboarding & offboarding), with documents included. I've removed the dependency on jinja since it's not needed, and the need to create temp folders/files (also not needed). 
I've also added detailed comments in the scripts so it will make it easier to convert them to docs later. 
Scripts consume from a payload file that will be created by the robozome app, when running manually you can create your own payload file by basing it off the examples provided in this PR.

Add robozome ns

---

cluster-scope/overlays/prod/moc/smaug/externalsecrets/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/externalsecrets/service-catalog.yaml

Part of https://github.com/operate-first/service-catalog/issues/128
Create an external secret for a secret in vault. The SA `vault-secret-fetcher` has already been created. Namespace has been added to the `smaug-k8s/moc-ops` role.
/cc @tumido

feat(catalog): Create exeternal secret for service-catalog

---

prow/overlays/smaug/config.yaml

`prow` (`tide`) is not merging pull requests for the `sefkhet-abwy` repository. See for example https://github.com/AICoE/sefkhet-abwy/pull/203
The pre-commit check driven by the aicoe-ci pipelines was removed a while ago, and this is now covered by a prow pre-submit job, so this PR removes that check from the tide query list for that repo.

[prow] Remove legacy presubmit check for from tide config

---

cluster-scope/base/core/serviceaccounts/service-catalog-prometheus-plugin/kustomization.yaml
cluster-scope/base/core/serviceaccounts/service-catalog-prometheus-plugin/serviceaccount.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-prometheus-plugin/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-prometheus-plugin/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

Adds SA, Clusterrole and binding for prometheus plugin that this token to access rbac-query-proxy of MCO. More information can be found [here](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html-single/observability/index#external-metric-query)
Part of https://github.com/operate-first/service-catalog/issues/16
Unblocks https://github.com/operate-first/service-catalog/pull/189

feat(service catalog): Add service account with role for prometheus plugin

---

.github/workflows/techdocs.yaml

GitHub complains we use invalid workflow file:
https://github.com/operate-first/apps/actions/runs/3462888258/workflow
We have multiple definitions of the same key `send-repo-dispatches`. Let's fix this via `matrix` strategy.
/cc @SamoKopecky

chore: Fix techdocs CI

---

prow/overlays/smaug/plugins.yaml

Allow robozome-op1st app to trigger prow tests.
already discussed at
https://github.com/thoth-station/support/issues/122
@tumido you mentioned a prow upgrade, but it looks like we're pulling always the master images and the dashboard reports version v20220812-9414716697
so I guess this would work?

allow robozome-op1st for prow trigger plugin

---

cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/opf-ci-prow/kustomization.yaml
prow/overlays/smaug/externalsecrets/cookie.yaml
prow/overlays/smaug/externalsecrets/github-oauth-config.yaml
prow/overlays/smaug/externalsecrets/github-token.yaml
prow/overlays/smaug/externalsecrets/hmac-token.yaml
prow/overlays/smaug/externalsecrets/oauth-token.yaml
prow/overlays/smaug/externalsecrets/s3-credentials.yaml
prow/overlays/smaug/externalsecrets/ssh-secret.yaml

the SecretStore was missing from opf-ci-prow namespace
```
Status:
Conditions:
Last Transition Time:  2022-11-15T13:37:15Z
Message:               could not get store reference
Reason:                SecretSyncedError
Status:                False
Type:                  Ready
Events:
Type     Reason           Age                  From              Message
----     ------           ----                 ----              -------
Warning  InvalidStoreRef  2m2s (x20 over 36m)  external-secrets  could not get SecretStore "opf-vault-store", SecretStore.external-secrets.io "opf-vault-store" not found
```

add secret store to prow

---

cluster-scope/base/operators.coreos.com/subscriptions/camel-k/subscription.yaml

Upgrade to `stable` which keeps track with minor version upgrades

feat: Upgrade camel-k to stable channel

---

argocd/overlays/moc-infra/projects/global_project.yaml

Fix the new pulp CR reference in argocd list
Related-to: https://github.com/operate-first/apps/pull/2615

Fix the new pulp CR reference in argocd list

---

prow/overlays/smaug/ghproxy.yaml

ghproxy is being OOMKilled and is raising TLS handshake errors/timeouts.
OOM kills should be solved by increasing memory request/limit from the original really restrictive `64Mi` (upstream [has none](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/ghproxy.yaml)).
I think TLS handshakes errors can be caused by delays due to really low CPU limit - 2 milicores (upstream [has no limit](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/ghproxy.yaml)).

fix: Increase ghproxy resources to avoid OOM kills

---

kfdefs/overlays/osc/osc-cl1/cnbi/kfdef.yaml

The Custom Notebook Image functionality at this point needs the meteor operator and the ODH dashboard in the same namespace.
This PR moves the staging ODH deployment to the aicoe-meteor namespace.

Move the OSC cl1 staging ODH deployment to the meteor namespace

---

prow/overlays/smaug/ghproxy.yaml

After #2619  it seems `ghproxy` has stabilized. Utilization is below request so let's match limits to request.
Memory utilization averages around `50Mi` and CPU around `2m`. I think `128Mi` and `10m` (matching the limit to request values) is quite generous with a large enough buffer.

fix: Match ghproxy resource request and limit

---

cluster-scope/overlays/prod/emea/jerry/imageregistry.operator.openshift.io/configs/cluster/config.yaml
cluster-scope/overlays/prod/emea/jerry/imageregistry.operator.openshift.io/configs/cluster/kustomization.yaml
cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
cluster-scope/overlays/prod/emea/jerry/persistentvolumeclaims/image-registry-storage/kustomization.yaml
cluster-scope/overlays/prod/emea/jerry/persistentvolumeclaims/image-registry-storage/persistentvolumeclaim.yaml

https://docs.openshift.com/container-platform/4.10/registry/configuring_registry_storage/configuring-registry-storage-baremetal.html
change PVC to `ReadWriteOnce`, since we don't have distributed storage, and change replicas to 1

change image registry

---

prow/overlays/smaug/plugins.yaml

As @durandom proved via https://github.com/operate-first/apps/pull/2611 (manifested for example via https://github.com/operate-first/apps/pull/2622 ), `trusted_apps` settings work.
Let's enable it for `dependabot` and `renovate` in the whole `operate-first` org.
Note: It seems the `repos` list can reference whole orgs per inline docs here:
https://github.com/kubernetes/test-infra/blob/780d24ca7b96bdfadc09985d511694efe1929f39/prow/plugins/config.go#L433 
FFR: https://github.com/thoth-station/support/issues/122

feat: Trust renovate and dependabot to run CI in Prow

---

cluster-scope/base/security.openshift.io/securitycontextconstraints/nfs-server-and-provisioner/securitycontextconstraints.yaml

hostPath is added to live manifest, so the cluster-resources app is always out of sync

add hostPath to scc

---

kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/elyra-image.yaml
kfdefs/overlays/osc/osc-cl2/jupyterhub/notebook-images/elyra-image.yaml

The most recent versions of the image, 0.2.0 and 0.2.1, have a bug that is causing the notebook to fail to load. An issue has been opened with the upstream project, but until it is fixed and new image is released, we need to pin to last working version. Fixes operate-first/support#1137
Signed-off-by: Eric Ball <eball@linuxfoundation.org>

Pin custom elyra image until 0.2.x bug is fixed

---

cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml

This PR is to add myself to the `cluster-admins` for OSC's odh-cl1 cluster.
The driver for this is the ongoing development of ODH's custom notebook images functionality, whose staging env is in that cluster.
In that context, I would complement @harshad16 who is already on that list.

Add Pep to the cluster admins group for the osc-cl1 cluster

---

cluster-scope/base/operators.coreos.com/subscriptions/pulp-operator/subscription.yaml
pulp/overlays/moc/smaug/opf-pulp-backup.yaml

Update pulp version and include nodeaffinity to pulp backup
- The channel is to be updated to `beta`
https://github.com/pulp/pulp-operator/blob/8a20f46d878ac29856334d3364629847385b8a1d/bundle/metadata/annotations.yaml#L7
fixes: https://github.com/operate-first/support/issues/1148
- The Pulp backup is requiring node affinity to fix the issue of PVC bound.
Related-to: https://github.com/pulp/pulp-operator/issues/782

:zap: Update pulp version and include nodeaffinity to pulp backup

---

cluster-scope/base/core/namespaces/wildfly-service/kustomization.yaml

I requested a medium quota last week, but unfortunately that is not enough.
The service currently consists of a postgres instance and a back-end 'manager'. The intent is that users upload their Java applications, and they get deployed to a provisioned WildFly instance. Invoking a `deploy` via the manager results in a Helm chart getting installed, which creates a series of buildconfigs and image streams, and then it starts the first build in the chain (one-deployment-build-1-build in the below error) as a binary build uploading applications.
Trying to do this with my manager, I see the following errors in the logs
> 22s         Warning   FailedCreate             build/one-deployment-build-1                      Error creating build pod: pods "one-deployment-build-1-build" is forbidden: …

Request large quota for WildFly

---

kvm-device-plugin/base/buildconfig.yaml
okd-centos/base/buildconfig.yaml

The image has been renamed from okd-golang-builder to okd-builder.

OKD: Update builder Dockerfile path and image name

---

kfdefs/overlays/osc/osc-cl1/cnbi/kfdef.yaml

This is to add the pipeline manifests that implement the Custom Notebook Image (CNBi) functionality to the `cnbi` ODH deployment on osc-cl1

osc-cl1: Add CNBi / CRE pipelines to the osc-cl1 deployment

---

kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/iris-notebook.yaml
kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/kustomization.yaml

Code and container are currently stored in my personal spaces. Once it has been validated in cl1, we can move the code and container to OS-Climate orgs and apply the cl2.
Signed-off-by: Eric Ball <eball@linuxfoundation.org>

Add initial test of Iris notebook for osc-cl1

---

grafana/overlays/osc/common/grafana_oauth_patch.yaml
grafana/overlays/osc/osc-cl1/grafana_oauth_patch.yaml
grafana/overlays/osc/osc-cl2/grafana_oauth_patch.yaml

Original PR https://github.com/operate-first/apps/pull/2654 has caused only sostrades to be sole group that has access (also was malformed) , this PR is correcting this issue and adding sostrades under patch in common

Fixed patch for OSC grafana to include sostrades as editors

---

cluster-scope/base/core/namespaces/openshift-tuning/kustomization.yaml

We want our project Kruize HPO with namespace 'openshift-tuning' to be accessible for everyone on the smaug cluster. requesting you to approve this

Added project view public access for openshift-tuning

---

cluster-scope/base/core/namespaces/smart-village-view/kustomization.yaml
cluster-scope/base/core/namespaces/smart-village-view/resourcequota.yaml

Hello Operate First team! Could I please increase the ResourceQuota of the smart-village-view project with a custom ResourceQuota with a 16 CPU limit? 
We are onboarding a new FIWARE Context Broker and other applications as part of our IoT Traffic Simulations. We also have large data imports and it seems to be limited by the database, search engine, cluster manager, and application having enough CPU limit to process the data.

Requesting 16 cpu limit for smart-village-view

---

cert-manager/overlays/emea/jerry/api/certificate.yaml
cert-manager/overlays/emea/jerry/api/issuer.yaml
cert-manager/overlays/emea/jerry/ingress/certificate.yaml
cert-manager/overlays/emea/jerry/ingress/issuer.yaml
cert-manager/overlays/moc/curator/api/certificate.yaml
cert-manager/overlays/moc/curator/api/issuer.yaml
cert-manager/overlays/moc/curator/ingress/certificate.yaml
cert-manager/overlays/moc/curator/ingress/issuer.yaml
cert-manager/overlays/moc/infra/api/certificate.yaml
cert-manager/overlays/moc/infra/api/issuer.yaml
cert-manager/overlays/moc/smaug/api/certificate.yaml
cert-manager/overlays/moc/smaug/api/issuer.yaml
cert-manager/overlays/moc/smaug/ingress/certificate.yaml
cert-manager/overlays/moc/smaug/ingress/issuer.yaml
cert-manager/overlays/osc/osc-cl1/ingress/certificate.yaml
cert-manager/overlays/osc/osc-cl1/ingress/issuer.yaml

Small cleanup, `kustomize build` diff yields 0 since the `namespace` is already defined in the `kustomization.yaml`.

chore: Remove duplicit namespace definitions from cert-manager manifests

---

cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-restricted-seccomp/clusterrolebinding.yaml
cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-restricted-seccomp/kustomization.yaml
cluster-scope/base/security.openshift.io/securitycontextconstraints/restricted-seccomp/README.md
cluster-scope/base/security.openshift.io/securitycontextconstraints/restricted-seccomp/kustomization.yaml
cluster-scope/base/security.openshift.io/securitycontextconstraints/restricted-seccomp/securitycontextconstraint.yaml
cluster-scope/bundles/cert-manager/kustomization.yaml
cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
cluster-scope/overlays/prod/moc/curator/kustomization.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml

This change will allow cert-manager to use http01 challenge. This SCC is equivalent to `runtime-v2` available since OCP 4.11.
https://docs.openshift.com/container-platform/4.10/security/seccomp-profiles.html#configuring-default-seccomp-profile_configuring-seccomp-profiles
https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-auth-pod-security-admission
https://cert-manager.io/docs/release-notes/release-notes-1.10/#on-openshift-the-cert-manager-pods-may-fail-until-you-modify-security-context-constraints

feat: Create SCC with seccomp runtime/default

---

pulp/overlays/moc/smaug/certificate.yaml
pulp/overlays/moc/smaug/issuer.yaml
pulp/overlays/moc/smaug/kustomization.yaml

Depends on: #2675
Related to: #2662
This will create a `pulp-letsencrypt` Secret in the `opf-pulp` namespace. This secret will contain `tls.crt` and `tls.key` keys.
/hold (until requirements are merged)
/cc @fao89 @harshad16

feat: Create certificate for pulp.operate-first.cloud

---

argocd/overlays/moc-infra/projects/global_project.yaml

#2676 fails to deploy because `Certificate` and `Issuer` is not allowed for regular ArgoCD projects. This PR fixes that.

feat: Allow Certificate and Issuer in ArgoCD global_project template

---

cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayclusters.ray.io/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayjobs.ray.io/customresourcedefinition.yaml
cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayservices.ray.io/customresourcedefinition.yaml
cluster-scope/bundles/ray-operator/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

We've forgot to actually deploy the changes in https://github.com/operate-first/apps/pull/2645

feat: Deploy ray operator cluster resources to Smaug

---

argocd/overlays/moc-infra/projects/apex.yaml

Argo app fails with "application destination
{https://api.smaug.na.operate-first.cloud:6443 apex} is not permitted in project 'apex'"
Hoping this should fix it.
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>

argocd: Fix Apex Destinations

---

cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/machinesets/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-compute-notebook.yaml
cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-kepler-edge-m4.yaml
cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-kepler-edge-m5.yaml
cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-kepler-edge-m6.yaml
cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-notebook-gpu-g.yaml
cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-worker.yaml
cluster-scope/overlays/prod/osc/osc-cl1/nodefeaturediscovery/kustomization.yaml
cluster-scope/overlays/prod/osc/osc-cl1/nodefeaturediscovery/nfd-instance.yaml
cluster-scope/overlays/prod/osc/osc-cl1/nvidia-gpu/gpu-cluster-policy.yaml
cluster-scope/overlays/prod/osc/osc-cl1/nvidia-gpu/kustomization.yaml

Part of the process of bringing osc-cl1 cluster to the level of control by operate-first processes as for ocs-cl2. Adding previously manually managed machinesets to the repo. Also adjustments to address https://github.com/os-climate/os_c_data_commons/issues/246

Added machinesets to osc cl1 to sync with cl2

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/apex/apex-qa.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/apex/apex.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/apex/kustomization.yaml
cluster-scope/base/core/namespaces/apex-monitoring/kustomization.yaml
cluster-scope/base/core/namespaces/apex-monitoring/namespace.yaml
cluster-scope/base/core/namespaces/apex-qa/kustomization.yaml
cluster-scope/base/core/namespaces/apex-qa/namespace.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

This adds two new namespaces:
- apex-qa (for our QA environment)
- apex-monitoring (where we'll be setting necessary prometheus/grafana/jaeger resources to monitor the apex and apex-qa namespaces)
It updates our `apex` ArgoCD application based on a incoming code change, and adds a new `apex-qa` application that handles our staging environment deployment.

Expand Apex!

---

argocd/overlays/moc-infra/projects/b4mad.yaml
argocd/overlays/moc-infra/projects/global_project.yaml
argocd/overlays/moc-infra/projects/operate-first.yaml

Resolves: https://github.com/operate-first/apps/issues/1964
Additionally removes these resources from projects which inherit from `global_project` template.

feat: Enable Grafana* resources in ArgoCD globally

---

cluster-scope/overlays/prod/moc/smaug/imageregistry.operator.openshift.io/configs/cluster/config_patch.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Further refinement of #2709 
Current PVC fails to bind with multiple replicas, adjusting according to:
https://docs.openshift.com/container-platform/4.8/registry/configuring_registry_storage/configuring-registry-storage-baremetal.html#installation-registry-storage-block-recreate-rollout-bare-metal_configuring-registry-storage-baremetal

fix(smaug): Relocate image registry to PVC part 2

---

cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/persistentvolumeclaims/image-registry-storage/persistentvolumeclaim_patch.yaml

Further refinement of  #2709 and #2710
PVC needs to be `ReadWriteOnce` as it is on Jerry

fix(smaug): Relocate image registry to PVC part 3

---

prow/overlays/smaug/config.yaml

changes name of bucket in config to match new s3 bucket generated on infra.
/cc @tumido

moving prow storage to ionos s3 bucket

---

argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/sostrades/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/sostrades/sostrades.yaml
argocd/overlays/moc-infra/projects/sostrades.yaml

On behalf of sostrades team from OS-Climate adding new project and application to ArgoCD. This PR should address https://github.com/operate-first/support/issues/1185. Source for artifacts is outside of operate-first org. All artifacts will be created in sostrades on OS-Climate  `osc-cl2` cluster  . 
@sostrades-radouanbouadel , please check PR to make sure that it is addressing your requirements and provide 'lgtm'

Add Sostrades project and applications to argocd

---

cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin-acm/clusterrole.yaml

Update `ClusterRole` definition for service catalog OCM plugin, see https://github.com/janus-idp/backstage-plugins/pull/67.

chore(catalog): Update ClusterRole for OCM plugin

---

openmetadata/base/openmetadata-dependencies/configmaps/files/pod_template.yaml
openmetadata/base/openmetadata-dependencies/configmaps/openmetadata-dependencies-config-envs.yaml
openmetadata/base/openmetadata-dependencies/deployments/airflow-db-migrations.yaml
openmetadata/base/openmetadata-dependencies/deployments/airflow-scheduler.yaml
openmetadata/base/openmetadata-dependencies/deployments/airflow-sync-users.yaml
openmetadata/base/openmetadata-dependencies/deployments/airflow-web.yaml
openmetadata/base/openmetadata-dependencies/deployments/airlfow-triggerer.yaml
openmetadata/base/openmetadata/deployments/openmetadata.yaml
openmetadata/overlays/osc/osc-cl2/kustomization.yaml
openmetadata/overlays/osc/osc-cl2/patches/deployments/openmetadata.yaml

This includes updating the Trino-attached image to 320, and redirecting all references to the non-public/non-existent operate-first/om-ingestion repo to os-climate/ingestion.
Signed-off-by: Eric Ball <eball@linuxfoundation.org>

Update Openmetadata to 0.13.1

---

scripts/onboarding.sh

Follow up to #2705
Fixes failure observed at #2719 
Unfortunately I was unable to find any alternative to `kustomize init/create` for `kind: Component`

fix: Project admin component has to be of a Component kind, not Kustomization

---

cluster-scope/base/core/namespaces/opf-jupyterhub/resourcequota.yaml

Jupyterhub is unable to spawn up because the cpu limits are reached. Increased the resource limits and request

increased cpu limits

---

openmetadata/base/openmetadata/configmaps/files/check_db_migrations.sh
openmetadata/base/openmetadata/configmaps/kustomization.yaml
openmetadata/base/openmetadata/jobs/openmetadata-db-migrations-hook.yaml

To prevent issues during the Openmetadata upgrade state of previous db upgrades needs to be validated and potentially repaired . This change adds script to perform validation as configmap and job to execute script . While configmap is added to kustomization.yaml file , job may need to be executed manually . Related to recent changes as part of https://github.com/os-climate/os_c_data_commons/issues/223

Add scripts and job to perform db validation and repair

---

cluster-scope/overlays/prod/emea/jerry/imageregistry.operator.openshift.io/configs/cluster/config.yaml

otherwise upgrading the openshift-image-registry will not work, since our storage in jerry is only block storage

change rollout strategy

---

kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_hive_ingest.properties

The goal is to align the timestamp format between hive and iceberg, and greatly reduce friction on data ingestion due to timestamp format mismatches.
cc @MichaelTiemannOSC

set hive.timestamp-precision to MICROSECONDS

---

argocd/overlays/moc-infra/projects/janus-idp.yaml
argocd/overlays/moc-infra/projects/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/janus-idp/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/janus-idp/opf-vault-store.yaml
cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml

We want to deploy https://github.com/janus-idp/backstage-showcase to OPF via ArgoCD and helm chart.
This PR is a foundation enabling the team to access Vault and ArgoCD.
cc @PatAKnight

feat: Enable Vault and ArgoCD for Janus-IDP

---

cluster-scope/base/user.openshift.io/groups/janus-idp/group.yaml

chore: Add myself to the janus-idp group

---

cluster-scope/overlays/prod/moc/smaug/externalsecrets/janus-idp.yaml

Add k8s plugin tokens to the `janus-idp` namespace since we need them for the `ocm` plugin installation. I also updated the `janus-idp` policy to allow reads to the referenced vault secret.

feat: Add k8s plugin tokens to janus-idp

---

cluster-scope/overlays/prod/moc/smaug/groups/cluster-admins.yaml
cluster-scope/overlays/prod/moc/smaug/groups/vault-admins.yaml

As some OPF workloads are migrating to ROSA, Ryan requires to gain visibility into how OPF manifests and resources look like.

adding ryan cook to smaug and vault admins

---

cluster-scope/base/core/namespaces/physrisk-resilience/kustomization.yaml
cluster-scope/base/core/namespaces/physrisk-resilience/resourcequota.yaml

This team will need cpu and ram limits similar to a "large" resource quota, but need to have storage and objectbucketclaims unlimited for now.

chore: Update physrisk-resilience resource quotas

---

argocd/overlays/moc-infra/projects/kruize.yaml

We were getting InvalidSpecError -application destination {https://api.smaug.na.operate-first.cloud:6443 openshift-tuning} is not permitted in project 'kruize' and realised we hadn't specifed server in the yaml file.

Updating Kruize.yaml to add smaug server URL

---

cluster-scope/base/core/namespaces/web-terminal-service-catalog/kustomization.yaml
cluster-scope/base/core/namespaces/web-terminal-service-catalog/namespace.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml
cluster-scope/overlays/prod/moc/smaug/kustomization.yaml

Adds a namespace for service-catalog webterminal because by design only kubeadmin can create DevWorkspaces in `openshift-terminal` namespace. I went with small quota because each workspace uses roughly 200m so this means we can run roughly 5 terminals at one time which seems to me like good starting point. For now I have also allowed to users who are in `service-catalog` rolebinding to use this namespace.

feat: Add namespace for users service-catalog

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/kruize/kruize.yaml

Earlier the application name was just hpo - renaming it to Kruize-HPO for better understanding

Updating Kruize application name

---

.pre-commit-config.yaml
.prow.yaml
cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
cluster-scope/base/user.openshift.io/groups/odh-admin/group.yaml
cluster-scope/overlays/prod/moc/smaug/groups/cluster-admins.yaml

- update the pre-commit container image
- update the pre-commit hook versions
- add goern to a few admin groups

add goern to some admin groups, so that he can help out

---

.prow.yaml

It seems that the https://github.com/operate-first/apps/pull/2759 fails because of not enough memory for kubeval validation. This PR increases this limit to 1GB

fix: Increase kubeval job memory request to 1GB

---

.prow.yaml

As the bump to 1 GB in https://github.com/operate-first/apps/pull/2761 does not seem to be enough (as can be seen in https://github.com/operate-first/apps/pull/2759, which is still being OOMKilled)  and from testing which I did it seems that kubeval can use more than 2 GB, I am bumping this value to 4GB to have some reserve.
Reason why this is happening is that kubeval caches in memory schemas which it might need for the validation. These schemas are regularly updated in [schema-store](https://github.com/operate-first/schema-store) and I suspect that lately there has been some change that impacted size of the schemas dramatically. This means that also size that is cached increased.

fix: Increase kubeval job memory request to 4GB

---

cluster-scope/overlays/prod/moc/infra/configmaps/observability-metrics-custom-allowlist.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

This PR adds new metrics to be gathered by the MCO observability 
Part of: https://github.com/operate-first/service-catalog/issues/68

feat: Add metrics to observability

---

cluster-scope/overlays/prod/emea/jerry/kustomization.yaml

PR to update OpenShift Pipelines to Version 1.8 at Jerry cluster.
Discussed here: https://operatefirst.slack.com/archives/C01RF4SPNDD/p1675620390285109

Update OpenShift Pipelines at Jerry to version 1.8

---

cluster-scope/overlays/prod/moc/infra/configmaps/thanos-ruler-custom-rules.yaml
cluster-scope/overlays/prod/moc/infra/kustomization.yaml

This PR adds a MachineWithoutValidNode alert.
The metrics it uses do not include `managed_cluster_id`
label by default but they have `clusterID` instead. In this case `clusterID` is the ID of the cluster the alert originated in (therefore we can define `managed_cluster_id` label ourselves). For now I used following [guide](https://github.com/openshift/machine-api-operator/blob/master/docs/user/Alerts.md) If you have ideas for better guide feel free to point them out.

feat: Add MachineWithoutValidNode alert

---

cluster-scope/base/core/namespaces/web-terminal-service-catalog/kustomization.yaml

I found out that `small` resource quotas are not enough for running at least two webterminals at once (one devworkspace has limit 800m) therefore we cant spawn two devworkspaces at once

feat: Increase quota for web-terminal-service-catalog namespace

---

cluster-scope/overlays/prod/moc/infra/groups/cluster-admins.yaml

needed permissions in infra for context when migrating osc clusters

---

argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml

/cc @cooktheryan 
Will remove manifests entirely once we have resolved syncing issues.
related to: https://github.com/operate-first/apps/pull/2778

removing osc argocd apps from op1st management

---

cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin/clusterrole.yaml

`pipelinerun` and `taskrun` resource permissions are required for fetching these resources in the Tekton plugin 
/cc @tumido

feat(tekton): Add new pipeline resource permissions for tekton plugin

---

argocd/overlays/moc-infra/applications/envs/moc/smaug/okd-team/kustomization.yaml
argocd/overlays/moc-infra/applications/envs/moc/smaug/okd-team/okd-tekton-release-pipeline.yaml

This argoCD app will allow the automatic deployment of resource of okd release pipelines when a new commit is merged on main branch.

OKD-89: feature: adds a new argoCD app to deploy okd tekton pipeline
